### ISSUE TITLE
my accounts

### ISSUE THREAD

**Issue by dm2912** [umbrellaplug/umbrellaplug.github.io#1]
would you consider sharing the same myaccounts package that is currently being used by both Ezra and Kingpin

Ezra github.com/ezra-hubbard
Kingpin github.com/wilson-fisk

those addons are both already sharing a plugin.module.myaccounts, and both are fairly established now, ezra especially, so introducing another identical module to the scene at this point will cause confusion (and issues for all addons)

(note that if anyone has ezra or kingpin repo's installed then umbrella install wont be able to load your version of accounts)

**Comment by tundrablasen** [comment]
Would love that

**Comment by Ezra-Hubbard** [comment]
> Will also check with Ezra to see if I he's okay with sharing my account modules. If so I'll change my repo and requirements to point at his.

That's absolutely fine, I have also made the myaccounts module public in Git today (well yesterday) so it can take merge requests. All the ezra branding has been removed from it as well (apart from font)

I think the main concern was more that Kodi is funny since v19 about updating addons from anything other than original install source, and so users who already had ezra would have that version and would never update to yours which down the line could cause issues if something fundamentally changed in the ez  version. 

>Umbrella is setup to pull id's from myaccount modules instead of hard coded. I purposely set my version of myaccount lower than ezra. 

yeh, ezra's intention is to do the same

Also want to add to the accounts module the ability to enter personal api and secret for trakt so that fen./venom forks have ability for user api keys for trakt as well as tmdb

**Comment by umbrellaplug** [comment]
> 

Just to confirm, you are wanting to setup Trakt like TMDB in the MyAccounts module? Where a user could set their own keys? This is something I could implement for you if that's what you're looking to do.

**Comment by Ezra-Hubbard** [comment]
> Just to confirm, you are wanting to setup Trakt like TMDB in the MyAccounts module? Where a user could set their own keys? This is something I could implement for you if that's what you're looking to do.

yes, in exactly the same way, so in my accounts trakt settings there is option for api key and secret key in the same was as tmdb, and if empty uses the current hard coded.

would offer the module a level of protection if api keys are revoked down the line as with fen/venom, or if users wish to use their own (which generally is quicker i find)


the my accounts module is public now https://github.com/Ezra-Hubbard/script.module.myaccounts
so if you are able to do it easily, that would be great. im very much still learning python, so would take me longer lol.

**Comment by umbrellaplug** [comment]
@Ezra-Hubbard Update has been pushed from for My Accounts. Add a new enable custom trakt keys option in settings and if turned on the user has the ability to input their trakt api keys for authorization. Afterwards the token is stored as before. You can test this by switching it out with my keys and when you authorize the addon you will see without any custom keys it's "My Accounts" from your id, with my ids in the fields it should come in as "Jsoh Trakt". I don't want to post my keys here again. Use the client_id and client_secret from the myaccounts module posted on my repo currently.

Will be making my next umbrella update point to your github for the my accounts module. I will let users know to remove the previous my accounts they had from my repo and install your so no furhter conflicts arise. I believe pointing to your repo directly from my repo in my addons.xml should resolve any Kodi 19 "files from a different place" bugs, but we shall see.

**Comment by Ezra-Hubbard** [comment]
merged. Seems to work just fine, tested with built in keys and personal keys.

**Comment by umbrellaplug** [comment]
I've setup the public branch of My Accounts as a sub-module of my repo. Going forward my version should always match with Ezra. Setting it this way should avoid users having to remove it before being able to update. The "file source" is still the original repo I was using for My Accounts module and it's just pointing to the Ezra repo. The version requirement for My Accounts was removed in the latest version of Umbrella as well.

Request Complete: Ezra, Kingping, and Umbrella now share 1 My Accounts module. :)

I believe I should be okay to close this issue now. If anything comes up, feel free to re-open it.

**Comment by kodifitzwell** [comment]
hello fellows,

libreelec with generic xbox controllow is my daily driver.  I thought about the option of a user added trakt clientid/secret in my Fen fork but have been sitting on it as each string is 64 chars.

I see you added it to your "myaccounts."  in windows, there is copy/paste, for those who use libreelec without keyboard attached (and maybe fire devices with limited remotes) have you considered the user experience for a simple way to enter these?  as far as I could find, this cannot be pulled from the api like username.

**Comment by umbrellaplug** [comment]
> hello fellows,
> 
> libreelec with generic xbox controllow is my daily driver. I thought about the option of a user added trakt clientid/secret in my Fen fork but have been sitting on it as each string is 64 chars.
> 
> I see you added it to your "myaccounts." in windows, there is copy/paste, for those who use libreelec without keyboard attached (and maybe fire devices with limited remotes) have you considered the user experience for a simple way to enter these? as far as I could find, this cannot be pulled from the api like username.

Due to needing a Client ID and Client Secret to use the api, this isn't a way to pull those from the api. I use libreelec as well. I use the Kodi Remote application. I copy my keys from the browser and paste them in using the keyboard in the kodi remote app.

**Comment by kodifitzwell** [comment]
cool, I'll add it.  I didn't know that was an option, but if a user asks now I know.

**Comment by dm2912** [comment]
Yeh, both Kore (the kodi remote app) and Yatse work with Coreelec so they will work with Libreelec

my api keys are all in a note on my pc that sync with nextcloud to nextcloud notes on my phone, so i just copy paste from notes app to remote
