### ISSUE TITLE
Feature req: the ability to use multiple plex shares a sources and not only one at a time.

### ISSUE THREAD

**Issue by TheGuyWhoo** [umbrellaplug/umbrellaplug.github.io#100]
Finally getting around to opening an issue for this. Thank you for entertaining the idea.

**Comment by umbrellaplug** [comment]
This is next on the list.

**Comment by TheGuyWhoo** [comment]
Sweet, thanks for taking a look!

**Comment by TheGuyWhoo** [comment]
Any updates on this? No hurry, I'm just very curious haha

**Comment by umbrellaplug** [comment]
Been working on this. Scraper dev still too busy with real life. Understandable. 

It's not been dropped, just not getting much love right now. I use plex also so this will get done though just not as high of priority right now as bug fixes. Thanks for your patience. I look forward to getting this added.

**Comment by TheGuyWhoo** [comment]
Sweet, thanks for the update!

**Comment by TheGuyWhoo** [comment]
Any updates on this?

**Comment by umbrellaplug** [comment]
Added. Will be in the next update.

**Comment by TheGuyWhoo** [comment]
Sweeet! Thanks man. Hope it wasn't too much of a headache.

**Comment by umbrellaplug** [comment]
> Sweeet! Thanks man. Hope it wasn't too much of a headache.

No problem, wasn't much on my side as I just needed to adapt for settings. Scraper Dev got the real work. I've got a copy on the test repo of new version of coco with the new stuff included, I'm still waiting for scraper dev to push to their repo for official.

**Comment by TheGuyWhoo** [comment]
Tell him I say thanks if you don't mind!

**Comment by TheGuyWhoo** [comment]
Hey! I just played around with this and so far it's dream, everything I've been looking for in a plex addon. I did notice a small issue in the way the scraper scrapes for episodes. Sometimes instead of having the official title of the episode, the episodes will just be listed as 'episode 1', 'episode 2', etc. It seems that cocoscrapers do not return those episodes, only episodes that match the episode title that you're scraping for. Instead it would probably better to match episode and season number, and not the full title of the episode. Should I open an issue for that here?

**Comment by umbrellaplug** [comment]
Nah, the scraper developer will not change that. I can tell you already because it's been a topic of many discussions. The plex shares are brought in using the same checks as torrents and others so anything named like that unfortunately will not return for us.

**Comment by TheGuyWhoo** [comment]
Oh damn okay, thank you for the heads up. I will see if I can't convince the server owners to get proper metadata instead.

**Comment by umbrellaplug** [comment]
Can you turn logs on in coco. Scrape an send me the logs. There's a url in the logs I would like. I think there may be metadata embedded in the returns that I may be able to replace the file name with, but I'd need some samples.

**Comment by TheGuyWhoo** [comment]
Currently I am unable to scrape, on a fresh install and everything. It's telling me I need a debrid account. Something must have changed, it was working flawlessly last night.

**Comment by umbrellaplug** [comment]
What do the logs say?

**Comment by TheGuyWhoo** [comment]
Umbrella logs or scraper logs?

**Comment by umbrellaplug** [comment]
That's likely umbrella. But either one if there's any hints of what might be going on.

**Comment by TheGuyWhoo** [comment]
![yes](https://user-images.githubusercontent.com/72744967/212322556-0672a603-9753-4182-b4f6-bfcf2224de0a.png)

I checked coco logs but it seems to be empty.

**Comment by umbrellaplug** [comment]
Looking over the code to see what could be causing you that issue. Are you on cocoscrapers 1.0.9?

**Comment by TheGuyWhoo** [comment]
Yes I am

**Comment by TheGuyWhoo** [comment]
Rolling back umbrella doesn't work, same results for both .06 and .07 as in .08. Nor does rolling coco back to 1.0.8 work. I have tested this on two devices, across three profiles and I always get the "no debrid account setup" message, despite being able to use it without a debrid account in the past.

**Comment by umbrellaplug** [comment]
No worries, I found your issue. When I changed over to the new version of cocoscrapers I removed the settings for several of the plex settings. It's checking one of those removed settings to indicate "debrid" account or not. I'll have an update for you momentarily to fix this.

**Comment by TheGuyWhoo** [comment]
Okay I see, thank you!

**Comment by umbrellaplug** [comment]
6.6.09 has been pushed. it should resolve your issue. let me know.

**Comment by TheGuyWhoo** [comment]
Yes it does, it's working again. Thanks mate! I will get you that log for the episodes now. Does it need to be from the episodes that are improperly named or does it not matter?

**Comment by TheGuyWhoo** [comment]
I mean from where the scrape should be initiated.

**Comment by umbrellaplug** [comment]
Yes, I need a sample where you're searching a show and you know there are episodes available but they are not coming back due to naming.

**Comment by TheGuyWhoo** [comment]
I think there might be an issue with cocoscapers logging. All I get is a completely empty file.

**Comment by umbrellaplug** [comment]
nah, just looked scraper developer removed logging of urls from .08 to .09... lol of course. If i send you a zip here are able to install from zip?

**Comment by TheGuyWhoo** [comment]
Yep, sure!

**Comment by TheGuyWhoo** [comment]
I wonder why, is there a good reason he did that?

**Comment by umbrellaplug** [comment]
We use logging to test things when building new features or finding bugs, but typically we remove it before pushing to public side.
It's just a courtesy to remove it, some people run their system nonstop without reboots and the more we write to the log the larger that file gets so we try to keep logging down.
Here's a link for cocoscrapers with logging for the url turned back on.
https://www.dropbox.com/s/1qulzshvpoehsn9/script.module.cocoscrapers-1.0.10.zip?dl=0

Make sure you have cocoscrapers set to debug>on and logging location "addon log"

**Comment by TheGuyWhoo** [comment]
[2023-01-13 20:18:08] [COLOR red][ COCOSCRAPERS INFO ][/COLOR]: url = https://78-89-155-225.c447778286624b6684077355e6bd17e0.plex.direct:32402/hubs/search?query=8%20Out%20of%2010%20Cats%20Does%20Countdown%20Jonathan%20Ross%2C%20Joe%20Wilkinson%2C%20Roisin%20Conaty%2C%20Ahir%20Shah&limit=30&X-Plex-Client-Identifier=0xab6386f60918&X-Plex-Token=BaftxWwExTsGL5LeyZPJ
        [2023-01-13 20:18:08] [COLOR red][ COCOSCRAPERS INFO ][/COLOR]: url = https://74-110-198-48.9c6ff24122e74a53935f908fd476a35b.plex.direct:22675/hubs/search?query=8%20Out%20of%2010%20Cats%20Does%20Countdown%20Jonathan%20Ross%2C%20Joe%20Wilkinson%2C%20Roisin%20Conaty%2C%20Ahir%20Shah&limit=30&X-Plex-Client-Identifier=0xab6386f60918&X-Plex-Token=cYtEsUUq3G8K1ByzteZj
        [2023-01-13 20:18:08] [COLOR red][ COCOSCRAPERS INFO ][/COLOR]: url = https://85-10-198-14.c210110498a64f3a90842b52e2fdf7c7.plex.direct:32410/hubs/search?query=8%20Out%20of%2010%20Cats%20Does%20Countdown%20Jonathan%20Ross%2C%20Joe%20Wilkinson%2C%20Roisin%20Conaty%2C%20Ahir%20Shah&limit=30&X-Plex-Client-Identifier=0xab6386f60918&X-Plex-Token=4GpvfUhPzddrkhxUC9GH
        [2023-01-13 20:18:08] [COLOR red][ COCOSCRAPERS INFO ][/COLOR]: url = https://142-115-43-243.be2a6356aa1941b2ac2c727cb8f3aea9.plex.direct:32400/hubs/search?query=8%20Out%20of%2010%20Cats%20Does%20Countdown%20Jonathan%20Ross%2C%20Joe%20Wilkinson%2C%20Roisin%20Conaty%2C%20Ahir%20Shah&limit=30&X-Plex-Client-Identifier=0xab6386f60918&X-Plex-Token=PJuisxGgVd4mQHqMag3Q
        [2023-01-13 20:18:08] [COLOR red][ COCOSCRAPERS INFO ][/COLOR]: url = https://68-129-10-149.77d0731a1fe647e999399b1f47227d52.plex.direct:32499/hubs/search?query=8%20Out%20of%2010%20Cats%20Does%20Countdown%20Jonathan%20Ross%2C%20Joe%20Wilkinson%2C%20Roisin%20Conaty%2C%20Ahir%20Shah&limit=30&X-Plex-Client-Identifier=0xab6386f60918&X-Plex-Token=KdgXsh_DGxsx8AWRwxNS
        [2023-01-13 20:18:08] [COLOR red][ COCOSCRAPERS INFO ][/COLOR]: url = https://116-202-51-96.868417fdcb9f4eb1a43bdbfdc74227f3.plex.direct:32404/hubs/search?query=8%20Out%20of%2010%20Cats%20Does%20Countdown%20Jonathan%20Ross%2C%20Joe%20Wilkinson%2C%20Roisin%20Conaty%2C%20Ahir%20Shah&limit=30&X-Plex-Client-Identifier=0xab6386f60918&X-Plex-Token=eYa2DytU6Siitnz_-CUA
        [2023-01-13 20:18:08] [COLOR red][ COCOSCRAPERS INFO ][/COLOR]: url = https://142-198-157-30.664fc44fddbb4a25b7c5ba31750ba5a4.plex.direct:42400/hubs/search?query=8%20Out%20of%2010%20Cats%20Does%20Countdown%20Jonathan%20Ross%2C%20Joe%20Wilkinson%2C%20Roisin%20Conaty%2C%20Ahir%20Shah&limit=30&X-Plex-Client-Identifier=0xab6386f60918&X-Plex-Token=jJyGH9RAnpyQWws2eza2

Is that what you're looking for? This is from scraping for this from within umbrella, from the episode. It returns two results, but I know there's another server that has it that doesn't have the proper title for the episode.

**Comment by TheGuyWhoo** [comment]
(btw that's the full file, I didn't cut anything)

**Comment by umbrellaplug** [comment]
that's perfect. Looks like you have 7 shares. It's looking through each one sending this:

8 Out of 10 Cats Does Countdown Jonathan Ross, Joe Wilkinson, Roisin Conaty, Ahir Shah&limit=30

When you're in plex and you search the same thing do you see this server as one of the results?

If you go to each ones of these urls individually you can see only 2 or 7 return results. Seems your missing server isn't returning anything for that title. At this point in the "scrape" episode number or any of that hasn't even been introduced it's just searching for the title.

**Comment by TheGuyWhoo** [comment]
No, since the episode is only episode number in the season, it wouldn't show up when you search the proper title.

**Comment by TheGuyWhoo** [comment]
I'm gonna edit the links out btw, kinda feel weird about it being out in the open haha

**Comment by umbrellaplug** [comment]
> No, since the episode is only episode number in the season, it wouldn't show up when you search the proper title.

This is important to understand. We get your item you are searching for from list/widget whatever you pressed to start the scrape. In the plex scraper it checks the info sent for tvshowtitle. If we see tvshowtitle, we know it's an episode we then hit a plex url for searching with the episode title. On you're server that has the stuff on it that is named wrong and isn't returned on these searches it's because of the result not coming back from the plex server. A better way to put it I guess is as long as the "title" of the episode matches, with plex scraping you should still get a result no matter the file name. I don't know if custom query would fix that for as it would still be looking for episode or movie, but worth a try. Really your first response nailed it, it needs to be fixed at the plex side so when you search the title of the episode you get a result from that server.

**Comment by TheGuyWhoo** [comment]
Yeah, it's definitely an issue that should be fixed server side. 

I apologize for going even more off topic, but how do I get a person trakt list to sort according to last watched item? I've been through the settings and widget sort options, but nothing seems to work. The trakt list sorts correctly in trakt, but in kodi I can't get it to follow the default I set inside of trakt.
