### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by Redsand51** [umbrellaplug/umbrellaplug.github.io#101]
I was able to duplicate the issue of disappearing files when downloading.  It appears filenames ending with .avi are saved to the wrong download folder. .mkv files are correctly downloaded. I have two separate download folders specified:  tvshows and videos for movies. When the download file option is changed from Torrent filename to Title (year) or Title S01E01 avi files are saved in the video folder. Sure enough all the downloaded were there. Not sure about mp4 files.  Hope this makes sense.
RS

**Comment by umbrellaplug** [comment]
Love it, very detailed. I will look into this for you.

**Comment by umbrellaplug** [comment]
What show are you getting AVI sources for? lol, i can't seem to find any.

**Comment by Redsand51** [comment]
Law and Order SVU Season 2

**Comment by umbrellaplug** [comment]
Thank you. I'll see what I can figure out for you.

**Comment by Redsand51** [comment]
Thank you. Your work much appreciated. One other issue I noticed when option is set to  Title (year) or Title S01E01 the right most digit it missing. Ex: S01E0

**Comment by umbrellaplug** [comment]
What debrid source are you using? Are these coming from packs?

**Comment by umbrellaplug** [comment]
Made changes that I could for this. These are named terribly unfortunately. Should at least go to the correct folders now.

**Comment by umbrellaplug** [comment]
Next update will have these adjustments.

**Comment by Redsand51** [comment]
Sorry for the delay. Real Debrid. And yes it was from a pack.  Your changes seem to work fine and once again thanks for your efforts. So glad to see someone take over the great work done by the Venom Dev. Probably one of the best addons overall since XBMC.  Kudos.
RS
