### ISSUE TITLE
[Feature Request] Sorting - Filtering for Keywords/Key Phrases

### ISSUE THREAD

**Issue by tundrablasen** [umbrellaplug/umbrellaplug.github.io#102]
I proposed a new feature over at Tikipeters Github. I think it would be a great addition also for umbrella.

So that we do not have 2 seperate conversations, i hope its ok, to just link the Issue here.

https://github.com/Tikipeter/repository.tikipeter/issues/60

**Comment by Tikipeter** [comment]
I have no interest in doing this.

It sounds useless.

**Comment by umbrellaplug** [comment]
I was told Seren offers this.
