### ISSUE TITLE
Coco scrapers update failed

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#103]
I keep trying to install the update and it says failed but I also have tikiPeter in there. It could be the problem. There is no log error to go with this

**Comment by umbrellaplug** [comment]
Sorry about that, I wasn't aware. I'll let the scraper dev know.

**Comment by Arthur1967** [comment]
No worries it's still working the add-on, but it won't update, but like I said, I have tiki Peter in there, too, which uses the same scraper thank you for all your work. I will close this now.
