### ISSUE TITLE
Movie network logos don’t show up

### ISSUE THREAD

**Issue by xyzfre** [umbrellaplug/umbrellaplug.github.io#104]
I’m using AH2 movie network logos don’t show up for TV shows they do show up correctly ,, Nvidia Shield 2019 Pro K19.4

**Comment by xyzfre** [comment]
![Uploading D5895AE9-BCE0-4CCB-B1C1-2F9B8E386D41.jpeg…]()
Umbrella

**Comment by xyzfre** [comment]
![Uploading C034CD33-6053-4D7F-B122-F6A019210194.jpeg…]()
TMDb H

**Comment by xyzfre** [comment]
![Uploading CC600C2F-4F91-43E4-BFA0-466C959D64FA.jpeg…]()
Umbrella

**Comment by xyzfre** [comment]
![9B7BD2AD-C6FD-47B6-BA4C-B58947A3856F](https://user-images.githubusercontent.com/49699869/195845515-760b2660-8a94-49d5-a300-c0bfa53c8b85.jpeg)
Umbrella

**Comment by xyzfre** [comment]
![B7F8EA1B-7F46-457A-BFC1-AE70FBB75FCF](https://user-images.githubusercontent.com/49699869/195845579-d194851a-ba45-4c96-ba43-edf7848bf39a.jpeg)
TMDb H

**Comment by umbrellaplug** [comment]
Seems to be a simple metadata label I'm not gathering or assigning. I'll add it in.

**Comment by umbrellaplug** [comment]
Added. Will be in the next update.
