### ISSUE TITLE
TV Show Times

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#105]
Hi, Just came across your addon.
Great work so far, and a lot more potential.
I know you're probably a busy Man/Lady, and not sat on your hands.
One addition I would like to see if possible, would be Run Times on TV Shows, if I use LOTR series as an example, it says 1 hour for every episode. 
Issue is, I sat down this evening at 9pm, thinking that last episode was 1 hour long, so plenty of time foe me to have my warm milk and cookies, but heaven forbid it turned out to be over 2 1/2 hours, far to late for me, so kinda ruined my eve. So actual play time would be fabulous if possible?

Thank you for your time 😃

**Comment by adamosborne83** [comment]
Hi, apologies for the additional message, just it's been over 24hrs, and just checking that you have seen this?

**Comment by umbrellaplug** [comment]
The current run-time on Rings of Power -  Episode 8 is 72 minutes. I'm not sure what you were watching for 2.5 hours, but it wasn't that. In your confusion of having an incorrect run time did you maybe watch it twice? :)

This has been fixed and will be available in the next update.
