### ISSUE TITLE
[BUG] TMDBH Error When Scrolling Over "Accounts" Tab in Settings Menu

### ISSUE THREAD

**Issue by rtuRgALp** [umbrellaplug/umbrellaplug.github.io#108]
Whenever I have Umbrella and TMDBH installed together, when I scroll over the Accounts tab in the Settings Menu, an error is thrown. 

https://paste.kodi.tv/egixacokex

Not sure if this is an issue with Umbrella itself or TMDBH, but starting here. 

This happens on my MacBook Air and Apple TV 4K. To reproduce, open Kodi, install TMDBH from jurialmunkey Alpha repo, install Umbrella, and open setting Menu and scroll over Accounts tab.

**Comment by umbrellaplug** [comment]
Your log is loaded with TMDB helper errors. I'd check with the developer of tmdbhelper.
