### ISSUE TITLE
Anime One piece season 2 - season 17 missing 

### ISSUE THREAD

**Issue by krishne35** [umbrellaplug/umbrellaplug.github.io#11]
Idk why but one piece season 2- season 17 are not listed 
And it never fetches proper links for one piece it will scrape some random episode :(
Only with one-piece

**Comment by umbrellaplug** [comment]
Anime can be extremely difficult. Try making sure Nyaa is turned on in your umbrella scrapers. I can't remember if I enabled it by default. It has had a few adjustments for anime and may give you some better results. Let me know. I can look into it further.

**Comment by krishne35** [comment]
I tried with nyaa enable 
Many other anime works just fine apart from one piece 
Only addon that worked fine with one-piece was torrentio (stremio addon) 

[Feature request]
And is it possible to make some sort of database where it stores all caches links from all users so that is any website is blocked on my isp the addon could look from database 
Idk how but torrentio shows many more links coz jts hosted remotely somewhere
With that we only need rd and no need for any vpns

**Comment by umbrellaplug** [comment]
Yeah. I have something in the works for torrentio on an upcoming update actually. Stay tuned.

**Comment by krishne35** [comment]
Excited !!!

**Comment by krishne35** [comment]
Is it possible to fetch meta data for (Premium>rd>cloud storage) files 
Like some sorta context menu

**Comment by umbrellaplug** [comment]
> Is it possible to fetch meta data for (Premium>rd>cloud storage) files 
> Like some sorta context menu 

Would need research. TMDB ID is used for meta. If we have that, it may be possible. Try your anime search now. See if it's improved. Torrentio scraper was updated.

**Comment by krishne35** [comment]
No luck 
Only addon i had success with one piece anime was "[torrentio](https://github.com/TheBeastLT/torrentio-scraper)" 
Scraper used to be open-source but he moved it into private couple days ago tho

**Comment by krishne35** [comment]
Sorry didn't follow up 
Yes turing that started to show the seasons but they scape the wrong episodes and cloud scrape doesn't seem to work either coz I have manually added so many one piece torrents to Rd yet get some random episode links ;-;

Addon that does the scraping property is [kaito beta](https://github.com/Goldenfreddy0703/plugin.video.kaito.beta)
