### ISSUE TITLE
Using Hide watched new episodes exist but shows remain hidden in Trakt library

### ISSUE THREAD

**Issue by cg00001** [umbrellaplug/umbrellaplug.github.io#110]
This is solved only when "Force Trakt Sync to local database" is used.
This only affects a few shows, today I checked the shows disabling Hide watched, found the shows, and after a Force Trakt Sync 3 shows appeared in my Trakt library with Hide watched enabled.

If you need a log, you'll have to wait for new episodes to come out so I can replicate this.

**Comment by umbrellaplug** [comment]
I will try to duplicate this myself and let you know. I apologize in advance for any delay it's an very busy week for me at my full time job.

**Comment by cg00001** [comment]
Maybe these help:
Old kodi.log with new show episodes that doesn't show with Hide Watched.
[kodi.old.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/9882795/kodi.old.log)

New kodi.log with shows appearing after Force Trakt sync using Hide Watched.
[kodi.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/9882802/kodi.log)

Video showing the issue.
https://user-images.githubusercontent.com/38960370/198388321-7cd6d9b1-f307-4870-905e-d67b3ec949c6.mp4

Video after Force Trakt Sync.
https://user-images.githubusercontent.com/38960370/198388454-ee829621-4d9e-4b51-b0b4-185e76f310b6.mp4

**Comment by umbrellaplug** [comment]
Finally getting to these. 
What skin are you using? 
Are you using LibreElec?

**Comment by cg00001** [comment]
Friends noticed this in Xonfluence skin, I'm using Titan MOD, Equinox & Cosmic in Arch Linux.
This happens in both Matrix and Nexus.

**Comment by umbrellaplug** [comment]
Okay, I just needed to know what skin to load to find duplicate it. I do not run Arch linux, but I have an idea of what the issue may be. Can you tell me if in Kodi > Settings > System Info > Network Does arch linux have a "Internet:" value? Example my shield has

Link:
Mac Address:
IP address:
Subnet Mask:
Gateway:
Primary DNS:
Secondary DNS:
Internet:

My pi does not have the "Internet". I'm thinking this may have been removed in most linux builds. Can you verify if you see that in your settings or not?

**Comment by cg00001** [comment]
> Okay, I just needed to know what skin to load to find duplicate it. I do not run Arch linux, but I have an idea of what the issue may be. Can you tell me if in Kodi > Settings > System Info > Network Does arch linux have a "Internet:" value? Example my shield has
> 
> Link: Mac Address: IP address: Subnet Mask: Gateway: Primary DNS: Secondary DNS: Internet:
> 
> My pi does not have the "Internet". I'm thinking this may have been removed in most linux builds. Can you verify if you see that in your settings or not?

![200715](https://user-images.githubusercontent.com/38960370/205128033-98f1699c-ae87-4cc4-86b6-3634fc11f6e4.jpg)

**Comment by cg00001** [comment]
Current skin I'm using is Titan MOD.
New repo is here, just install skin from it:
https://github.com/Fuchs246/repository.fuchs246

**Comment by cg00001** [comment]
A note, this also happens in Flatpak Kodi (Matrix), and I've seen it in other addons as well -I don't use those anymore, could be Fen and/or Seren.
Maybe this is a Kodi issue, and not a skin or addon issue, regarding the way Kodi hides new episodes when Hide watched is enabled?

**Comment by umbrellaplug** [comment]
Hide watched uses a flag set on the infolabel of the items called "playcount". I'll look into this a little more. I've been working on a some other things.
![Uploading Screen Shot 2022-12-08 at 8.14.50 PM (2).png…]()

**Comment by cg00001** [comment]
I remembered I opened a similar issue in Trakt in the past -no one answered.
https://github.com/trakt/script.trakt/issues/524

**Comment by umbrellaplug** [comment]
It could be a number of things (menu caching, database not updating). I'll install the theme and mess with it a bit more and see what I can find.

**Comment by umbrellaplug** [comment]
This should be resolved in the latest update. update 6.6.13
