### ISSUE TITLE
Playlist popup appears after watching an episode

### ISSUE THREAD

**Issue by cg00001** [umbrellaplug/umbrellaplug.github.io#112]
Using Arch Linux with Flatpak Kodi (Matrix) and Kodi Nexus.
![014619](https://user-images.githubusercontent.com/38960370/200090968-f651ca04-29f5-4836-85c2-97e5605104cf.png)

I don't know if this has to do with Thread LanguageInvoker or a playlist, you can see line 1888 -maybe earlier too.
Couldn't find a setting to disable Thread LanguageInvoker.

[kodi.Matrix.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/9942540/kodi.Matrix.log)

[kodi.Nexus.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/9942543/kodi.Nexus.log)

**Comment by umbrellaplug** [comment]
Are you running TMDBHelper?

**Comment by cg00001** [comment]
> Are you running TMDBHelper?

TMDbH is not even installed.

**Comment by cg00001** [comment]
This happens on every episode:

https://user-images.githubusercontent.com/38960370/200132582-11e9edd4-9feb-4132-979c-e6378afc0881.mp4

**Comment by umbrellaplug** [comment]
Weird, okay. That was my next question. I'm seeing it on "Stop" but not on playing till the end. Let me keep trying here see if I can find what's causing that.

**Comment by umbrellaplug** [comment]
Found the issue. I will push an update for it soon.

**Comment by umbrellaplug** [comment]
Latest update should resolve this for you. Please let me know.

**Comment by cg00001** [comment]
> Latest update should resolve this for you. Please let me know.

Thank you, popups are gone.
