### ISSUE TITLE
After playback ends

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#114]
https://paste.kodi.tv/xinoyupupo

**Comment by TechXXX** [comment]
I get an error on stop too

**Comment by Arthur1967** [comment]
Ever since the latest update I'm glad I'm not the only one thank you will see what he says

**Comment by umbrellaplug** [comment]
Can you guys give me steps to duplicate this? I'm thinking it's a result of a particular chain of actions.

**Comment by Arthur1967** [comment]
Anytime, I watch a movie or a series and it finishes I get that error

**Comment by Arthur1967** [comment]
And when the update came it wanted to change my language envoker setting and it won't allow you to ignore this when the new update came

**Comment by TechXXX** [comment]
Ah another update blocked me from reading that properly, all I got was something with language. Cheers for that Arthur. I second that with every movie and show you get an error on stop. Wait a second, I have another Kodi on here ;).

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/200129931-80caa443-99b1-4ecf-b8f1-22417e3dd1ea.png">

**Comment by TechXXX** [comment]
sorry it's AH2, don't know if it's skin related

**Comment by umbrellaplug** [comment]
> And when the update came it wanted to change my language envoker setting and it won't allow you to ignore this when the new update came

No worries. I'm looking into it.

**Comment by Arthur1967** [comment]
It's not the skin I use xconfluence end it happens. It's really not a major deal. It works fine but I get an error every time playback stops.

**Comment by Arthur1967** [comment]
Like I said, it works fine. You just get an error after playback stops. Thank you for looking into this.

**Comment by TechXXX** [comment]
On my second Kodi I don't see it with movies, I get this notification on series 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/200130804-3be02801-39a0-4499-9e71-1c6ac5bbe54e.png">

**Comment by TechXXX** [comment]
[kodi.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/9944283/kodi.log)

**Comment by TechXXX** [comment]
> > And when the update came it wanted to change my language envoker setting and it won't allow you to ignore this when the new update came
> 
> No worries. I'm looking into it.

Cheers, appreciate it.

**Comment by umbrellaplug** [comment]
The popup you got for language invoker is due to the addon being set default to invoker on, but in your settings you have it turned off. When the addon loads an update and sees in the update that invoker is turned on in addon.xml, but not in settings.xml it detects the mismatch and forces it back on. You can turn this back off by going to developer options in tools and setting it back to false.

On the playback fail popup, I'm looking into that one. It's strange I never had that or any of the testers, but I was able to duplicate it once just now. I'm looking it over.

**Comment by Arthur1967** [comment]
Perfect thank you. It's reloading now.

**Comment by TechXXX** [comment]
> The popup you got for language invoker is due to the addon being set default to invoker on, but in your settings you have it turned off. When the addon loads an update and sees in the update that invoker is turned on in addon.xml, but not in settings.xml it detects the mismatch and forces it back on. You can turn this back off by going to developer options in tools and setting it back to false.
> 
> On the playback fail popup, I'm looking into that one. It's strange I never had that or any of the testers, but I was able to duplicate it once just now. I'm looking it over.

That might all be true except I've never enabled/opened the debug menu until just now, certainly haven't turned something off in there, no idea what the invoker does.

**Comment by TechXXX** [comment]
hmmm problem resolved after an AH2 update

**Comment by TechXXX** [comment]
Thanks a lot Mr. Umbrella, you rock.

**Comment by adamosborne83** [comment]
> 

Yes he does

**Comment by adamosborne83** [comment]
> Thanks a lot Mr. Umbrella, you rock.

Yes he does

**Comment by Arthur1967** [comment]
Still the same for me, but I will close it for now

**Comment by TechXXX** [comment]
> Still the same for me, but I will close it for now

yeah, same here

**Comment by saxoloman** [comment]
Still geting the error

**Comment by TechXXX** [comment]
One or more items couldn't play...words to that effect


<img width="870" alt="image" src="https://user-images.githubusercontent.com/10571873/200136894-230810c3-fa6d-48b1-b88c-0aa7014c6015.png">

**Comment by umbrellaplug** [comment]
Yeah, there's a problem. I'm working on it.

**Comment by umbrellaplug** [comment]
Found the issue. I will push an update for it soon.

**Comment by umbrellaplug** [comment]
Latest update should resolve this for you. Please let me know.

**Comment by TechXXX** [comment]
Can confirm, no more pop up on stop. Thanks a bunch.
