### ISSUE TITLE
Popcorn ratings not showing 

### ISSUE THREAD

**Issue by DROIDshield** [umbrellaplug/umbrellaplug.github.io#115]
I have api for tmdb and omdb and all other ratings show up but no popcorn ratings. Yet using the same in Seren shows Popcorn Ratings. Using Kodi 19.4 with Titan Bingie Mod Skin. Am I missing something?
![20221105_133943](https://user-images.githubusercontent.com/97023369/200122813-4be73986-e1dc-4b3a-870e-e94a6ac39174.jpg)

**Comment by DROIDshield** [comment]
Wow okay.Are you using api though umbrella at all?Sent from my Galaxy
-------- Original message --------From: umbrellaplug ***@***.***> Date: 07/11/2022  16:02  (GMT+00:00) To: "umbrellaplug/umbrellaplug.github.io" ***@***.***> Cc: DROIDshield ***@***.***>, Author ***@***.***> Subject: Re: [umbrellaplug/umbrellaplug.github.io] Popcorn ratings not showing  (Issue #115) 
Hey, I double checked this and I'm not getting the same issue. I don't use Titan Bingie Mod, so I just downloaded it and tried it. Once I turned show ratings on in the settings of the skin, this is what I got.

**Comment by umbrellaplug** [comment]
I'm sorry, I'm not 100% sure what you're asking me here. I have tmdb and fanart setup with my own keys in accounts meta. I also have library integration, so I may be seeing the popcorn ratings from that. I'm not big on themes so I apologize I'm pretty lost in setting this thing up to use Umbrella for widgets.

**Comment by umbrellaplug** [comment]
Figured out widgets on this skin. Don't know how you guys do this. :)

I'll see what I can find on the ratings.

**Comment by umbrellaplug** [comment]
I tried to duplicate your issue. I got nothing but new issues. Not sure what to tell you on this one. If I could duplicate the issue to see why I'd be happy to look into it, but not worth dedicating much more time on it for me.

**Comment by DROIDshield** [comment]
Thanks for your time with what you tried. I know setup of the skin is a bit complicated but the fact that you where getting popcorn tells be I might have a glitch so I'll wipe all data from your addon and the skin and start again. Cheers for the effort.
