### ISSUE TITLE
Play random videos

### ISSUE THREAD

**Issue by ShockStabber13** [umbrellaplug/umbrellaplug.github.io#12]
Hello. I'm using Kodi 19.4 Matrix currently. Whenever i click on play random, all goes well as the links load up on the screen. However, as soon as i press on a link, it doesn't play the video.

**Comment by umbrellaplug** [comment]
Logs?

**Comment by ShockStabber13** [comment]
![Untitled](https://user-images.githubusercontent.com/105432148/177199012-d6c38316-a996-4205-9cdc-c63482007272.png)

**Comment by umbrellaplug** [comment]
Okay. Please go to settings on umbrella. Debugging. Enable debug then set debug to extra.info.

Try to play again. Let the error happen. Go to settings debug upload log. Let me know the url of logs from that.

**Comment by ShockStabber13** [comment]
![Untitled](https://user-images.githubusercontent.com/105432148/177204085-b7babe91-7ee5-4dff-88e0-7abe7bd6c773.png)
It's weird cause i never searched for Bill Bellamy. I searched for Kenan and Kel yes.

**Comment by ShockStabber13** [comment]
Btw, this only happens when i play random. I tried it from the series itself, from its seasons themselves .

**Comment by ShockStabber13** [comment]
It opens a dialogue saying "Resolving" but it doesn't open the dialog that says "Opening stream"

**Comment by Wilson-Fisk** [comment]
@umbrellaplug I've actually noticed this same functionality in Kingpin as well, so definitely a base venom problem

**Comment by ShockStabber13** [comment]
Any tips to resolve this issue if it really is a glitch?

**Comment by ShockStabber13** [comment]
What code is Kodi written by may i ask if you know?

**Comment by Wilson-Fisk** [comment]
> What code is Kodi written by may i ask if you know?

python

**Comment by ShockStabber13** [comment]
I dont know much about Python. I'm more into PHP. So many languages so little time i guess haha

**Comment by umbrellaplug** [comment]
Haven't had a chance to look into yet. WIll though and report back.

**Comment by ShockStabber13** [comment]
Much appreciated

**Comment by umbrellaplug** [comment]
Found the issue. it's info being passed from random vs info being passed from select. Will attempt fix in next update.

**Comment by ShockStabber13** [comment]
Hello, thank you for putting my request under consideration :) 
I appreciate it, I really do. Would you mind if i contribute by giving you more suggestions? This itself is another suggestion i guess. Don't worry, don't feel obliged haha.

**Comment by ShockStabber13** [comment]
Oh and btw, i tested it and so far, no bugs. Pretty impressive work!
