### ISSUE TITLE
Frequent umbrella error

### ISSUE THREAD

**Issue by jaimsitecom** [umbrellaplug/umbrellaplug.github.io#120]
Error notifications by umbrella have been appearing frequently lately.  Something about trakt. Is there something i need to enable/disable to stop the error?  Thanks always!

http://paste.kodi.tv/uyoxoqiquz

**Comment by umbrellaplug** [comment]
This error in your log would not cause a notification. Can you try to reproduce the notification then upload a full log? May be worth it to just revoke trakt then re-authorize.

**Comment by jaimsitecom** [comment]
> This error in your log would not cause a notification. Can you try to reproduce the notification then upload a full log? May be worth it to just revoke trakt then re-authorize.

It comes up randomly, sometimes upon opening of kodi, sometimes when scraping, sometimes after finishing a tv show. 

I’ll try revoking and logging back on the trakt inside umbrella setting. Will report if the errors will be gone.
Thanks again!

**Comment by jaimsitecom** [comment]
Revoked and logged back in. After 5-10ish minutes, umbrella error notification flashed. 

Tried to open umbrella log but it said logger isn’t turned on (even of it is). Anyways, i got the kodi log link below:

https://mega.nz/file/8RJzxTbL#HJlo-jqJD4FXqU9wHkJgK2gkCiMO0zZhm2CSxSXwcAs

hope the full log helps. 

Ty!

**Comment by umbrellaplug** [comment]
Unfortunately, not a lot in that log for trakt error. Can you update your tmdbhelper to the latest version? I'm seeing .21 in your log. I'm not having the issue on my side, but I'm using .23 of tmdbhelper.

**Comment by jaimsitecom** [comment]
Updated TMDB HELPER. 

i’ll monitor now. Ty

**Comment by umbrellaplug** [comment]
Anymore issues?

**Comment by jaimsitecom** [comment]
> Anymore issues?

sorry fell asleep awhile ago. Just turned on the kodi again. 

So far so good. will observe for another hour now. Will report in case of error coming up again

ty

**Comment by jaimsitecom** [comment]
Umbrella Error popup hasn’t come up yet so i guess it’s all good for now. Will reopen the iquiry if ever it comes backs later. Thanks so much
