### ISSUE TITLE
Issue downloading from repository on update 6.5.80

### ISSUE THREAD

**Issue by xxflip916xx** [umbrellaplug/umbrellaplug.github.io#121]
https://user-images.githubusercontent.com/117857321/200916640-0e1d5fb2-690f-4c79-a565-b9ee6cb196dd.MOV

**Comment by umbrellaplug** [comment]
script.module.requests is from the default kodi repo. It seems like you may be having issues with your kodi there. Sounds stupid, but you may want to verify that device has internet access.
[](url)
![Screen Shot 2022-11-09 at 1 50 13 PM](https://user-images.githubusercontent.com/107957815/200927445-e156e59c-95e6-4b7f-ab11-b45e561c92c2.png)

**Comment by umbrellaplug** [comment]
Great! Closing issue.
