### ISSUE TITLE
Feature Request: Movies after boxoffice

### ISSUE THREAD

**Issue by mysteryman69** [umbrellaplug/umbrellaplug.github.io#124]
"Discover Movies" > "Movies [released/soon to be released] to disk/streaming" 

the majority of the discover sub folders list movies which are very new and as one would expect, have subpar quality sources. Is there a good way to filter these? Perhaps by pulling a "released to disk" list from some site? I'm not sure exactly where to pull this data, if it is on TMDB, IMDB or Trakt of another source. I would imagine it's on IMDB site ...SOMEWHERE 

I'm aware some movies are available much sooner than others but I'd be happy "missing" a few movies for a month or two than to go through 20 movies that are of unacceptable quality to find one good source. Once they're released to disk/streaming there's a good bet they will be available in acceptable quality. Perhaps adding a "soon to be released to disk/streaming" option as well"

**Comment by adamosborne83** [comment]
Trending trakt is usually a good indication if a movie is of acceptable quality. Out of the first 50 movies on there only Black Panther is sub par...

**Comment by umbrellaplug** [comment]
I'm trying to think of a good way to accomplish this. I wanted to reply and acknowledge the request and let you know it was seen. I will see what I can figure out. I'm not sure yet the best way to do this or if it could be done.

**Comment by umbrellaplug** [comment]
I got with Peter (Fen Developer) and he gave me a few things to try for this. I will be pushing out an update with a new list for this in the next few days.

**Comment by mysteryman69** [comment]
Thanks for the quick turnaround! Loving the plugin! I'll try out the new feature when it rolls out and I'll try adamosborne83's idea too!

**Comment by umbrellaplug** [comment]
This was pushed to the test repo tonight. As long as know issues are found it will be in the next update.
