### ISSUE TITLE
"Playback failed" 

### ISSUE THREAD

**Issue by Slaughterpad** [umbrellaplug/umbrellaplug.github.io#128]

**Comment by umbrellaplug** [comment]
"Playback failed" After selecting a link to play a title, I get a dialog box stating "One or more items failed to play. Check log for more information". However, the selected title has already started playing in the background. When I remove the dialog box by selecting "OK", the movie stops playing. How do I correct this issue with the playback dialog box? 

Moved your title into the comments and renamed. Can you provide a log?

**Comment by umbrellaplug** [comment]
Requested log. Never responded. 

"If your logs are requested and you do not post them within 48 hours your issue will be closed without being looked at."

Closing issue.
