### ISSUE TITLE
Trakt Reauthenticate Issue?

### ISSUE THREAD

**Issue by HashaRock** [umbrellaplug/umbrellaplug.github.io#13]
https://www.reddit.com/r/Addons4Kodi/comments/vr30h1/is_anyone_else_experiencing_trakt_issues_when/

Saw this on Reddit and realized I had the same thing for Umbrella. Is there a fix for this yet? I use the Trakt Addon from the Kodi Repo anyways but its super annoying for the alerts to come up like every 5 seconds.

**Comment by adamosborne83** [comment]
> https://www.reddit.com/r/Addons4Kodi/comments/vr30h1/is_anyone_else_experiencing_trakt_issues_when/
> 
> Saw this on Reddit and realized I had the same thing for Umbrella. Is there a fix for this yet? I use the Trakt Addon from the Kodi Repo anyways but its super annoying for the alerts to come up like every 5 seconds.

Download the newest version 6.5.41, revoke trakt, then clear cache, reauth trakt, make sure you sync then all should be OK.

**Comment by umbrellaplug** [comment]
Yes, the latest version of umbrella resolved this issue. Please make sure you are using Umbrella 6.5.3. Please keep in mind though that if you are running any other clones of Venom that have not been patched you will continue to run into this issue until they are patched. Kingpin has been patched. Umbrella 6.5.40 or higher will have the fix. Another update coming today for a potential fix for episodes not being marked as watched also.

**Comment by HashaRock** [comment]
You are too good Umbrella, thank you!
