### ISSUE TITLE
Source select - tvshows

### ISSUE THREAD

**Issue by Zicster** [umbrellaplug/umbrellaplug.github.io#132]
When I try to change the setting to allow me to select the source for tv shows it doesn't stick when I change it from autoplay to source select and goes back to autoplay when I click ok. I do not want the tv show to autoplay I want to select the source. How do I fix this?

**Comment by Tikipeter** [comment]
Turn OFF `Settings->TV Shows->Continuous Episode Playback Settings->Enable PlayNext popup`.

**Comment by umbrellaplug** [comment]
Working as expected.

**Comment by Zicster** [comment]
Thank you
