### ISSUE TITLE
Split source filtering option (Max Quality) into 2 parts for TV and Movies.

### ISSUE THREAD

**Issue by woodside007** [umbrellaplug/umbrellaplug.github.io#133]
**Feature Request:** Would like the option to set maximum quality in sorting and filters for movies and television shows separately if at all possible.

**Comment by umbrellaplug** [comment]
I'm not sure about this one. It may lead to more settings some people have to set that may further complicate the addon.

**Comment by woodside007** [comment]
No problem. If it's too much of a headache then it probably isn't worth it. I just like to watch movies in 4k and TV shows in 1080p. For some reason TV shows look better to me in 1080p than they do in 4k. I can live with it though. Cheers.
