### ISSUE TITLE
Trakt Collection Not syncing

### ISSUE THREAD

**Issue by mildmanneredjon** [umbrellaplug/umbrellaplug.github.io#134]
On the Firestick the Trakt collections sync function (resources.lib.modules.trakt.sync_collection() ) isn't running.
[umbrella.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10188956/umbrella.log)

**Comment by umbrellaplug** [comment]
Please post the full log.

**Comment by mildmanneredjon** [comment]
This is the Kodi log. The previous was the full Umbrella log
[kodi.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10189070/kodi.log)

**Comment by umbrellaplug** [comment]
Can you try a force sync with trakt from trakt tools in settings?

**Comment by mildmanneredjon** [comment]
Ran the force sync yesterday which brought Trakt collection up to date. But when checking today it hasn't updated for new episodes available today again

**Comment by umbrellaplug** [comment]
Okay. Can you give me an example show I can add so I can attempt to duplicate here? What model fire stick are you using? I may need to go get a fire stick to try this.

**Comment by mildmanneredjon** [comment]
[kodi.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10196342/kodi.log)
[umbrella.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10196345/umbrella.log)

**Comment by umbrellaplug** [comment]
Hey, not sure what happened there but you've got some corruption in your trakt database. Multiple errors in your log for unable to access tables and such. I would delete the file traktsync.db from addon folder and restart kodi and see if it starts to sync again as expected. Lots of writing errors for sqlite in your log for that table. If you need instructions on how to do this from Kodi let me know.

**Comment by mildmanneredjon** [comment]
Hi, yes that's fixed it. Many thanks

**Comment by umbrellaplug** [comment]
Awesome. Glad that helped. Usually corruption like that happens from sudden power loss or two processes trying to write to the same table at the same time. I'll close this issue out. if anymore issues come up feel free to reopen.
