### ISSUE TITLE
[FEATURE] - MdbList and more Trakt options

### ISSUE THREAD

**Issue by TechXXX** [umbrellaplug/umbrellaplug.github.io#136]
Hi Mr. Umbrella, wonderful progress lately! However I'm still depending on TMDB helper for a few of my widgets and I'd love it if I could keep those 'in house' as well. I use Recently Watched TV shows from the Trakt menu item in tmdb helper: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/206912258-00752d79-8218-4190-ab37-c4887776c19a.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/206912291-679953d9-0060-4807-abb0-02c18d6d7c15.png">

I also love the MdbList option in tmdb helper from which I get the 'latest tv shows' list for a widget. The other lists like disney+ are great for widgets too. 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/206912451-51c8fc81-1986-4d40-89cd-048ae0d3e3b3.png">

Preferably I'd like access to all the menu items in Trakt & Mdblist from tmdb helper, some are already present in Umbrella like progress and watchlist but many are missing, the randomized items are cool too. 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/206912595-512e908c-fdae-42f3-97b1-b6b88718ed5c.png">

Right now I have tmdb helper setup with Umbrella as a player but this breaks certain things (next up notification on episodes) and is slower, it would be great to have these inside Umbrella for faster loading and overall stability. Thanks for anything you can do.

**Comment by umbrellaplug** [comment]
More lists are on the radar. Also looking into adding SimKL support and mdblist additions. Would like to provide options for providers and remove requirements.

Recently added these: 
Trending Today and Trending this Week from TMDB (Movies and TV)

Based on Recently Watched (List from TMDB, random watch picked from trakt)
Similar to Recently Watched (List from TMDB, random watch picked from trakt)

The SimKL guys were extremely helpful and are working on getting some trending lists setup for api access as well.

**Comment by TechXXX** [comment]
That's great news, thanks a lot. With the recent troubles on trakt.tv it's an awesome idea to add SimKL. As mentioned I'd like 'Your Recently watched TV Shows' from Trakt to be added, no rush ;).
