### ISSUE TITLE
Auto try next link on resolve failure (Source Select)

### ISSUE THREAD

**Issue by kenta210** [umbrellaplug/umbrellaplug.github.io#138]
I want to suggest an option to turn off the "auto try next link" if the link does not resolve. Thank you :)

**Comment by umbrellaplug** [comment]
Can you explain further? Is this with autoplay sources turned on?

**Comment by kenta210** [comment]
Autoplay sources turned off. Currently using Source Select.

I click on a movie and am shown a list of sources. I click on the first source. A dialog box pops up saying that it is resolving the first source. After waiting, it then auto resolve the next source when it failed to resolve the first one. So im suggesting an option to disable this "auto resolve next source" so that we can go back to Source Select and pick another source to our liking.

**Comment by umbrellaplug** [comment]
Perfect. Thanks for the details. I'll look into it and get back to you.

**Comment by umbrellaplug** [comment]
This will be available in the next version of the addon. I'm putting it under Source Select > "Do not try more than one source on fail"
You can turn this on to disable the auto-retry.

All credit for this goes to Fen Developer @Tikipeter 
He noticed you asking about this on my github and contacted me with an easy way to implement your request.

Thanks!
