### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by opnlms** [umbrellaplug/umbrellaplug.github.io#139]
When i try to do a search in the umbrella addon I keep getting nothing found.

**Comment by opnlms** [comment]
I'm sorry I'm new to this. Can you give me inductions on how to download and update please.  Thank you!--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 12/13/22, 6:57 PM umbrellaplug ***@***.***> wrote:

   
  Search uses trakt. Trakt is down. Download the latest update and switch your search provider in settings to TMDB.

**Comment by umbrellaplug** [comment]
Kodi> Addons > install from repository

Select the umbrella repo and hold. In the pop up menu select "check for updates". From there it should show you the new version of umbrella. You can then just download and it'll overwrote your existing version. Also if you have auto update, It will auto update.

**Comment by opnlms** [comment]
Yes, auto-update is on and the search is showing results now. I'm trying to add a favorite by holding down the select button on a program but doesn't seem to work. It does work on other Kodi addons I use.--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 12/14/22, 5:58 AM umbrellaplug ***@***.***> wrote:

   
  Kodi> Addons > install from repository 
  Select the umbrella repo and hold. In the pop up menu select "check for updates". From there it should show you the new version of umbrella. You can then just download and it'll overwrote your existing version. Also if you have auto update, It will auto update.

**Comment by umbrellaplug** [comment]
Are you using a skin?

**Comment by opnlms** [comment]
I'm sorry, what is a skin?--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 12/14/22, 10:57 AM umbrellaplug ***@***.***> wrote:

   
  Are you using a skin?

**Comment by umbrellaplug** [comment]
A skin is a "theme" for kodi. A lot of people use them. What you are asking about with holding to get the popup is a native Kodi feature called context menu. Context menu will change from one screen to another based on the items you have selected. An example would be a tv show vs a list would have completely different menus when holding select on either of those in a list. I'm not sure why you're context menu wasn't popping up to allow you to add a favorite. What were you trying to add as a favorite?

**Comment by opnlms** [comment]
Thank you for the information. I'm learning. I figured out what the issue was not being able to save a 'favourite'. It was the TV smart remote. The select button on the TV smart remote does not function with the Android TV (Onn/Walmart) box I'm using.
