### ISSUE TITLE
[Feature Request] Silent Scraping

### ISSUE THREAD

**Issue by cboRD181** [umbrellaplug/umbrellaplug.github.io#146]
As far as I'm aware there are 2 options for how the scraping process is displayed: in the foreground or in the background -- meaning, in the top right corner. 

Would it be possible to not display that processing at all? And instead just show the normal loading icon of the skin?

**Comment by umbrellaplug** [comment]
I plan on introducing a new option for scraping screen soon. It was actually the opposite of this, but I'll look into adding an icon only progress window.

Instead of normal loading icon of skin, split the difference and maybe put a single color umbrella icon in corner and let it fill with color as progress bar? Seem like it would work?

**Comment by adamosborne83** [comment]
> I plan on introducing a new option for scraping screen soon. It was actually the opposite of this, but I'll look into adding an icon only progress window.
> 
> Instead of normal loading icon of skin, split the difference and maybe put a single color umbrella icon in corner and let it fill with color as progress bar? Seem like it would work?

Chop Chop

**Comment by cboRD181** [comment]
> I plan on introducing a new option for scraping screen soon. It was actually the opposite of this, but I'll look into adding an icon only progress window.
> 
> Instead of normal loading icon of skin, split the difference and maybe put a single color umbrella icon in corner and let it fill with color as progress bar? Seem like it would work?

Sounds good to me! I know it's a small thing, but I try to keep the complexity that the end-user interacts with to a minimum.  

Like, if I share a Kodi configuration with a family member, it can be a bit overwhelming for them when they just want to watch a movie/show: opening the app presents them with a lot of unfamiliar and unintuitively named components, e.g. Kodi logo splash screen -> Kodi Matrix splash screen -> Arctic Horizon 2 loading screen -> after clicking on a movie, Umbrella scraping dialogue -> finally the movie.  

At the same time, I get that you and other contributors have put a lot of effort into your addons, so it makes sense that you'd want the work they do to be acknowledged with a recognizable name/logo.  I've just had a lot of what's kodi? what's matrix? what's AH2? what's umbrella? what's scraping? questions and it seems like it detracts from the experience a bit, haha.

**Comment by umbrellaplug** [comment]
This is in testing. It should be available in the next version on source dialog > icon only.
