### ISSUE TITLE
Tv select action not working

### ISSUE THREAD

**Issue by Lala1976** [umbrellaplug/umbrellaplug.github.io#147]
When i change "tv select action" to source select and hit ok, then return, it's changed back to auto.
Can't change it.

I'm on kodi 20 RC1

**Comment by umbrellaplug** [comment]
Turn OFF Settings->TV Shows->Continuous Episode Playback Settings->Enable PlayNext popup.

**Comment by Lala1976** [comment]
Continuous Episode Playback Settings is OFF, and PlayNext popup is enabled.
Still can't change tv selection action, and when i try to play an episode it still starts playing automatically, can't choose a source myself.

**Comment by umbrellaplug** [comment]
> Continuous Episode Playback Settings is OFF, and PlayNext popup is enabled.
> 
> Still can't change tv selection action, and when i try to play an episode it still starts playing automatically, can't choose a source myself.

That's impossible. Continuous playback is the section in the settings enable playnext is the actual setting. There's literally text on the setting telling you it will force back to auto play if enabled. 

If playnext is enabled, autoplay is forced on. Turn off playnext, then set back to source select for tv and it will stay that way. If you enable playnext again it's going to force autoplay back on. This is working as intended.

**Comment by Lala1976** [comment]
For some reason autoplay in kodi itself (in the player section) is always turning back to episodes enabled.
Don't no why

**Comment by umbrellaplug** [comment]
It's because you enabled playnext.

**Comment by Lala1976** [comment]
Thanks that dit it. Turned kodi on to englisch, had it on Dutch.
