### ISSUE TITLE
[Feature Request] Next Up window - Percentage instead of time left

### ISSUE THREAD

**Issue by juniorpainkiller** [umbrellaplug/umbrellaplug.github.io#151]
Hello! Have you thought about making this feature available? I've been using it on another addon and it would be great to have it here.  For example when I set it at 98% progrees, usualy the Next Up window shows few seconds before/after credit roll starts.
Thanks for your effort so far. btw. Your addon's great. Cheers!

**Comment by umbrellaplug** [comment]
This feature is already coming in the next update. It will be available soon. I didn't want to push a new release on Christmas.
