### ISSUE TITLE
My TV Shows > Progress; All episodes time is 0 mins or 1 mins with Trakt Direct Progress Scraping setting enabled

### ISSUE THREAD

**Issue by MagicFirefly** [umbrellaplug/umbrellaplug.github.io#152]
Kodi 19.5 / Skin: Arctic Horizon (Original) 0.5.75 / Device: Nvidia Shield 2019 / Umbrella: 6.5.98

When the setting for Trakt **Direct Progress Scraping** is enabled the My TV Shows Progress shows all episodes time is either 0 mins or 1 mins. When the setting is disabled the progress episode displayed continues to display 0 mins or 1 mins, however selecting the episode to go into the episodes list shows correct episodes time.

**Comment by umbrellaplug** [comment]
I've looked into this. I'm seeing some strange behavior on my side also but I do not have the same results in estuary. I've reached out to Jurial to see if there is a value he needs me to assign to show this and I'm awaiting a reply. I'm setting duration in the code on the items so I'm at a loss for why ah2 isn't showing the correct times or any times.

**Comment by umbrellaplug** [comment]
Found the issue. Will be fixed in next update.

**Comment by MagicFirefly** [comment]
Appreciate the research. Looking forward to the update. Thanks!

**Comment by umbrellaplug** [comment]
Just pushed version 6.6.02. This should be resolved with this version.
