### ISSUE TITLE
Feature Request: Option to hide the "Cancel" button when Scraping and Resolving

### ISSUE THREAD

**Issue by Spark-NV** [umbrellaplug/umbrellaplug.github.io#153]
Would it be possible to add an option to hide/disable the cancel button when its scraping AND during the "Resolving" screen?

My aunt sometimes double clicks with her remote on accident often and that will cause the movie to cancel as you would expect, but obviously not meaning to cancel it. 

An option that either hides the button to cancel or just greys it out making it un-clickable would be awesome.

![Screenshot 2022-12-26 152434](https://user-images.githubusercontent.com/38028193/209586377-42c4d6b9-ee70-4a3b-a934-3426cd7f484e.png)

**Comment by umbrellaplug** [comment]
This could potentially put you into a state where you'd be stuck if it froze while resolving. I've added an "icon only" scrape option in the latest update. It should be out today.
