### ISSUE TITLE
Playing incorrect episodes

### ISSUE THREAD

**Issue by juniorpainkiller** [umbrellaplug/umbrellaplug.github.io#155]
I'm currently watching That Mitchell and Webb Look series. In 4th season it plays episodes from season 1. So I tried to clear cache and everything, but nothing helped 
Later I installed Zen addon to try and it worked. I'm relatively new to Kodi and not sure if this is an  common  for all addons, just with different series. Something similar I've expirienced with Love, Death & Robots.

**Comment by umbrellaplug** [comment]
Uploaders have uploaded the file under the wrong name. Unfortunately, we cannot fix that.
