### ISSUE TITLE
Trakt watchlist issue

### ISSUE THREAD

**Issue by leemacca13** [umbrellaplug/umbrellaplug.github.io#156]
Hi so I seem to be unable to rearrange the order in which my tv show watchlist from trakt is displayed, no matter what settings I seem to change in the umbrella settings it is always displayed with the most recent shows at the top and the oldest at the bottom. Ideally I'd like to be able to have this the other way around. But weirdly my movie list seems to work fine apart from it showing movies I've added that won't be released until next year. 

Thank you in advance for your help and the hard work you put in especially this most recent update. Thank you.

**Comment by umbrellaplug** [comment]
This is in your settings. You need to change the setting to be Settings> TV Shows > Watchlist Sorting

**Comment by leemacca13** [comment]
Thank you for this I had just changed the setting in the general tab I didn't realise the was a setting in tv shows as well. Very sorry.

**Comment by umbrellaplug** [comment]
No worries, glad I could help.
