### ISSUE TITLE
Unreleased movies appearing in Trakt watchlist

### ISSUE THREAD

**Issue by leemacca13** [umbrellaplug/umbrellaplug.github.io#157]
Hi I just wondered is it possible to hide unreleased movies from my movies watchlist from trakt? I have ticked the hide movies in cinema option but I'm still seeing movies on my watchlist not due to be released until 2023 and 2024.

**Comment by adamosborne83** [comment]
Just me over thinking things......... but, if you don't want to see movies in your Trakt list that haven't been released yet, why even add them into Trakt? Surely that's an easier step?

**Comment by umbrellaplug** [comment]
I know there is an option for hiding movies in cinema butt I'm not sure if that applies to trakt list or not. I'll look over the code and see if I can give you a more definite answer.

**Comment by umbrellaplug** [comment]
This will be fixed in the next update.

**Comment by umbrellaplug** [comment]
in update 6.6.10
