### ISSUE TITLE
Small question regarding colors

### ISSUE THREAD

**Issue by SirRickie** [umbrellaplug/umbrellaplug.github.io#158]
My scraper progress dialog is set to foreground. Scraper dialog highlight color is set to fuchsia and high light color (under general) is set to Lime. So in the progress dialog I have a combination of these 2 colors, which I like.
But when I set the progress dialog to Full Screen (which I like a lot) and I don't change the colors (they remain fuchsia and lime), all the results in the dialog are in fuchsia (no items such as 4K, 1080p, are in Lime anymore). Am I doing something wrong or do I miss something ?Tnx.

**Comment by umbrellaplug** [comment]
Full screen uses only the scraper dialog color. I can make some changes to that. I've got an update coming with more simkl stuff added very soon. I'll get this added before I push that one.

**Comment by SirRickie** [comment]
Great. Tnx.

**Comment by umbrellaplug** [comment]
Just pushed version 6.6.02. Changed new screens to use the highlight color and scraper dialog in the same context as the previous ones did.

**Comment by SirRickie** [comment]
Awesome. That's exacty what I was asking for. Looks great. Btw, Umbrella has really become my number one addon. It's the best since many years (amazingly quick). All the best for 2023.
