### ISSUE TITLE
[BUG] Progress episodes not playing

### ISSUE THREAD

**Issue by leemacca13** [umbrellaplug/umbrellaplug.github.io#159]
Have updated to 6.6.01 and seem to be having trouble getting episodes to play from the progress section of shows. It seems to sometimes let me play one show out of say maybe four. This is the same whether I use a widget or go directly into the addon. I have tried force closing and clearing the cache but seems to make no difference. I'm using kodi 19.5 and the Auramod skin. 

I have attached a log if that is any help for you. 

https://paste.kodi.tv/oyehubakuh

**Comment by umbrellaplug** [comment]
Can you see if you have the same result outside of your skin? I'm seeing invalid handler and a lot of python errors in your logs.

**Comment by leemacca13** [comment]
I've just tried using the confluence skin and have the same problem.

**Comment by umbrellaplug** [comment]
What provider are you using? It seems you've got something else going on here. I'm able to get every show on my progress in one try from multiple devices. Are you on a vpn?

May be worth it to clear your cache from plugin and try pulling in progress again.

**Comment by leemacca13** [comment]
Using real debrid and not using a VPN, I have seren installed as well and that seems to be pulling in things ok. But I will clear out the cache and see if that helps.

**Comment by leemacca13** [comment]
So I cleared the cache and it worked ok for a couple of shows but then the same problem happened. I then went into the settings and changed the scraper progress dialog from full screen back to foreground and that seems to have stopped it happening.

**Comment by umbrellaplug** [comment]
Okay. So it was from full screen progress using my tv shows > progress 

I will see if I can duplicate it here. Can you grab a new log so I can try to match up what you were watching and source and all that.

**Comment by leemacca13** [comment]
Yeah that's correct, 

Of course, do you want me to switch the option back to full screen whilst I do the new log or keep it as foreground?

**Comment by umbrellaplug** [comment]
That's would be great. It's going to be some type of meta not being passed into that screen so that would help.

**Comment by leemacca13** [comment]
Hopefully this will be ok for you. I tried 3 different shows and each one failed to open. 

https://paste.kodi.tv/ezudoyuken

**Comment by umbrellaplug** [comment]
Perfect thanks. You've found some type of bug with full screen scrape. I'll check it out and try to get an update out to patch it.

**Comment by leemacca13** [comment]
That's great, thank you for your help.

**Comment by umbrellaplug** [comment]
Just pushed version 6.6.02. This should be resolved with this version.

**Comment by leemacca13** [comment]
That's great thank you for your help. I updated and have been trying it out today. So far it all seems to be working great with no issues. Thanks again.
