### ISSUE TITLE
[BUG] Movies and Shows named dumb shit have issues creating strm file

### ISSUE THREAD

**Issue by umbrellaplug** [umbrellaplug/umbrellaplug.github.io#160]
### Bug

Adding movies or shows to library with special characters at the beginning result in a "." being used for the start of the .strm file which makes it hidden.

### Expected Result

The strm file should not be hidden.

### Steps To Reproduce

Add a movie with some stupid ass name to your library.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by adamosborne83** [comment]
If you want a quick fix, just go into kodi settings and allow Hidden Files, then it will scrape.
You're welcome
