### ISSUE TITLE
[FEATURE] Play Directly from TV Show

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#161]
### Feature

Look into changing default select action on TV Show View. (Container.ListItem.DBTYPE tvshow, Container.Content tvshows)

### Is this feature available already in another plugin?

FEN

**Comment by umbrellaplug** [comment]
Coming up on the list. Thanks for your patience.

**Comment by adamosborne83** [comment]
Thanks

**Comment by umbrellaplug** [comment]
Looked at this. It will need to be done using an extras screen the same as Fen or other addons. It's been added to the list of possible features,  but this issue is quite old and I'm going to close it now.
