### ISSUE TITLE
Unlike lists

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#162]
It's not a big deal, but I tried to unlike some Liz today and it failed to unlike any of them just reporting it. There is no log error.

**Comment by Arthur1967** [comment]
Lists

**Comment by umbrellaplug** [comment]
Trakt lists?

**Comment by umbrellaplug** [comment]
No response, No logs.

**Comment by Arthur1967** [comment]
Yes, it was a Trakt list but it gave me no log. It just said failed but then when I went back into it after I open, Kodi,they were gone. But while it was doing it, it said failed but like I said they were gone when I went back into Cody. Thank you.
