### ISSUE TITLE
Scraping

### ISSUE THREAD

**Issue by Alex20090313** [umbrellaplug/umbrellaplug.github.io#164]
After I scrape it takes long for source select to come up, I'm using a Apple TV 4K 2022 128gb and after the latest update, every time I click on a show and it scrapes it try to get the source it does not pop up right away like it use to prior to the update now it takes time, it may take 5 min to pop up and sometimes after it pops up and you click on the show it will pop up while watching the show and when you back out it will display a source error

**Comment by umbrellaplug** [comment]
No logs attached.

**Comment by Alex20090313** [comment]
How do I attach logs from Apple TV to here there is no way to send them over

**Comment by Alex20090313** [comment]
https://vimeo.com/785272506

This is the issue that is happening
