### ISSUE TITLE
Not finding streams using Real Debrid on Apple TV 4

### ISSUE THREAD

**Issue by Fowly33** [umbrellaplug/umbrellaplug.github.io#166]
### Bug

Using Apple TV 4.  I have programmed my own as well as my son’s.  I have Android devices as well and we both use Real Debrid. Umbrella (Fen too) does not work on this device. RD is authorized on both but both will not bring up any streams. Other addons are working with Debrid (Seren, The Promise, Homelander etc.). I prefer to use Umbrella. 

### Expected Result

I expected streams to appear. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Can you grab a log from one of the devices doing this? There's a way to upload logs built into the addon and instructions for doing it can be found on here.
