### ISSUE TITLE
[BUG] Cached Links doesn't work in Source Select

### ISSUE THREAD

**Issue by psp2111-ADSLGATE** [umbrellaplug/umbrellaplug.github.io#168]
### Bug

Hi
I am on the latest Umbrella version 6.6.01.
Source Select work fine for first attempt to search for links and choosing one.
but if I close it and start search again or want to choose a different link, non of the links work anymore and the only fix is to delete the cache from the settings

### Expected Result

cached links should work the same as first attempt 

### Steps To Reproduce

1. choose any movie or episode
2. start searching for links
3. close the Source Select window
4. start searching again
5. non of the links will work

### Logs, Screenshots, and Additional Info

Windows 10
Kodi 19.5
Umbrella 6.6.01
Arctic Horizon 2 

I will upload my debug log if needed or if you cant reproduce the BUG

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Thanks for the bug report. I had actually already found this one and it has been fixed. I'll be pushing an update soon for this. In the meantime, you can get around it by using background or foreground scrape instead of fullscreen.

**Comment by umbrellaplug** [comment]
Just pushed version 6.6.02. This should be resolved with this version. Let me know if you have issue still.

**Comment by psp2111-ADSLGATE** [comment]
Thanks for the fast reply and the hard work
