### ISSUE TITLE
[FEATURE] Add "return to previous page" button to source select for touchscreen users

### ISSUE THREAD

**Issue by Loccy** [umbrellaplug/umbrellaplug.github.io#169]
### Feature

Would it be possible to add a button onto the source select screen that would effectively go back a page (i.e. to wherever you selected the movie/episode from, same as the back button would at that point?). I often use Umbrella on a Microsoft Surface with the keyboard unclipped or folded back. If I'm on the source select screen and change my mind about playing something right now, I have to re-attach my keyboard to hit the backspace or escape key.

I'd suggest just a simple back button at the top left of the screen - unobtrusive, probably wouldn't be noticed by many, but very useful to us touchscreen deviants :)

### Is this feature available already in another plugin?

Seren has a "Close" button on their source select screen.

**Comment by umbrellaplug** [comment]
Thanks for the suggestion! I will add an option to show a close button on the source select screen for you.

**Comment by umbrellaplug** [comment]
Hey, just wanted to check with you. I was looking into this and noticed I can capture gestures as actions in kodi. I was wondering if instead of adding a button a swipe left to cancel gesture would work?

**Comment by Loccy** [comment]
In my use case, it would if the touch/gesture system on Kodi remotely worked under Windows. Unfortunately, I don't think it does - it sees touches as mouse clicks. Gestures to navigate things like skipping etc have never worked in Windows for me, so I suspect this wouldn't either. Would probably work well on Android though (but no help to me unless they fix gestures/touch in Windows)

**Comment by umbrellaplug** [comment]
Completed will be in next update.
