### ISSUE TITLE
Idea (Not obligation): Show full episode from all seasons playlist when clicking on episode.

### ISSUE THREAD

**Issue by ShockStabber13** [umbrellaplug/umbrellaplug.github.io#17]
I really like how Seren has a feature where you can play from random episode. Hence, i have an idea for your impressive plugin. When you click on "Play from here", it shows the complete playlist of all the episodes of all seasons. However, it doesn't do that when you click from "Play Random". I think you can do one better by implementing a playlist feature at the sidebar of the video player whenever someone clicks on "Play Random". The playlist will show episodes from all seasons. This way, we can shuffle the playlist and do basically anything we want with it. That'd be pretty amazing. Just an idea, no obligations, no pressure haha. Lemme know yea?

**Comment by umbrellaplug** [comment]
I'm not 100% convinced on anymore work on the play random feature honestly. I will put it as a possibility for something to work on but for now priority for me is trying to fix bugs and keep features working. Not saying it's a bad idea, just not something I will make any promises to at this point. I will look at the differences between play random and play from here.
