### ISSUE TITLE
[FEATURE] Trending Recent Movies

### ISSUE THREAD

**Issue by hobbit200** [umbrellaplug/umbrellaplug.github.io#171]
### Feature

It would be great if you could add a Trending Recent Movies list like the one that exists in Seren. The current trending lists include movies that are not always recent.

Thank you for a wonderfull addon.

### Is this feature available already in another plugin?

Seren

**Comment by hobbit200** [comment]
Yes something like that whould be awasome.

**Comment by umbrellaplug** [comment]
Completed. Will be in next update.

**Comment by hobbit200** [comment]
Than you very much. Your hard work is  truly appreciated.
