### ISSUE TITLE
[FEATURE] Option to autoscrape next episode from play-next popup

### ISSUE THREAD

**Issue by ewan58385** [umbrellaplug/umbrellaplug.github.io#173]
### Feature

An option to autoscrape the next episode from the play-next dialogue (instead of autoplaying the top source) would mean those who prefer to choose their sources (in case the auto-chosen link is broken) doesn't have to back out of the video OSD to choose from a source manually :) 

I love the new AH2 style option, but I cannot use it as I always like to choose my source. 

### Is this feature available already in another plugin?

Avalible in Fen & Seren, maybe more.

**Comment by umbrellaplug** [comment]
This feature has been requested before. I'm sorry but this is a much larger request then people realize. I'm open to requests, but this is not one I'm willing to take on now.

Maybe in a later update, but currently there are no plans to do this.

**Comment by psp2111-ADSLGATE** [comment]
how about if you make it AUTO play next episode when choosing a "Pack" source?

that way we only use Source select window for the first episode in the "pack" then at the end of the episode play next pop up and ask me to automatically play the next one in the same pack. and of course play next wont show up for single episode sources.

idk if that even possible or easier than @ewan58385 request.
