### ISSUE TITLE
[FEATURE] Remove hardcoded blue text from context menu

### ISSUE THREAD

**Issue by Stanton** [umbrellaplug/umbrellaplug.github.io#176]
### Feature

The [blue text in the context menu](https://github.com/umbrellaplug/umbrellaplug.github.io/blob/master/matrix/context.umbrella/addon.xml#L9) doesn't play well with the provided dark theme, providing a rough 1.8:1 contrast ratio which is difficult to read.

Recommend removing the colour value, allowing the user's UI text colour to style it to compliment the light/dark theme, as I suspect the setting in `General > Highlight Color` won't apply here.

<img width="471" alt="Screenshot 2023-01-06 at 09 31 25" src="https://user-images.githubusercontent.com/18653/210973297-27cfe0cc-8046-4ab4-bc78-f1f6379b317f.png">

**Comment by umbrellaplug** [comment]
Changed to allow for highlight color to be used instead. Will be available next update.
