### ISSUE TITLE
[FEATURE] playnext percentage trigger increments 

### ISSUE THREAD

**Issue by IG2022** [umbrellaplug/umbrellaplug.github.io#177]
### Feature

Hey there. I'm really enjoying the major updates you've recently released with umbrella it's looking great and working really well! 

I wanted to ask if it would be possible to have smaller increments for the playnext percentage trigger option. Right now the increments are 5 percent, would it be possible to drop those down to increments of 1 percent? 95 percent seems to be a little too early for the trigger the next episode and 100 percent is too late. I'm hoping to set it at 97 or 98 percent. 

Thanks!

**Comment by umbrellaplug** [comment]
Changed to a 1 step instead of 5 step. It will be available in the next update.

**Comment by IG2022** [comment]
> Changed to a 1 step instead of 5 step. It will be available in the next update.

Thanks!
