### ISSUE TITLE
No easy news links

### ISSUE THREAD

**Issue by Slivovitsa** [umbrellaplug/umbrellaplug.github.io#18]
Thank you for your awesome work on this addon. But I had problem. Realdebrid work like a sharm.  But easynews doesn't. It doesn't show me any link of easynews. Boath RD and EN I set it up correctly in Account settings of Umbrella addon (same in My Accounts addon). Can someone confirm for me that easynews works in Umbrella addon or does this problem only happen to me. Thank you.

**Comment by umbrellaplug** [comment]
I'm looking into this. I currently have only been able to get it to work from premium services section. I will see what I can find.

**Comment by umbrellaplug** [comment]
This should be resolved in the latest update. Please make sure to clear your provider cache after adding in easy news in my accounts module and enabled in umbrella scrapers.

**Comment by Slivovitsa** [comment]
Thank you very much. After latest update now easynews works. Thanks again.
