### ISSUE TITLE
Library tmdb.

### ISSUE THREAD

**Issue by Greg0580** [umbrellaplug/umbrellaplug.github.io#181]
### Bug

Just want to report that Tmdb TV import/s is Not importing,  TV Favorites, watchlist . I am using a Firestick Max.  

### Expected Result

I just wanted to report the fault.  I think it is the fault is with tmdb.  The Movie section is importing both favorite and watchlist. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Where are you seeing an option to import a tmdb list? I see the tmdb list in my tv shows, but I don't see any options to import the list.

This is why the issue form asks for the steps to reproduce the issue, but I see you skipped that and didn't attach logs.

**Comment by Greg0580** [comment]
Under tools/ Umbrella:Library



Sent from my Galaxy



-------- Original message --------
From: umbrellaplug ***@***.***>
Date: 8/01/23 16:25 (GMT+12:00)
To: "umbrellaplug/umbrellaplug.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [umbrellaplug/umbrellaplug.github.io] Library tmdb. (Issue #181)


Where are you seeing an option to import a tmdb list? I see the tmdb list in my tv shows, but I don't see any options to import the list.

This is why the issue form asks for the steps to reproduce the issue, but I see you skipped that and didn't attach logs.

**Comment by umbrellaplug** [comment]
Not a bug, this feature was de-activated when the list import manager window was added. TMDb list imports will be re-added into the import manager window eventually.
