### ISSUE TITLE
[FEATURE] Prioritise Normal and SDH subtitles over Forced subtitles

### ISSUE THREAD

**Issue by kenta210** [umbrellaplug/umbrellaplug.github.io#182]
### Feature

Currently, when subtitles setting is enabled, the default available english subtitle from stream will be used. However, when the stream has Normal, SDH and Forced subtitles available, it tends to choose the forced subtitles over the rest. Is it possible to prioritise the Normal and SDH subtitles over the Forced subtitles?

**Comment by umbrellaplug** [comment]
This is a kodi setting. Kodi Settings> Player > Language > Preferred Subtitle Language. Set it to your language instead of forced.
