### ISSUE TITLE
[BUG] playnext library

### ISSUE THREAD

**Issue by djdirty60** [umbrellaplug/umbrellaplug.github.io#183]
### Bug

Good day,

Unfortunately, when I look through the library, playnext doesn't work, but if I watch via the addon itself, it works.

Could you look at this

Thanks in advance

### Expected Result

…

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Playnext is current not supported using library.
