### ISSUE TITLE
[BUG] AH2's Episode selector starts Tmdb helper 

### ISSUE THREAD

**Issue by TechXXX** [umbrellaplug/umbrellaplug.github.io#190]
### Bug

If you start a TV episode and near the end (mind you this is without playnext/autoplay enabled) and you want to play the next episode you press down to enter the episode scroller, you find the next episode and click it, it then fires up tmdb helper to try and play the episode. This works but there are a few negatives here, namely the speed loss when the 'building player dialogue' of tmdb helper pops up and it also breaks a4ksub's auto subtitle search feature. I thought this was an AH2 issue, Jurialmunkey begged to differ, see his reply on below opened issue: 

https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/739

### Expected Result

Stay within Umbrella while selecting other episodes in the ah2 episode selector

### Steps To Reproduce

start tv show - play episode - press down to enter episode scroller - select next episode - tmdb helper dialogue pops up 

### Logs, Screenshots, and Additional Info

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/212095315-528a32b4-dc28-47dd-b4e4-e8bc623bd930.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/212095412-01e0c265-e058-4a75-ace4-f9f7a45f979b.png">

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I noticed Jurial's response to this issue previously as well and did not understand the actual issue till you posted here. Seeing what you posted, that's not something I believe I can fix. The widget you're launching from when you go to that episode scroller is built by your skin, that's why it's calling tmdbhelper. I do not have any control of that. Jurial responded about building a playlist within the addon for multiple episodes. That's exactly what the playnext setting does in the addon. If you're not using playnext and you want to use that widget to manually go to each episode it's going to use tmdbhelper.

**Comment by TechXXX** [comment]
Yeah non native speakers will want to do source select every time in order to select a source for which a subtitle file is more likely to be present. I can get away with playnext because I only use english subs but for family and friends this isn't an option. I'll relay what you said to Jurial, I was hoping it could be solved in a similar fashion as with the search paths in AH2 but I guess it's a bit more complicated.

**Comment by umbrellaplug** [comment]
I don't know if you're paying attention on the Jurial side of this, but what he's saying is that widget uses playlist sent by addon if it doesn't find one, it uses playlist from tmdb. The addon does not build a playlist if playnext is not turned on. The changes required to adjust for this are not something I'm willing to commit to currently. Hard truth is it's just more work than it's worth. Maybe down the road or if I can think of an easier way to handle it. I'll put some thought into it, but don't get your hopes up.

**Comment by TechXXX** [comment]
Yessir I'm watching it like a hawk, as per usual anything you can do will be appreciated and if not, no hard feelings, just trying to make it work better/faster and removing tmdb helper from operations will definitely do that. 

Did this comment by Jurial make sense to you? It's too technical for me obviously: 

_"I think you can still autoplay if you use setresolvedurl() - just set a param in your playback path which routes your playback method to whatever method allows selecting a source. Then pass the source selected to setresolvedurl and it should work.

That's the point of setresolvedurl - to do some other work to decide (resolve) the url to be used for playback before giving it to kodi"_
