### ISSUE TITLE
Scraping windows

### ISSUE THREAD

**Issue by Lala1976** [umbrellaplug/umbrellaplug.github.io#191]
### Bug

There's just one thing still.
In the scraping window ,you can't see the amount of sources.  Behind the sources 4k-1080p-720p-sd there is no text. That's the only thing I can find that still isn't ok.

### Expected Result

Fix scraping window

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Settings > Source Options > Scraper Dialog Highlight Color

**Comment by Lala1976** [comment]
No when it's done scraping and you see all the sources that's ok, but when it is scraping the little window that comes up and counts all the sources it's finding, there is no text, only behind 4k ,but the counter stays at 0. Behind all the other sources there is no text and it doesn't count.

It's not a problem ,just thought you'd want to know. ;)

**Comment by umbrellaplug** [comment]
Did you try setting that scraper dialog highlight color? I changed mine to yellow and tried in full-screen, background, and foreground and it's working.

![Screen Shot 2023-01-12 at 11 24 32 AM (2)](https://user-images.githubusercontent.com/107957815/212136647-06b2e58e-6a91-42ec-8202-c32a90963e36.png)
![Screen Shot 2023-01-12 at 11 23 25 AM (2)](https://user-images.githubusercontent.com/107957815/212136649-e68fb9f2-ebe8-4e1e-9f64-a91f028dd20f.png)
![Screen Shot 2023-01-12 at 11 18 21 AM (2)](https://user-images.githubusercontent.com/107957815/212136650-05aa5f2d-b40d-49de-a478-08eca9ab688a.png)

**Comment by Lala1976** [comment]
White works to.
Maybe set it as a default on a different color, for the next update.
Thanks for the quick respond
