### ISSUE TITLE
Plexshares not visible on Cocoscraper

### ISSUE THREAD

**Issue by diimaan** [umbrellaplug/umbrellaplug.github.io#192]
<img width="1183" alt="cocoscrapers-log" src="https://user-images.githubusercontent.com/3683925/212187769-1253f152-af07-4c13-8cb6-dd2b4f90a81d.png">

Hi with the new cocoscraper version, I have added my plex id. But it did not ask me any shares to select. So I checked settings in cocoscraper but it showed an error when I tried show active shares or select (re)select shares. I enabled debug log and opened it again. This is what I am getting.

Not sure this should be logged with the scraper dev or here. Feel free to close this and redirect me in case if you want this to be on scraper dev's issue!

**Comment by umbrellaplug** [comment]
Try 1.0.9
