### ISSUE TITLE
Continuous source select.

### ISSUE THREAD

**Issue by TheGuyWhoo** [umbrellaplug/umbrellaplug.github.io#195]
### Feature

I was wondering if this is already possible, or something you would be willing to look at? 

So basically all the benefits of autoplay, but instead of automatically going to the next episode it automatically goes to the next source select screen.

### Is this feature available already in another plugin?

Seren

**Comment by umbrellaplug** [comment]
This request has been made many times. It's a large amount of work for one feature and not something I want to spend the time and effort required to change at this point.

**Comment by TheGuyWhoo** [comment]
No worries mate, it saves two clicks so it's not a big deal.
