### ISSUE TITLE
Personal trakt list does not sort correctly.

### ISSUE THREAD

**Issue by TheGuyWhoo** [umbrellaplug/umbrellaplug.github.io#196]
No matter what I do, I can't get it to sort according to the default sort method I set in trakt. I've been over the sorting options in TV settings but it's just not sorting correctly. It always sorts according to date added, regardless of any setting I change inside of umbrella.

**Comment by TheGuyWhoo** [comment]
For transparency's sake I feel I should mention I'm going to be trying out library integration tomorrow, so it might not end up being an issue for me.

**Comment by adamosborne83** [comment]
> No matter what I do, I can't get it to sort according to the default sort method I set in trakt. I've been over the sorting options in TV settings but it's just not sorting correctly. It always sorts according to date added, regardless of any setting I change inside of umbrella.

Addon Sertings.
Tv Shows.

Scroll down towards bottom, Shiw Sorting DEFAULT.
Watchlist sorting DEFAULT.


If you want movie trakt lists changed then, 

General 
Down to My Movies and List options.

Then change all to default.

**Comment by TheGuyWhoo** [comment]
Yup, done all that.

https://user-images.githubusercontent.com/72744967/212542041-0026d1d5-0dcc-43b1-82ca-e5b331e29572.mp4

**Comment by TheGuyWhoo** [comment]
Sorry for how jumpy it is.

**Comment by umbrellaplug** [comment]
Hey can you try clearing your cache between changing the sorting settings? Lists are cached. See if sorting changes after clearing cache. I will try it on my side as well.

**Comment by TheGuyWhoo** [comment]
I actually did right before I took the video, I can confirm clearing cache does not have an effect. I will quickly make another, just going to go fix myself some coffee.

**Comment by umbrellaplug** [comment]
No worries, it's also a slower day for me. I'm checking this out now, I just managed to drag myself to the computer. Give me a bit to read over your issue and watch the video and try to duplicate it.

**Comment by TheGuyWhoo** [comment]
https://user-images.githubusercontent.com/72744967/212548367-f8f7e7a6-a33d-45e6-923f-958358b0501a.mp4

Since I've already made it I thought I'd share it anyways. Very glitchy, sorry. The screen recorder tried warning me but I didn't listen.

**Comment by TheGuyWhoo** [comment]
Oh and thank you for taking a look, like I mentioned earlier there's no rush.

**Comment by umbrellaplug** [comment]
I'm only seeing an issue with date watched sorting on tv shows. Change it to or anything else and see if it changes. You do not need to clear cache. I'm looking into why date watched doesn't work now.

**Comment by TheGuyWhoo** [comment]
Yes I can corroborate that, only date watched isn't working.

**Comment by umbrellaplug** [comment]
Next update will have a fix for this.

**Comment by umbrellaplug** [comment]
in update 6.6.10
