### ISSUE TITLE
[FEATURE] Font color of RD auth.

### ISSUE THREAD

**Issue by TechXXX** [umbrellaplug/umbrellaplug.github.io#197]
### Feature

Just a little improvement, the real-debrid code is hard to read, could we get that in a red font please? And if you're bored (hah, fat chance eh) I'd really dig that feature Seren has where it automatically copies the code to clipboard. 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/212675648-fa533c5a-a455-4781-80cf-6e041ace8f35.png">

**Comment by DROIDshield** [comment]
Think your using the same skin as me AH2 ? You can goto settings>Skin>Colours  I set mine to HighContrast+Darker setting.

You can see everything clearly using this skin that way.

**Comment by DROIDshield** [comment]
![Uploading 20230116_134500.jpg…]()

**Comment by DROIDshield** [comment]
![20230116_134500](https://user-images.githubusercontent.com/97023369/212693177-a288c526-8625-4365-8f69-34d506c4a92f.jpg)

**Comment by TechXXX** [comment]
yeah that's why I opted for red or maybe orange is better, then we should both be able to see it ;)

**Comment by TechXXX** [comment]
until someone shows up with a red skin, but that would be racist I'm sure

**Comment by umbrellaplug** [comment]
Next update will use highlight color for these codes. Copy to clipboard added.

**Comment by TechXXX** [comment]
that's awesome! thanks a lot

**Comment by umbrellaplug** [comment]
in update 6.6.10
