### ISSUE TITLE
[BUG] unaired season of tv show appears on library

### ISSUE THREAD

**Issue by jaimsitecom** [umbrellaplug/umbrellaplug.github.io#198]
### Bug

Since Version 6609, one particular tv show in my case ‘SLOW HORSES’, umbrella keeps on downloading the whole season 3, even if it’s not even made. 😀

had to go downgrade to avoid the annoyance of downloading the said season 3 every library updates and then deleting them everytime it gets placed in the library. 

Is there a new setting i have to enable/disable to stop it?  I thought i went thru every possible setting for tv show seasons but nothing worked. 

thanks in advance!

### Expected Result

Hoping the bug gets squashed and the unaired whole season/episodes don’t get added in the library anymore. 

### Steps To Reproduce

To reproduce the bug, try adding the tv show SLOW HORSES into the kodi library. There are 2 finished seasons that were aired recently. But no season 3 yet.  Then expect the whole season 3 to get added the next time library updates. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Bad metadata. All 6 episodes of season 3 show released 1/13

**Comment by umbrellaplug** [comment]
I was able to clear all cache, uncheck include unaired episodes, and uncheck include episodes with unknown air dates in settings> library and import slow horses and I only got two seasons.
