### ISSUE TITLE
[BUG] Missing episodes for certain season of show

### ISSUE THREAD

**Issue by SmokePuddingEveryday** [umbrellaplug/umbrellaplug.github.io#200]
### Bug

Latest episodes for Love and Marriage: Huntsville not being listed in Umbrella, but are on some alternatives like Seren.

### Expected Result

The latest episodes and descriptions for them appear in Umbrella.

### Steps To Reproduce

1. Load up Umbrella
2. Search for Love and Marriage: Huntsville
3. Attempt to watch Love and Marriage: Huntsville Season 5, any episode past 7
4. Observe the lack of recent episodes or episode descriptions appearing in the list

### Logs, Screenshots, and Additional Info

Good evening Umbrella devs / users.

To begin, I'm not sure if this is an issue or bug relevant to Umbrella or a different entity and I'm also not sure if this is the best place to ask such a question, so apologies if either of those things is true.

I'm currently having an issue with Umbrella not updating the episode list for a certain show, Love and Marriage: Huntsville. On Umbrella, most episodes from the latest season are missing and none of the episodes have descriptions. I'm able to find torrents for the episodes online and alternative addons like Seren can find the episodes like normal. However, Stremio also seems to not be updated past Episode 7.

I have Real-Debrid as well as checked on a fresh installation of Umbrella on a different device but same thing occurs. I tried clearing my cache as well. I'm not sure if this problem affects other shows but this is the only one I've noticed it happen to.

I also searched for settings that may change how shows are listed but I couldn't find anything.

Is there any way I could force an update to the episodes list?

Thank you.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This is due to metadata missing. It needs to be updated on TMDB.
https://www.themoviedb.org/tv/86882-love-marriage-huntsville/season/5?language=en-US

**Comment by umbrellaplug** [comment]
A friend added it for you. It takes a few hours for tmdb data to update. Clear your metadata in the next few hours and you should see your other episodes show up now.
