### ISSUE TITLE
[BUG] playnext popup error

### ISSUE THREAD

**Issue by Sunseng** [umbrellaplug/umbrellaplug.github.io#201]
### Bug

Shield TV with Kodi 20 nexus release and AH2 skin, all good only playnext error.

### Expected Result

Playnext episode run without error.

### Logs, Screenshots, and Additional Info

https://paste.kodi.tv/pavolubiwa

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Playnext isn't supported with library playback.

**Comment by Sunseng** [comment]
I dont have tv show on library and never play any library with umbrella, all tv show i watch from umbrella streaming

**Comment by umbrellaplug** [comment]
It looks like for some reason when you started the video a playlist position was not assigned. Where did you play from? a homescreen widget? the seasons screen on a widget? inside the actual umbrella addon?
Do you have direct progress scraping enabled in Trakt tab? (it causes issues with playnext)

**Comment by Sunseng** [comment]
Playing from AH2 skin homescreen widget and season all from widget. I have direct progress scraping enabled on trakt tab.

**Comment by umbrellaplug** [comment]
There is currently a bug in playnext and direct progress scraping combined. I have already fixed it, but due to complaints of updates happening too much I have not pushed the fixed version yet. If you disable direct progress scraping does playnext work as expected?

**Comment by Sunseng** [comment]
I thought i got the workaround to assign the playlist. Install kodi default nextup addon, as dependancy in AH2 skin, then  i think the playlist assigned and umbrella nextplay window always popup and run very smooth, no error so far.
To avoid double window popup, i just disable nextup checkmark in nextup addon setting.

**Comment by Sunseng** [comment]
Oh just read your reply, sorry. I am at work atm so will try with disable direct progress scraping later. Thank you

**Comment by Sunseng** [comment]
Tested with uninstall kodi nextup addon, and disabled direct progress scraping, and the result, umbrella playnext broken again. Reinstall kodi nextup addon, and umbrella playnext working again, so i thought umbrella playnext need kodi nextup addon installed?

**Comment by umbrellaplug** [comment]
No, you should not need the nextup addon for playnext to work. It actually shouldn't work like that. :)

**Comment by umbrellaplug** [comment]
Can you post new logs?

**Comment by Sunseng** [comment]
The non working log? Let me reproduce it again later.

**Comment by Sunseng** [comment]
https://paste.kodi.tv/foyilehopa.kodi

**Comment by Sunseng** [comment]
From progress widget, or from progress widget then browse series, play the episode 1.
I found another bug on me again, if i click stop instead of watch now icon in nextplay popup window, then the show/episode stop instanly then return to widget list, after that if we click play the next episode, the playnext broken again and no window popup and the show just stop after ending.

**Comment by TechXXX** [comment]
I tested this multiple times on nexus, no errors, played just fine, windows 11

**Comment by TechXXX** [comment]
Just tried it on a firestick (amazon android - fireos), no errors, went to next episode twice via 2 popups. AH2 style, subtitle trigger with 60 sec fallback.

**Comment by umbrellaplug** [comment]
Are you still have this error on the latest version of the plugin?

**Comment by Sunseng** [comment]
Its fixed. Thank you.
