### ISSUE TITLE
Please add more debrid services to umbrella & cocoscrapers

### ISSUE THREAD

**Issue by ohmichael** [umbrellaplug/umbrellaplug.github.io#202]
### Feature

More debrid services from resolveurl please add it to coco & umbrella - I like to see linksnappy for one added in.

### Is this feature available already in another plugin?

No if it is I don’t know about it

**Comment by umbrellaplug** [comment]
I don't do scrapers.

https://github.com/CocoJoe2411/repository.cocoscrapers
