### ISSUE TITLE
[BUG] (Plex) running into an issue where it says it can't find any sources on scrape. 

### ISSUE THREAD

**Issue by TheGuyWhoo** [umbrellaplug/umbrellaplug.github.io#206]
### Bug

Hi. This is specifically regarding plex shares. Sometimes scraping takes really long(like times out) and then it says it can't find any sources(even on stuff that it previously did find sources).

(Btw, this is on content that I know is on multiple different servers. It should 100% be finding sources)

My best guess is this is due to a server going offline, but I don't know anything about this stuff. If that is the cause either being able to select priority for the different servers, or a per server time out would be great.

### Expected Result

To find sources. 

### Steps To Reproduce

I'm really not sure. I'm just iniating a scrape here. As I said my best guess is that it happens when a server is offline.

### Logs, Screenshots, and Additional Info

Scraper log:

Https://paste.kodi.tv/dobakameti

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I can add some timeouts. You can always reselect your shares any time in Scrapers also.

**Comment by TheGuyWhoo** [comment]
Thank you! That is what I usually do but it is a bit inconvenient

**Comment by DROIDshield** [comment]
Hmmm I finding that a specific program I have been watching via kodi addons ( Black ink Crew, new york) was finding the links now no sources found, yet if I use my iptv and search the same program comes up and all the links are there and work find. As said above, I don't know how the Scraper system works so is the iptv searching different servers to the addons?... not sure...

**Comment by TheGuyWhoo** [comment]
I think you should open an iptv specific issue. Make sure to post logs.

**Comment by DROIDshield** [comment]
No...no.. my iptv is used via Tivimate so completely different source. Just saying that via addons it cannot find links to it but via my iptv it can but does it search the same servers... I don't know and can't tell where the iptv get it VOD links from, same severs or not. I have no idea on that part. Was hoping the reply would come from those in the know.

**Comment by TheGuyWhoo** [comment]
Oh, are you specifically talking about plex? If not you should make a separate issue.

**Comment by adamosborne83** [comment]
> No...no.. my iptv is used via Tivimate so completely different source. Just saying that via addons it cannot find links to it but via my iptv it can but does it search the same servers... I don't know and can't tell where the iptv get it VOD links from, same severs or not. I have no idea on that part. Was hoping the reply would come from those in the know. 

On iptv, the video in demand is preloaded onto servers to which you have access for. So basically the person who owns the iptv subscription has already downloaded what you're trying to watch, so therefore no need to scrape and find it.

**Comment by DROIDshield** [comment]
> > No...no.. my iptv is used via Tivimate so completely different source. Just saying that via addons it cannot find links to it but via my iptv it can but does it search the same servers... I don't know and can't tell where the iptv get it VOD links from, same severs or not. I have no idea on that part. Was hoping the reply would come from those in the know.
> 
> On iptv, the video in demand is preloaded onto servers to which you have access for. So basically the person who owns the iptv subscription has already downloaded what you're trying to watch, so therefore no need to scrape and find it.

Thanks for clearing my situation up. I thought might have had a similar issue to TheGuyWhoo above. Hope you get your issue above sorted..Thanks Adam.

**Comment by umbrellaplug** [comment]
30 second timeout added.

**Comment by TheGuyWhoo** [comment]
Thanks! I just checked, but I don't see an update.

**Comment by umbrellaplug** [comment]
I have not pushed the update. I will soon. I've been working on pushing updates less often due to complaints. 

-"another bloody update"

**Comment by TheGuyWhoo** [comment]
Oh okay, I see. I wonder if those guys know you cash turn off auto update.

**Comment by TheGuyWhoo** [comment]
Thanks for the update!

So what this timeout does is apply a timeout to each server individually, thus preventing a offline server from taking over the scrape, is that correct?

**Comment by TheGuyWhoo** [comment]
I happen to have access(well "access") to a server that is permanently offline. I just tested this fix and the behavior is still the same. One server being offline causes it to not find sources. It wastes its time on the offline server instead of moving on to servers that are online, which causes the scrape to time out.

**Comment by umbrellaplug** [comment]
The fix is in the scrapers they have not been updated yet. That's dependant on the scraper dev. Until they are updated you will need to continue to remove servers that are offline.

**Comment by umbrellaplug** [comment]
Do you have a discord or a way I can message you outside of here? I do want to post coco here. If you can give me a way to contact you, I can send you the package of coco with timeouts.

**Comment by TheGuyWhoo** [comment]
Ooh okay, I see. My discord username is triplen#3587
