### ISSUE TITLE
[BUG] Download issue

### ISSUE THREAD

**Issue by Audi-Vid** [umbrellaplug/umbrellaplug.github.io#207]
### Bug

Umbrella download creates the folder name of the file to be downloaded but the file does not exist when download completes.
Nvidia Shield Pro 2019 - Kodi Nexus v20  
Download File Name Format - Title (Year) or Title S01E01

### Expected Result

Downloaded file is saved to disk in the named folder that was created.

### Steps To Reproduce

1. Open Umbrella
2. Search movie or tv show 
3. Select movie or tv show
4. Long press file source
5. Select download
6. Download creates folder name of movie or tv show (ex. 3 Stooges)
7. Download status updated until 100% is reached
8. Downloaded file does not exist in named folder  (ex. 3 Stooges.mp4)

### Logs, Screenshots, and Additional Info

Downloads worked properly in Kodi v 19.5
System updated to Kodi v20
Downloaded files are no longer present.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
On Android TV go to Settings -> Apps - Kodi -> Permissions -> Files and Media and select Allow all the time.

Then reopen Kodi.

**Comment by Audi-Vid** [comment]
Settings -> Apps - Kodi -> Permissions -> Files and Media was set to Allow.
New folder is created but dloaded files not present.

Setting change to Allow all the time resolves issue.
Thx
