### ISSUE TITLE
[FEATURE] Allow deletion of individual searches from the Search History

### ISSUE THREAD

**Issue by mirtim1** [umbrellaplug/umbrellaplug.github.io#209]
### Feature

It would be nice if I could remove individual searches rather than having to clear all searches. The list can get pretty long. I might want to remove the search for a movie or show I have seen but  I don't want to remove the search for shows (series) I am still watching. I'd like to be able to clean up my search list without clearing the whole list.

**Comment by roieeedouek** [comment]
You can long press to open the context menu on a specific search and "Clear Search Phrase" should appear, which behaves like you expect, deleting only the chosen search phrase...

**Comment by mirtim1** [comment]
That works. Thank you so much. Sent from my mobile device. Tim Snow770-402-6986On Jan 22, 2023, at 6:55 PM, roieeedouek ***@***.***> wrote:﻿
You can long press to open the context menu on a specific search and "Clear Search Phrase" should appear, which behaves like you expect, deleting only the chosen search phrase...

**Comment by umbrellaplug** [comment]
Existing feature in context menu. Closing issue.
