### ISSUE TITLE
[FEATURE] Trakt in Progress TV shows menu item

### ISSUE THREAD

**Issue by TechXXX** [umbrellaplug/umbrellaplug.github.io#210]
### Feature request

EDIT: I think I know what's going on here, stupid I didn't see it before but after reading a reddit it became obvious, progress in Umbrella isn't Progress from Trakt, it's in progress episodes, not in progress TV shows, can we please have an in progress TV shows menu item from Trakt: https://trakt.tv/users/mijnkodi/progress ?  I'll change from Bug to feature request. 

I'm hesitating posting this because it's not reproducible but maybe you can help out nonetheless. I'm missing shows from my Trakt progress, i.e. when I look at the website trakt.tv/users/mijnkodi/progress the results don't correspond with what I'm seeing in the Umbrella progress list, some are there but some are missing. 

When I add a show manually from the website to see if this one goes missing too it doesn't happen and it shows up on the list without a problem. When I try it on a fresh install with a fresh trakt.tv account, there's no issue. I would delete my trakt.tv account and start fresh were it not that on 2 other addons (seren and tmdb helper) I do see the missing shows. I've also tried Fen's in progress tv shows and I get results but they're completely random i.e. not ordered by date whatsoever. (EDIT: I've managed to at least get them ordered in Fen by altering the settings - Navigation - Sorting)

So on Seren I get my list without missing items on myshows - recently watched and in tmdb helper on trakt - your in-progress shows. 

Here's how it looks on the trakt.tv website: 

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/10571873/214019795-13a393e4-b252-4f8c-8642-848aaccf418b.png">

And here is a widget from mytvshows - progress (Umbrella):

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/214020001-39db5688-a0b2-4026-a542-18b5a4cc0034.png">

Here's tmdb helper - trakt - your in-progress : 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/214020316-2bba5675-9f74-4afd-8f8f-f6eb85100c4d.png">

As you can see some shows, show up, others don't. 

Sorry for the long winded report but I didn't how else to explain it in a more concise way. I'd be more than willing to provide you with my trakt.tv login/password if that would help. By the way, great work on recent fixes, I'm loving the codes being copied to clipboard for trakt and RD. 

[kodi.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10478957/kodi.log)

same behaviour on 19.5, nexus

### Expected Result

See the same shows as on trakt.tv/progress . 

### Steps To Reproduce

login to my trakt account - view progress and compare with Umbrella's mytvshows - progress

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I see you changed this to a feature request. Just so I'm clear on what to be doing here, you are wanting in-progress tv-shows as well as in-progress episodes?

**Comment by TechXXX** [comment]
Yes that's exactly it, just what's displayed on trakt.tv/users/xxxx/progress which I believe is 'In progress tv-shows'. In progress episodes just shows unfinished episodes so if you completely watch an episodes and then want to watch the next episode the tv show won't show up on the widget. Would be great if you could add it to the menu.

**Comment by umbrellaplug** [comment]
This is in the works and should be in the next update in the next few days.

**Comment by TechXXX** [comment]
Great, appreciate you!

**Comment by umbrellaplug** [comment]
@TechXXX Can you try out the latest test version and see if it looks more like what you're looking for.

**Comment by TechXXX** [comment]
Ok, I just tried it on a fresh install of 20.1, default skin because on my other installs the sorting was completely off. Now it's almost right but some shows are missing. Here's my trakt progress: 

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/10571873/232237905-0e34043b-bb42-472b-a95a-b296c8c85e61.png">

and here it is within Umbrella, somehow Beef is missing: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/232237934-b9a28272-db7b-49e0-96bd-61603860349c.png">

Few entries down that 'Commando' show is missing: 

<img width="1578" alt="image" src="https://user-images.githubusercontent.com/10571873/232237979-f7020779-cd4b-4c60-9485-cd2e4198d84a.png">

**Comment by umbrellaplug** [comment]
I'm thinking that May be due to then being 100% watched and not showing any new episodes available yet. I'd be interested to see if the ones that are showing that are 100% show episodes announced yet for future seasons.

**Comment by TechXXX** [comment]
South park is also missing, still running and no 100%

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/10571873/232239327-952cb828-1ee8-4761-80db-6887d300b141.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/232239369-24d09937-758d-403d-b369-451c5e060126.png">

**Comment by TechXXX** [comment]
Isn't it possible to copy the relevant code from tmdb helper's menu item? It displays trakt.tv/progress perfectly. 

This is a screenshot from tmdb helper's 'recently watched tv shows' in the Trakt menu: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/232239799-d46a782c-40cc-4df9-b69d-3bd564f6e740.png">

**Comment by umbrellaplug** [comment]
Okay. I've tried to accommodate here. Telling me just to copy tmdbhelper is insulting. Just use tmdbhelper. I'm closing this issue.

**Comment by TechXXX** [comment]
I'm sorry about that, didn't mean to insult you. I thought developers borrowed/used each others code all the time for inspiration etc.

**Comment by umbrellaplug** [comment]
Try the latest test build if you get a chance and see if tv show progress lines up better to trakt. 

Umbrella is already doing a lot of the same thing tmdbhelper is doing with the code. Tmdbhelper ha over 800 lines of code for just it's progress section. It's not a simple thing to "just take a look at". The current episode behavior in progress seems to mimic tmdbhelper, but with some elimination of episodes. If venom123 was still around I could ask him why, but I'm not sure. I matched the new tv show progress up to what I see on trakt.tv when I compare my progress. Hopefully this is what people are looking for. I'm not 100% sure.

**Comment by TechXXX** [comment]
Ah you seem to have nailed it, your progress tv shows even caught/displayed a show I watched that Trakt didn't register in trakt.tv/users/mijnkodi/progress/ , namely Futurama, I'm betting because it's an unaired season. The rest of the shows are in perfect order as it's displayed on the website, so it not only displays trakt.tv/progress but improves it! Well done. 

I would have never guessed the relevant code was 800 lines of code, I was thinking a couple, 5 max. Please don't take offense on account of my ignorance. I realise inheriting code from previous devs must be frustrating without being able to consult them but you seem to have come up with a working solution. Thanks a lot and keep up the good work!
