### ISSUE TITLE
[FEATURE] Letterboxd lists!

### ISSUE THREAD

**Issue by cboRD181** [umbrellaplug/umbrellaplug.github.io#211]
### Feature

Would be awesome if Letterboxd lists and watchlists were integrated into the addon, since they've added an API.  

The site's quite popular and has a ton of great content.  Currently, the only way to import letterboxd lists is through mdblist, but umbrella is not recognizing imported lists in the mdblist section. It may recognize the list if I made it static on mdblist, but then it wouldn't update in line with letterboxd. 

Hopefully this wouldn't be too difficult to implement and will warrant your consideration.  

Cheers!

### Is this feature available already in another plugin?

Not that I'm aware of.

**Comment by adamosborne83** [comment]
Have you inputted your MDBList api into Umbrella and then adjusted the cache in settings so it updates regularly. I do this and no issues.

**Comment by cboRD181** [comment]
> Have you inputted your MDBList api into Umbrella and then adjusted the cache in settings so it updates regularly. I do this and no issues.

I have, still no luck.  Are the MDBList lists you have imported from another service? If I create a list on MDBList it appears in Umbrella as expected.

**Comment by adamosborne83** [comment]
> > Have you inputted your MDBList api into Umbrella and then adjusted the cache in settings so it updates regularly. I do this and no issues.
> 
> I have, still no luck.  Are your MDBList lists imported from another service? If I create a list on MDBList directly it appears in Umbrella as expected.  

I can see my mdblist direct from mdblist and also can see them in my trakt too.

**Comment by umbrellaplug** [comment]
Letterboxd is currently still in private stages for their api. Unfortunately, I have not been approved for access yet. I put in a request for access.

https://letterboxd.com/api-beta/
