### ISSUE TITLE
[BUG] more of a cocoscrapers issue not umbrella

### ISSUE THREAD

**Issue by ohmichael** [umbrellaplug/umbrellaplug.github.io#212]
### Bug

I didn’t know where to go but some reason cocoscrapers will not find my 3rd party server I joined other day - it finds my server just fine but won’t find my friends server which is attached to my account as a library - idk what to do I’m drawing straws.

### Expected Result

I expect cocoscrapers to find my other “friends” server not just my direct server which is my device - I joined a free plex server & it’s not finding it.
Do I need a plex pass to make this work?

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Plexshares that are not local and support direct play are the only types supported. You may want to ask your friend if they have enabled remote access on their share.

**Comment by ohmichael** [comment]
Ok ty
