### ISSUE TITLE
Test version

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#213]
I would like to try a test version of your repo. Yours is the only add-on I use.

**Comment by adamosborne83** [comment]
> I would like to try a test version of your repo. Yours is the only add-on I use.

What don't you just download the test repo from his github? 

Also, be warn, being a test versions it will be prone to issues! It is NOT recommended at all.
Any changes in the test repo will be implemented in the main repo. So better to stick.
