### ISSUE TITLE
Filenamename error downloads

### ISSUE THREAD

**Issue by Redsand51** [umbrellaplug/umbrellaplug.github.io#215]
### Bug

Downloads enabled
-File Name Format                 Title (year) or Title S01E01

Download creates filename "S01E0" with rightmost digit missing.
Download of more than one file sequential can create duplicate filenames 

### Expected Result

Correct filename creation

### Steps To Reproduce

Tools
Downloads
-File Name Format          Title (year) or Title S01E01
Download any video

### Logs, Screenshots, and Additional Info

none required

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This is being looked into.

**Comment by umbrellaplug** [comment]
Can you give me an example of something you are experiencing this with?

**Comment by umbrellaplug** [comment]
fix will be in next update.

**Comment by umbrellaplug** [comment]
in update 6.6.13

**Comment by Redsand51** [comment]
Many thanks for your efforts. Sorry I got side tracked past few weeks. Will check out the fixes this evening.

**Comment by Redsand51** [comment]
Download filenames now correct. Please know your efforts are very much appreciated.
RS
