### ISSUE TITLE
[BUG] Failure to cache torrent to AllDebrid Cloud

### ISSUE THREAD

**Issue by alinnastac** [umbrellaplug/umbrellaplug.github.io#216]
### Bug

When I try to download a torrent in my AllDebrid Cloud account, the operation fails with this error:

23-01-28 22:16:23.129 T:14979   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'debrid_function' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.umbrella/umbrella.py", line 10, in <module>
                                                       router.router(sys.argv[2])
                                                     File "/storage/.kodi/addons/plugin.video.umbrella/resources/lib/modules/router.py", line 895, in router
                                                       success = debrid_function().add_uncached_torrent(url, pack=pack)
                                                   UnboundLocalError: local variable 'debrid_function' referenced before assignment
                                                   -->End of Python script error report<--

### Expected Result

Torrent should be downloaded into my AllDebrid Cloud account.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Update to the latest version.

**Comment by alinnastac** [comment]
I have already the latest version, which is 6.6.11 AFAIK.

I worked around this this issue by adding the following code to router.py at line 895:
                else:
                        from resources.lib.debrid.alldebrid import AllDebrid as debrid_function
This proves that params.get('caller') don't contain the expected value of 'AD'.

Btw, my Kodi version is 19.3.

**Comment by umbrellaplug** [comment]
Sounds like you got it.

**Comment by umbrellaplug** [comment]
Your fix is still missing some things. There's a few places that will need to be changed. I'll re-open your issue and fix it.

**Comment by umbrellaplug** [comment]
This has been resolved and will be in the next update.

**Comment by umbrellaplug** [comment]
in update 6.6.13
