### ISSUE TITLE
[BUG] Cocoscraper not finding sources

### ISSUE THREAD

**Issue by DjAnu** [umbrellaplug/umbrellaplug.github.io#217]
### Bug

Cocoscraper is not able to find some sources

### Expected Result

A4k scraper is able to find sources from Bitsearch, GLO, LIME & Torrentio, I have these torrents enabled in cocoscraper setting but on search 0 results come out while A4k shows several streams.

### Steps To Reproduce

Search for a movie title, for example "PATHAAN", A4K Scrapper showed 25+ results while Cocoscraper had 0 results.

### Logs, Screenshots, and Additional Info

![image](https://user-images.githubusercontent.com/5419410/215357521-b7ca9266-8d29-4a01-bfa4-2d49d7729846.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Wrong project. I don't do CocoScrapers.

**Comment by DjAnu** [comment]
Thanks for your quick response. I tried to find a repo for coco but couldn't.  where can i report this ?

**Comment by DjAnu** [comment]
Or can you possibly help me with this ? I love your Add-on and don't want to use anything else.

**Comment by umbrellaplug** [comment]
I stay away from the scrapers and development of them so I'm not able to help much with that. I'll let the scraper developer know. He has a repo, but I don't think issues are opened.

https://github.com/CocoJoe2411/repository.cocoscrapers

**Comment by DjAnu** [comment]
Ah, Thanks. Yes I see issues aren't open on his repo. Is there anyway I can reach out to developer ? or is this something you could also guide me to check and fix ? I am not a software guy but I am willing to get my hands wet in it if needed. Thanks so much. I have been using Kodi for almost 7-8 years now and Umbrella is the best add on I have came across so far. Keep up the good work.

**Comment by DjAnu** [comment]
Okay I finally figured issue was having cocoscraper default filter setting to exclude streams with only 1 foreign audio source. unselected it and now all is fine. Thanks a bunch for an awesome Addon.
