### ISSUE TITLE
[FEATURE] widget hide watched items

### ISSUE THREAD

**Issue by saxoloman** [umbrellaplug/umbrellaplug.github.io#218]
### Feature

Hi,

Is it possible to hide watched items in Umbrella widgets?

I'm still using Tmdbhelper widgets instead of Umbrella widgets because of that.

It would be very useful. I don't want to see movies I've already seen in "Trending this week" Umbrella widget.

Any chance to have this feature added by Umbrella dev?

Maybe some workaround? Any ideas?

Regards

Original post from reddit
https://www.reddit.com/r/Addons4Kodi/comments/10p9mej/umbrella_hide_watched_items_in_widgets

**Comment by umbrellaplug** [comment]
I'll look into this. Sorry, I didn't see your post. I don't check reddit as much these days.

**Comment by saxoloman** [comment]
Thanks allot , it is very much appreciated

**Comment by heimdall47** [comment]
It would be great if you could add this feature so that a button is available to hide watched items

**Comment by umbrellaplug** [comment]
in update 6.6.13

**Comment by saxoloman** [comment]
Thank you,this works beautifuly.
I have one more question regarding this feature.
Is it possible for a paginated trakt list that displays 40 items to accommodate for removed(watched) items ?
So that list remains with 40 titles ?

Thank you for great work
