### ISSUE TITLE
[FEATURE] Update Listitem Property Assignments for Kodi 20

### ISSUE THREAD

**Issue by umbrellaplug** [umbrellaplug/umbrellaplug.github.io#219]
### Feature

Update property assignments for new infolabel requirements in kodi 20 to reduce log warnings and bring addon up to date with current version of Kodi.

**Comment by umbrellaplug** [comment]
@jigoop1 Latest commit on this seems to have most things looking good on the kodi 20 side. Still need to test more on kodi 19 and make sure no unintended effects there.

**Comment by jigoop1** [comment]
@umbrellaplug 
i thinks we should use float(resumetime) in set_info b'cos some time value come NoneType and it gives error
instead of 
`control.set_info(item, meta, setUniqueIDs, float(resumetime))`
using this will be easy
`control.set_info(item, meta, setUniqueIDs, resumetime)`

```
def set_info(item, meta, setUniqueIDs=None, resumetime=''):
	if resumetime: resumetime = float(resumetime)
```

**Comment by umbrellaplug** [comment]
Yeah, I had moved the check for that into the top of the function above the if kodi20 due to needing that value either way. I'm committing that version of umbrella now. I also checked through the code for any place meta was set to a blank string and set it to a blank object instead to avoid errors. you may notice some "isinstance" checks in my version.

**Comment by umbrellaplug** [comment]
Sorry, it auto-closes when I merge the branch in.

**Comment by umbrellaplug** [comment]
in update 6.6.13
