### ISSUE TITLE
[BUG] Upcoming Progress - Nothing Listed After v6.6.13 Update

### ISSUE THREAD

**Issue by apothegm** [umbrellaplug/umbrellaplug.github.io#221]
### Bug

The section for Upcoming Progress has stopped listing unaired episodes immediately after updating to v6.6.13 (feb 7).

Although I normally don't use this section too often. I, instead prefer to see them listed above already aired episodes within Progress section, but now that's also affected.
I no longer see the unaired episodes in the different color text that is normally above the rest of the Progress section. 
Progress is sorted by Date Premiered.

I have confirmed "Unaired Episodes" are enabled in settings.
 

### Expected Result

Upcoming Progress and Progress (with option enabled) normally list unaired episodes for TV shows I'm watching.

### Steps To Reproduce

1. Update to v6.6.13.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi Version: 19.5
Type of Device: Windows 10

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Should be resolved in 6.6.14 update.
