### ISSUE TITLE
[BUG] Youtube section doesn't work in Linux?

### ISSUE THREAD

**Issue by cg00001** [umbrellaplug/umbrellaplug.github.io#222]
### Bug

When I select any Youtube channel Kodi closes at once.  
It is the first time I'm using the Umbrella's Youtube feature, Youtube addon works fine for me -I have my own credentials working with it for many years.

### Expected Result

See Youtube channel contents.

### Steps To Reproduce

Use Umbrella's Youtube section as usual.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.0
PC.
Arch Linux.

[kodi.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10709852/kodi.log)

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Umbrella passes off to youtube. Problem appears to be on the youtube addon.
