### ISSUE TITLE
Searching for Movies or Shows returns "Nothing was found" 

### ISSUE THREAD

**Issue by onthatb0mbshell** [umbrellaplug/umbrellaplug.github.io#223]
### Bug

Just tonight I was trying to add some movies and shows to my library from the addon, whenever I type the name into search I always get Nothing was found message.  I'm using Kodi 20, running on Android TV. 

### Expected Result

A list of Movies or Shows depending on my search term. 

### Steps To Reproduce

Search Movies
New Search
Enter Text

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Using Kodi20
Running on Android Smart TV

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Can you post some logs?

**Comment by onthatb0mbshell** [comment]
If I can remember how to do that I will, its been a few years from I've done it, just an FYI I can find the shows or movies I'm looking for by doing an actor search

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by onthatb0mbshell** [comment]
> Can you post some logs?

https://paste.kodi.tv/zeqewuyihi

**Comment by umbrellaplug** [comment]
Your're stuck on a bad version of Umbrella. It's trying to download from a repo that doesn't exist.

All you need to do is go Kodi > Settings > Addons > Install from zip

Select the umbrella repo from your sources you previously added and it should re-add the correct repo for you. Then you can download the latest version that should resolve those issues for you.
6.6.14 is the latest version.

**Comment by onthatb0mbshell** [comment]
Thanks for the info, I've now updated to the latest version, but now when I enter a search term I just have spinning cog wheel hanging, it's been like that for the last few minutes

**Comment by onthatb0mbshell** [comment]
Fanart.TV temporary server problem message.
The results have come through now but I'd say it was several minutes before it did so.

**Comment by umbrellaplug** [comment]
strange, might want to clear some cache there or something.

**Comment by onthatb0mbshell** [comment]
> strange, might want to clear some cache there or something.

Seems  to be working a lot quicker now, only issue now is when I find my movie and use context button and add to library, the movie is not showing on front page of kodi movies section, I can navigate and see the . strm file is there and the scraping seem to take place but the movie is not showing in kodi front page?

**Comment by umbrellaplug** [comment]
Sounds like you need to set the content of your movie folder to movies.

**Comment by onthatb0mbshell** [comment]
> 

Yip, done that and it's scraped the movie OK now, not sure why it changed as I have movies already populated there, maybe updating to new version meant I had to set content again. Anyway all seems good now, appreciate the quick response time and the help, love the addon 👍

**Comment by umbrellaplug** [comment]
Great. Closing this issue.
