### ISSUE TITLE
[BUG] urllib3,  Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by SJ50** [umbrellaplug/umbrellaplug.github.io#224]
### Bug

I am getting following error with plexshare 

"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='my-external-ip.8c59e55566f5416bb5f3d25b4a15f8a5.plex.direct', port=23130): Max retries exceeded with url: /hubs/search?query=Brooklyn%20Nine-Nine%20Kicks&limit=30&X-Plex-Client-Identifier=myIdentifier&X-Plex-Token=mytoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x83cfbbf0>: Failed to establish a new connection: [Errno 111] Connection refused'))"

If I run "https://my-external-ip.8c59e55566f5416bb5f3d25b4a15f8a5.plex.direct:23130/hubs/search?query=Brooklyn%20Nine-Nine%20Chasing%20Amy&limit=30&X-Plex-Client-Identifier=xxxxxxxxxxx&X-Plex-Token=xxxxxxxxxxx" in browser I get XML in return. 

port 32400 is open in my router.

### Expected Result

should get xml from plex without any error. 

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi version - Kodi Version: 20.0 (20.0.0) Git:20230115-389e701cb9 on Nvidia Shield TV and Fire stick 4k max.
note- removed external ip, identifier and token info.

fill log after I scrap for result.
https://paste.kodi.tv/iwiparaqug.kodi

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This has nothing to do with Umbrella.
Try running database optimization on your plex server under troubleshooting. Not much I can do to make any difference here as this is a connection issue. Best of luck to you in getting it resolved.
