### ISSUE TITLE
Trakt check marking 

### ISSUE THREAD

**Issue by tougfndrsn** [umbrellaplug/umbrellaplug.github.io#226]
I have checked as best I could for this issue, but haven't found anything. I have seen other trackt issue, but not this particular one. 
I am running The Crew fork of Kodi 19.4. I love the umbrella add-on, it pretty much works flawlessly except for unchecking ready to watch TV series in my collection, the episode itself is unchecked, but the series is not. It is kinda of a tedious process to go thru all my shows to see if an episode is ready to watch, so I always have to go into tools, trakt management tools, and force trakt sync to local database in order to uncheck the TV series. There is no Kodi log to upload, so hoping that this info is enough to look into the issue and come up with a fix. Thank you in advance.

**Comment by umbrellaplug** [comment]
There is not a lot I can tell from this information. Honestly, I'm still not even 100% sure what your issue is other than entire tv shows are not being marked in some way you're wanting. Is this for items in your trakt collection you have synced to your library? Is this just your trakt collection from TV Shows menu?

What are the steps to take to reproduce this issue?

Here are some easy to follow instructions for how to get your logs.
https://github.com/umbrellaplug/umbrellaplug.github.io#logs

Without this information I'm not going to be able to resolve your issue.

**Comment by tougfndrsn** [comment]
I will upload a file tomorrow as I have already forced trakt today. There are some episodes that I will be able to play tomorrow. So before I do I will try to maybe take photos or a video and post for you to see. Will that work?

**Comment by tougfndrsn** [comment]
I am not sure how to upload the log. I can view the log and get a url to upload to pastebin, but not sure how to attach it to here. I don't use my android box for communication with GitHub, I use my phone, I do not use my phone to watch Kodi. That link is a photo I just took from log file. I hope that will help. 
![16764720165103914482208398954426](https://user-images.githubusercontent.com/37504671/219059061-7d5d42e0-2deb-4701-805e-fd179f245379.jpg)

**Comment by tougfndrsn** [comment]
I had to force tracked to local database again this morning to get my shows that were ready to watch. Here is a picture of the umbrella log file that came about after I forced tract. 
![16764723132984930215198845695086](https://user-images.githubusercontent.com/37504671/219060284-5893bb01-14b2-46be-9271-629517fe1538.jpg)

**Comment by tougfndrsn** [comment]
![16764726268377335913705851661071](https://user-images.githubusercontent.com/37504671/219061705-d0992bc6-939a-45bb-8ecf-4b0fab9a016f.jpg)

**Comment by umbrellaplug** [comment]
In umbrella go to tools, logging tools, umbrella upload log file to pastebin. It will give you a url, if you could post that, it would be very helpful. May need the kodi log also. 

I removed the picture you posted earlier. You had some personal photos in there also I figured would be best to remove.

**Comment by tougfndrsn** [comment]
> In umbrella go to tools, logging tools, umbrella upload log file to pastebin. It will give you a url, if you could post that, it would be very helpful. May need the kodi log also.
> 
> I removed the picture you posted earlier. You had some personal photos in there also I figured would be best to remove.

Thank you

**Comment by tougfndrsn** [comment]
![16764729294964371420662564968378](https://user-images.githubusercontent.com/37504671/219063160-9463b6f6-e8f7-43d1-abfb-0efd70648e13.jpg)

**Comment by tougfndrsn** [comment]
![Uploading 16764729717944881434388058601247.jpg…]()

**Comment by tougfndrsn** [comment]
![16764730281915696796667393913645](https://user-images.githubusercontent.com/37504671/219063646-3e4f6677-5937-4af4-b6ca-d8b4d4a6b7e9.jpg)

**Comment by umbrellaplug** [comment]
perfect! looking over these now. I'll see if anything stands out.

**Comment by tougfndrsn** [comment]
> perfect! looking over these now. I'll see if anything stands out.

Cool, I appreciate you and all you and tikipeter do to keep this add-on up and running!!

**Comment by tougfndrsn** [comment]
> ```
> [2023-02-15 09:37:03] [ plugin.video.umbrella: ERROR ]: From func name: /resources/lib/database/traktsync.py.cache_insert() Line # :759
>                        msg : OperationalError -> database is locked
> ```
> 
> Indication of a corrupt database file for trakt in Umbrella. This usually happens from a sudden power loss or shut off during a write operation to the database file. There's a database file that will need to be deleted then do the trakt force sync 1 more time and that should correct your issue for you. I'll give you the path to the file and how to delete it using kodi here.
> 
> \userdata\addon_data\plugin.video.umbrella\traktSync.db
> 
> In kodi on main menu click the little settings cog/icon. File Manager. On the left or right side (doesn't matter) click "profile directory", then "addon_data", then "plugin.video.umbrella". You will see traktSync.db in that directory. click and hold on that file and a context menu will come up. You can select Delete from the context menu and it will delete it.
> 
> You could always remove the addon and data and re-add it as well if this seems too hard for you, but I'd hate to go through setting everything back up.

Done, removed traktsync.db, thank you. I will let you know in a day or two, depending on when I have new shows available. I appreciate it very much.

**Comment by tougfndrsn** [comment]
I did have to reauthorize tract but that's no big deal. So I just went through some of my shows to find out when the next one should be available. I have one that should be available tomorrow morning we will see if it is unchecked I will let you know. thank you so much.

**Comment by umbrellaplug** [comment]
Hopefully that gets you fixed. Ill leave this issue open so you can let me know.

**Comment by umbrellaplug** [comment]
Any update on this today?

**Comment by tougfndrsn** [comment]
> Any update on this today?

Yes I do have an update , it did not work. The girlfriend opened Cody this morning try to play that one show The TV show itself is still checked marked but when you go into the TV show the season is unchecked marked also the episode is not checkmarked telling me it's ready to watch it's just the TV show itself in the collection is not unchecking. I will take pictures of the log again and send them to you. She also came up with a playback failed era which I've seen a lot in the past haven't had it in a while but it's starting to rear its ugly head again. Give me a few minutes and I will send you pictures of the logs thank you

**Comment by tougfndrsn** [comment]
![16765576816814694267075210094161](https://user-images.githubusercontent.com/37504671/219392199-2c0be794-8349-4666-af37-7967ec921deb.jpg)

**Comment by tougfndrsn** [comment]
Hopefully those will give you a little bit more information thank you so much for helping

**Comment by umbrellaplug** [comment]
Good news, I don't see the trakt database issue anymore. Bad news, I don't see a clear reason for your issue either. Let me work on duplicating the issue on my side and see if I can figure out where things are messing up.

I'm not familiar with builds and I don't use anything from the crew on my devices. Is there somewhere I can get this build so I can load it and try to see if I can track this down? What type of device are you using for kodi?

**Comment by tougfndrsn** [comment]
I am using a tanix X4 pro 4 x 64 running Android 11. I don't use a build just your add-on, I don't use the crew addon, I just use there 19.4 forked version of Kodi. I only use your add-on and their wizard to clean cash upon startup. 
https://bit.ly/thecrewmc24 that is the kidi fork I am using.

**Comment by tougfndrsn** [comment]
![1676558769132313282517920442280](https://user-images.githubusercontent.com/37504671/219396966-6b3b2591-31e1-4555-8edd-30a79b7246d6.jpg)

**Comment by umbrellaplug** [comment]
okay thank you for all the info. I will check it out and get back to you. I was able to download the apk.

**Comment by umbrellaplug** [comment]
Wanted to clarify. I see you mentioned your trakt collection. Are you importing your trakt collection to library or are you accessing your trakt collection another way?

**Comment by tougfndrsn** [comment]
I know this is a little confusing for both of us, but I search shows within your add-on if I like the show I save it to my trakt. TV shows I save in my collection are usually available the next day after they air. After it is aired the show within the collection usually gets unchecked but it is not happening within your add-on. Within the TV show in the collection the season and the episode get unchecked but not the TV show within the collection itself. Not sure if that makes any more sense but that is the only way I can think of to describe it. There are other add-ons that I have tried in the past that the TV show within the collection becomes unchecked the next day after they air. I am not going to move away from your ad on because I really love it, so if there is no fix for my issue then I will just have to sync tracked on a daily basis.

**Comment by umbrellaplug** [comment]
Yeah, no worries. I'm just trying to duplicate it here so I can see what's going on. I know this stuff can be hard to explain from both sides. I'm trying to figure out if your using library, a widget, or one of the menus within umbrella so I can see what information needs to be refreshed.

When you say you save a show to your collection. Are you saving to Trakt Collection or adding to library or adding to collection and importing collection? There's so many ways it could be added that's why I ask. :)

When you access your shows and they are not updated as you say is this on your homescreen in a widget? Is this on your homescreen under tv? Or are you taking steps through Umbrella to see these shows? Example: Discover Shows> My TV Shows> Collection 

Please let me know so I can add some shows with new episodes coming out soon and try to duplicate the issue.

**Comment by tougfndrsn** [comment]
Steps thru umbrella, my TV shows, collection.

**Comment by meesterexx** [comment]
> I have checked as best I could for this issue, but haven't found anything. I have seen other trackt issue, but not this particular one. I am running The Crew fork of Kodi 19.4. I love the umbrella add-on, it pretty much works flawlessly except for unchecking ready to watch TV series in my collection, the episode itself is unchecked, but the series is not. It is kinda of a tedious process to go thru all my shows to see if an episode is ready to watch, so I always have to go into tools, trakt management tools, and force trakt sync to local database in order to uncheck the TV series. There is no Kodi log to upload, so hoping that this info is enough to look into the issue and come up with a fix. Thank you in advance.

Pardon me for jumping in here, but from your description, it sounds like you are using the completed status of the series (checkmark) in your collection to determine whether you have unwatched episodes to watch. Is there a reason you are not using Trakt Progress (My Shows > Progress) ? It's sole purpose is to show you your next unwatched  episodes  being tracked by Trakt.

**Comment by umbrellaplug** [comment]
Just wanted to follow up and let you know this wasn't dropped. I've added some shows to my collection and i'll be testing tomorrow when new episodes come out. I'm using 1923 for my tests and it has a new episode tomorrow.

**Comment by tougfndrsn** [comment]
> Just wanted to follow up and let you know this wasn't dropped. I've added some shows to my collection and i'll be testing tomorrow when new episodes come out. I'm using 1923 for my tests and it has a new episode tomorrow.

No worries, I figured you would need a few days.

**Comment by umbrellaplug** [comment]
Mine unchecked as expected this morning.

**Comment by tougfndrsn** [comment]
So I guess il will uninstall and reinstall and reconfigure.

**Comment by umbrellaplug** [comment]
I'd wait. Windows showed correctly. Android did not.

**Comment by tougfndrsn** [comment]
So there is no fix for my issue, right? I'll just keep forcing for now.

**Comment by umbrellaplug** [comment]
I'm still looking into it. I believe it's related to cache time period.

**Comment by tougfndrsn** [comment]
> I'm still looking into it. I believe it's related to cache time period.

Oh cool thank you for all your work and dedication to this add-on. I really do like it. It's fast and very user friendly.

**Comment by tougfndrsn** [comment]
Not sure if you found and fixed issue, but my TV shows in my collection that played yesterday and watchable today are unchecked!!! Yay. I didn't have to force this morning!!! Thank you for all your hard work, dedication and support!!

**Comment by tougfndrsn** [comment]
> Not sure if you found and fixed issue, but my TV shows in my collection that played yesterday and watchable today are unchecked!!! Yay. I didn't have to force this morning!!! Thank you for all your hard work, dedication and support!!

**Comment by umbrellaplug** [comment]
Sounds like it's working better for you. That's great news.

**Comment by tougfndrsn** [comment]
My bad, I guess I spoke to soon. Ugh, forcing trakt to get my ready to watch shows. No big thang. LoL

**Comment by umbrellaplug** [comment]
Are you still having issues?

**Comment by umbrellaplug** [comment]
Try updating to a current version of Kodi. I'm not able to duplicate this and I'm not getting any other reports of this. I'm going to close this issue out as likely an issue with your setup.

**Comment by tougfndrsn** [comment]
Ok I will update to version 20 and see how 5hat works. Thank you for all your help. 

Sent from AOL on Android 
 
  On Wed, Mar 22, 2023 at 9:21 AM, ***@***.***> wrote:   


Closed #226 as completed.
