### ISSUE TITLE
Scraping Display 

### ISSUE THREAD

**Issue by ronfrankhill** [umbrellaplug/umbrellaplug.github.io#228]
Is it possible to have the scraping results display like how Seren and Fen has it during scraping. That will look cool.

**Comment by umbrellaplug** [comment]
Can you elaborate? Sounds like you need to look at the source select and scraping dialog options in the settings.

**Comment by ronfrankhill** [comment]
I mean how it's displayed. Fen and Seren looks cool.

**Comment by umbrellaplug** [comment]
Post a screenshot.

**Comment by ronfrankhill** [comment]
Okay. I will.

**Comment by ronfrankhill** [comment]
![IMG_20230216_215456](https://user-images.githubusercontent.com/39697733/219529668-ea02e6af-4543-4154-91aa-2bf01cd0bc89.jpg)

**Comment by ronfrankhill** [comment]
![IMG_20230216_215458](https://user-images.githubusercontent.com/39697733/219529956-0883585a-96d4-407c-9e3f-96bab84ebbfa.jpg)

**Comment by umbrellaplug** [comment]
Umbrella > Tools > Settings > Source Options > Under the "Scraper Progress Dialog" options set the Progress Dialog (Scraping and Resolving) to "Full-Screen"

**Comment by ronfrankhill** [comment]
Okay. I will try that out. Thanks

**Comment by umbrellaplug** [comment]
No problem, enjoy... one of my favorite features. I didn't do the dots like Peter did for Fen. I made a spinning umbrella logo instead. :)

**Comment by ronfrankhill** [comment]
Cool.
