### ISSUE TITLE
[BUG] No Tagline shown for Movies

### ISSUE THREAD

**Issue by meesterexx** [umbrellaplug/umbrellaplug.github.io#229]
### Bug

ListItem.Tagline seems to be empty for Movies, but is there for TV Shows. I've checked movies in Fen and TMDBHelper and tagline is shown for same movie in same skin, so it seems to be an issue with the meta info just for movies in Umbrella.

Tagline for TV Show in Umbrella:
![showtagline](https://user-images.githubusercontent.com/13154733/219788566-ed417477-d2d3-4f9e-b605-e3b14645c18f.png)

But no tagline for movie in Umbrella:
![notagline](https://user-images.githubusercontent.com/13154733/219788657-56152786-8c84-4ceb-8914-339956653573.png)

Same movie / same skin in TMDBHelper (and Fen) shows tagline:
![tmdbhtagline](https://user-images.githubusercontent.com/13154733/219788732-61fbd744-8d8c-4a84-8c94-a4b4916f1935.png)

### Expected Result

Would expect to see tagline for Movies like I do for Shows in Umbrella

### Steps To Reproduce

1. In Estuary/Umbrella go to Discover Movies > Popular (TMDB) and set view to List. No tagline is shown between title and plot
2. In Estuary/Umbrella go to Discover TV Shows > Popular (TMDB) and set view to List. Tagline is shown between title and plot
3. In Estuary go to another addon like Fen or TMDBHelper  > Movies > Popular and set view to List. Tagline is shown between title and plot

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20, default Estuary and Estuary fork on Windows 11 desktop

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Looks like Venom123 had commented tagline out of movie meta for some reason. Unfortunately, he's not around to ask why these days. I'll add it back in.

**Comment by meesterexx** [comment]
Thanks!
