### ISSUE TITLE
[BUG] Trakt Direct Progress Scrapping Broken

### ISSUE THREAD

**Issue by Liquidrag** [umbrellaplug/umbrellaplug.github.io#232]
### Bug

Sorry to bother you but one of the recent updates seem to have broken the "direct progress Scrapping" function. When checked, in My TV Shows>Progress it normally played the episode of the series. Now it plays the next episode of the next show in progress.

### Expected Result

When Direct progress is checked,  in My TV Shows>Progress it normally played the episode from the same series

### Steps To Reproduce

1. My Tv Shows
2. Progress
3. Select the desired episode to play
4. wait for next up popup to show wrong item

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

I'm on K20 nexus, Umbrella 6.6.17, and tested on my mac and Shield tv .

The popup should be for My Hero Academia instead of Welcome to Chippendales.
<img width="1280" alt="rsz_screen_shot_2023-02-21_at_74332_am" src="https://user-images.githubusercontent.com/43726430/220365505-86fd0a74-984c-4a42-966b-c6a9731ac420.png">

Screenshots of my settings that previously worked fine.
<img width="1280" alt="rsz_screen_shot_2023-02-21_at_73746_am" src="https://user-images.githubusercontent.com/43726430/220366244-1cdc44ee-7362-499e-a826-67c8ca6c7c29.png">
<img width="1280" alt="rsz_screen_shot_2023-02-21_at_73823_am" src="https://user-images.githubusercontent.com/43726430/220366249-feb1377e-625b-4a4c-8cfd-78a5328d4c43.png">

Heres my log file.
https://paste.kodi.tv/povocahiju.kodi

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Fixed version 6.6.18

**Comment by Liquidrag** [comment]
Thank you!
