### ISSUE TITLE
[REQUEST] Progress to show Specials

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#233]
### Feature

Hi

If ```Include Special Episodes (Season 0)``` is set I would like to see unwatched Specials appear in Progress

Also the Context menu for Progress shows ```Mark as watched``` and not ```Watched in Trakt``` Edit: Context menu correct from Umbrella My Tv Progress but incorrect when Progress set as a widget in AH2

**Comment by umbrellaplug** [comment]
Torn on this request. Not sure if it's possible as specials would almost always show first due to season 0.

**Comment by Ade-AV** [comment]
Would be cool if you could

My case for this is Umbrella treats Specials differently to other Addons I've tried where if you're hiding Watched then Unwatched Specials only show if a regular (non Special) is also Unwatched. Getting it to work with Progress would further enhance the way Umbrella handles Specials which is to treat them the same as regular non Specials

**Comment by umbrellaplug** [comment]
The entire progress sections are being redone. I will consider this request in that process.
