### ISSUE TITLE
[FEATURE] unhide watched in search widgets

### ISSUE THREAD

**Issue by saxoloman** [umbrellaplug/umbrellaplug.github.io#234]
### Feature

Hello.
Thank you very much for adding hide watched in widgets option
I wanted to ask you if you could please exclude search widget from that rule ?
Reason being that i use umbrela search as a widget in AH2 and if i want to watch some old movies again like John Wick part 1 ,search comes up empty.
If its not to much trouble i hope you consider this.
Thank you

**Comment by umbrellaplug** [comment]
Can I ask why you are using a widget for search instead of just using umbrella search strings in the built in search in that skin?

**Comment by saxoloman** [comment]
I phrased it incorrectly. I am using umbrela search string in built in ah2 search. I replaced tmdb helper search string with umbrela.

Thank you so much for looking in to this

**Comment by umbrellaplug** [comment]
Fixed. Will be in next update.

**Comment by saxoloman** [comment]
Did a quick test on my phone from test repo. 
Only tried movies and it works fine now 👍
I will test properly on my box when its officially released.
Thank you
