### ISSUE TITLE
My TV Shows > History. Empty 

### ISSUE THREAD

**Issue by mg1221** [umbrellaplug/umbrellaplug.github.io#235]
### Bug

When accessing "My TV shows> History" the most recently Watched episodes appear as normal. If you back out of the menu and try to access it again you get a "Episodes, Nothing Was Found" notification and cannot access the menu. 

It also seems to prevent me from accessing other menu items within "My TV Shows" until I back out to the umbrella main menu and go back into "My TV Shows" might not be related.

Clearing the cache manually seems to fix the problem.

### Expected Result

the "History" menu shouldn't be empty after leaving and coming back in. 

### Steps To Reproduce

1. Go to "My TV Shows> History"
2. See that the menu is filled with the episodes you just watched. 
3. Back out of the "History" Menu
4. Try to go back into "History"
5. Receive notification "episodes, nothing was found" 
6. Can't access the menu until you clear the cache.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

- OS:  OSMC running Kodi 19.5 - 2022-12-30
- DEVICE: Vero 4k+ 
- LOG: `https://pastebin.ubuntu.com/p/JTcwhrc4xP/`

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Duplicated here. I'll see what's up. Thanks for the report.
