### ISSUE TITLE
[FEATURE] Sort Results by Audio Language

### ISSUE THREAD

**Issue by tfouto** [umbrellaplug/umbrellaplug.github.io#236]
### Feature

For non-native english is very important to use audio languages. Especially kids. 

It would be a great feature, to have an option to sort by Audio Language. For instance on results list the first results (if available) to be on a specified language. For instance: Spanish. The user would choose a default audio language on settings Umbrella, and on results list, there would be the first results on that audio language. The next results would be on the same order as today. 

As an option there could be an indication of the audio language for each stream, either by text or a flag.

Thanks for you great addon.

**Comment by umbrellaplug** [comment]
I'm still trying to figure out an effective way to do this.
