### ISSUE TITLE
[FEATURE] Premium

### ISSUE THREAD

**Issue by LouCyphir** [umbrellaplug/umbrellaplug.github.io#238]
### Feature

I'm trying to download a pack but it says I need premium, how would I do this?

I have Real-Debrid

**Comment by umbrellaplug** [comment]
There is no option to download a pack. There is no premium.

**Comment by LouCyphir** [comment]
Thank you for the heads up

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
