### ISSUE TITLE
[BUG] Short Description

### ISSUE THREAD

**Issue by KillerChinoe** [umbrellaplug/umbrellaplug.github.io#239]
### Bug

I added the repository to my kodi, but i think it is missing files from the zip folder. After installation i can only add the scraper module from the repository. There are no video add-ons that i can add.

### Expected Result

-

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

![FE5AD918-F65B-4B08-B6F3-2D2B4147D2C0](https://user-images.githubusercontent.com/73716803/221430338-7ec5963d-409d-45c2-a2b3-cd8470f8040a.jpeg)
![552E7991-A142-4595-A697-2B3530C4267A](https://user-images.githubusercontent.com/73716803/221430342-dde56c29-01ff-4ac3-a953-07bb99746d7c.jpeg)

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Kodi version?

**Comment by KillerChinoe** [comment]
18.9.0

**Comment by umbrellaplug** [comment]
Kodi 18 isn't supported.
