### ISSUE TITLE
Trakt Progress TV Section 

### ISSUE THREAD

**Issue by ronfrankhill** [umbrellaplug/umbrellaplug.github.io#240]
### Bug

It might be nothing. Yesterday l tried to watch Season 1 Episode 8 of 1923 TV series but instead it plays or stream The Mayor of Kingston Season 2 Episode Episode 7 instead. I cleared the provider cache in settings twice but it keep playing not that Episode 8 of 1923. I just assuming the source was tag wrong from the link it's coming from. 
Another thing l noticed that this TV Season 8 Still Standing don't show up in trakt progress section after it aired but only in another add-on ( Seren). It not a major issue for me. 

### Expected Result

This happen the second with another series some weeks ago. I put it as the link was tag wrong where the source is coming from.

### Steps To Reproduce

Trakt progress TV section. Direct scraping. In settings is set to auto select the links.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Nexus 20 platform on Android 32bit box.

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
We do not have any control.over incorrectly named files. Your other show not showing in umbrella but showing in Seren would be because the TMDB data needs to be updated. Seren uses trakt for season and episode info. Umbrella uses tmdb for season and episode information. Once updated on tmdb it will show correctly.
