### ISSUE TITLE
Settings 

### ISSUE THREAD

**Issue by ronfrankhill** [umbrellaplug/umbrellaplug.github.io#241]
Is it possible to add this extra feature like Fen in settings to display extra ratings e.g. metacritic, tomato rating critic, tomato rating user etc. So users can decide if they want to watch movies or TV episodes base on other users that viewed it already. Just asking.

**Comment by adamosborne83** [comment]
This works in Fen due to the fact Fen has 'extra' which opens up a whole entire other menu system when selecting a movie or TVShow.
Which Umbrella does not do (yet)
A majority of the time users will have a skin on their set up with produces the IMDb info, ie, titan Bingie, Cosmic, AH2 etc etc.

**Comment by DROIDshield** [comment]
Why not just skin it, I always skin my Kodi so I get all of the ratings. Heres mine with AH2
![20230209_194853](https://user-images.githubusercontent.com/97023369/221948347-67cd84e6-511a-4ec9-be07-36b556706a81.jpg)

**Comment by umbrellaplug** [comment]
Planned down the road.
