### ISSUE TITLE
[BUG] Progress Context menu incorrect when set as a widget in Arctic Horizon 2

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#243]
### Bug

The Context menu is incorrect when setting Progress as a widget on the Home screen in Arctic Horizon 2

Menu is correct from Umbrella My TV Shows Progress

### Expected Result

Correct Context menu to show

### Steps To Reproduce

Set Progress as a widget in AH2
Bring up Context menu for any Episode

![image](https://user-images.githubusercontent.com/121737707/222924591-74090d55-d981-43d6-8c3e-0516d9d2141c.png)

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Logs from macOS (same result on Apple TV)

http://paste.kodi.tv/obakehenak

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
What version of Kodi?

**Comment by Ade-AV** [comment]
20.0

**Comment by Ade-AV** [comment]
Hi

This setting appears to bring it back on my Mac but ```Browse Series/Progress``` (possibly others) do not work

```Widget Context Menu->Use Full Context Menu in Widgets (Kodi 20 Only)```

What does this setting do?

**Comment by umbrellaplug** [comment]
In Kodi 20, widgets are recognized with their context menu items. In Kodi 19 they were not. Turning that setting on enables items to have their original context items if you're running Kodi 20 instead of the extra context items added by the widget context menu settings.

**Comment by Ade-AV** [comment]
Thanks for the explanation, guess we can close this

**Comment by Ade-AV** [comment]
Closing as issue resolved with setting but can you have a look at ```Browse Series/Progress``` please
