### ISSUE TITLE
[FEATURE] It would be nice to have a calender section where the list item dates always corrospond to the current week.

### ISSUE THREAD

**Issue by TheGuyWhoo** [umbrellaplug/umbrellaplug.github.io#248]
### Feature

For example, you only have one "monday" item in this section and that item always points to monday of the current week. This would be useful to folks who would like to make a custom window out of those items for example, right now it would require you to go into the custom window and update the dates every week.

**Comment by umbrellaplug** [comment]
I'm not sure what you're requesting here. What do you mean go into the custom window?
