### ISSUE TITLE
Trakt syncing not working (?)

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#249]
### Bug

Would expect a show added to Trakt (outside of Kodi) to appear in Umbrella on next sync check based on ```Trakt service sync interval (in minutes)```

### Expected Result

Show added to Trakt to sync to Umbrella (and widgets to be refreshed)

### Steps To Reproduce

On Trakt website add a show to e.g. User List, wait for Umbrella Trakt sync (15mins), show doesn't show up unless Cache cleared

Nothing seems to be happening after this (?)

```
[2023-03-19 17:33:38] [ plugin.video.umbrella: DEBUG ]: From func name: resources.lib.modules.trakt.sync_user_lists() Line # :1571
                       msg : Trakt User Lists Sync Update...(local db latest "lists_updatedat" = 1679114176, trakt api latest "lists_updatedat" = 1679200175)
```

http://paste.kodi.tv/zuvositalu
http://paste.kodi.tv/azupibehar

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

20.1
Apple TV
MacOS

Works in Fen

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Trakt sync is working fine. I just tried multiple devices and adding to different lists and all are showing on the lists they were added to. You may need to change your list cache settings.

**Comment by umbrellaplug** [comment]
Tools> Settings> Cache> Trakt User Lists

Lower the amount of hours it's cached. 0 means none.

**Comment by Ade-AV** [comment]
Thanks, any downside setting it to 0? and can the widgets be refreshed?

**Comment by umbrellaplug** [comment]
It will cause the list to be refreshed from trakt every time you open it. That's the only downside.

**Comment by Ade-AV** [comment]
Perhaps the Trakt Sync should override/ignore the Cache settings if there's been a change? If not then how about adding a Help tip

**Comment by umbrellaplug** [comment]
Sure. Ill be awaiting your commit.

**Comment by Ade-AV** [comment]
OK, can't say I know what I'm doing but adding the following after this [line](https://github.com/umbrellaplug/umbrellaplug.github.io/blob/master/matrix/plugin.video.umbrella/resources/lib/modules/trakt.py#L1588) seems to work for me
```
cache.cache_clear()
control.trigger_widget_refresh()
```
And adding the widget refresh to ```sync_watch_list``` also working
