### ISSUE TITLE
Change Number of Episodes Till Still Watching

### ISSUE THREAD

**Issue by rogermae** [umbrellaplug/umbrellaplug.github.io#25]
Can the number be reduced to 0 for this?
With Continuous Playback enabled this popup cancels out the next play if you don't select an option. It defeats the purpose of auto next play.

**Comment by umbrellaplug** [comment]
I will look into adding an additional setting to disable still watching.

**Comment by rogermae** [comment]
I think i found a fix for this. I had installed the Up Next addon.  I uninstalled the addon and now Continous Episode Playback works as it should.
One note though, the addon was configured to allow 0 episodes to play in order for the Still Watching popup to display. So it shouldn't have popped up anyway. Anywho, its working now.

**Comment by umbrellaplug** [comment]
Umbrella is not compatible with up next, but if that's working for you great! I'm pushing an update tonight that increases the max number from 10 to 40 for episodes for the actual supported play next feature in the plugin. I thought that would be a better route in case the player somehow got left running. Closing issue.
