### ISSUE TITLE
Real Debrid Authorization Error

### ISSUE THREAD

**Issue by DJMix-I-Can** [umbrellaplug/umbrellaplug.github.io#252]
### Bug

Hello, hope all is well with you & yours.
I was watching Youtube videos within Kodi & noticed an Umbrella Error pop up. It stated that Umbrella was not authorized with Real-Debrid. It just started within the past hour & have had Kodi open for most of the day. I closed Kodi & restarted. The notification popped up again. I revoked the authorization for Real-Debrid & tried to Reauthorize it again. It doesn't happen, I get another Umbrella error & the Real Debrid code window never pops up. I looked at the debug log file & it seems to point to a SSL Certificate expiration error.  Thought I'd post it now & give you a heads up, before the reddit posts get out of hand.
Edit: I forgot to add. I renewed my Real-Debrid last week & it's valid until August 31, 2023.
Thanks.

### Expected Result

I expected to be able to authorize Real-Debrid within Umbrella.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Using an Nvidia Shield 8.2.3OS
Kodi Nerds Nexus March 20 2023 version, which I updated it two days ago & Umbrella was still running without errors.
Umbrella 6.6.18
This is the [debug log.](https://paste.kodi.tv/xacamomera.kodi)

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This is a problem with real debrid. They let their ssl expire.

**Comment by DJMix-I-Can** [comment]
That's what I thought. I didn't get that same error with another addon. I just tried scraping that addon & it scrapes fine but won't play anything. The cache & cloud are empty, which is where the SSL comes to play with Real-Debrid. Got it....
Thanks for the quick reply. 
Be well...
