### ISSUE TITLE
[FEATURE] Plex Direct always at the top no matter what

### ISSUE THREAD

**Issue by MrMeatballSub** [umbrellaplug/umbrellaplug.github.io#255]
### Feature

I know we already have priority setting, but say for example you have a 1080p plex video that you want at the top of the source list (for autoplaying).  Right now if there is a 4k file that gets scraped from realdebrid, it will still be used over the plex share video.  Maybe something that can be added possibly?

**Comment by umbrellaplug** [comment]
Have you tried setting Plex to a lower priority than real debrid? The lower the priority number the higher in the list it appears.

**Comment by MrMeatballSub** [comment]
Yes, but it still takes quality priority.  So if my plex movie is 1080p but realdebrid video is 4k, the 4k video is on top

**Comment by umbrellaplug** [comment]
I'll think on this one more. It seems may need some sorting adjustments to allow for sorting by providers also.

**Comment by SJ50** [comment]
I did some experiments.
Currently to get Plex result at top following 4 conditions should be satisfied. 

turn off everything under “sorting and filtering” > “source sorting option” 
turn off  “source options” > “sort by file size” 
set “source options” > “Torrent/Hoster sorting method” to “do not group”
set priority of Plex to minimum.

If any of above criteria does not satisfy then Plex result will not be at top.

**Comment by SJ50** [comment]
I want results in following order
1 Plex at top no matter what
2 hevc or av1 
3 size

**Comment by ssjoverhaul** [comment]
I think Seren handles it by allowing you to set the "direct" stream the highest priority

**Comment by umbrellaplug** [comment]
Next update will have an option to prioritize direct to the top.

**Comment by ssjoverhaul** [comment]
> Next update will have an option to prioritize direct to the top.

That is fantastic, thank you sir

**Comment by umbrellaplug** [comment]
Available in latest update.
