### ISSUE TITLE
Not an issue I just need a bit of help!

### ISSUE THREAD

**Issue by milesmcclane** [umbrellaplug/umbrellaplug.github.io#259]
Hello! 

Sorry to clog the issues page up with this. 

How can I access my RD cloud within Umbrella? 

I read somewhere that it’s at Premium Services>Real Debrid

For the life of me I can’t work out where that is. 

Here’s hoping you can point me in the right direction. 

Miles.

**Comment by umbrellaplug** [comment]
From the main menu of Umbrella. Premium Services > Real Debrid
You will have 3 options 
Real-Debrid: Torrent Transfers
Real-Debrid: My Downloads (Your Cloud)
Real-Debrid: Account Info

Premium Services may not show on the main menu until you authorize real-debrid in the addon.

**Comment by milesmcclane** [comment]
Thank you so much! What a wonderful addon you’re making.
