### ISSUE TITLE
Trakt live scrobbling 

### ISSUE THREAD

**Issue by krishne35** [umbrellaplug/umbrellaplug.github.io#26]
Iirc present implementation is such that when ever I start a ep or movie it will delete previous playstate if any and will send a new playstate when we stop the content 

Can live scrobbling like it's implementation on trakt script posible coz sometimes the video might fc and umbrella won't scrobbe the content to trakt

**Comment by umbrellaplug** [comment]
We rely on events from kodi to mark as watched or scrobble. I can look into capturing different events. When you ask "Can live scrobbling like it's implementation on trakt script" can you elaborate? What trakt script?

**Comment by krishne35** [comment]
The default trakt addon from kodi repo live scrobbling meaning it will constantly update the play state of what I'm watching

**Comment by krishne35** [comment]
[https://cdn.thenerdystudent.com/wp-content/uploads/2019/03/traktscrobble.png]()
