### ISSUE TITLE
[Feature] Auto rescrape all sources if no sources found

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#261]
### Feature

Hi Umbrella Dev,
Love your work. Also, nice to see you back on the scene with an update. I was wondering though, by default not all scrappers are enabled on CoCo scrappers (I know this is not your addon btw) which is great for speed, but sometimes a Source cannot be found, it would be neat if that happens then the addon would automatically scrape again but this time using all providers in the hope that it will find a source. 
Hoping I make sense.

**Comment by TheGuru276** [comment]
@adamosborne83 are you aware that there is a context menu feature to enable a rescrape with these options.  There is also a configuration setting that you can enable that changes this context menu option to change between bringing up all of the rescrape options or to just do a full rescrape automatically when you select it.

**Comment by adamosborne83** [comment]
> @adamosborne83 are you aware that there is a context menu feature to enable a rescrape with these options.  There is also a configuration setting that you can enable that changes this context menu option to change between bringing up all of the rescrape options or to just do a full rescrape automatically when you select it.

Hi, Yes I am aware that there is a context menu to do this, it's just for a streamless experience, for it to automatically do this when no sources are found. That's all.

**Comment by umbrellaplug** [comment]
available in latest update. default off.
