### ISSUE TITLE
[BUG] episode count update

### ISSUE THREAD

**Issue by saxoloman** [umbrellaplug/umbrellaplug.github.io#263]
### Bug

Hi
I have an issue when new episode comes out of any tv show and my episode count dont update,even after few days of release.
Only thing i found that fixes it is force sync trakt to local database
This image shows mandalorian and ted laso showing checked mark but it should show 1 episode unwatched
![IMG_20230405_115755](https://user-images.githubusercontent.com/99698419/230049346-1dd1d61c-9eb6-438e-bbe0-075bbb9720e9.jpg)

This is how it should be after force trakt sync
![IMG_20230405_120019](https://user-images.githubusercontent.com/99698419/230049767-86a72fbf-399f-46c1-ae07-0e5b9e0ab819.jpg)

If i need to submit any other logs can you please tell me wich ones ?
Thank you

### Expected Result

I expect show episode count to update when new episode is released

### Steps To Reproduce

1. watch all episodes of any ongoing tv show
2. Wait for new episode to come out in 7 days
3. Check episode count status

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.1
Coreelec latest nightly
Odroid n2+

https://paste.kodi.tv/nelumowuju

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I attempted to duplicate this today with futurama. The episodes counts were updated. I had to reload skin for the widgets on homescreen to update.
