### ISSUE TITLE
Liked Trakt Lists

### ISSUE THREAD

**Issue by jcommon123** [umbrellaplug/umbrellaplug.github.io#265]
Hi,
I've liked a few lists in Trakt, when trying to open the official ones, nothing loads. A pop up states 'Nothing Was Found'. In the log, when trying to poll the API its coming back with a 404 error. Is this something that can be fixed or is just an issue with Trakt's API. I've attached the log file to this. I've also dropped a link to one that I liked.

Many thanks.

[umbrella.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/11173857/umbrella.log)
https://trakt.tv/lists/official/ted-collection?sort=rank,asc

**Comment by umbrellaplug** [comment]
Had another report of this as well earlier. I have not had an issues here. I'll see if I can track down any issues. Other user reported:
"Reauth trakt, clear cache, reboot kodi
Fixed it for me"
