### ISSUE TITLE
[BUG] Apple TV Search Results no 4K icon

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#266]
### Bug

4K icon missing on Apple TV from search results

### Expected Result

4k icon to display

### Steps To Reproduce

Select TV episode or film that has 4K results, Search results missing 4K icon

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

20.1, Apple TV, cannot upload logs at the moment

![IMG_3532](https://user-images.githubusercontent.com/121737707/230848614-40752101-b54d-4bcb-8ac1-8bbdf83efad6.jpg)

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I will load up my apple tv and test this.

**Comment by umbrellaplug** [comment]
Duplicated here. I'll update you once it's fixed.

**Comment by umbrellaplug** [comment]
Fixed in latest update.

**Comment by Ade-AV** [comment]
Hi

Just reinstalled Kodi/Umbrella and noticed the 4K icons are missing again

Thanks
