### ISSUE TITLE
[Possible BUG] Progress as widget in AH2, Context Browse Series/Progress not working

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#267]
### Bug

In Arctic Horizon 2 create a widget on the home screen from My TV Shows->Progress, setting Use Full Context Menu in Widgets (Kodi 20 Only) is set

Bring up Context menu against an episode, Browse Series/Progress not working

### Expected Result

Browse Series/Progress to work

### Steps To Reproduce

As above

Works ok direct from Umbrella->My TV Shows->Progress

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

20.1, macOS, Apple TV, cannot currently upload logs

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
These items shouldn't be showing on this menu on widgets. I've corrected it. Thank you.
