### ISSUE TITLE
IMDb options

### ISSUE THREAD

**Issue by webmaher** [umbrellaplug/umbrellaplug.github.io#27]
Is possible to add this:
IMDb:
Authentication via cookie
Browsing for titles
Trending
Fan Favourites
Recommended
Discover by Year
Browsing Shows
Seasons
Season episodes
Lists
Watchlist
Search for titles or people
Debrid files/transfers browsing
Auto mark as watched when played more than 90 percents
Contextmenu
Cast and Crew browsing
Trailers
Mark as watched/unwatched (by rating/unrating a title)
Add/Remove to/from list
Rate/Unrate titles
Seeing similar titles (i.e. More like this)
Add new sources to debrid cache

Trakt is not good 4 me i like IMDb just like here https://github.com/a4k-openproject/a4kStreaming

**Comment by umbrellaplug** [comment]
The majority of what you have requested is either available already, in TMDBHelper (which integrates with Umbrella), or not even available at all on IMDB's api. I may look into further IMDB features or updates, but at this time this is not something high on priority list.
