### ISSUE TITLE
CPU hogging

### ISSUE THREAD

**Issue by Gemini88** [umbrellaplug/umbrellaplug.github.io#270]
### Bug

Choppiness in whatever video that I play with Umbrella enabled when disabled no such problem

### Expected Result

No cpu taxing and smooth video playback

### Steps To Reproduce

1. Intall addon 
2. Play any video

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21.0 
Nvidia Shield  TV

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Umbrella doesn't control playback. We pass a url of media to Kodi. Kodi plays the video. You're on an alpha version of Kodi. You also opened an issue without attaching a log.

**Comment by Gemini88** [comment]
As I said the cpu is being hogged when the addon is enabled, nothing to do with playback its a addon Kodi is the player thats obvious what im saying is that when your addon is enabled video playback has minor stuttering there isnt any stuttering when your addon is disabled I have many video addons none cause playback except Umbrella

**Comment by umbrellaplug** [comment]
For sure changed my mind with these comments. I'll get right to working on fixing your **alpha** Kodi. 

Downgrade to a stable version of Kodi.
