### ISSUE TITLE
Hosters

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#274]
I can't seem to get hosters anymore. Is there a setting for it? Thank you.

**Comment by umbrellaplug** [comment]
I'm sorry, I don't understand the issue. Can you be more specific about what you're having the issue with? Hosters are typically turned on and off in CocoScrapers, but I'm not sure if that's what you're asking.

**Comment by Arthur1967** [comment]
Im not getting rlbb streams anymore and ive made sure its on on coco scrapers

**Comment by umbrellaplug** [comment]
Okay. I don't use RLSBB on my personal setup so I'm not super familiar with it. I also do not do the scrapers. I will see if there's anything I can do to help though.

**Comment by Arthur1967** [comment]
OK it just appears when you click on any of the hosters none of them are bringing in anything torrentio is  though thanks
