### ISSUE TITLE
watch trailer option for movies section [FEATURE] Short Description

### ISSUE THREAD

**Issue by swoosh1325** [umbrellaplug/umbrellaplug.github.io#279]
### Feature

I know this is already there under information but it has stopped working in the past few weeks, not sure if this is something you can fix or if its something on the youtube addon end. Anyways either way the addon is fantastic and thanks for all that you do!

**Comment by umbrellaplug** [comment]
Have you tried updating to the youtube plugin that's in the Umbrella repo? They had some issues a while back and I had to put a beta version on my repo for it to work. This may be the same issue. Can you try that and let me know?

**Comment by swoosh1325** [comment]
I see you were already onto it, that worked like a charm! thanks a lot.

**Comment by swoosh1325** [comment]
Also thanks for such a quick response, you have no idea how much it means to have such a great functional addon to depend on that just keep improving !
