### ISSUE TITLE
[FEATURE] Menue for Local Watched Progress not Relying on Trakt

### ISSUE THREAD

**Issue by slmlm2009** [umbrellaplug/umbrellaplug.github.io#281]
### Feature

Hi

I love Umbrella and I love how fast it is getting updated and all the features it has such as showing next episode pop up after the subtitle file ended, it's simply lovely.

However, there is only one feature that I am missing and having that will make Umprella perfect IMO.

Back when I was using Fen, there is a menue for in progress episodes/movies based on local Kodi watched status provider. Hence authentication to Trakt is not required to have this as a widget in your home screen. I don't like authorizing Trakt to streaming addons because that make them bulcky and full of errors. However in Umbrella without Trakt authentication there is no menue for local progress at all.

I really appreciate it if you could implement this same feature available in Fen. This as what I said will make Umbrella perfect in my opinion.
 
If you need more explanation please let me know.

All the love

**Comment by umbrellaplug** [comment]
Added to list of things to add.

**Comment by umbrellaplug** [comment]
Decided not to do this.
