### ISSUE TITLE
[FEATURE] Alphabetize and make Non-colored lists in Hidden Progress Manager etc, so Shift + Letter works

### ISSUE THREAD

**Issue by cg00001** [umbrellaplug/umbrellaplug.github.io#282]
### Feature

Kodi doesn't recognize colored lists when Shift + Letter is pressed, so if you have a lot of movies/shows you can't find eg shows from T, got to scroll a lot.
Alphabetizing whole lists would also work in combination with the above.
![HPM](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/38960370/5e04e69d-41be-48e1-96a8-7c46a8460463)

**Comment by adamosborne83** [comment]
Use Stremio?

**Comment by cg00001** [comment]
> Use Stremio?

Should I?

**Comment by adamosborne83** [comment]
> > Use Stremio?
> 
> Should I?

100%

**Comment by cg00001** [comment]
@umbrellaplug Is the above guy a freelance spammer, or I can hire him?

**Comment by umbrellaplug** [comment]
He usually is pretty helpful. I don't know what's with this stremio bullshit everywhere in the Kodi stuff lately. The screens are built using xml. I'll look into of there's a way to index them.

**Comment by umbrellaplug** [comment]
Looked into this. Spoke with some other developers about it as well. Unfortunately not possible on a custom xml. The list is alphabetically sorted now. Going to go ahead and close this issue out. Have a good one.

**Comment by cg00001** [comment]
Thank you for checking it out.
