### ISSUE TITLE
Cocoscrapers 

### ISSUE THREAD

**Issue by ronfrankhill** [umbrellaplug/umbrellaplug.github.io#283]
### Feature

Just asking. I can't remember the last time cocoscrapers got updated or maintenance? Was it two months ago. Normal it might be once per month which l might be wrong as many torrent sites were pulled down within those two months.

**Comment by umbrellaplug** [comment]
Been a while. I don't do the scrapers.

**Comment by ronfrankhill** [comment]
Okay. Thanks. Is it possible to tell those responsible. Please. Because l know that they are very busy also.

**Comment by umbrellaplug** [comment]
What problems are you having?

**Comment by ronfrankhill** [comment]
Nothing. I just grown accustomed to the once a month maintenance or update for cocoscrapers. As we all know that torrents sites come and go especially what happened with certain torrents that had closed their sites in June for good.
