### ISSUE TITLE
[BUG] Resume Trakt episode from 'Finish Watching' menu uses wrong duration (breaking 'Filter Episode by Size')

### ISSUE THREAD

**Issue by bbviking** [umbrellaplug/umbrellaplug.github.io#284]
### Bug

When resuming a partially watched episode, specifically from within the finish watching menu, the duration being used is incorrect (Only a matter of seconds). This causes either only a few very low quality results to show or none when used with the  'Filter Episode by Size' option as the max_size is innacurate.

When I attempt to resume an episode from within any other menu this bug is not present.

### Expected Result

The duration being used should be the same pulled from TMDB.

### Steps To Reproduce

1. Authorise a trakt account with Umbrella
2. Go to 'My TV Shows'
3. Go to 'Finish Watching'
4. Attempt to resume any partially in progress episode

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.1
Windows 11 PC

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Fix for this should in the latest test version.

**Comment by umbrellaplug** [comment]
Feature in latest update.
