### ISSUE TITLE
[FEATURE] Short Description

### ISSUE THREAD

**Issue by bquiet1** [umbrellaplug/umbrellaplug.github.io#286]
### Feature

under Discover tv shows;   networks; BBC1:  none of the current shows are in the lists.  the same issue exists in numerous other networks listed.  Is there a network list for IMDB?

**Comment by Tikipeter** [comment]
>none of the current shows are in the lists.

Of course they're in the lists. All shows premiered on the Network will be in the list.

Do you mean you want them to be ordered by newest shows first, thereby the newest shows will be on the first page?

**Comment by umbrellaplug** [comment]
Duplicate issue opened. Please see the response there.
