### ISSUE TITLE
[FEATURE] Trailer on right click 

### ISSUE THREAD

**Issue by The-cpu-max** [umbrellaplug/umbrellaplug.github.io#287]
### Feature

![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/102416233/63bdd7e3-4a50-460c-aa3d-23f3f5dbb5b7)
There are so many things, but when you right-click on the movie, there is no option in the right-click menu to see the trailer
I would like you to add a first button in the menu option to see the trailer

**Comment by Omarscomin** [comment]
I'm kinda blown away by the fact that all of your feature _requests_ sound like demands/expectations🤔

**Comment by The-cpu-max** [comment]
> I'm kinda blown away by the fact that all of your feature _requests_ sound like demands/expectations🤔

I didn't understand, don't you want to improve the existing one? I'm just offering advice for improvement It's not a requirement

**Comment by Omarscomin** [comment]
> > I'm kinda blown away by the fact that all of your feature _requests_ sound like demands/expectations🤔
> 
> 
> 
> I didn't understand, don't you want to improve the existing one? I'm just offering advice for improvement It's not a requirement


Would you be willing to add a 'view trailer' option, at the top of the context menu?" sounds a lot nicer than "I would like you to add a first button in the menu option to see the trailer". You came across low-key bossy & demanding.

**Comment by The-cpu-max** [comment]
> > > I'm kinda blown away by the fact that all of your feature _requests_ sound like demands/expectations🤔
> > 
> > 
> > I didn't understand, don't you want to improve the existing one? I'm just offering advice for improvement It's not a requirement
> 
> "Would you be willing to add a 'view trailer' option, at the top of the context menu?" sounds a lot nicer than "I would like you to add a first button in the menu option to see the trailer". You came across low-key bossy & demanding.

I'm sorry you feel that way. That was not my intention In any case, I have many more useful tips I would love for you to do so

**Comment by Omarscomin** [comment]
> > > > I'm kinda blown away by the fact that all of your feature _requests_ sound like demands/expectations🤔
> 
> > > 
> 
> > > 
> 
> > > I didn't understand, don't you want to improve the existing one? I'm just offering advice for improvement It's not a requirement
> 
> > 
> 
> > "Would you be willing to add a 'view trailer' option, at the top of the context menu?" sounds a lot nicer than "I would like you to add a first button in the menu option to see the trailer". You came across low-key bossy & demanding.
> 
> 
> 
> I'm sorry you feel that way. That was not my intention In any case, I have many more useful tips I would love for you to do so

I'm not the developer. And we should all take a moment to be thankful for that, because I'll never be patient enough to tolerate "requests" like yours😬😂

**Comment by adamosborne83** [comment]
> I'm kinda blown away by the fact that all of your feature _requests_ sound like demands/expectations🤔

He's all over github, he's comical.

**Comment by Omarscomin** [comment]
> > I'm kinda blown away by the fact that all of your feature _requests_ sound like demands/expectations🤔
> 
> He's all over github, he's comical. 

I'm really hoping that English is not his first language.

**Comment by umbrellaplug** [comment]
This has been added into version 6.6.253 on the test repo and after testing will be pushed to release version.

**Comment by adamosborne83** [comment]
Works fine

**Comment by umbrellaplug** [comment]
Feature in latest update.
