### ISSUE TITLE
[FEATURE] Adding Telegram into an umbrella

### ISSUE THREAD

**Issue by The-cpu-max** [umbrellaplug/umbrellaplug.github.io#288]
Today there is an Israeli bulid of Kodi
which includes a telemedia extension - the extension makes it possible to see content from Telegram
I would love for you to look into the issue of including the source in the umbrella as well

**Comment by umbrellaplug** [comment]
Can you provide more information? I don't really want to install a build to understand a request. I understand you're asking for telegram support, but I looked into this previously and I do not have any telegram sources to use for testing/writing the code for this.

It's also likely I would need to work with the scraper developer to add support for this.

**Comment by The-cpu-max** [comment]
> 



> Can you provide more information? I don't really want to install a build to understand a request. I understand you're asking for telegram support, but I looked into this previously and I do not have any telegram sources to use for testing/writing the code for this.
> 
> It's also likely I would need to work with the scraper developer to add support for this.

Telegram is full of groups that have content
I would be happy to send you a private message on Telegram

**Comment by umbrellaplug** [comment]
I do not use telegram as it requires a phone number.

**Comment by The-cpu-max** [comment]
> I do not use telegram as it requires a phone number.

The use of Telegram requires a phone number
There is no other way to enter without it

**Comment by umbrellaplug** [comment]
Must be a language barrier here. I do not use telegram because it requires a phone number. I will not be putting my phone number or any other identifying information into any app. Closing this issue.
