### ISSUE TITLE
[FEATURE] duff you addon

### ISSUE THREAD

**Issue by The-cpu-max** [umbrellaplug/umbrellaplug.github.io#289]
### Feature

Please add the duff you extension to the repo
It is better than YouTube because it does not require an API to use

**Comment by umbrellaplug** [comment]
Another unclear request.

Are you wanting an addon add to the repo just to have it on another repo or are you wanting support for this added vs YouTube?

**Comment by The-cpu-max** [comment]
> Another unclear request.
> 
> Are you wanting an addon add to the repo just to have it on another repo or are you wanting support for this added vs YouTube?

I just wanted you to add it to your repo's repository
I saw that there was only regular YouTube

**Comment by umbrellaplug** [comment]
I only maintain youtube on the repo because it's a different version than the one available on the kodi repo. There is already a version of the duff you available on mrgsi. I'm not interested in maintaining another addon.
