### ISSUE TITLE
Autoplaylist Creation 

### ISSUE THREAD

**Issue by IG2022** [umbrellaplug/umbrellaplug.github.io#29]
Hey back again this time with a request rather than an issue. I'm not sure how realistic or plausible this would be but I've seen it implemented in another addon. 

Would it be possible to have autoplaylist creation for episodes in the progress section? At the moment when we click on an episode it takes us to another page that loads up all the episodes for that particular season/show. Would it be possible to allow the user to directly click and play an an episode in the progress section the episode plays and a playlist is created automatically? I know that direct progress scraping exists but that doesn't allow for continuous playback. 

Again not sure how possible or plausible it is but I thought I'd ask.

**Comment by Wilson-Fisk** [comment]
This function should already essentially exist through the auto play feature. Also using the play from here context menu item should creatr the playlist items if I'm remembering correctly

**Comment by IG2022** [comment]
> This function should already essentially exist through the auto play/play next dialogue feature. Also using the play from here context menu item should creatr the playlist items if I'm remembering correctly

Yeah it does exist but with an extra step. (I'm hoping the step that takes you to the page with all the episodes can be eliminated and the episode would just play when being selected directly from the progress section)  Also the "play from here" function doesn't work with some skins (specifically Arctic Horizon 2) when clicking play from here in that skin it creates a playlist for the shows in the progress section not the specific show you select I'm not sure why it behaves like this on AH2. In this case I can't really use direct progress scrape and play from here for continuous playback.

**Comment by umbrellaplug** [comment]
I'm aware of this issue. It has to do with the skin allowing you to launch episodes from episodes or seasons view. In most skins and the plugin you go show>seasons>episodes. There are different list types in Umbrella for these and methods to populate them.  With these skins you are launching episodes from seasons or episodes. I will look into this and see if I can adjust for this. This issue also effects "Play Next". It will not work when launched from seasons but will on episodes.

**Comment by umbrellaplug** [comment]
#35
