### ISSUE TITLE
[Feature] Force View Type in settings

### ISSUE THREAD

**Issue by cgwprs** [umbrellaplug/umbrellaplug.github.io#290]
### Feature

I highly prefer the InfoWall (type 54) when browsing for content. I was able to find where to change the setting in the .xml files but many people I know would not have been able to do that.

**Comment by umbrellaplug** [comment]
This is a preference. If you want a particular view type then save it in view types.

**Comment by Arthur1967** [comment]
Make sure the skin you’re using allows for that view type and if it does,
it will be there if it doesn’t allow for that if you type it won’t be
there. Also, the view type may be a setting right in the skin.

**Comment by umbrellaplug** [comment]
It's in the options for umbrella. Under viewtypes. You can set and save what view type to use for each view like movies episodes and such.

**Comment by cgwprs** [comment]
Thank you. It just wasn't in the place I expected it to be. In a few other addons I have seen that setting in the right click settings menu instead of opening the addon and then going through a settings menu. cheers
