### ISSUE TITLE
[FEATURE] SIMKL Watchlist and Watched Indicators

### ISSUE THREAD

**Issue by Lortac** [umbrellaplug/umbrellaplug.github.io#291]
### Feature

Hey since i Prefer SIMKL to TRAKT i woud be pretty hyped when you could add more SIMKL Functionality like for Trakt. Watched Status Indicators and a option to view the Watchlist in the addon like with Trakt.

**Comment by umbrellaplug** [comment]
I have been wondering what the interest level was in simkl. I'll see what options can be added.

**Comment by umbrellaplug** [comment]
Unfortunately, I have not seen as much interest in Simkl as I had hoped for. At this point it does not seem worth it to integrate simkl any further. I'll keep it in mind as a future possibility if it becomes more requested.
