### ISSUE TITLE
Trakt

### ISSUE THREAD

**Issue by ronfrankhill** [umbrellaplug/umbrellaplug.github.io#292]
### Bug

I opened the section call My TV Shows but no trakt progress and trakt watchlist is coming up. I re authorized twice but still nothing. Did l did something wrong. This is version 6.6.25

### Expected Result

Nothing is showing for trakt.

### Steps To Reproduce

Kodi 20.2 on Android TV box

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

This never happened before 

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
No logs or other information provided.
