### ISSUE TITLE
[BUG] Resume progress says 0%

### ISSUE THREAD

**Issue by 666jones** [umbrellaplug/umbrellaplug.github.io#294]
### Bug

Resume progress says 0% on movies and shows that have been stopped during playback.

I have indicators set as trakt and resume progress set as trakt scrobbles. If I resume a show or movie it has the correct resume point however it just says 0% on the skin indicators.

I am using titan bingie mod im not sure if this is a bug or a comparability issue or maybe I just need to change a setting I have thoroughly gone over the settings so I do apologise if this is the case.

### Expected Result

It would be nice if it could show the % of what's been watched for in progress movies and episodes

### Steps To Reproduce

Start a show or movie skip 20 mins in resume point is saved. But % says 0 in the skin indicators.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

20.2 alpha 2 Kodi 
Titan binge mod 
Amazon firecube 3rd gen
Amazon firestick 4k max

Everything is upto date

I have attached a photo
![20230720_142640](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/121204283/a57f1409-908c-4f98-895e-0bfce139ce7a)

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I'll load the skin and see what values it's using for this. It may be something I can set.

**Comment by 666jones** [comment]
I'm going to go ahead and close this as it works perfectly in other skins and I  now use fuse and don't have that issue with this skin
