### ISSUE TITLE
[FEATURE] PlayNext for full shows

### ISSUE THREAD

**Issue by 666jones** [umbrellaplug/umbrellaplug.github.io#296]
### Feature

It would be very cool if you could make it so PlayNext will continue to work when starting the next season. Currently PlayNext stops works when on a final episode. I know I mentioned this the other day on Reddit just thought I'd post it in the appropriate place as it's a feature request. Thanks for all your time and effort.

**Comment by umbrellaplug** [comment]
This was in the latest update pushed today.
