### ISSUE TITLE
A.V. Andrews: Dawn

### ISSUE THREAD

**Issue by ronfrankhill** [umbrellaplug/umbrellaplug.github.io#297]
### Feature

Sorry to bother you but when you have time tonight. Could you check for me. If this drama TV series called V.C. Andrews: Dawn that started streaming on Lifetime 8 July 2023 is available on torrent sites. Please. I am not seeing any links coming up.

**Comment by adamosborne83** [comment]
That doesn't seem like an umbrella issue, it's the scraper addon that gets links, not umbrella.

**Comment by ronfrankhill** [comment]
That's why I ask the developer to investigate on my behalf. Nothing was mentioned it was related to the add-on. The issue is the scrapers which the developer of the add-on have to ask those responsible for Cocoscrapers on my behalf.

**Comment by adamosborne83** [comment]
> That's why I ask the developer to investigate on my behalf. Nothing was mentioned it was related to the add-on. The issue is the scrapers which the developer of the add-on have to ask those responsible for Cocoscrapers on my behalf.

Or maybe raise the issues on the CoCo scrapers Github? Just a thought.

**Comment by adamosborne83** [comment]
Just an FYI, Umbrella is not a piracy addon, when you mention 'issues' of this description within Umbrella GitHub it can flag up as a 'piracy' addon and therefore get this GitHub account closed..... just saying.

**Comment by umbrellaplug** [comment]
I see no results for this. It's not a scraper issue. It's a lack of results. I did see results on usenet. Try easynews if you have it.

**Comment by ronfrankhill** [comment]
Okay. Thanks. I will do that. I will sign up for easynews
