### ISSUE TITLE
[BUG] Tv Shows always flatten

### ISSUE THREAD

**Issue by versus2** [umbrellaplug/umbrellaplug.github.io#298]
### Bug

Whatever you select in tools >tv shows. Whether you select or I select Flatten Tv shows list always appears flatten. One cannot get shows to appear with season folders.

### Expected Result

Yours houmf be able to switch from flattened to seasoned in accordance with the choice in tools>tv shows > Flatten Tv Shows

### Steps To Reproduce

1. Settings
2. Tv Shows
3.. Flatten Tv Shows > list is  always flatten regardless the option is checked or inchecked

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi Nexus > Cosmos widget

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Not happening on default skin. This is related to your skin.
