### ISSUE TITLE
Little request

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#3]
Good afternoon,
Firstly thank you for forking venom, and fantastic and detailed responses so far, so I am hoping you maintain and grow this.

Just a little, if you would, from an icon package would you consider adding Exuary back into it? I just like the clean lines.

**Comment by adamosborne83** [comment]
> Yep, I can put those and the ole' red back. I'd rather have more options than less. I shouldn't have removed them in the first place. I'm working on a build right now with some stuff in it to address a server response I've started seeing from trakt. When I push that build I'll add the icons back in.

Thank you ever so much for doing that.... I am loving the clean simple logo.
Fab work. 
Hopefully I won't pester you with issues as much as I did 123venom haha.....

**Comment by umbrellaplug** [comment]
Pushed in latest update. Old Icons are in settings. Closing issue. Enjoy!
