### ISSUE TITLE
[BUG] playnext issue 

### ISSUE THREAD

**Issue by 666jones** [umbrellaplug/umbrellaplug.github.io#300]
### Bug

When playing a TV show if you press the return / back button when the playnext window is on the screen the window stops appearing and PlayNext no longer works until clearing the cache within umbrella. 

My settings are deult window style. And show the playnext window with 60 seconds remaining.

Here is a log maybe this will help.
https://paste.kodi.tv/fevucivahe

### Expected Result

Playnext widow to still be shown the next time I watch a TV show. Pressing return / back causes the playnext feature to completely stop working 

### Steps To Reproduce

1.Start a TV show.
2. Skip near the end so the play next window appears.
3. Press return / back button the playext widow will close. Press back / return again to stop / exit the video.
4. Start a new show and the playnext widow doesn't appear and it no longer plays the next episode.
5. Clear cache and it will work again.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.2
Firestick 4k
Umbrella 6.6.26 also happened on 6.6.25

Kodi log: https://paste.kodi.tv/fevucivahe

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by Omarscomin** [comment]
> Also I just noticed it has stopped showing the playnext popup again without even pressing the return back button so what I believed was causing the issue might not be the case. tired to get a log but it was larger then 1mb so was unable Todo so. I exited Kodi and loaded it back up and the play next started to work again.

I can relate. The Playnext pop up stops working if I switch from one show to another. I have to reload my skin to get it to work again.

**Comment by 666jones** [comment]
> 

Are you using the default pop up window? I'm wondering if changing the window style might help

**Comment by Omarscomin** [comment]
> > > Also I just noticed it has stopped showing the playnext popup again without even pressing the return back button so what I believed was causing the issue might not be the case. tired to get a log but it was larger then 1mb so was unable Todo so. I exited Kodi and loaded it back up and the play next started to work again.
> 
> > 
> 
> > I can relate. The Playnext pop up stops working if I switch from one show to another. I have to reload my skin to get it to work again.
> 
> 
> 
> Are you using the default pop up window? I'm wondering if changing the window style might help
> 
> 
> 
> 

No, I'm using the AH2 style. I haven't played around with any other styles yet, or any other skins.

**Comment by umbrellaplug** [comment]
I'm on vacation a few days. I'll check this out when I get back.

**Comment by 666jones** [comment]
> I'm on vacation a few days. I'll check this out when I get back.

Kl man hope you have a nice holiday

**Comment by umbrellaplug** [comment]
Bad news, I attempted to duplicate this on my shield and could not duplicate the issue. Steps I took.

Enabled playnext and set to default.
Picked a random TV Show.
Played episode, FF to last couple of minutes and waited for playnext popup.
Hit back on controller when playnext popped up.
Let next episode play then FF to last couple of minutes and playnext came up again. Hit back on controller.
Let next episode play then FF to last couple of minutes and still watching came up. Hit back on controller.
Playback stopped.

**Comment by umbrellaplug** [comment]
@Omarscomin 
No, I'm using the AH2 style. I haven't played around with any other styles yet, or any other skins.

Are you using a skin also?

**Comment by Omarscomin** [comment]
> @Omarscomin 
> 
> No, I'm using the AH2 style. I haven't played around with any other styles yet, or any other skins.
> 
> 
> 
> Are you using a skin also?

Yes, I'm using Arctic Horizon 2.

**Comment by Omarscomin** [comment]
> @Omarscomin 
> 
> No, I'm using the AH2 style. I haven't played around with any other styles yet, or any other skins.
> 
> 
> 
> Are you using a skin also?

Sorry for my double reply, but I wanted to add that pressing back is not what causes the issue for me. I'm fairly certain that the popup stops working once I finish a season of a show and start a new season. If I _change_ tv shows, I have issues as well. If I don't reload the skin after changing shows, the previous show that I was watching usually starts playing from where I left off (same thing happens when I switch to a movie without reloading the skin). Occasionally, the correct show and episode starts playing, but the up next pop up won't work until I reload the skin.

**Comment by umbrellaplug** [comment]
> Sorry for my double reply, but I wanted to add that pressing back is not what causes issues for me. If I _change_ tv shows, I have issues. If I don't reload the skin after changing shows, the previous show that I was watching usually starts playing from where I left off, even if I completely finished watching the last episode (same thing happens when I switch to a movie without reloading the skin). Occasionally, the correct show and episode starts playing, but the up next pop up won't work until I reload the skin.

I tried duplicating this and I was not able to. I'm running the default playnext and no skins though. Let me switch to ah2 style without skin and test. I will try ah2 with ah2 skin after.

**Comment by 666jones** [comment]
> I was unable to duplicate this with ah2 style and skin. Please try to reproduce the issue on your system and grab a log and open a new issue for it. I'm going to go ahead and close this one out since the original poster was able to resolve their issue by restarting kodi.

I did play about with it earlier and definitely managed to reproduce the issue. On a fresh install with just arctic fuse skin, umbrella, and tmdb helper installed. I think a step to replicate issue I made a error on because I have a keymap to stop the video so when I go back it actually stops and ends playback. I'll test it out without my keymap and get back to you. Just cooking dinner quickly. I'll also get a log for you when it happens. Thanks very much for taking the time to look into this

**Comment by 666jones** [comment]
Oh I also have the same thing happen as omarscomin said. Happens when I swop shows and when I swop shows it plays the last show I watched like there was a episode lined up in a playlist or something. not quite sure what's going on but I'll play about and send you a log

**Comment by umbrellaplug** [comment]
> Oh I also have the same thing happen as omarscomin said. Happens when I swop shows and when I swop shows it plays the last show I watched like there was a episode lined up in a playlist or something. not quite sure what's going on but I'll play about and send you a log

This has to do with the prescrape. Once the "playnext window" has appeared on the screen even if you stop or go back a lot of the time the next video has already been queued up by the prescrape in the background so when you select the next item to play it actually plays that video that was queued instead of the one selected. I'm not sure there's a lot I can do about that one. Usual workaround is just to hit stop and select your video again and the correct one should play or hit stop on last episode you plan to watch before the playnext window appears. I will look and see if there's anything I can do in that scenario, but that's been a known thing for a while. Fen will do the same.

**Comment by Omarscomin** [comment]
> > Oh I also have the same thing happen as omarscomin said. Happens when I swop shows and when I swop shows it plays the last show I watched like there was a episode lined up in a playlist or something. not quite sure what's going on but I'll play about and send you a log
> 
> 
> 
> This has to do with the prescrape. Once the "playnext window" has appeared on the screen even if you stop or go back a lot of the time the next video has already been queued up by the prescrape in the background so when you select the next item to play it actually plays that video that was queued instead of the one selected. I'm not sure there's a lot I can do about that one. Usual workaround is just to hit stop and select your video again and the correct one should play or hit stop on last episode you plan to watch before the playnext window appears. I will look and see if there's anything I can do in that scenario, but that's been a known thing for a while. Fen will do the same.

I had a feeling this was either a Kodi issue or a skin issue. I wasn't 100% where/who to report it to, if at all. Thank you for looking into it for us!

**Comment by 666jones** [comment]
Ok it works flawlessly on the estuary skin tested it 14 times and had the pop up everytime no matter what I did (using AH2 playnext theme)

Then tested it 3 times using arctic fuse skin and I only had the pop up once and that was on my first attempt.

Used the same episode for all the testing.

Here is my log 
https://paste.kodi.tv/ulisinojut

**Comment by 666jones** [comment]
Would it be worth me trying the test version? Or a older version of umbrella? I have all my stuff backed up so not worried if something goes wrong. I tried to install the test version via zip but got a error failed to install addon from zip

**Comment by 666jones** [comment]
> > Also I just noticed it has stopped showing the playnext popup again without even pressing the return back button so what I believed was causing the issue might not be the case. tired to get a log but it was larger then 1mb so was unable Todo so. I exited Kodi and loaded it back up and the play next started to work again.
> 
> I can relate. The Playnext pop up stops working if I switch from one show to another. I have to reload my skin to get it to work again.

I been playing about with some settings. And mine seems to be working great now.

When you get time try these settings and let us know how you get on.

1.Enable playnext 
2. I chose subtitle end
3. Backup trigger if subtitles fall seconds remaining
4. 60 seconds 
5. Play next default action: Play
6. Show close/ hide button: no
7. Number of episodes till still watching? 4
8. Still watching default action: pause

If you have your number of episodes set to 3 definitely try it on 4. That's what seems to have made a noticeable difference for me.

**Comment by Omarscomin** [comment]
> > > Also I just noticed it has stopped showing the playnext popup again without even pressing the return back button so what I believed was causing the issue might not be the case. tired to get a log but it was larger then 1mb so was unable Todo so. I exited Kodi and loaded it back up and the play next started to work again.
> 
> > 
> 
> > I can relate. The Playnext pop up stops working if I switch from one show to another. I have to reload my skin to get it to work again.
> 
> 
> 
> I been playing about with some settings. And mine seems to be working great now.
> 
> 
> 
> When you get time try these settings and let us know how you get on.
> 
> 
> 
> 1.Enable playnext 
> 
> 2. I chose subtitle end
> 
> 3. Backup trigger if subtitles fall seconds remaining
> 
> 4. 60 seconds 
> 
> 5. Play next default action: Play
> 
> 6. Show close/ hide button: no
> 
> 7. Number of episodes till still watching? 4
> 
> 8. Still watching default action: pause
> 
> 
> 
> If you have your number of episodes set to 3 definitely try it on 4. That's what seems to have made a noticeable difference for me.
> 
> 

My up next popup is functioning properly as well. Only issue I'm having is not being able to swap shows without refreshing the player in some way, but that's not Umbrella-related, so we're all good!🙂Thanks for checking in! I'll definitely give these settings a try if I run into any issues!
