### ISSUE TITLE
[BUG] New episodes do not show up when view filter is set to unwatched

### ISSUE THREAD

**Issue by endlessterror** [umbrellaplug/umbrellaplug.github.io#303]
### Bug

On my trakt account I've got a number of ongoing series in my collection. I've also got the view set to be unwatched. This way while viewing shows I can see only the shows for which there are episodes left to watch and in episodes view, only unwatched episodes are displayed.

I discovered the issue by accident while waiting for a series' new episode to come up. Took a peak in "recent episodes" and found out that a new episode came up for a series I was watching. I went to the trakt series collection but with the filter set to unwatched the series was not displayed.

Setting the filter to "All" made the show appear in the series list, with a checklist next to its name (all episodes watched). Entering this show I can see that the single season currently playing has also a check mark next to its name. Entering it showed:
* the watched episodes with a checkmark (viewed), as expected
* the new unwatched episode did appear but without a checkmark at all!

Moving back to the series list, the show remains with the checkmark next to it. And changing the filter to "unwatched" makes this show disappear from the shows list.

### Expected Result

Upon a new episode and with the view filter set to unwatched, the show should appear, as well its season. And entering the season should display the unwatched episodes.

### Steps To Reproduce

1. Add an ongoing series to the trakt collection (foundation for example)
2. Mark all episodes as watched
3. Set filter to "unwatched", the series should disappear from the series display panel
4. Keep an eye on the recently released episodes. When a new episode appears for the series, try to check the trakt collection. If the issue is exhibited, then the show will still not be displayed at all
5. Now toggle the filter to **all**. The show will appear with all episodes that were watched having a tickmark (watched), whereas the new one will also appear without a tickmark.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.1  / LibreELEC 11 on Odroid C2.

umbrella.log does not depict anything of interest with the exception of the following lines:

[2023-07-28 18:39:18] [ plugin.video.umbrella: DEBUG ]: From func name: resources.lib.modules.trakt.sync_liked_lists() Line # :1614
                       msg : Trakt Liked Lists Sync Update...(local db latest "liked_at" = 72000, trakt api latest "liked_at" = 1593380948)
[2023-07-28 18:54:25] [ plugin.video.umbrella: DEBUG ]: From func name: resources.lib.modules.trakt.sync_liked_lists() Line # :1614
                       msg : Trakt Liked Lists Sync Update...(local db latest "liked_at" = 72000, trakt api latest "liked_at" = 1593380948)
[2023-07-28 19:09:32] [ plugin.video.umbrella: DEBUG ]: From func name: resources.lib.modules.trakt.sync_liked_lists() Line # :1614
                       msg : Trakt Liked Lists Sync Update...(local db latest "liked_at" = 72000, trakt api latest "liked_at" = 1593380948)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Steps To Reproduce

    Should be self-explanatory

I will see what I can figure out since it should be so self explanatory.

**Comment by endlessterror** [comment]
> Steps To Reproduce
> 
> ```
> Should be self-explanatory
> ```
> 
> I will see what I can figure out since it should be so self explanatory.

Hahaha, feel free to bash me, I deserve it! I've updated the OP with some hopefully clear steps to reproduce. I just hope the issue **will** exhibit itself on your setup :)

**Comment by endlessterror** [comment]
Some additional info: In the past I had watched its single season 1 and then removed it from the collection. Since a new season appeared, I re-added the show to the collection, so basically the show consists of the watched season 1 and the unwatched season 2. If I visit the collection list in umbrella with the filter set to "unwatched" the show does not display at all.

Not sure if this specific scenario can be reproduced, but I'm outlining the steps required:
1. Add a dual season show to collection
2. From umbrella mark the 1st season as watched
3. Remove the show entirely from collection and then re-add it
4. Set filter view in the series pane in umbrella to "unwatched". The show will not appear at all.

I can see that after my issue, a number of Trakt-related issues were reported as well. If there's a test version that you'd like me to try, I'd be more than happy to do so and report my findings.

**Comment by umbrellaplug** [comment]
See if you're having this behavior still on the latest test version. Changes have been made to indicators.

**Comment by endlessterror** [comment]
Issue is resolved, thank you!

**Comment by endlessterror** [comment]
Seems the issue is back. For example Foundation had the watched tick, seasons 1 and 2 also had the same tick, but entering season 2 showed correctly new (and non-watched) episodes S02E19 and S02E20.

**Comment by umbrellaplug** [comment]
Please don't reopen bugs from months ago.

**Comment by endlessterror** [comment]
My bad, so open a new issue for this one, right?

**Comment by endlessterror** [comment]
Quick question: in opening a new ticket and apart from the umbrella log, which logs should I enable that might be helpful in your investigation of the issue?
