### ISSUE TITLE
[FEATURE] AH2 playnext theme skin compatibility 

### ISSUE THREAD

**Issue by 666jones** [umbrellaplug/umbrellaplug.github.io#304]
### Feature

Would it be possible to make the ah2 playnext theme compatible with arctic fuse skin what is also made by jurialmunkey. As it stands the buttons don't display correctly (I have attached a photo) and the (are you still there) popup doesn't show. It's a very lovely looking playnext widow and would be awesome combined with the fuse skin

![20230730_233927](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/121204283/c4ccb86f-5264-413b-a59a-a36fa8c1339a)

**Comment by umbrellaplug** [comment]
oh cool. that's a new one. I'll have to load the skin up and try it out. I will see what I can do.

**Comment by 666jones** [comment]
> oh cool. that's a new one. I'll have to load the skin up and try it out. I will see what I can do.

It's a very nice skin indeed I really like the menu it's very customisable. fingers crossed :) hope you had a nice holiday

**Comment by umbrellaplug** [comment]
This should be resolved in the latest update pushed today.
