### ISSUE TITLE
[BUG] Watched shows NOT being marked as watched in Trakt

### ISSUE THREAD

**Issue by Madddcow** [umbrellaplug/umbrellaplug.github.io#309]
### Bug

As per the report title, I've found that shows I've watched with Umbrella aren't being marked as watched in Trakt.  However, I have no problems at all with this when using Fen.

I've tried a bunch of things including revoking/reauthorising Trakt, forcing Trakt syncs, uninstalling/reinstalling Umbrella, changing the Mark Watched percentage threshold etc.  Interestingly, I've had ongoing issues with this for months and at one stage, changing the Mark Watched percentage threshold appeared to have worked to fix the problem, but that's no longer the case,

### Expected Result

If I watch a show to the end (or past the Mark Watched percentage threshold), then the show will be marked as Watched in Trakt.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.2
Nvidia Shield Pro 
I have no idea what type of logging data would be required for this??

### Checklist
[Umbrella Log.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12280017/Umbrella.Log.txt)
[Kodi log.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12280019/Kodi.log.txt)

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by Omarscomin** [comment]
Just out of curiosity, are you 100% sure that things aren't being marked as watched on Trakt? Are you confirming that on the Trakt website?

The reason I ask is because I am facing a similar issue. When I finish a movie or episode, the "in-progress" indicator remains on the thumbnail of said movie or episode. However, it is technically marked as "watched", according to the Trakt website. Additionally, when I long press on the watched movie/episode, within Kodi, and select "Trakt Manager" from the context menu, I'm given the option to mark it as *unwatched*, which further confirms that Trakt has marked the content as "watched".

**Comment by Madddcow** [comment]
Great question, @Omarscomin. 
I haven't checked the Trakt website but when I check the Trakt status in Kodi by long-pressing the item title and selecting "Trakt Manager", it's indicated as unwatched and I have to select "Mark watched in Trakt".  I've also allowed several hours for Umbrella to sync with Trakt (in addition to forcing Trakt syncs) but the items are definitely not being marked as watched.

However, I'll start checking the Trakt website to confirm 100%.  Great suggestion...thanks!

**Comment by Omarscomin** [comment]
> Great question, @Omarscomin. 
> 
> I haven't checked the Trakt website but when I check the Trakt status in Kodi by long-pressing the item title and selecting "Trakt Manager", it's indicated as unwatched and I have to select "Mark watched in Trakt".  I've also allowed several hours for Umbrella to sync with Trakt (in addition to forcing Trakt syncs) but the items are definitely not being marked as watched.
> 
> 
> 
> However, I'll start checking the Trakt website to confirm 100%.  Great suggestion...thanks!

Cool, keep me posted if you don't mind! Sorry to barge in on your post, but it caught my eye since I'm experiencing something similar! The fact that the context menu/Trakt manager gives you the option to mark the content as watched leads me to believe that we are facing 2 different issues, but it's definitely worth looking into! Thank you! :)

**Comment by Madddcow** [comment]
Ok, I just watched S02E09 of The Lincoln Lawyer and pressed stop at the closing credits with just over 3:06 mins of credits remaining.,,,which is approx 98% watched.  My watched threshold is set to 85% and so the episode should most definitely have been marked as watched.  I just logged into my Trakt account online and the show has NOT been marked as watched.

So, there's definitely an issue with Umbrella and Trakt not marking media as being watched.

**Comment by adamosborne83** [comment]
You'll need to add a log

**Comment by umbrellaplug** [comment]
@adamosborne83 is correct, logs will be needed.

Just tried to duplicate this with the exact episode. It was marked as watched for me. Can you set your logging to debug > extra.info then try again and send a link for the log here? It's really a guess of what the issue could be without logs.

**Comment by Madddcow** [comment]
@umbrellaplug , here are both logs sent from the Umbrella Logging tool.  
[Umbrella Log.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12279880/Umbrella.Log.txt)
[Kodi log.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12279881/Kodi.log.txt)

Can you let me know if these are ok?

**Comment by umbrellaplug** [comment]
Yep that works. From looking at those logs you are having some connection issues with Trakt. If you look at your Umbrella.log you can actually see a lot of errors in syncing with Trakt. Are you using a VPN?

**Comment by Madddcow** [comment]
Ok, that's what I was thinking, too i.e. connection issues with Trakt.  No VPN being used and Fen has no issues with Trakt.  I'm really puzzled about this.

**Comment by Madddcow** [comment]
Something else I tried last week was to reset the Trakt settings in Umbrella to Defaults....just in case I'd inadvertently changed a parameter.  So everything is set to the default settings.

**Comment by Madddcow** [comment]
Ok, I'm genuinely sorry about that.  I only mentioned it to demonstrate that it doesn't appear that I'm experiencing overall issues with Trakt on my system.

**Comment by umbrellaplug** [comment]
Have you tried doing a force trakt to sync to local database from trakt management tools in options?

Are you using the trakt addon with Umbrella? There's no problem there, just make sure if you're using both trakt addon and umbrella only one of the two is set to scrobble. I have had reports in the past of weird issues with trakt when both were set to scrobble.

**Comment by Madddcow** [comment]
Yep, I've Forced a Trakt Sync to the local database and that came up fine.  I'm not using the Trakt addon and it's never been installed on my system.

**Comment by Madddcow** [comment]
I'm currently watched S01E04 of Special Ops: Lioness and will post back about what happens when it finishes, and will also check the log.

**Comment by umbrellaplug** [comment]
You're still getting a large amount of errors related to trakt. I'm reviewing your logs more now. I'll look through and see if I can determine what's causing your issue. A few things appear to be causing you errors outside of trakt that may actually be bleeding over into the trakt side. No excuses on my side, but I'm swapping computers today so it's taking me a bit longer to look through the code. Your log shows Linux, but you've listed a Shield as your device in the issue. What type of device is this? I'd like to try to duplicate the issues, but I need to match the device.

**Comment by Madddcow** [comment]
I’m definitely using an Nvidia Shield Pro

**Comment by umbrellaplug** [comment]
Yeah, my shield reports as Linux also. I'm seeing a lot of connection errors on your logs. There's also a lot of connection errors outside of Umbrella. I would check some of your settings on the shield. Turning off ipv6 might help. I understand you're having a different experience with Fen, but Peter was actually discussing this exact issue with me earlier and we were looking over the log and agreed a lot of the issue appears connection related.

**Comment by Madddcow** [comment]
Are the connection errors due to the Shield being "turned off" but Kodi still somehow running in the background?  On the Shield, I've disabled all power-saving and related features but I press the remote's power button to turn off the TV and Shield.  However, I can only assume the connection errors are primarily occurring when the Shield is technically turned Off.

Regardless, why would there be so many connection issues with Umbrella trying to connect to Trakt?

**Comment by Madddcow** [comment]
I've now turned off ipv6 and will see what happens.

**Comment by umbrellaplug** [comment]
> Regardless, why would there be so many connection issues with Umbrella trying to connect to Trakt?

I think it's likely Umbrella hitting Trakt more. I will keep testing, but my log from my shield doesn't show the connection errors like this.

**Comment by Madddcow** [comment]
Ok cool.  I've just cleared the Umbrella log for clarity, and tried skipping through a bunch of files; they were all marked as Watched in Trakt.  Then I turned off the Shield and I'll see what happens in the next hour or so.

**Comment by Madddcow** [comment]
@umbrellaplug, I've just watched a show from beginning to end and it wasn't marked as watched.  ipv6 is disabled and I had no problems earlier.  What I can't understand is that my system was obviously online when watching the show and there shouldn't have been any reason why a connection couldn't be made to Trakt.
[Umbrella Log 3.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12290228/Umbrella.Log.3.txt)

**Comment by Madddcow** [comment]
Another show watched, another log file.  Please note these posts aren't nags.....I'm simply trying to provide relevant info as something happens.
[Umbrella Log 4.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12291508/Umbrella.Log.4.txt)

**Comment by umbrellaplug** [comment]
> Another show watched, another log file. Please note these posts aren't nags.....I'm simply trying to provide relevant info as something happens.
> 
> What I find weird is that there's never a log entry for when the show is stopped and there's no communication with Trakt i.e. I stopped watching this particular show between approx 10:56pm to 10:58pm but the last log entry is at 10:48pm. Does the lack of an error at the time when I actually pressed Stop (at the end of the episode) mean anything? Shouldn't I be seeing some form of communication error at that time? [Umbrella Log 4.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12291508/Umbrella.Log.4.txt)

No worries, I don't take your comments as nagging. Does your kodi.log show any connection errors with any other addons?

I'm actually in the process of an update. I will add some logging into the mark watched call on the next test version. That will give us clear info on every time something is being marked as watched. I will log whatever show, episode, season, or movie for what it's marking so it will be easy to see. It may be a bit of time till you see this test version though because there are several things being added / worked on (playnext skin fixes, playnext skin added, playnext multi season, new color pallette, logging for playnext calls for another issue). I will reply here and let you know when it's pushed to the test repo so you can grab it for the extra logging.

**Comment by Madddcow** [comment]
Good question re.the Kodi log, @umbrellaplug. I don't know the significance of a bunch of things in the logs but here's the Kodi log. The only two video plugins I'm currently using are Umbrella and Fen.  Seren is installed but currently disabled.
[Kodi Log 2.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12291716/Kodi.Log.2.txt)

**Comment by umbrellaplug** [comment]
Okay, looking at your kodi.log it looks like connection errors started 8/7 23:09. Looks like a4ksubtitles got an exception hitting the opensubtitles.org api. Hopefully that helps. Can you try disabling a4ksubs and restarting kodi and see if that helps?

You can look at your kodi log you attached here. Search for `23:09:06.805 T:24544   error <general>: Exception in thread ` Somehow an exception happened in the requests module trying to get subtitles for "Sound of Freedom" using a4ksubs.
It looks like that exception also affected Fen and Umbrella as both addons use the requests module as a dependency.

**Comment by umbrellaplug** [comment]
Just pushed test version to test repo that has more logging for marking watched. Please load the test version from the test repo.

https://umbrellaplug.github.io/umbrellatest

version is 6.6.272

**Comment by Madddcow** [comment]
@umbrellaplug, I installed the test version earlier today and have been watching a number of different shows this evening.  Every single one has been marked as Watched in Trakt.

I haven't disabled a4ksubs yet because I wanted to see what would happen.

Here are my most current logs.
[Kodi Log 3.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12302276/Kodi.Log.3.txt)

[Umbrella Log 5.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12302275/Umbrella.Log.5.txt)

**Comment by umbrellaplug** [comment]
I'm still under the impression this issue is going to come down to connection issues. Let me know if you have anymore issues with it. I'll give it some time before marking this one completed.

**Comment by Madddcow** [comment]
Well, we've watched a few shows this evening and the first two were ok but the third didn't get marked as Watched. 
[Umbrella Log 6.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12311994/Umbrella.Log.6.txt)
[Kodi Log 4.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12312001/Kodi.Log.4.txt)

**Comment by umbrellaplug** [comment]
Once again...... you're having issues with a4ksubtitles. Log shows 08/09 23:31:58... exceptions in the requests module. It's exactly the same as my reply previously. Looks like it's trying to do something with the opensubtitles api and causing exceptions in the requests module that are bleeding over into every other addon that uses the requests module.
After that connection issues start happening in Umbrella with Trakt.

There are a large number of exceptions in the umbrella log for a darkColor comparison I have in the code, but that's related to the color changes I've been working on and should be resolved in the latest version posted on the test repo and it's unrelated to your issue.

**Comment by Madddcow** [comment]
Hey there @umbrellaplug 
There was a prompt to update to v6.6.279 the other day and so I updated, but it was really messed up i.e. there were no Watched checkmarks but those files were marked as Watched in Trakt.  There were also no year indicators at the left of each show title but instead, there were 4 dots. I downgraded to 6.6.27 and all is better again, but it'd be nice to get hold of 6.6.272 because that appears to have been the most reliable so far?

I disabled A4ksubtitles and have installed an addon for Podnapisi.net subtitles instead. However, I'm still experiencing shows not being watched as Watched.  Most current logs are below:
[Umbrella Log 7.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12331439/Umbrella.Log.7.txt)
[Kodi Log 5.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12331440/Kodi.Log.5.txt)

Thanks so much for helping out with this situation!  I really appreciate it!

**Comment by Omarscomin** [comment]
> Hey there @umbrellaplug 
> 
> There was a prompt to update to v6.6.279 the other day and so I updated, but it was really messed up i.e. there were no Watched checkmarks but those files were marked as Watched in Trakt.  There were also no year indicators at the left of each show title but instead, there were 4 dots. I downgraded to 6.6.27 and all is better again, but it'd be nice to get hold of 6.6.272 because that appears to have been the most reliable so far?
> 
> 
> 
> I disabled A4ksubtitles and have installed an addon for Podnapisi.net subtitles instead. However, I'm still experiencing shows not being watched as Watched.  Most current logs are below:
> 
> [Umbrella Log 7.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12331439/Umbrella.Log.7.txt)
> 
> [Kodi Log 5.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12331440/Kodi.Log.5.txt)
> 
> 
> 
> Thanks so much for helping out with this situation!  I really appreciate it!
> 
> 
> 
> 

This is kinda the name of the game when you are running the test version of Umbrella. The issues that you're describing have since been resolved in the more recent updates, but you might still consider switching back over to the official version of Umbrella.

**Comment by umbrellaplug** [comment]
This should be resolved in the latest version of the test build but I'm awaiting feedback.

**Comment by umbrellaplug** [comment]
This should be resolved in the latest update pushed today.

**Comment by Madddcow** [comment]
@umbrellaplug, is the new version 6.6.28? If so, I’m still experiencing the same bug i.e. I’ve just been testing on another platform I have in our bedroom (Amazon FireStick 4K) and shows still aren’t consistently being marked as watched with 6.6.28. 

Debug logging wasn’t activated but it is now.

**Comment by Omarscomin** [comment]
> @umbrellaplug, is the new version 6.6.28? If so, I’m still experiencing the same bug i.e. I’ve just been testing on another platform I have in our bedroom (Amazon FireStick 4K) and shows still aren’t consistently being marked as watched with 6.6.28. 
> 
> 
> 
> Debug logging wasn’t activated but it is now. 

Just out of curiosity, do you have you resume point source set to Trakt Scrobbles or local?

(Umbrella settings > Trakt > Resume Point source)

**Comment by umbrellaplug** [comment]
> @umbrellaplug, is the new version 6.6.28? If so, I’m still experiencing the same bug i.e. I’ve just been testing on another platform I have in our bedroom (Amazon FireStick 4K) and shows still aren’t consistently being marked as watched with 6.6.28.
> 
> Debug logging wasn’t activated but it is now.

Will need a log. Your issues is completely different than what was pushed in this update. There was an issue with the key for trakt not being available when trakt was making calls that was fixed. Your issue is clearly a connection issue from your logs. I know you don't want to hear that, but every log shows connection issues.

Last example I have before the new version here's an example from Kodi.log

```
023-08-13 20:59:33.433 T:5509  warning <general>: CFileCache::Process - <https://th4ykc.debrid.it/dl/2udfnca0b8e/masterchef.australia.s15e42.1080p.hdtv.h264-cbfm%5Beztv.re%5D.mkv> source read returned 0! Will retry
2023-08-13 20:59:35.434 T:5509  warning <general>: CCurlFile::CReadState::FillBuffer - (0x3129bfecf0) Reconnect, (re)try 1
```

then the Umbrella log starts with issues connecting to trakt and just throws non-stop errors.
```
[2023-08-13 20:37:39] [ plugin.video.umbrella: ERROR ]: From func name: /resources/lib/modules/trakt.py.getTrakt() Line # :41
                       msg : getTrakt Error:  -> ConnectionError -> ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by Madddcow** [comment]
That makes total sense to me because I can the correction errors…..but what I can’t understand is why no other addon has issues marking files as watched?

Regardless, can I just check if jumping through a file to the end is a reliable way to check if files get marked as Watched? I want to make sure that I’m testing in a way that’s conducive to obtaining accurate results.

**Comment by Madddcow** [comment]
> > @umbrellaplug, is the new version 6.6.28? If so, I’m still experiencing the same bug i.e. I’ve just been testing on another platform I have in our bedroom (Amazon FireStick 4K) and shows still aren’t consistently being marked as watched with 6.6.28.
> > Debug logging wasn’t activated but it is now.
> 
> Just out of curiosity, do you have you resume point source set to Trakt Scrobbles or local?
> 
> (Umbrella settings > Trakt > Resume Point source)

Local

**Comment by Omarscomin** [comment]
> > > @umbrellaplug, is the new version 6.6.28? If so, I’m still experiencing the same bug i.e. I’ve just been testing on another platform I have in our bedroom (Amazon FireStick 4K) and shows still aren’t consistently being marked as watched with 6.6.28.
> 
> > > Debug logging wasn’t activated but it is now.
> 
> > 
> 
> > Just out of curiosity, do you have you resume point source set to Trakt Scrobbles or local?
> 
> > 
> 
> > (Umbrella settings > Trakt > Resume Point source)
> 
> 
> 
> Local 

Change to Trakt Scrobbles! I think this will resolve your issue! You may need to force a Trakt sync and clear cache, after you change the setting.

**Comment by Madddcow** [comment]
I’ve changed to Trakt Scrobbles and forced a Trakt sync and cleared the cache on 3 different devices running Kodi: an Nvidia Shield Pro, an Amazon FireStick 4K and my MacBook Pro…..all exhibit the same behaviour i.e. Umbrella is not marking some shows as Watched in Trakt. However, Seren and Fen are 100% fine. 

I’ve disabled A4Ksubtitles and my internet is working fine on all 3 devices. I’ve also done some quick checks with Crew, The Oath and POV (on my MacBook) and they’re all fine. The problem has to be something with Umbrella when 3 different devices and multiple video addons don’t have the same issue.   

I’ll send logs through later but I can say that it’s the same connection errors. 

I’m also not sure why this topic isn’t tagged as Open because the problem is still very much present.

**Comment by Omarscomin** [comment]
> I’ve changed to Trakt Scrobbles and forced a Trakt sync and cleared the cache on 3 different devices running Kodi: an Nvidia Shield Pro, an Amazon FireStick 4K and my MacBook Pro…..all exhibit the same behaviour i.e. Umbrella is not marking some shows as Watched in Trakt. However, Seren and Fen are 100% fine. 
> 
> 
> 
> I’ve disabled A4Ksubtitles and my internet is working fine on all 3 devices. I’ve also done some quick checks with Crew, The Oath and POV (on my MacBook) and they’re all fine. The problem has to be something with Umbrella when 3 different devices and multiple video addons don’t have the same issue.   
> 
> 
> 
> I’ll send logs through later but I can say that it’s the same connection errors. 
> 
> 
> 
> I’m also not sure why this topic isn’t tagged as Open because the problem is still very much present. 

I'm sorry that didn't resolve your issue. I'm going to look over the rest of my settings later to see if there's anything else I can think to suggest to you. This seems to be happening to only you, from what I can tell, so it's possible that something just isn't configured quite right. 

I noticed that you mentioned a lot of add ons. Are you using the "Account Manager" add on too, by chance? I ask because that add on didn't play nicely with Umbrella for me, back when I tried it out.

**Comment by Madddcow** [comment]
@Omarscomin, don’t apologise! You and @umbrellaplug are being so helpful and I really, really appreciate it. 

On the Shield and FireStick, I normally only run 2 x video addons and for a while now, these have been Umbrella and Fen. I used to use Seren and Fen but prefer to get some variety in results, and so I’d disabled Seren in favour of Umbrella. I only enabled it again today to see if it has issues with Trakt…which it doesn’t. 

My MacBook has a bunch of video addons and I primarily use this platform for testing new addons….so there are quite a few installed at the moment. 

However, the Kodi installs on the Shield and FireStick are fairly minimal because their resources are significantly more limited compared to my Mac. 

No, I’m not using the Account Manager addon. Actually, hang on…is that called My Accounts (by Ezra Hubbard)? I’ve just checked my FireStick because that’s what I’m using right now and that addon is installed. Must be a remnant from when I had the Ezra video addon installed ages ago. 

Finally, would it matter that I use the Orion addon? I wouldn’t think so but you never know.

**Comment by 666jones** [comment]
There is alot to read so sorry if you have done this or it's already been mentioned but have you tried to de authorise trakts and the authorise it again? Might be worth a shot

**Comment by Omarscomin** [comment]
> @Omarscomin, don’t apologise! You and @umbrellaplug are being so helpful and I really, really appreciate it. 
> 
> 
> 
> On the Shield and FireStick, I normally only run 2 x video addons and for a while now, these have been Umbrella and Fen. I used to use Seren and Fen but prefer to get some variety in results, and so I’d disabled Seren in favour of Umbrella. I only enabled it again today to see if it has issues with Trakt…which it doesn’t. 
> 
> 
> 
> My MacBook has a bunch of video addons and I primarily use this platform for testing new addons….so there are quite a few installed at the moment. 
> 
> 
> 
> However, the Kodi installs on the Shield and FireStick are fairly minimal because their resources are significantly more limited compared to my Mac. 
> 
> 
> 
> No, I’m not using the Account Manager addon. Actually, hang on…is that called My Accounts (by Ezra Hubbard)? I’ve just checked my FireStick because that’s what I’m using right now and that addon is installed. Must be a remnant from when I had the Ezra video addon installed ages ago. 
> 
> 
> 
> Finally, would it matter that I use the Orion addon? I wouldn’t think so but you never know. 

Do you have Reddit, by chance? If so, message me at u/Omars-comin 

I want to discuss this further, but I don't want umbrellaplug to get blown up by all of the replies. I definitely want to know more about the "My Accounts" add on, and I'd like know exactly how you have all of your Umbrella settings configured.

**Comment by umbrellaplug** [comment]
My accounts is an old addon used by fen and venom to share account info for real debrid and trakt and all that. It shouldn't interfere with umbrella. I'm busy this morning, but I'll respond to this more when I can. I really wish you wouldn't mention like 5 other addons here. Im not going to lie. The typical response to that is "use those addons then". Especially POV, fuck that guy.

**Comment by Madddcow** [comment]
Righto. But perhaps think of it this way: I don’t WANT to use those other addons because I much prefer Umbrella….it kicks their ass! I wouldn’t be wasting your time (or mine) otherwise. That’s why I’d like to get my Umbrella issue resolved 👍🏻 and possibly learn some things along the way.

**Comment by Madddcow** [comment]
@Omarscomin 
Yup, I’m on Reddit. I’ll hit you up tomorrow my time (I’m in Australia)

I’m actually not well at the moment with the flu and am about to go to bed to try and shake it off.

**Comment by umbrellaplug** [comment]
@Madddcow Whenever you're feeling better, Can you please verify you have logging turned on for umbrella and set to debug with extra.info? There's logging in the code where if this is setup this way it will log out when it tries to mark as watched or scrobble. This will tell us a lot.

**Comment by Madddcow** [comment]
Hi @umbrellaplug 
Logging is enabled for Umbrella on all 3 devices; it was set to Normal but is now set to debug on all devices.  Given that I've been sick this week, I've been primarily using Kodi on the FireStick in my bedroom.  Attached are logs from the FireStick.

Interestingly, I haven't had as many issues over the past few days and am not sure why that is. The Kodi config on all 3 devices is basically identical - and the Umbrella config on all 3 should be identical (except for the Shield's max resolution being 4K, as opposed to 1080 on the FireStick and Mac).  

[Umbrella log 1 - FireStick.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12364935/Umbrella.log.1.-.FireStick.txt)
[Kodi log 1 - FireStick.txt](https://github.com/umbrellaplug/umbrellaplug.github.io/files/12364936/Kodi.log.1.-.FireStick.txt)

**Comment by Madddcow** [comment]
@umbrellaplug, just letting you know that Watched on Trakt is still intermittent on all three of my devices. Not sure why this issue has been marked as Closed when it's still ongoing.

**Comment by umbrellaplug** [comment]
> @umbrellaplug, just letting you know that Watched on Trakt is still intermittent on all three of my devices. Not sure why this issue has been marked as Closed when it's still ongoing.

I marked this issue as closed because it appears to be related to your connection. I believe I've told you this at least 3 other times in the comments here. The issue with items not being marked as watched in trakt previously had to do with a API key. Your issue is related to your connection (as I've mentioned a few times now). Your comment comes across real shitty with "not sure why this issue has been marked as closed when it's still ongoing"

I tried to be nice and helpful here but I guess you need me to tell you one more time.... you're having connection issues. here's the proof from your log. (once again)

```
[2023-08-15 13:55:06] [ plugin.video.umbrella: ERROR ]: From func name: /resources/lib/modules/trakt.py.getTrakt() Line # :41
                       msg : getTrakt Error:  -> ConnectionError -> ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2023-08-15 13:55:06] [ plugin.video.umbrella: ERROR ]: From func name: /resources/lib/modules/playcount.py.markEpisodeDuringPlayback() Line # :180
```

please stop wasting my time.

**Comment by Madddcow** [comment]
What I don't understand is why Umbrella is experiencing connection issues but no other addon is experencing this? It makes no sense at all, especially given that it's occurring on three different devices and only with Umbrella.

**Comment by Omarscomin** [comment]
> Not sure why this issue has been marked as Closed when it's still ongoing.

Yikes. Sounds like you're reaching out to a major corporation/paid streaming service. Why do you feel like you can demand assistance from one person who is doing this for free, as a hobby? It's really weird. 

It seems like you're the only one who is having this issue, and the fact that you didn't have your resume points set to "Trakt Scrobbles" until just a few days ago leads me to believe that it's very possible that you misconfigured something along the way. 

Perhaps you should start over and do a fresh install of Kodi. As I already said before, my inbox is open, and we could go over all of our Umbrella settings to see if they match up. It might benefit you to compare your settings with someone who is having zero issues with Trakt functions. 

Another option is to install the universal Trakt add on, and let _that_ add on do the scrobbling for _all_ of your video add ons (you'd need to disable Trakt scrobbling within all of your videos add ons if you went this route)

Try completely rebooting your router as well. You'd be surprised how often that resolves any weird network issues that you might be experiencing (even if it's only related to one app/add on/website/etc).
