### ISSUE TITLE
Information screen settings not working

### ISSUE THREAD

**Issue by Omarscomin** [umbrellaplug/umbrellaplug.github.io#310]
### Bug

Information screens do not open for movies or TV shows upon select, despite both settings being enabled within Umbrella. Selecting a movie immediately initiates source scrapers, and selecting a TV show immediately displays the different seasons/episodes to choose from. 

### Expected Result

The information screen should appear when selecting a movie or tv show

### Steps To Reproduce

1. Enable “Show information screen for TV show on select” and “Show information screen for Movie on select” in Umbrella’s settings 
2. Select any movie or TV show

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi version: 20.2
Umbrella version: 6.6.27
Device: 2019 Nvidia Shield Pro
Skin: Arctic Horizon 2
Log: https://paste.kodi.tv/hisaraxepu

I apologize if I forgot anything. Please let me know if you need anything else. Thank you for your help!

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by 666jones** [comment]
I noticed this to. However I ended up adding a keymap XML file to make long press open information that way I can still use one click to play stuff fast and a long click if I want to see information. Ino this isn't relevant but might be a option for you

**Comment by umbrellaplug** [comment]
Ehhhh good reminder. Those don't work. I worked on setting that ability up a while back and it was "janky". That's something that needs to be added down the road. A screen for extras like Fen is planned, but it's not high on the list right now. I'll get those removed. good catch.

**Comment by Omarscomin** [comment]
> Ehhhh good reminder. Those don't work. I worked on setting that ability up a while back and it was "janky". That's something that needs to be added down the road. A screen for extras like Fen is planned, but it's not high on the list right now. I'll get those removed. good catch.

Cool. Happy to know that something similar is in the works for the future :) I currently have "show information upon select" enabled in Kodi's settings for videos, which will do me just fine until then. Thanks for the reply!

**Comment by Omarscomin** [comment]
> I noticed this to. However I ended up adding a keymap XML file to make long press open information that way I can still use one click to play stuff fast and a long click if I want to see information. Ino this isn't relevant but might be a option for you 

I loathe long presses😬🤣but, I have "show information upon select" enabled in Kodi's settings for videos, which has been a fine work around for me personally. That setting makes certain Umbrella functions a little wonky though, which is why I would've liked to configure that feature through Umbrella itself. Happy to know that we can look forward to it in the future!

**Comment by umbrellaplug** [comment]
I'm utterly shocked my reddit troll @adamosborne83 didn't crawl out from under his rock to comment on this request. This has been one of his two biggest request since I started working on Umbrella.

**Comment by Omarscomin** [comment]
> I'm utterly shocked my reddit troll @adamosborne83 didn't crawl out from under his rock to comment on this request. This has been one of his two biggest request since I started working on Umbrella.

Lmao, I can tell that he keeps you on your toes ;) not gonna lie, that feature will be huge for me too. And Umbrella will be damn near perfect after that!!!🤌

A shortcuts folder would be cool too😇I'm currently using Super Favourites, but it's soooo damn slow

**Comment by adamosborne83** [comment]
> I'm utterly shocked my reddit troll @adamosborne83 didn't crawl out from under his rock to comment on this request. This has been one of his two biggest request since I started working on Umbrella.

Well, I'm currently in Spain with family, and enjoying myself, although Mr Umbrella knows he's a coño, yes my friend, but still a coño.

**Comment by adamosborne83** [comment]
> > I'm utterly shocked my reddit troll @adamosborne83 didn't crawl out from under his rock to comment on this request. This has been one of his two biggest request since I started working on Umbrella.
> 
> Lmao, I can tell that he keeps you on your toes ;) not gonna lie, that feature will be huge for me too. And Umbrella will be damn near perfect after that!!!🤌
> 
> A shortcuts folder would be cool too😇I'm currently using Super Favourites, but it's soooo damn slow

Trust me my friend, He has ALOT more work to do to make it perfect x

**Comment by umbrellaplug** [comment]
> > I'm utterly shocked my reddit troll @adamosborne83 didn't crawl out from under his rock to comment on this request. This has been one of his two biggest request since I started working on Umbrella.
> 
> Lmao, I can tell that he keeps you on your toes ;) not gonna lie, that feature will be huge for me too. And Umbrella will be damn near perfect after that!!!🤌
> 
> A shortcuts folder would be cool too😇I'm currently using Super Favourites, but it's soooo damn slow

He just put a request in the other day for the "Favorites" feature from Fen. I haven't turned it down yet, but I haven't agreed. He actually joked he would just ask @Omarscomin to request it because I'm "nicer to you". For some reason he feels he doesn't need to open github issues for requests. which is brave with my memory.


The other two he nags the shit out of me about are:

 "Scrape, Resolve, Play" all in one screen.
 "Umbrella Extras screen so he can have information for movies and play for tv shows"

**Comment by adamosborne83** [comment]
> > > I'm utterly shocked my reddit troll @adamosborne83 didn't crawl out from under his rock to comment on this request. This has been one of his two biggest request since I started working on Umbrella.
> > 
> > Lmao, I can tell that he keeps you on your toes ;) not gonna lie, that feature will be huge for me too. And Umbrella will be damn near perfect after that!!!🤌
> > 
> > A shortcuts folder would be cool too😇I'm currently using Super Favourites, but it's soooo damn slow
> 
> He just put a request in the other day for the "Favorites" feature from Fen. I haven't turned it down yet, but I haven't agreed. He actually joked he would just ask @Omarscomin to request it because I'm "nicer to you". For some reason he feels he doesn't need to open github issues for requests. which is brave with my memory.
> 
> 
> The other two he nags the shit out of me about are:
> 
>  "Scrape, Resolve, Play" all in one screen.
>  "Umbrella Extras screen so he can have information for movies and play for tv shows"

Because we're 'freinds' although you're hard work.

**Comment by Omarscomin** [comment]
> > > I'm utterly shocked my reddit troll @adamosborne83 didn't crawl out from under his rock to comment on this request. This has been one of his two biggest request since I started working on Umbrella.
> 
> > 
> 
> > Lmao, I can tell that he keeps you on your toes ;) not gonna lie, that feature will be huge for me too. And Umbrella will be damn near perfect after that!!!🤌
> 
> > 
> 
> > A shortcuts folder would be cool too😇I'm currently using Super Favourites, but it's soooo damn slow
> 
> 
> 
> He just put a request in the other day for the "Favorites" feature from Fen. I haven't turned it down yet, but I haven't agreed. He actually joked he would just ask @Omarscomin to request it because I'm "nicer to you". For some reason he feels he doesn't need to open github issues for requests. which is brave with my memory.
> 
> 
> 
> 
> 
> The other two he nags the shit out of me about are:
> 
> 
> 
>  "Scrape, Resolve, Play" all in one screen.
> 
>  "Umbrella Extras screen so he can have information for movies and play for tv shows"

LOL! Y'all are killin' me over here😂

Ahh yes, the "Scrape, Resolve, Play" all in one screen. I remember this request. I still don't get it though. It hurts my brain trying to figure out what it means😵‍💫

How ironic that the Super Favourites add on updated today, and it's been broken for me ever since. I may or may not start nagging you for a shortcuts folder now😈

**Comment by Omarscomin** [comment]
> > > I'm utterly shocked my reddit troll @adamosborne83 didn't crawl out from under his rock to comment on this request. This has been one of his two biggest request since I started working on Umbrella.
> > 
> > Lmao, I can tell that he keeps you on your toes ;) not gonna lie, that feature will be huge for me too. And Umbrella will be damn near perfect after that!!!🤌
> > 
> > A shortcuts folder would be cool too😇I'm currently using Super Favourites, but it's soooo damn slow
> 
> Trust me my friend, He has ALOT more work to do to make it perfect x

_This_ is why Umbrella Dev is so much nicer to me than he is to you😈🤣
