### ISSUE TITLE
[FEATURE] info / extras (umbrextras)  page for TV shows and movies 

### ISSUE THREAD

**Issue by SJ1O** [umbrellaplug/umbrellaplug.github.io#313]
### Feature

A info / extras page would be awesome.

You could have afew buttons for example Play / Play next, play random, seasons, rescrape, add to watch list ect 

Then for information you could display nominations / wins and ratings. Plot, reviews, cast, similar shows or movies, parental guide ect.

The main thing being a play next button. Rather then using trakts next up you could just go to in progress shows and the information page on a show could have a play next button  This would be so awesome and convenient. I would love to see this in umbrella one day.  Umbrella is the most feature rich and fully functional add on that I know of would make sense to add this awesome feature to it's list :)

**Comment by umbrellaplug** [comment]
Planned for the future but this is a huge task. I'm going to close this issue for now but it's on the list of features to add in the future.

**Comment by umbrellaplug** [comment]
Decided not to do this.
