### ISSUE TITLE
[BUG] Not playing nice with TheMovieDb Helper

### ISSUE THREAD

**Issue by cpease61** [umbrellaplug/umbrellaplug.github.io#314]
### Bug

When attempting to play through helper will not resolve link.

https://paste.kodi.tv/raveboxavi

Seems to work fine when accessing directly through Umbrella

### Expected Result

It should play selection, Did before the latest update.

### Steps To Reproduce

Search through TMDB Helper

Attempt to play through the same

Playback error

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 19.4

Nvidia Shield

OS: Android 11.0.0 API Level 30

The Nvidia Shield also appears to say it is playing selection and it is not coming through

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Your log doesn't show anything. I tried to duplicate this here and I was able to play episodes from a widget and from within a season folder using tmdbhelper with autoplay and source select. Can you please turn on debug logging in the addon, try again, and upload new logs?

**Comment by cpease61** [comment]
try this

https://paste.kodi.tv/jevibolalo

Yours

**Comment by 666jones** [comment]
I was unable to duplicate this issue.
Using kodi 21 omega 
Tmdb helper v5.1.33-nexus
Tmdb helper umbrella player setting: is_resolvable: true 

Is your player configured to be resolvable within tmdb?

**Comment by umbrellaplug** [comment]
What version of tmdbhelper are you running?

I'm willing to try to help, but I think this is likely related to tmdbhelper settings.

**Comment by umbrellaplug** [comment]
Closing. Lack of response.

**Comment by cpease61** [comment]
I sent a reply by email apparently that is not the way.

Helper version 5.0.55
