### ISSUE TITLE
[FEATURE] Add debrid-link.com

### ISSUE THREAD

**Issue by baloo24** [umbrellaplug/umbrellaplug.github.io#317]
### Feature

Hey, could you please try adding debrid-link ? https://debrid-link.com/api_doc/v2/introduction

**Comment by umbrellaplug** [comment]
Pretty broad request here. What are you looking for? This is not a service I'm familiar with but they do not seem to offer the same things as existing providers.

**Comment by baloo24** [comment]
It is a debrid service like real-debrid for torrent caching. I'm using them with an addon that uses ResolverURL but you don't seem to support either ResolverURL or debrid-link

**Comment by umbrellaplug** [comment]
I'm not currently interested in adding anymore debrid providers. Maybe down the road, but not something I want to work on right now.
