### ISSUE TITLE
[FEATURE] Favorites TV/ Movies

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#318]
### Feature

You know what I want.

Getting this in before you close issues AGAIN

**Comment by adamosborne83** [comment]
> I have no idea what you want, but I'm gonna assume and make what I want.

That's a shocker...... I pay for a service, I expect professionalism.

**Comment by umbrellaplug** [comment]
Changed title. Re-opened to use for "umbrella favourites"
