### ISSUE TITLE
[BUG] After today's update: No stream available

### ISSUE THREAD

**Issue by ksdomino** [umbrellaplug/umbrellaplug.github.io#320]
### Bug

After the 24/08/2023 update, it ays no stream available for everything.
It still shows all the movies in lists eg : discover movies, in theatres (IMDB), but no longer plays anything (no stream available).
I can still play (very limited) content from my provider (All-debrid) by going into premium services, all debrid, all-debrid: cloud storage so I know my connection is fine. I'll atempt to rollback to the previous version and see if that works (if that's even possible).

### Expected Result

just expect it to work as it did an hour ago before the update, eg play content.

### Steps To Reproduce

1. go to discover movies
2. click on in theatres (IMDB)
3. click any movie
4. it says no stream available.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

probably not relevant as it literally just broke just after the umbrella update but kodi 20.2.0, windows 10, umbrella latest as of todays update (24.02.2023)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by adamosborne83** [comment]
Ladies and Gents, as I am sure you are well aware that Umbrella and FEN now require a external scraper package for it to work. 
This is currently CoCoScraper, which the repo can be found here

https://cocojoe2411.github.io/

I recommend installing this first, as that way any future CoCo updates will automatically be uploaded to your system. MAKE SURE TO INSTALL COCO SCRAPERS AGAIN, SO IT WILL RECEIVE REPO UPDATES. Do not worry you will not lose any settings in CoCo 

Now I am assuming you have done this, and have updated to the new version of Umbrella or FEN or BOTH. So Greedy. 


UMBRELLA SET UP

These are the steps required to allow Umbrella to now work with CoCo.

https://imgur.com/a/6LyyO3U


Fine, here is a Video too https://imgur.com/a/oiLDokr

This is a really easy process to which the above should show you step by step. Which consists of 6 photos.


Once completed you will see a little pop up "CoCo Scrapers External Module set succesfully"

FEN SET UP

Again, see the link below with a picture Step by Step guide with 5 pictures to follow

https://imgur.com/a/slPOHY9

Then you'll see "SUCCESS"

Simple as that.

Any issues then just say and I am sure people will be able to help.

PS... for those of you that know me and my videos, you would have noticed I no longer include my hypnotising wallpaper. There are a couple of people to blame for this huge loss. Although I will not mention names.

**Comment by umbrellaplug** [comment]
https://github.com/umbrellaplug/umbrellaplug.github.io#faq

**Comment by 666jones** [comment]
> Ladies and Gents, as I am sure you are well aware that Umbrella and FEN now require a external scraper package for it to work. This is currently CoCoScraper, which the repo can be found here
> 
> https://cocojoe2411.github.io/
> 
> I recommend installing this first, as that way any future CoCo updates will automatically be uploaded to your system. MAKE SURE TO INSTALL COCO SCRAPERS AGAIN, SO IT WILL RECEIVE REPO UPDATES. Do not worry you will not lose any settings in CoCo
> 
> Now I am assuming you have done this, and have updated to the new version of Umbrella or FEN or BOTH. So Greedy.
> 
> UMBRELLA SET UP
> 
> These are the steps required to allow Umbrella to now work with CoCo.
> 
> https://imgur.com/a/6LyyO3U
> 
> Fine, here is a Video too https://imgur.com/a/oiLDokr
> 
> This is a really easy process to which the above should show you step by step. Which consists of 6 photos.
> 
> Once completed you will see a little pop up "CoCo Scrapers External Module set succesfully"
> 
> FEN SET UP
> 
> Again, see the link below with a picture Step by Step guide with 5 pictures to follow
> 
> https://imgur.com/a/slPOHY9
> 
> Then you'll see "SUCCESS"
> 
> Simple as that.
> 
> Any issues then just say and I am sure people will be able to help.
> 
> PS... for those of you that know me and my videos, you would have noticed I no longer include my hypnotising wallpaper. There are a couple of people to blame for this huge loss. Although I will not mention names.

I wanted to see the hypnotising wallpaper. I do like your current wallpaper tho very lovely

**Comment by tarres** [comment]
So, Seren it is?

**Comment by 666jones** [comment]
> So, Seren it is?

It still uses same scraper just follow the steps. You need to click about 5 buttons then your done.

**Comment by 666jones** [comment]
> So, Seren it is?

Btw real debrid down for maintenance anyhow

**Comment by umbrellaplug** [comment]
> So, Seren it is?

**Please** help me to understand what this comment means? Are you asking if you should use Seren instead now?

**Comment by Omarscomin** [comment]
> So, Seren it is? 

Did you miss the fact that someone was nice enough to send you a link to a set up guide?🤦🏻‍♀️

**Comment by ksdomino** [comment]
Thanka ao much guys, op here. Scraper fixed it (thanks so much for links) and Plugin works the same as before.
Thanks again all.
