### ISSUE TITLE
[FEATURE] Progress Episodes play behaviour 

### ISSUE THREAD

**Issue by TheBigBooper** [umbrellaplug/umbrellaplug.github.io#321]
### Feature

An option for play behaviour for progress episodes to “play from here”, to simply play the next up episode, as opposed to drilling into a new directory, listing all unwatched episodes. Currently only possible with the context menu item “play from here”

**Comment by umbrellaplug** [comment]
Sorry but this request is unclear. You want play from here added but you state it is already an option?

What steps do I take to duplicate this?

What are you thinking should happen instead when I follow the provided steps?

Are you sure you doing just need to turn in direct progress scraping in settings to accomplish this?

**Comment by TheBigBooper** [comment]
Sorry for being unclear! What I was hoping for was for an option to have the context menu item ‘play from here’, to be a default play option for progress episodes. Currently, the default play option for progress episodes, when selecting the episode in the progress episodes list, results in entering a new list showing all unplayed episodes for the show. I was hoping there was a way to skip this step and just play the episode, without the extra step using the context menu.

**Comment by umbrellaplug** [comment]
Is this from a widget?

**Comment by TheBigBooper** [comment]
It’s in the ‘my TV shows’ section in the main add on. In my case it is pointing to trakt. Same result, both using it as a widget, and accessing it directly through umbrella add on. 

I’ve also tried turning on direct progress scrapping, however there isn’t any change in behaviour.

**Comment by TheBigBooper** [comment]
Ok, I solved it. The setting right next to direct progress scraping, 'browse progress-load all remaining episides'. It's on by default, turning it off solves this. Thanks for pointing me in the right direction for this setting!
