### ISSUE TITLE
[Question] YouTube menu API keys

### ISSUE THREAD

**Issue by 666jones** [umbrellaplug/umbrellaplug.github.io#323]
### Feature

Is there any workaround for the YouTube menu needing API keys. I installed the YouTube addon from umbrella so I get trailers ect they all work fine. However I just tried the YouTube menu part within umbrella and it says I need API keys. I did attempt to create some API keys but give up after a while. So my question is is this only going to work if I create YouTube API keys :)

**Comment by adamosborne83** [comment]
Correct, the api is required. Google it and follow the steps slowly.

**Comment by 666jones** [comment]
> Correct, the api is required. Google it and follow the steps slowly.

Thanks buddy I'll give it another go 😅

**Comment by Omarscomin** [comment]
Here are some resources from my personal stash of Kodi notes that might help you out!

•YouTube API keys video tutorial: https://odysee.com/@kodifiend:4/Youtube-api-and-autoplay-nextup:5 


•More info about YouTube API keys: https://www.reddit.com/r/Addons4Kodi/comments/10fziu4/installing_the_youtube_addon_plus_api_enabling_4k/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

**Comment by 666jones** [comment]
> Here are some resources from my personal stash of Kodi notes that might help you out!
> 
> •YouTube API keys video tutorial: https://odysee.com/@kodifiend:4/Youtube-api-and-autoplay-nextup:5
> 
> •More info about YouTube API keys: https://www.reddit.com/r/Addons4Kodi/comments/10fziu4/installing_the_youtube_addon_plus_api_enabling_4k/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

Ahh very lovely and thanks very much I'm going to attempt this again, I'll follow the links you provided. Did you manage to get your API keys to work?  I did create some API keys a while back but they never worked. Started playing about with it again today but then thought I might as well get some advice before I waste time trying again.

**Comment by Omarscomin** [comment]
> > Here are some resources from my personal stash of Kodi notes that might help you out!
> 
> > 
> 
> > •YouTube API keys video tutorial: https://odysee.com/@kodifiend:4/Youtube-api-and-autoplay-nextup:5
> 
> > 
> 
> > •More info about YouTube API keys: https://www.reddit.com/r/Addons4Kodi/comments/10fziu4/installing_the_youtube_addon_plus_api_enabling_4k/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1
> 
> 
> 
> Ahh very lovely and thanks very much I'm going to attempt this again, I'll follow the links you provided. Did you manage to get your API keys to work?  I did create some API keys a while back but they never worked. Started playing about with it again today but then thought I might as well get some advice before I waste time trying again.

Yep, I followed the instructions in the video that I sent you above, and I've never had any issues with the version of YouTube that's available in Umbrella's repo!

**Comment by 666jones** [comment]
> > > Here are some resources from my personal stash of Kodi notes that might help you out!
> > 
> > 
> > > 
> > 
> > 
> > > •YouTube API keys video tutorial: https://odysee.com/@kodifiend:4/Youtube-api-and-autoplay-nextup:5
> > 
> > 
> > > 
> > 
> > 
> > > •More info about YouTube API keys: https://www.reddit.com/r/Addons4Kodi/comments/10fziu4/installing_the_youtube_addon_plus_api_enabling_4k/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1
> > 
> > 
> > Ahh very lovely and thanks very much I'm going to attempt this again, I'll follow the links you provided. Did you manage to get your API keys to work?  I did create some API keys a while back but they never worked. Started playing about with it again today but then thought I might as well get some advice before I waste time trying again.
> 
> Yep, I followed the instructions in the video that I sent you above, and I've never had any issues with the version of YouTube that's available in Umbrella's repo!

Got it working took afew attempts kept entering wrong client secret. Followed that video he made it really simple. Thanks for sharing that information mate
