### ISSUE TITLE
[FEATURE] Section Labels

### ISSUE THREAD

**Issue by Omarscomin** [umbrellaplug/umbrellaplug.github.io#324]
### Feature

Hey! I hope you’ve had a great weekend!

I was just wondering if it might be possible for you to tweak Umbrella’s section labels, so that they reflect the category/genre of the content being displayed. It would look a little cleaner, when paired with a skin (see attached photos, since I’m having a hell of a time putting this into words😵‍💫)
![IMG_4937](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/129215684/a4558cba-69c8-49fc-8634-07a2a4109f38)
![IMG_4938](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/129215684/a6fa91af-952e-43b7-90bb-37083f0f1117)

Thank you for considering this, UD!

**Comment by umbrellaplug** [comment]
This is in the latest test version. In normal umbrella fashion, it's a setting. General section.

**Comment by Omarscomin** [comment]
https://github.com/umbrellaplug/umbrellaplug.github.io/assets/129215684/690337d7-77e8-4b88-b2a6-eb22ae75f7a7

**Comment by 666jones** [comment]
Ahh this seems like a good feature very lovely 🤗

**Comment by umbrellaplug** [comment]
> trim.A9B48044-59E3-4F50-9F25-E090C04C9CAC.MOV

What are you showing here?

**Comment by adamosborne83** [comment]
> > > trim.A9B48044-59E3-4F50-9F25-E090C04C9CAC.MOV
> > 
> > 
> > 
> > What are you showing here?
> 
> My personal Trakt lists for TV shows are being displayed, but nothing happens when I try to open them. It's not happening for my movie lists though. 

Are the lists showing in trakt? Silly question I know.

**Comment by Omarscomin** [comment]
> > > > trim.A9B48044-59E3-4F50-9F25-E090C04C9CAC.MOV
> > > 
> > > 
> > > 
> > > What are you showing here?
> > 
> > My personal Trakt lists for TV shows are being displayed, but nothing happens when I try to open them. It's not happening for my movie lists though. 
> 
> Are the lists showing in trakt? Silly question I know. 

Yes, and everything shows up as it should when I switch over to the official version of Umbrella.

**Comment by umbrellaplug** [comment]
I was able to see the issue here. Give me a little bit to look at it. Should only be those lists.. nice testing. Next time add a little context to the video. :)

**Comment by Omarscomin** [comment]
> I was able to see the issue here. Give me a little bit to look at it. Should only be those lists.. nice testing. Next time add a little context to the video. :)

My apologies. The text context was in our Reddit chat, but I wasn't able to post the video on there😬so, half of the info was on Reddit, and half of it was on here🫠lol. Won't happen again!😇

**Comment by umbrellaplug** [comment]
New test version should have this fixed.

**Comment by Omarscomin** [comment]
Personal Trakt lists, box sets/collections, IMDB genres, and IMDB people/actors are still displaying "Umbrella" as the section label. 

"Discover" categories (Popular, Most Voted, Trending, etc.) have the appropriate section label😊

Personal Trakt list:
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/129215684/372e8247-d65c-4c95-85bd-e2982eba3b7f)

IMDB Genre: 
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/129215684/6bdfebba-e671-4ac2-a2f2-839f32e15946)

Box set/collection:
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/129215684/264b50d8-9858-456d-80d1-151937b2c58a)

"Discover Movies" category:
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/129215684/b0958b4a-376f-4be4-af3e-13f28ec3b819)

**Comment by umbrellaplug** [comment]
Updated to add all that bullshit. let me know if anything else is missing. I added collection titles, I'm sure it won't be enough. 😊
