### ISSUE TITLE
Unwatched shows marked as watched. 

### ISSUE THREAD

**Issue by leemacca13** [umbrellaplug/umbrellaplug.github.io#330]
### Bug

So I’m currently using umbrella for a widget using AH2 that shows a list I have created for new UK tv shows and when I click on certain shows a green tick appears as if I have already watched them. If I try and watch one of those shows it plays fine but will not track using trakt and I manually have to go into the trakt website and mark it as watched. Even then when the show is moved to the progress section it still won’t track if I try and play the next episode. 

### Expected Result

When I’ve watched an episode the episode should be tracked as being watched via the trakt website. 

### Steps To Reproduce

1. Click on a show to watch  I have noticed the issue on the following shows so far. 

> Union with David Olusoga
> Badgers: their secret world
> Paranormal: the girl, the ghost and the gravestone. 
> Laura Whitmore investigates. 

2. Watch an episode of the show 
3. Once the show has finished it won’t show as tracked via the trakt website. 

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi version 20.2 on an Amazon fire cube. The list I’m using to find the shows is created via MDBlist and log is attached below. 

https://paste.kodi.tv/alufadopox

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Please make sure you have trakt scrobble enabled in your settings in Umbrella > Tools > Settings > Trakt

**Comment by leemacca13** [comment]
> Please make sure you have trakt scrobble enabled in your settings in Umbrella > Tools > Settings > Trakt

I've just double checked and trakt scrobble is enabled in settings.

**Comment by umbrellaplug** [comment]
I'm not seeing in your log where it's trying to mark an item as watched. I see the sync start with trakt but never see the usual messages for syncing playback and resume times. Can you try force trakt to sync with local database from trakt management in tools section of umbrella then watch an episode once that's complete and see of it is marked as watched and resend a new log?

**Comment by leemacca13** [comment]
> I'm not seeing in your log where it's trying to mark an item as watched. I see the sync start with trakt but never see the usual messages for syncing playback and resume times. Can you try force trakt to sync with local database from trakt management in tools section of umbrella then watch an episode once that's complete and see of it is marked as watched and resend a new log?

I have forced a trakt sync and tried watching an episode but the same thing is happening. I have attached a new log as well. It just seems to be certain shows that it's happening too, if I watch some shows it tracks fine which is what I find very confusing. 

https://paste.kodi.tv/ufoxeruvab

**Comment by umbrellaplug** [comment]
Dug into this a little more. That particular show. "Levison Wood: Walking with.." was missing some metadata on the tmdb website. Without getting into it too much, we use the data from tmdb for shows and movies, but we need the tvdb or imdb id for marking epsiodes as watched in trakt. That show was missing imdb and tvdb id. I was unable to find it on imdb, but I did find it on tvdb so I have updated the tmdb listing with the correct id. That should cause that particular show to start working as expected once tmdb updates the info. I'd try clearing my metadata tomorrow in the addon then watching an episode and seeing if it marks correctly. It seems you may be watching some shows with metadata not fully filled out on tmdb. Unfortunately, that's outside my control. We need those IDs to mark episodes. 

I'm going to see if I can find a reason I'm not marking episodes with tmdb id instead of tvdb or imdb only. As long as something doesn't break from that change I will go ahead and make a change to fallback to trying to mark using tmdb id if tvdb and imdb are missing.

**Comment by leemacca13** [comment]
> Dug into this a little more. That particular show. "Levison Wood: Walking with.." was missing some metadata on the tmdb website. Without getting into it too much, we use the data from tmdb for shows and movies, but we need the tvdb or imdb id for marking epsiodes as watched in trakt. That show was missing imdb and tvdb id. I was unable to find it on imdb, but I did find it on tvdb so I have updated the tmdb listing with the correct id. That should cause that particular show to start working as expected once tmdb updates the info. I'd try clearing my metadata tomorrow in the addon then watching an episode and seeing if it marks correctly. It seems you may be watching some shows with metadata not fully filled out on tmdb. Unfortunately, that's outside my control. We need those IDs to mark episodes. 
> 
> 
> 
> I'm going to see if I can find a reason I'm not marking episodes with tmdb id instead of tvdb or imdb only. As long as something doesn't break from that change I will go ahead and make a change to fallback to trying to mark using tmdb id if tvdb and imdb are missing.
> 
> 
> 
> 

Thank you for taking the time to look into it for me, I will definitely give that a try thank you. Do you think it would be worth me checking if I can find the other shows on tvdb and IMDb to add the info? That would be great if you could make that change. Thanks again for taking the time to look into it and consider working on a change. Really appreciate it.

**Comment by umbrellaplug** [comment]
No problem. It's always worth it to update the meta if it's missing for any show you watch. TMDB is all community driven so some shows only get updated when users update them. If you can tell me what other shows you're having issues with I can look and see if IDs are missing.

**Comment by leemacca13** [comment]
> No problem. It's always worth it to update the meta if it's missing for any show you watch. TMDB is all community driven so some shows only get updated when users update them. If you can tell me what other shows you're having issues with I can look and see if IDs are missing.

Thank you these are the one I've noticed so far I've been having issues with. 

Union with David Olusoga. 
Badgers: their secret world. 
Paranormal: the girl, the ghost and the gravestone. 
Laura Whitmore investigates.

**Comment by umbrellaplug** [comment]
It's as I thought. They are missing IDs. You can update these by going to www.themoviedb.org and updating the info for each show. I went ahead and found Union and Badgers for you, but I really don't have the time to update every series. It would be much better if you could update the ones you are having issues with.

You will need to register for a free account on tmdb then search your show. Look for external ids and make sure it has an imdb or tvdb id. If it's blank search the show on imdb.com or thetvdb.com and fill in the correct id for the show on tmdb.

![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/107957815/ad8e4f97-295c-49b6-8dce-7a4a8e70be09)

![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/107957815/c6806293-a519-48db-b711-50562994d11e)

**Comment by umbrellaplug** [comment]
going to go ahead and close this issue as "missing metadata". Thanks! Good luck!

**Comment by leemacca13** [comment]
That's great thank you, no that's totally fine I wouldn't expect you to go through each one for me. Really appreciate your time and thanks again. I will give that a try over the weekend.
