### ISSUE TITLE
Add search for MDB lists

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#331]
### Feature

Is there anyway you can add search for MDB list? If you can’t it’s no big deal but it would be nice. Thank you.

**Comment by umbrellaplug** [comment]
It looks like mdblists does offer a list search function on their api. I will look into adding this.

**Comment by Arthur1967** [comment]
OK thank you I know the movie database helper has it so I can just use that. Thanks.
