### ISSUE TITLE
[FEATURE] Stay on one screen when selecting to play

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#332]
### Feature

Currently (with my settings) if I select to play, e.g. an episode from Progress Episodes it will show a Preparing Sources screen, jump back to Progress Episodes then display a Total Sources screen, selecting shows a full screen with plot before jumping back to Progress Episodes again and then waiting before actually playing

Think it would be a better experience if after selecting an episode to play it stays on one screen and does not jump back before playing

Settings: Scraper Preparation->Source Select, Scraper Progress Dialog->Progress Dialog->Full-Screen, Use artwork for background

Thanks

**Comment by adamosborne83** [comment]
Wow, that sounds like a great idea, hopefully UD can implement this.

**Comment by umbrellaplug** [comment]
This requires a lot of work for a visual preference. I am not interested in doing this. There's no functionality gained or advantage to doing this.
