### ISSUE TITLE
Discover new tv show (IMBD) section  blank

### ISSUE THREAD

**Issue by pjcanales** [umbrellaplug/umbrellaplug.github.io#333]
### Bug

When going into discover tv show/ new TV show imdb,  it show up error nothing is found. Notice this aswell with anything having to do with imdb.

### Expected Result

I expected it to show new list of new TV shows that just got release.

### Steps To Reproduce

1. Discover tv shows
2. New tv shows imdb
3. Blank

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Running kodi 20.2 on a nvidia shield tv first gen. Sorry i can get to the log but unable to scroll down to take picture using my TV remote. 

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
IMDb made changes. IMDb lists are getting removed in the next update.

**Comment by pjcanales** [comment]
> IMDb made changes. IMDb lists are getting removed in the next update.

Would there be a substitute for imbd list for new shows on next update?

**Comment by umbrellaplug** [comment]
I can look into it and see if I can find a suitable list to replace it. I have re-written the imdb section of umbrella to use some of the new website format so a few of the lists that are not working in the release are working in the test version, but it's limited to a static amount for the lists now which is not a great solution.

**Comment by Omarscomin** [comment]
> > IMDb made changes. IMDb lists are getting removed in the next update.
> 
> Would there be a substitute for imbd list for new shows on next update?

@pjcanales you're welcome to use my "Latest TV Shows" Trakt list, if you'd like. It updates automatically every 24 hours, and it's sorted by IMDb popularity. 

https://trakt.tv/lists/25524649

**Comment by umbrellaplug** [comment]
I was able to fix this particular list. Only difference is it will have a limit set on the amount returned on next update. It will be under settings: general. Next update will have the fixed list.

**Comment by umbrellaplug** [comment]
Fix is in the latest update.
