### ISSUE TITLE
"Decades" category for movies and TV shows

### ISSUE THREAD

**Issue by Omarscomin** [umbrellaplug/umbrellaplug.github.io#334]
### Feature

Hi UD! I hope you had a great weekend!

I was wondering if it might be possible to add a "decades" category within "discover movies/TV shows". Example:

Movies released from 1910-1919
Movies released from 1920-1929
Movies released from 1930-1939
Movies released from 1940-1949
Movies released from 1950-1959
....and so on. 

 I find it preferable to the "years" option, because there are so many years to choose from.

**Comment by adamosborne83** [comment]
🤔🤔🤔

**Comment by umbrellaplug** [comment]
Looks like the best fit for this would be trakt genres combined with years.
For my own reference later I'm adding the correct api call for Trakt for this here. I'll work on this after the next update.

`https://api.trakt.tv/movies/popular?page=1&limit=20&genres=action&years=1990,1991,1992,1993,1994,1995,1996,1997,1998,1999`

**Comment by umbrellaplug** [comment]
This is in the latest version.

**Comment by Omarscomin** [comment]
> This is in the latest version.

THANK YOU!!!😊

**Comment by SJ1O** [comment]
Extras for Xmas 😅🙏🏻
