### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by zita72** [umbrellaplug/umbrellaplug.github.io#336]
### Bug

Hello - not sure if this is a bug. I have umbrella installed on a 4k firestick & shield. Pastebin logs are from the firestick. Youtube from umbrella repo installs & works independently with my own API key but when I click on youtube videos within umbrella it gives the error shown.

### Expected Result

It worked fine on the Shield but had to reinstall kodi the other day & now I get the same error as I have on thr firestick.

### Steps To Reproduce

1 go to umbrellla

2 click on youtube videos

3 umbrella error - check the log for more details 

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21.0 beta
Tv firestick 4k
https://paste.kodi.tv/yayiluleri
https://paste.kodi.tv/oqelilabus

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Fix was pushed in an update today.

**Comment by zita72** [comment]
Thanks 👍  much appreciated
