### ISSUE TITLE
Problem with movie lists 

### ISSUE THREAD

**Issue by Foreveraudio** [umbrellaplug/umbrellaplug.github.io#337]
### Feature

I used to be able to goto sorting and select year and I would use imdb and see movies in order now I see imdb is gone and if I select year and choose Tmdb I just see out of order things like movies from other years and short video clips - when I used IMDb it was only movies and in order with check marks by the ones you have watched is this a current bug that is being worked on or am I the only one complaining lol

**Comment by umbrellaplug** [comment]
IMDb changed their website. Lots of list were lost with that. The api for IMDb is thousands a year so we have to be happy with what we have. I will see if I can find a better substitute for years but don't get your hopes up.

**Comment by Foreveraudio** [comment]
Yeah I appreciate it - being ocd sucks when things change just like when goto was around was similar with the sorting only movies and only years - it wouldn’t be as bad on the tmdb side of it but it’s not all movies mostly clips ect - appreciate something to come ❤️

**Comment by Tikipeter** [comment]
>...or am I the only one complaining lol

Complaining to a dev doing this for free is funny?

**Comment by umbrellaplug** [comment]
Added back. The limit is in General Settings.

**Comment by Foreveraudio** [comment]
> Added back. The limit is in General Settings.

Awesome to see back woo hoo hood more gets added love ya thanks 🙏
