### ISSUE TITLE
Merge multiple lists

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#338]
### Feature

Hi Mr Umbrella.
I trust you're well.

I love the Genre Trakt lists you've implemented. Fabulous idea I must say.
Now, as you might be aware from the odd previous requests I've put in, I use a lot of library, but, I am thinking of doing away with these... but I love the amount of movies etc I have from different years etc etc etc .

What would be amazing if you could do it, now stick with me...

Is have the ability to create to create a sort of autowidget feature within Umbrella, 
So I could have for example..

Genre Action, then select Trending, Popular, then 80's. 
So when I then create a widget it pulls from all 3 lists, or whatever my heart desires. 

Sounds awesome doesn't it.

**Comment by umbrellaplug** [comment]
> Sounds awesome doesn't it.

Not really.
