### ISSUE TITLE
Hide Show from In Progress Shows List not working

### ISSUE THREAD

**Issue by Darian1978** [umbrellaplug/umbrellaplug.github.io#339]
### Bug

In the "Progress Shows" list view, if I want to hide a show and use the context menu to choose the Trakt Manager, then the Hide Show function and then select Watched Progress, I get a success message, but the show is still on the list. 

### Expected Result

The show should be removed from the "Progress Shows" list and be shown in the "Hidden Progress Manager" list.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.2 with Umbrella 6.6.39, reproduced on FTS 4k max as well as Win11

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
fixed in latest update
