### ISSUE TITLE
[FEATURE] Improvement to TV Show specials/Season 0

### ISSUE THREAD

**Issue by benedekAdam** [umbrellaplug/umbrellaplug.github.io#340]
### Feature

Introduce a new option that, when enabled, does not count Season 0 episodes in the watched/total counts on TV Show list pages, like "My TV Shows -> Progress Shows". To preserve current behavior, a new settings option can be added to achieve this outcome.

Suggestion of implementation:

1.  Create a new toggle in Settings -> TV Shows.
    * The new option would only be active if "Include Special Episodes (Season 0)" is enabled
    * The new option is disabled by default
2. While the new option is enabled, episodes in Season 0s are not counted in the watched/total progress indicators
3. While the new option is enabled, Season 0 is still visible in the season list
4. Season 0s would still have their own counter of watched/total

With this option added, a hypothetical TV shows (which has two seasons with 10 episodes each, and a Season 0 with 5 parts. The user watched the first season in full, but nothing else) would behave this way:

* With both options disabled, the counter will display **10/20**. Season 0 is **not visible** in the seasons list
* With only "Include Special Episodes (Season 0)" enabled, the counter will display **10/25**. Season 0 is **visible** in the seasons list
* With both options enabled, the counter will display **10/20**. Season 0 is **visible** in the seasons list.

**Comment by umbrellaplug** [comment]
This request is confusing to me. Maybe I need to wake up more before I try to read it. Or break out a whiteboard or something. ![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/107957815/5d375d68-ffb0-4508-a455-2ba2432970be)

**Comment by benedekAdam** [comment]
I am sorry, it wasn't my intention to be confusing. By season 0, I meant the extras and special episodes for a given series. This collection is categorized as "Season 0" in Umbrella, and is hidden by default.

For example, take [Doctor Who](https://thetvdb.com/series/doctor-who-2005). Other than its many seasons, over the year it aired many special episodes as well, many of which move the story forward, and should not be skipped. These, combined with bts footage, cast interviews and other types of extras make up Season 0. My problem is, I have absolutely no interest in the hundred or so other pieces of content, yet I would have to watch them (or at least mark them watched) to be able to accurately view my progress.

Another, maybe better example is the series called [Bodyguard](https://thetvdb.com/series/bodyguard-2018#seasons). This series has a single, 6 episodes long season, along with a few minutes long special which I don't care for. Still, unless I mark the special as viewed, in the "My TV Shows -> Progress Shows" list my progress will be forever displayed as 6/7.

There are many series I follow that "require" specials to be enabled because they are real content, while in other cases, these extras can be safely ignored.

My request, if implemented, would offer the best of both worlds: if the user wants to, they can display every episodes (specials included) of every series, but without the extras showing up in the total episode count.

Please, if my request is still confusing, tell me how can I improve it. English is not my first language, and while I tried to be as clear as I could, it is possible I could have be even more clear.

**Comment by scapix** [comment]
has this been implemented?
special seasons unwatched episodes are still counted no matter what (even if you have them hidden) and i have not found any setting to not count them in unwatched
