### ISSUE TITLE
[BUG] Result pagination broken when using a filtered view

### ISSUE THREAD

**Issue by endlessterror** [umbrellaplug/umbrellaplug.github.io#342]
### Bug

This is a bug that affects pagination. I have a lot of series/movies in my trakt collections. When I browse them with the filter set to "all" everything works fine. Pages are formed every 30 results.

In my case I've around 40 series, in two pages (first 30, second the remaining 10). Obviously pagination happens automatically. 

Now if I set the filter to unwatched and mark say 28 out of the first 30 series watched, I would expect that the remaining 12 series (the 2 unwatched from the first page and the 10 from the second) would be displayed together, in a single result page. This does not happen. Instead, the 2 unwatched are displayed as page 1, and the 10 from page are displayed together as page 2.

I'm providing photos:
* of the lower part of the first page when the filter is set to all
* of the entire first page, when the filter is set to "unwatched".

### Expected Result

Complete description above, see also screenshots,

### Steps To Reproduce

1. Go to a trakt collection containing enough series or movies, to have to paginate, when filter is set to show all
2. Mark all items on page 1 as watched, except two
3. Set filter to "unwatched"

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi version: 20.1.0 (Libreelec 11.0.1)
Platform is Odroid C2

![showall](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8733010/ef96de09-cce8-44d8-a552-2cf39d5e9585)
![filter_unwatched](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8733010/e3f0e14f-0783-4b28-a35f-ea018326a06d)

Kodi log: https://paste.kodi.tv/umodebixev
umbrella log: https://paste.kodi.tv/jevecimete

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I'm not re-writing pagination for this. You will have to deal with this bug.
