### ISSUE TITLE
[FEATURE] Post scraping filters

### ISSUE THREAD

**Issue by irondave** [umbrellaplug/umbrellaplug.github.io#343]
### Feature

**Feature**

Hi Umbrella dev!

It would be really useful to have the ability to be able to filter post-scraping results.
For example, I happen to want to watch a movie in my native language but this involves having to search through several scraping results.
It would be very useful to be able to search in the title, or with the torrent information. 
By searching in the title I could find a torrent with the desired language in a few moments (e.g. ENG/JPN, ENG/RUS, ENG/FRE torrents, ...).
Some ideas of filters could be by video quality, by debrid (might be useful if I am subscribed to both Real-Debrid and All Debrid), by provider, etc... 
A feature like this I think is a huge step toward improving the daily use of this excellent addon.
I hope I have explained myself in the best way, if not please let me know.
Thank you for your incredible work!

**Comment by umbrellaplug** [comment]
These filters already exist.

**Comment by irondave** [comment]
Sorry but I can't find something similar of what I'm talking about.
Can you please help me?

**Comment by Arthur1967** [comment]
Sort and filter in the tools section

**Comment by Arthur1967** [comment]
And then there's another section in tools called source options

**Comment by umbrellaplug** [comment]
> It would be really useful to have the ability to be able to filter post-scraping results.
> For example, I happen to want to watch a movie in my native language but this involves having to search through several scraping results.

You can set filters for in undesirables in scrapers to filter out titles with languages in the file name you do not want. This would be in the scraper settings, not Umbrella.

> It would be very useful to be able to search in the title, or with the torrent information.
This just isn't possible with custom xml screens like source results.

> Some ideas of filters could be by video quality, by debrid (might be useful if I am subscribed to both Real-Debrid and All Debrid), by provider, etc...

You can enable providers and disable providers at will within Umbrella using the settings. Settings for sorting and filtering by quality, size, audio, and encoding type can all be found in Tools> Settings> Sorting and Filters. You can also sort by providers as well.

**Comment by irondave** [comment]
As I thought you didn't understood my request.
Of course before open a github issue I walk through the entire menu and I didn't find what I'm searching for.
Leaving out that using the options you mentioned you'll find all of your scraping result filtered meanwhile with what I mean it's a post scraping set of filters so you can use that for specific research only.
Just to be clear I'll use what Fen offers as an example.

All the scraping results (not filtered in any way):
![Scraping results](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8292014/28de15f1-5d58-4d04-a923-aef1705cdda9)

Filters menu inside the results screen:
![Post scraping filter](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8292014/9ad9c98b-262f-46a2-ac61-85e48901c0db)

I'm going to filter results for what is in the title:
![Search for titles](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8292014/53e5ad01-32e4-4186-a2cb-edb196033bea)

I'm searching for results with "ita" in the title:
![Search in titles](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8292014/e12b8ff4-669f-433f-9fc3-a2666cab31d2)

Here the result of the post scraping filter, it show the only one torrent with "ita" in the title:
![Filter results](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/8292014/44b0e2dd-5f72-4527-ad7b-e374bcce2f39)

I hope it's clearer now what I mean.
I took Fen as an example to do before, I hope it's not a problem.
Thank you for your attention and especially for the great work you are doing.
