### ISSUE TITLE
Cache to Real-Debrid Cloud error

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#345]
### Bug

Attempting to add uncached torrent to Real-Debrid Cloud throws Umbrella error with empty dialog box

This is on the latest Umbrella, both Apple TV 20.3 and MacBook 20.1

### Expected Result

Adds torrent to cache

### Steps To Reproduce

Bring up source select for TV episode (details in Umbrella log)
Attempt Cache to Real-Debrid against one of the uncached torrents with seeders

Attached Umbrella logs, let me know if you need Kodi

Thanks

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

https://paste.kodi.tv/aguxesafiw

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Fixed. Next update will include the fix.

**Comment by Ade-AV** [comment]
Confirmed as working, thanks
