### ISSUE TITLE
Settings swap between GUI and settings.xml for remove video codecs source filtering for av1 and atvp

### ISSUE THREAD

**Issue by phatboyj** [umbrellaplug/umbrellaplug.github.io#346]
### Bug

while comparing the settings.xml for separate installs I stumbled across a discrepancy between what is set in the settings gui and what is written to the .xml for 2 of the video filter options.

 Remove av1, "in the gui" sets setting id="remove.atvp", "in the .xml",  and vice versa.

1.a)
when toggling the the av1 filter in the GUI it unexpectedly writes the setting to the atvp .xml entry  setting id="remove.atvp"

1.b)
when toggling the the atvp filter in the GUI it unexpectedly writes the setting to the av1 .xml entry  setting id="remove.av1"

behavior was observed running on 20.3 with 6.6.45 Umbrella installed and is easily repeatable by

changing one of the above settings in the GUI and then comparing it to what is written to the intended settings.xml entry and then observing that the other setting entry was actually altered instead

I hope I've accurately reported the problem if more details are needed I am glad to help as an avid fan of your work

 

### Expected Result

Settings marked via gui match the corresponding .xml entries

### Steps To Reproduce

1.a)
when toggling the the av1 filter in the GUI it unexpectedly writes the setting to the atvp .xml entry  setting id="remove.atvp"

1.b)
when toggling the the atvp filter in the GUI it unexpectedly writes the setting to the av1 .xml entry  setting id="remove.av1"

repeatable by

changing one of the above settings in the GUI and then comparing it to what is written to the intended settings.xml entry and then observing that the other setting entry was actually altered instead

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

20.3 Shield 2017 Umbrella 6.6.45

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This has been fixed. It will be included in the next update. Thanks!
