### ISSUE TITLE
No sources found - intermittent (Apple TV?) issue

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#347]
### Bug

Every now and then on my Apple TV when attempting to play there will be no sources found, only way to resolve is to Quit/Restart Kodi or sometimes it will work at a later stage

### Expected Result

Sources found

### Steps To Reproduce

Attempt to play TV episode - No Sources Found
Try Rescrape Options Filterless, All - No Sources Found

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

20.3, Apple TV

https://paste.kodi.tv/asogohonuq

Thanks

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This has nothing to do with umbrella. Your log shows it's an issue with getting the file from real-debrid.

`[2024-02-09 10:30:44] [ plugin.video.umbrella: INFO ]: From func name: 2._post() Line # :121
                       msg : Real-Debrid Error:  hoster_unavailable`

**Comment by Ade-AV** [comment]
Tried with a different show, no real-debrid error this time

https://paste.kodi.tv/ayakulisif

**Comment by Ade-AV** [comment]
On further investigation I get the ```can't start new thread``` error when trying to scrape with all providers, seems the limit is round about 9 or 10 before it starts complaining

Workaround is to increase my providers from 1 to 9 and turn off ```Auto-Retry using all providers if no sources are found.```
