### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by Redsand51** [umbrellaplug/umbrellaplug.github.io#348]
### Bug

If External Provider is enabled and no provider is entered an endless error loop begins. Reboot is only escape.

### Expected Result

Exit from provider entry

### Steps To Reproduce

1. Providers
2. Enable External Provider
3. Cancel

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi V11 and 12

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Don't enable external providers without setting one. This isn't a bug, this is user error. I'm not going to spend time writing code to cover this scenario.
