### ISSUE TITLE
K21 Compatible 

### ISSUE THREAD

**Issue by ronfrankhill** [umbrellaplug/umbrellaplug.github.io#350]
### Feature

Just asking. Would you be making umbrella K21 compatible to use? As Omega 21 was officially release yesterday as a stable version for users.

**Comment by umbrellaplug** [comment]
> ### Feature
> 
> Just asking. Would you be making umbrella K21 compatible to use? 

It was only released yesterday, but as far as I know there aren't any issues with running umbrella on kodi 21. I've had one issue reported so far and it's pretty particular to their setup.

**Comment by ronfrankhill** [comment]
Okay. Just making sure. Thanks.

**Comment by umbrellaplug** [comment]
No problem. That's the main reason I've opened issues back up here the past few days. Even though I haven't listed Kodi 21 as compatible on my GitHub yet, there have been changes made to accommodate the new version. Please let me know if anything comes up.

**Comment by ronfrankhill** [comment]
Thanks.

**Comment by ronfrankhill** [comment]
Dumb question on my part. Can play items with video codec VP9 in it?

**Comment by adamosborne83** [comment]
Thanks for the hard work
