### ISSUE TITLE
[FEATURE] (Progress) Episodes Widget Artwork/Title

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#353]
### Feature

Hi

In Arctic Horizon 2 Skin I have a Widget based on Progress Episodes and the artwork is shown as a thumb(?) 

Would it be possible to have an option to display the Fanart instead similar to TMDB Helper which has a ```Preferred artwork for thumbs``` option?

And can there be options for the Title format? My preferred option would be no title

Thanks

Umbrella Progress Episodes
<img width="350" alt="Umbrella Progess Episodes thumb" src="https://github.com/umbrellaplug/umbrellaplug.github.io/assets/121737707/80f0e68e-8aa1-46c1-91df-e31205a8291e">

TMDB Helper Next Episodes (Fanart selected)
<img width="378" alt="TMDB Next Episodes Fanart" src="https://github.com/umbrellaplug/umbrellaplug.github.io/assets/121737707/d34182a6-b6a0-4a8a-961b-ca38074f1250">

**Comment by umbrellaplug** [comment]
There are already options for prefer tmdb or prefer fanart. I'm not 100% familiar with tmdbhelper, but the "thumbs" as you describe appear to be the poster. Which image used for the poster is determined by the settings I just referenced and the skin. I think it can be a range of different images used based on the size like thumb, landscape, fanart, or the poster. I'm not real sure which one you're requesting changes on here.

Titles:
Are you asking for the ability to customize the way titles show throughout the addon for shows or are you asking for an option to format how titles look in widgets?

**Comment by Ade-AV** [comment]
The prefer tmdb or fanart doesn't seem to make a difference, the screenshots are both using the AH2 Landscape Style, Umbrella is thumb and Tmdb is fanart (changed in settings from default thumb)

Both the artwork and titles requests are for widgets

<img width="1035" alt="tmdb widget episodes settings" src="https://github.com/umbrellaplug/umbrellaplug.github.io/assets/121737707/d1045b07-cdd0-48ad-a7e2-562954d7d296">

**Comment by umbrellaplug** [comment]
I guess it's me but I still don't understand the request. No offense, but I don't want to spend time my loading tmdbhelper and a skin just to understand a request. I'd say just use tmdbhelper at this point. It seems to do what your wanting.

**Comment by Ade-AV** [comment]
I think Umbrella is setting the artwork for Progress Episodes as a thumb (episode screenshot) and tmdbhelper is doing the same but has the option to override to fanart. I could use tmdbhelper but prefer to use Umbrella for my widgets

**Comment by umbrellaplug** [comment]
I have added both of these requests into the latest test version of umbrella.

**Comment by umbrellaplug** [comment]
Can you test the version in the test repo and let me know if that resolved your requests?

**Comment by adamosborne83** [comment]
> Can you test the version in the test repo and let me know if that resolved your requests?

Not my request, but can confirm this works on Arctic Fuse.

**Comment by Ade-AV** [comment]
It's working but I think it would be better to use the Fanart TV Thumb and whatever the equivalent TMDB image is, think this is ```landscape``` in the code

**Comment by umbrellaplug** [comment]
I'll be removing this. I'm not getting into an endless "make the art look this way". The artwork that was being used before looked better. I'll keep the widget title change. The artwork changes are going to be reverted back to what they were. The artwork being used is fine. I do not see a good reason to continue working on this.
