### ISSUE TITLE
[BUG] 4k Icons not showing on some systems

### ISSUE THREAD

**Issue by umbrellaplug** [umbrellaplug/umbrellaplug.github.io#354]
### Bug

On apple and amlogic devices icons are not showing for 4k on the source select screen.

### Expected Result

Icons to show next to 4k results.

### Steps To Reproduce

Apple or amlogic device needed.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.5

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
@saxoloman
@Ade-AV

Can you confirm the 4k icons are now showing in the latest test build?

**Comment by saxoloman** [comment]
> @saxoloman @Ade-AV
> 
> Can you confirm the 4k icons are now showing in the latest test build?

It is working correctly now .
thank you for fixing it :)

On this new version is it possible to toggle clearlogo off  ? 
I cant find a way to do it from settings.

**Comment by umbrellaplug** [comment]
No. Why would you want to turn clearlogo off?

**Comment by saxoloman** [comment]
Ahh ok no worries , im not asking you to add it, i was just curious.
it interferes with my skin and i liked it alot more before,
but it all just comes down to personal taste i guess.
pic before
https://postimg.cc/bd78v2wC
pic after
https://postimg.cc/dZ8f335p

**Comment by umbrellaplug** [comment]
> Ahh ok no worries , im not asking you to add it, i was just curious. it interferes with my skin and i liked it alot more before, but it all just comes down to personal taste i guess. pic before https://postimg.cc/bd78v2wC pic after https://postimg.cc/dZ8f335p

The two pictures look almost exactly the same to me. Am I missing something? Sorry, I don't use a skin so I'm not super familiar with where I should be looking for the difference.

I think the difference you are seeing is the "Prefer TMDB images" may be applying the clearlogo now where it was not before. Try turning that setting off and clearing your cache and making sure enable fanart and enable extended are turned on.

**Comment by saxoloman** [comment]
logo is now different.
i circled it for you 
before
https://postimg.cc/Cdkrjv0g
after
https://postimg.cc/1gF7JMFw

i tried turning off Prefer TMDB images
and both fanart and extended fanart are on
cleared all cache, restarted kodi, but its still the same small clearlogo image instead of default skin big image.

**Comment by umbrellaplug** [comment]
Yeah, that doesn't seem right. I will look into it. Unfortunately you guys keep bringing up new issues on different issues so I'm going to be closing this issue.

**Comment by umbrellaplug** [comment]
4k icons missing will be fixed in the next update.

**Comment by saxoloman** [comment]
> Yeah, that doesn't seem right. I will look into it. Unfortunately you guys keep bringing up new issues on different issues so I'm going to be closing this issue.

I'm sorry, i honestly tough this was a feature and not a bug. i just wanted to see if there's a way to disable it.
thank you for taking time to look in to this. skin is Artic horizon 2 if it matters.
