### ISSUE TITLE
[BUG] Umbrella crashes Kodi when navigating to Next Page (2) in My Movies > Collection.n

### ISSUE THREAD

**Issue by Hemicrusher** [umbrellaplug/umbrellaplug.github.io#355]
### Bug

Umbrella crashes Kodi when navigating to Next Page (2) in My Movies > Collection.

When having exactly 20 movies in Collection, which is the max per page, Next Page (2) shows at the bottom. Clicking on Next Page (2) crashes/locks up Kodi, which then has to be killed under Android. If you have 21 movies, then clicking on Next Page (2) takes you to the second page, where movie #21 shows. If you have only 19 movies, then the Next Page (2) does not show.  

Also, when there were 21 movies in Collection, I removed one to test with 20, yet Umbrella still showed 21.

I don't know if this is a Trakt issue, or an issue with Umbrella.

### Expected Result

With only 20 movies, which is the max per page, Next Page (2) should not appear until another movie is added.

### Steps To Reproduce

See above

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21.0 stable for Android running on an ONN 4K Google TV device

[Kodi log file](https://pastebin.com/AiHWy0m5)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I'm unable to view that log currently. It's acting like pastebin is down. Are you running a skin?

**Comment by Hemicrusher** [comment]
> I'm unable to view that log currently. It's acting like pastebin is down. Are you running a skin?

I am just running the default skin,....Weird...the log link worked earlier.

I'll reproduce the issue again later tonight when I get home and post a new log. 

Thanks!

**Comment by Hemicrusher** [comment]
I've updated the link to the log file in the OP and [HERE](https://pastebin.com/AiHWy0m5).
