### ISSUE TITLE
[FEATURE] Better parsing/tagging on the results window, and support for static MDBlist lists

### ISSUE THREAD

**Issue by N0mad077** [umbrellaplug/umbrellaplug.github.io#357]
### Feature

Hi! First, I'd like to thank you for your efforts and time invested in the add-on. Been a user for a couple of months, and it's been a great experience.

I just wanted to voice a couple suggestions if you don't mind:

- Improved parsing/tagging on the results window. Addition of a line under each result with tags like 4K, REMUX, DV, HDR, and ATMOS would be very welcome. I'm assuming it wouldn't be too complicated to extract such tags since almost all sources follow a certain naming scheme.

- I'm an avid user of mdblist and Umbrella sadly doesn't show static lists I've created there. Self-updating external lists such as ones originating from Trakt do show without an issue, though. I've tested this on Tmdbhelper and both types of lists are shown under it's mdblist menu. It'd be really practical if Umbrella were capable of this as well.

Anyway, not sure if you're even interested in such suggestions, or updating the add-on anymore, but if you indeed are, I'd love to see/would greatly appreciate these additions.

Thanks for taking the time to read this, take care!

**Comment by adamosborne83** [comment]
https://imgur.com/a/2khw5ZX

I can access my lists without issue, and on source select is this no the info you want?

**Comment by Arthur1967** [comment]
![IMG_2314](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/69996032/10bd0aff-001f-4c6f-bd7e-4d8b7acbe2ed)
![IMG_2313](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/69996032/1e551889-c0aa-4b4c-af95-105bea2fbb3f)

**Comment by Arthur1967** [comment]
Static list show up on mine

**Comment by N0mad077** [comment]
> https://imgur.com/a/2khw5ZX
> 
> I can access my lists without issue, and on source select is this no the info you want?


Thanks for taking the time to upload that vid! Are any of those MDBlist lists static ones or are they all dynamic/self-updating? I just can't get my static lists to show up on Umbrella.

As for the source select menu, that's not what I meant. Say you have a source that goes like this:

The.Prestige.2006.Hybrid.2160p.UHD.BluRay.REMUX.HDR10 .HEVC.DTS-HD.MA.5.1-WiLDCAT.torrent

It'd be really useful while going through sources if there was a tagline under it that goes like this:

- 4K/UHD | REMUX | HYBRID | HDR10 | DTS-HD MA

That extra readability really helps. Should be quite simple for someone with umbrellaplug's talents to implement.

**Comment by adamosborne83** [comment]
> Thanks for taking the time to upload that vid! Are any of those MDBlist lists static ones or are they all dynamic/self-updating? I just can't get my static lists to show up on Umbrella.

Both, static and dynamic. Have you tried generating a new API within mdblist, then adding it to umbrella. Make sure you clear Umbrella Cache too.
> 
> As for the source select menu, that's not what I meant. Say you have a source that goes like this:
> 
> The.Prestige.2006.Hybrid.2160p.UHD.BluRay.REMUX.HDR10 .HEVC.DTS-HD.MA.5.1-WiLDCAT.torrent
> 
> It'd be really useful while going through sources if there was a tagline under it that goes like this:
> 
> - 4K/UHD | REMUX | HYBRID | HDR10 | DTS-HD MA
> 
> That extra readability really helps. Should be quite simple for someone with umbrellaplug's talents to implement.

Suck up.

**Comment by N0mad077** [comment]
> > Thanks for taking the time to upload that vid! Are any of those MDBlist lists static ones or are they all dynamic/self-updating? I just can't get my static lists to show up on Umbrella.
> 
> Both, static and dynamic. Have you tried generating a new API within mdblist, then adding it to umbrella. Make sure you clear Umbrella Cache too.
> 
> > As for the source select menu, that's not what I meant. Say you have a source that goes like this:
> > The.Prestige.2006.Hybrid.2160p.UHD.BluRay.REMUX.HDR10 .HEVC.DTS-HD.MA.5.1-WiLDCAT.torrent
> > It'd be really useful while going through sources if there was a tagline under it that goes like this:
> > 
> > * 4K/UHD | REMUX | HYBRID | HDR10 | DTS-HD MA
> > 
> > That extra readability really helps. Should be quite simple for someone with umbrellaplug's talents to implement.
> 
> Suck up.

Tried new API Key, no change.

It's a suggestion. Nobody's complaining here. It's up to the dev if he chooses to implement it or not. Nothing to 'suck up' here.

**Comment by umbrellaplug** [comment]
I'm trying to understand the requests.

> Improved parsing/tagging on the results window. Addition of a line under each result with tags like 4K, REMUX, DV, HDR, and ATMOS would be very welcome. I'm assuming it wouldn't be too complicated to extract such tags since almost all sources follow a certain naming scheme.

In Umbrella when you use source select (the picture you posted) as you hover over each link there are images used at the bottom of the source select screen for these exact items (4k, hdr, atmos).
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/107957815/aee838a0-e0d1-452b-aa1e-bcb8603c8320)

Also on the source select screen you can use the context menu on any link and select "Additional Link Info" and get a breakdown of all the formats, quality, and sound tags that were detected by the code.
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/107957815/eaadc03b-e4c0-424d-a6ca-bba95a3ca393)

Now knowing these options exist, is the request to add an additional line on each individual link displaying this same information? Basically, increase the height of each individual link and add a third link of text displaying this information?

> I'm an avid user of mdblist and Umbrella sadly doesn't show static lists I've created there. Self-updating external lists such as ones originating from Trakt do show without an issue, though. I've tested this on Tmdbhelper and both types of lists are shown under it's mdblist menu. It'd be really practical if Umbrella were capable of this as well.

I'm not sure I understand this. Are you unable to see lists you've created in mdblist in Umbrella after setting your mdblist api key? If so, I'm pretty sure that is not how I intended for that to work when I wrote the mdblist integration. What would be my steps to duplicate this issue if I was to try here? Create a list on mdblist of movies and see if it shows in Umbrella?


> Tried new API Key, no change.
> 
> It's a suggestion. Nobody's complaining here. It's up to the dev if he chooses to implement it or not. Nothing to 'suck up' here.

He's just joking with you. I'm not sure on the source select screen changes yet. I have some concerns about increasing the size of the cell holding each source for information that is already available, but I'm still trying to think it over and think of the best way to implement this request. The information is already there, it's just a matter of presenting it on the screen differently. I have asked a few questions throughout this response to try to get a better understanding of your request and make sure you were aware of any options that may already be available.

The mdblist stuff sounds like either an issue, a bug, or some type of configuration error. I'm happy to try to figure that one out, I just need a little more information to duplicate it.

Neither of these seemed like a complaint.

**Comment by N0mad077** [comment]
> I'm trying to understand the requests.
> 
> > Improved parsing/tagging on the results window. Addition of a line under each result with tags like 4K, REMUX, DV, HDR, and ATMOS would be very welcome. I'm assuming it wouldn't be too complicated to extract such tags since almost all sources follow a certain naming scheme.
> 
> In Umbrella when you use source select (the picture you posted) as you hover over each link there are images used at the bottom of the source select screen for these exact items (4k, hdr, atmos). ![image](https://private-user-images.githubusercontent.com/107957815/325053050-aee838a0-e0d1-452b-aa1e-bcb8603c8320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjgwODEsIm5iZiI6MTcxMzkyNzc4MSwicGF0aCI6Ii8xMDc5NTc4MTUvMzI1MDUzMDUwLWFlZTgzOGEwLWUwZDEtNDUyYi1hYTFlLWJjYjg2MDNjODMyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwMzAzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDRiMjVhYWRhMjE4NWFkYzg0NWExOWMwODgyN2MzNjJhNWZmZjg3MDRhMDIzZTYwM2RlZDFiZmEyZDk3ZjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xUUewf4Y4g7pXseBqNPs6x-3BgULbSH3KNnmcXMXYew)
> 
> Also on the source select screen you can use the context menu on any link and select "Additional Link Info" and get a breakdown of all the formats, quality, and sound tags that were detected by the code. ![image](https://private-user-images.githubusercontent.com/107957815/325053613-eaadc03b-e4c0-424d-a6ca-bba95a3ca393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjgwODEsIm5iZiI6MTcxMzkyNzc4MSwicGF0aCI6Ii8xMDc5NTc4MTUvMzI1MDUzNjEzLWVhYWRjMDNiLWU0YzAtNDI0ZC1hNmNhLWJiYTk1YTNjYTM5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwMzAzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGFlMGNhZDI3NGVkMDlkNDA0NDE4ZGFlZGEzNGI3ZjM0OGU4NjU5OTQ5OGQ3MDJiNjZjNTFjNzdkN2RjZDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R0-3SCUUkkmJcBbXMRMubLJgNZRHX0rNWXOKjTLQYA8)
> 
> Now knowing these options exist, is the request to add an additional line on each individual link displaying this same information? Basically, increase the height of each individual link and add a third link of text displaying this information?
> 
> > I'm an avid user of mdblist and Umbrella sadly doesn't show static lists I've created there. Self-updating external lists such as ones originating from Trakt do show without an issue, though. I've tested this on Tmdbhelper and both types of lists are shown under it's mdblist menu. It'd be really practical if Umbrella were capable of this as well.
> 
> I'm not sure I understand this. Are you unable to see lists you've created in mdblist in Umbrella after setting your mdblist api key? If so, I'm pretty sure that is not how I intended for that to work when I wrote the mdblist integration. What would be my steps to duplicate this issue if I was to try here? Create a list on mdblist of movies and see if it shows in Umbrella?
> 
> > Tried new API Key, no change.
> > It's a suggestion. Nobody's complaining here. It's up to the dev if he chooses to implement it or not. Nothing to 'suck up' here.
> 
> He's just joking with you. I'm not sure on the source select screen changes yet. I have some concerns about increasing the size of the cell holding each source for information that is already available, but I'm still trying to think it over and think of the best way to implement this request. The information is already there, it's just a matter of presenting it on the screen differently. I have asked a few questions throughout this response to try to get a better understanding of your request and make sure you were aware of any options that may already be available.
> 
> The mdblist stuff sounds like either an issue, a bug, or some type of configuration error. I'm happy to try to figure that one out, I just need a little more information to duplicate it.
> 
> Neither of these seemed like a complaint.

Hi! Thanks for taking the time to reply in such a concise manner.

It appears I've been ignoring the images that show up under a source representing tags all this time... I guess my suggestion would be accomplishing the same thing, only through written tags instead of images of tags. My bad.

As for the MDBlist issue; I just did some further testing by reinstalling Umbrella (complete re-install with all settings wiped) creating more test lists, and the issue seems to be replicatable on my end. Created a test static list, didn't show up even after clearing all cache. Created a test dynamic list, showed up just fine. 
![Screenshot_20240424_052045_Chrome](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/167133618/8d36b365-534e-4587-838e-15ca6c0a5290)
Anything under the tab 'Static Lists', doesn't matter if linked to trakt or not, do not show up in Umbrella's MDBlist menu.

It'd be much appreciated if you could help me out with solving this.

**Comment by umbrellaplug** [comment]
Okay, duplicated this by creating a static list. It appears in mdblists when you create a static list it does not return a list_type on static lists. Who knew?

One of the lines of code tries to match the list type to the section you navigated from so you only get movies when in the movies section and tv shows when in the tv shows section. Due to the list type missing and it looking to match with the current views list type it's throwing out the static lists. I adjusted my code and I'm able to get the static lists as well now, but it does create a small issue where static lists show the total amount of items on the list not just the movies or tv shows on the list. This doesn't seem like a big deal to me but I'm sure some users will want to know why the list count does not match the number of items on the list. 

All this aside, it's going to require code changes on my side to fix that.

**Comment by N0mad077** [comment]
> Okay, duplicated this by creating a static list. It appears in mdblists when you create a static list it does not return a list_type on static lists. Who knew?
> 
> One of the lines of code tries to match the list type to the section you navigated from so you only get movies when in the movies section and tv shows when in the tv shows section. Due to the list type missing and it looking to match with the current views list type it's throwing out the static lists. I adjusted my code and I'm able to get the static lists as well now, but it does create a small issue where static lists show the total amount of items on the list not just the movies or tv shows on the list. This doesn't seem like a big deal to me but I'm sure some users will want to know why the list count does not match the number of items on the list.
> 
> All this aside, it's going to require code changes on my side to fix that.

Awesome, thanks. At least I know now that it's not something wonky on my end. I also think it'd be more important to get the lists to show up than worrying about item count not matching. 

Also, I believe I've experienced exactly what you described where mdblist basically threw out the shows from an external list, when I attempted to create a static list from it. I was indeed filtering through the movies section. Sounds like a side-effect of what you're describing.

I wonder how other users who commented here were getting static lists to show up, though?

**Comment by umbrellaplug** [comment]
> I wonder how other users who commented here were getting static lists to show up, though?

They were incorrect. Looking over the code there's no way it was working.

**Comment by Arthur1967** [comment]
Just my opinion, but my static lists are showing up no problem and as for the other feature is this really necessary just my opinion thank you for the great work you do on this

**Comment by Arthur1967** [comment]
Could this also not slow down the speed adding all this stuff I think it's good the way it is just my opinion. Have a good day.

**Comment by umbrellaplug** [comment]
This has been fixed and will be in the next update.

**Comment by N0mad077** [comment]
> This has been fixed and will be in the next update.

Much appreciated, thanks.
