### ISSUE TITLE
Next page

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#358]
Since the latest update in my Trakt list when you get to the bottom, you can't go to the next page because there is no next

**Comment by Arthur1967** [comment]
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/69996032/3ca17331-f315-4a85-9bce-c54b158f9d22)

**Comment by umbrellaplug** [comment]
im not having this issue. i need steps to duplicate. this is why i ask for steps to duplicate when opening an issue. you waste my time and yours when you don't include the information requested.
