### ISSUE TITLE
No tracks collection list

### ISSUE THREAD

**Issue by mmheitzman** [umbrellaplug/umbrellaplug.github.io#359]
### Bug

Since update 5-9-24 I have no Trakt collection list. At first it had one page and no way to go to second page and then the list disappeared. I tried force sync with no luck. 

### Expected Result

Get Trakt collection list back. Umbrella is our go to addon. 

### Steps To Reproduce

Tools. Tracks tools. Collection. Empty

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi nexus 20.5

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by adamosborne83** [comment]
Have you de authorised trakt? The clear Cache and then authorised again?

**Comment by umbrellaplug** [comment]
Revoke Trakt, clear all cache, then re-authorize. Let me know if that makes a difference.

**Comment by mmheitzman** [comment]
No differenceMarye ***@***.*** from my iPhoneOn May 9, 2024, at 3:29 PM, umbrellaplug ***@***.***> wrote:﻿
Revoke Trakt, clear all cache, then re-authorize. Let me know if that makes a difference.

**Comment by mmheitzman** [comment]
Yes. Made no difference. Gen lite updated also and has the same problem. Seren running fine. Marye ***@***.*** from my iPhoneOn May 9, 2024, at 3:20 PM, adamosborne83 ***@***.***> wrote:﻿
Have you de authorised trakt? The clear Cache and then authorised again?

**Comment by umbrellaplug** [comment]
Mine works. Where's the log?

**Comment by umbrellaplug** [comment]
Try the latest update.

**Comment by mmheitzman** [comment]
Latest update did not fix my problem. Marye ***@***.*** from my iPhoneOn May 9, 2024, at 5:47 PM, umbrellaplug ***@***.***> wrote:﻿
Try the latest update.

**Comment by umbrellaplug** [comment]
Don't know. Not going to beg for logs.

**Comment by Arthur1967** [comment]
My issue was the next page not showing up. I thought I had the latest update installed, but I didn’t after I installed it. Everything works fine thank you
