### ISSUE TITLE
Prioritize AV1 video codec and BluRay source

### ISSUE THREAD

**Issue by LITUATUI** [umbrellaplug/umbrellaplug.github.io#36]
I appreciate the ability that this addon has to prioritize good and modern codecs like HEVC. Would it be possible to add AV1 to the list?

If we were able to choose the order of codecs that we prefer, I would configure it like this:

1. AV1
2. HEVC (H.265)
3. AVC (H.264)
4. Rest (old codecs like Xvid and Divx)

This would allow to maximize quality per bit. AV1 is a really good video codec, especially for 4K animations.

Another thing that might be worth considering is also allowing ordering per source:

1. BluRay
2. Web-DL
3. Web-Rip
4. TV-Rip
5. Rest

Ignore all this if is too much work. The addon is already great as it is :smiley:

**Comment by 123Venom** [comment]
Could you kindly show me a magnet source that is AV1 for review?
There's options to prioritize "HDR and Dolby-Vision to top" and 2nd one down is to prioritize "HEVC to top".  That 2nd option will place your items 2, 3, and 4 in order....as such
<img width="776" alt="8e" src="https://user-images.githubusercontent.com/46383815/180933477-85420190-1a87-4be0-a8bd-a739357f1a86.PNG">

Your 2nd set of questions...what's the difference between `Web-DL` and `Web-Rip`?

**Comment by LITUATUI** [comment]
Thanks, I already prioritize HDR and HEVC.

Sure:

[Dune (2021) in 4K.](https://www.1337x.to/torrent/5081491/Dune-2021-2160p-UHD-HDR-Bluray-AV1-Opus-dAV1nci/)

[The Suicide Squad (2021) in 1080p](https://www.1337x.to/torrent/4951801/The-Suicide-Squad-2021-MULTI-1080p-4K-Source-WEBRip-AV1-Opus-AV1D/).

[South Park S01](https://www.1337x.to/torrent/5246031/South-Park-S01-1080p-Bluray-AV1-Opus-AV1D/).

Web-DL is an unmodified downloaded stream that you get with tools like YT-DLP, if you reencode that stream it becomes a WEBRip.

If your machine supports hardware decoding of AV1, you need to use Kodi 20 to enable it. Nowadays, popular SoCs for cheap Android boxes like Amlogic S905X4, S905Y4 and S905W2 already support this codec.

If hardware decode isn't available and software decoding is used, 4K might be difficult to play in most computers. Otherwise, 1080p should work flawlessly.

**Comment by umbrellaplug** [comment]
Took some time to look over these sources. Understand what you're saying here, but I didn't have any hardware that supports any of these. It seems as though instead of pushing them to the top we should be filtering them out until Kodi 20 comes and they are supported. I tried on a Shield, Xbox Series X, Pi 4, and Fire Cube and was unable to find a device that these types of videos worked with. I'll work to identify these types of videos so they can be filtered and sorted in the future, but for now they appear unsupported on most devices.

**Comment by LITUATUI** [comment]
Just a heads up. Fen is back and now allows to prioritize or exclude AV1.

**Comment by umbrellaplug** [comment]
I am aware. The next update of Umbrella will include this as well. Going to go ahead and close this issue out. Thanks!
