### ISSUE TITLE
sort of [BUG] fyi latest update keeps failing

### ISSUE THREAD

**Issue by Mahava** [umbrellaplug/umbrellaplug.github.io#362]
### Bug

Omega stable
Windows
SG helper and all dependencies updated

### Expected Result

![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/32604452/8cc8c4fa-31f8-4848-982f-593ab5b8a816)

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/32604452/0a6bc224-0ae7-4465-a236-91c3b2dfe783)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Current version is 53. Update your repo on your devices.
