### ISSUE TITLE
Playing TV Shows

### ISSUE THREAD

**Issue by TheOGuser** [umbrellaplug/umbrellaplug.github.io#363]
### Bug

Hello Team.
I have an issue with trying to play TV Shows with Play Next

### Expected Result

TV Shows to play.

### Steps To Reproduce

Using Kodi 21
Kodi Settings
Media
Videos
Default Select Action
Show Information.

In Umbrella Settings
Playback
Enable PlayNext Popup--------- Enable

Click OK

Go into TV Shows and click any episode and nothing seems to happen.

I have RD enabled and CoCo Scrapers enabled.

Movies are working fine.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Will provide logs if required.

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Kodi made a change to the way items were added to playlists when using info as play action. This is outside of my control. Play next will not work with information set as your play action.

**Comment by TheOGuser** [comment]
> Kodi made a change to the way items were added to playlists when using info as play action. This is outside of my control. Play next will not work with information set as your play action.

Oh ok, guess i will stay with FEN for TV Shows. Thank you.
