### ISSUE TITLE
Refresh metadata

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#364]
### Feature

Have it in the Contacts menu the ability to refresh the metadata for a TV show or a movie

**Comment by adamosborne83** [comment]
Have you tried 'clear Metadata cache' in settings?

**Comment by Arthur1967** [comment]
Plus, it slows the app down

**Comment by umbrellaplug** [comment]
What is reason for this request? What's the purpose or intended result of refreshing the metadata of a single item? I'm trying to understand what this feature is intended to accomplish.

**Comment by Arthur1967** [comment]
The intended result would be to collect missing episodes just like the trakt website has

**Comment by Arthur1967** [comment]
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/69996032/221940d6-d900-4832-901e-f02636c7d0c9)

**Comment by Arthur1967** [comment]
It's no big deal it just saves people from going directly to trakt website to do it thank you

**Comment by Arthur1967** [comment]
I'll close it, but I saw it would be easier thank you
