### ISSUE TITLE
Question about how auto play works

### ISSUE THREAD

**Issue by keineahnungking** [umbrellaplug/umbrellaplug.github.io#367]
The scenario that I have is that I want to auto play a specific release of a tv show (for example one that has a specific audio language). I thought the way to achieve this was to add that release to my Real Debrid cloud. Even though that release is then shown at the top of the list when using rescrape -> source select, when using auto play it plays another release from an external scraper.
Is there a way to make Umbrella check only the cloud and not external scrapers when using AutoPlay?
Or can I change the AutoPlay behavior to always prefer Cloud sources?
Or is there another way to have it AutoPlay a preferred release?

Another issue that I'm having is that torrents show up as being in my cloud even though they actually are not there. Even though the setting to add resolved items to cloud is disabled, everything that I play once is shown as being in my cloud when using source select. However it doesn't actually add them to the cloud. When looking at the log it seems to send the magnet to cloud and then delete the torrent: pastebin.com/9PwpYTYm

I don't know if this the right place to ask these questions, let me know if there is a better way to contact you.

**Comment by keineahnungking** [comment]
So I noticed the problem is that Umbrella somehow actually adds all resolved torrents to the RealDebrid Cloud even though the setting is disabled. The files don't show up on my account but when I manually open the download link in my browser that Umbrella shows me when going to "Additional Link Info" I can access them. My auto play issues result from the fact that I can't delete those torrents that Umbrella automatically adds to the cloud because they don't show up in my account. So this seems like a bug with the Real Debrid integration.

**Comment by umbrellaplug** [comment]
> Is there a way to make Umbrella check only the cloud and not external scrapers when using AutoPlay?
Yeah, turn off the external provider. I wouldn't recommend that though as you'd only get cloud results.

> Or can I change the AutoPlay behavior to always prefer Cloud sources?
You could change the setting in source settings to terminate on cloud sources.

> Or is there another way to have it AutoPlay a preferred release?
No, autoplay is playing the first link in the list depending on your sorting.

> Another issue that I'm having is that torrents show up as being in my cloud even though they actually are not there. Even though the setting to add resolved items to cloud is disabled, everything that I play once is shown as being in my cloud when using source select. However it doesn't actually add them to the cloud. When looking at the log it seems to send the magnet to cloud and then delete the torrent: pastebin.com/9PwpYTYm

Everything you resolve is added to your real-debrid account under "My Downloads". That's how real-debrid works. Adding a pack or something to your real-debrid is not going to make it show as the first item when you try to scrape for an item or resolve. When you resolve a link, it's added to your cloud. That's what we are scraping, not every torrent you have in your torrents. You will need to access shows you add like that from the Premium Services > Real Debrid > Torrent Transfers.

> So I noticed the problem is that Umbrella somehow actually adds all resolved torrents to the RealDebrid Cloud even though the setting is disabled. The files don't show up on my account but when I manually open the download link in my browser that Umbrella shows me when going to "Additional Link Info" I can access them. My auto play issues result from the fact that I can't delete those torrents that Umbrella automatically adds to the cloud because they don't show up in my account. So this seems like a bug with the Real Debrid integration.

This is not a bug, this is literally the difference in the setting for Store Resolved Items in the Cloud. If you have that turned on the magnet will not be removed. You likely need to delete the files you're having issues with from real debrid. Login > Click Download at top > Click My Downloads on right menu. Delete anything you don't want from there.
