### ISSUE TITLE
Several bugs and Source Select request

### ISSUE THREAD

**Issue by Titan2313** [umbrellaplug/umbrellaplug.github.io#37]
I appreciate all the work you're putting into Umbrella and while I want to make Umbrella my default - because the results are much better and it's lightning fast - I have to fall back on Seren very often since I have some issues with it.

I use the latest Umbrella with Kodi Matrix on a Windows Platform with the new Artic Horizon 2 skin.

The bugs

1. Tools > Umbrella Scraper Settings is Empty when using the AH2 skin, it works in Ezra but not in Umbrella (no log errors but empty screen).

2. Not all of my Trakt Progress is added to My TV Shows > Progress. Most of the shows are there but some things are not and the entire show won't show up (even after a trakt resync without errors in the log, N.aruto Shippuden is a good example of this). These shows do show up in Seren so Trakt does pass them to kodi.

3. If I search for a show that's in progress but doesn't show up in the Progress menu the tracking will be messed up (example N.aruto Shippuden 80% watched on trakt only shows season 1 with a watched check in Umbrella, even after a resync). This works fine in Seren so Trakt does pass everything to kodi.

The requests

1. Seren allows you to source select with AutoPlay on. I miss this feature the most in Umbrella because the first option isn't always the best. Even if you set up filters the right way it doesn't always play the source I want and have to switch AutoPlay off. 
I have the biggest problem with playing Anime. It picks the best source but that means it could play a Sub while I want a Dub (there is unfortunately little dubbed Anime integration in Umbrella) or even a OVA pack that doesn't match. If you switch to Source Select, pick the right pack and switch back it also doesn't remember your choice like Seren so the next episode has the same issue.

If possible I hope you can add a feature that allows to AutoPlay shows but let you Source Select after each UpNext pop-up like in Seren.

2. Trakt doesn't live scrobble during playback. This has been suggested before and is a luxury request but I enjoy that feature a lot in Seren so I want to +1 it if you have the chance to add this.

Thank you very much for maintaining Umbrella. It is a great addon, with some of the best results.

**Comment by umbrellaplug** [comment]
1. Unaware of this. Umbrella scrapers will be removed in a coming update. I will make sure the new scraper settings work in ah2 before pushing that update.
2. Logs
3. Logs

Requests:
1. I will look into this. I can add a setting for it, but there's other work I need to do with the way playlist are passed to the player window from the plugin that will need to be done first.
2. Live scrobble is pretty low on the priority list for me honestly. It's on the list, but it's after several other things.
