### ISSUE TITLE
[Cache titles mismatched with actions in v6.6.56]

### ISSUE THREAD

**Issue by Goguma69** [umbrellaplug/umbrellaplug.github.io#370]
### Bug

You're probably aware of this already; but in the latest version (I think) 6.6.56 some of the 'Clear' function titles within "CACHE FUNCTIONS" are now mismatched with their actions/results... i.e. 

"CLEAR CACHE" now appears to clean the Fanart Cache

"CLEAR FANART CACHE" may/not clear the actual Cache, but the pop-up says it does

"CLEAR LIBRARY MOVIES CACHE" pop-up reports that the "Cache Successfully Cleared"; but it is unclear if that is the application cache, or really the library cache

(Admittedly, I'm too scared to mess the "CLEAR ALL CACHE" and "CLEAR METADATA CACHE" for fear of causing some irreparable harm to the installation, but maybe you could look at those as well...? 

### Expected Result

correction of the "clear cache" descriptors noted above with their subsequent action results, and possibly better clarity in the confirmation pop-up messages

### Steps To Reproduce

1. Go to TOOLS/CACHE FUNCTIONS
2. Click on "CLEAR CACHE", "CLEAR FANART CACHE" and "CLEAR LIBRARY MOVIES CACHE" to see the mismatched action/result v. pop-up dialogues

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Onn 4K/Google box running Kodi Nexus v21.0 (21.0.1)
Git: 202409-7e760d1063
Compiled: 2024-04-09

UMBRELLA v: 6.6.56

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
The only change made to cache clearing was made to allow for clearing the fanart database file that is built locally to store the artwork downloaded from fanart.tv. It was added for it's own setting and added to the clear all cache function. I'll change the confirmation messages, but just know that's only popups. Everything is working as expected.

**Comment by umbrellaplug** [comment]
Fixed in update.

**Comment by Goguma69** [comment]
Thank you and my apologies. Didn't mean to waste your time.

Sent from Proton Mail Android

-------- Original Message --------
