### ISSUE TITLE
[BUG] Anime Menu is broken, no results...

### ISSUE THREAD

**Issue by Hemicrusher** [umbrellaplug/umbrellaplug.github.io#375]
### Bug

Clicking on Anime > Movies gives zero results
Clicking on Anime > TV Shows results in Kodi freezing with the spinning circle.

### Expected Result

Not sure what the results should be, but other addons show Simkl Anime lists,

### Steps To Reproduce

1) Go to Anime > Movies = No results
2) Go to Anime > TV Shows = Kodi freezes for a minute, then returns to the Anime menu.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21 stable
ONN 4K Google TV

[Kodi Log File](https://pastebin.com/7yBr0ThJ)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Looks like yet another imdb change. Will be fixed in next update.

**Comment by Hemicrusher** [comment]
Fixed!

I appreciate the work you do!

Thanks!
