### ISSUE TITLE
Sorry. It's your "Favourite" pain in the ass again... 

### ISSUE THREAD

**Issue by Goguma69** [umbrellaplug/umbrellaplug.github.io#376]
I hope this doesn't trigger some kind of alarm and workflow that takes you off other tasks, but (FYI) I found a Program Add-on called "Order Favourites" from https://github.com/doko-desuka/plugin.program.orderfavourites
that works well in estuary and solved my stupid favorite sorting request from a few weeks ago. 

Credit where due. (Is Umbrestuary skin still a thing? I loved it, but can't find it anywhere anymore.)

Pax. 

J. Nichols

**Comment by umbrellaplug** [comment]
Umbrestuary is still a thing, but it's just fentastic with things modified for Umbrella. He's put most of those changes into Fentastic now. If you still want it, let me know and I'll attach a link.

**Comment by Arthur1967** [comment]
Can you attach a link so I can get it please? Thank you.

**Comment by umbrellaplug** [comment]
Umbrestuary should be available on the main repo now. You may need to update your repo for it to show.
