### ISSUE TITLE
[BUG] Search Movies by Actor is broken.

### ISSUE THREAD

**Issue by Hemicrusher** [umbrellaplug/umbrellaplug.github.io#377]
### Bug

Doing a search for an actor like Steve Martin returns random results. Many don't even list Steve Martin anywhere on IMDB. I also tested on a few other Venom based addons that I won't name and they all have this issue, so I did not attach a log, but I will if you need it.

### Expected Result

Search Movies by Actor should return a list of movies with the actor that was searched for.

### Steps To Reproduce

Go to "Search" > "Search Movie by Actor > Type "Steve Martin"

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21 running on a ONN 4K Google TV box

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Another IMDb change. I will remove this option.

**Comment by Hemicrusher** [comment]
> Another IMDb change. I will remove this option.

I had an issue and needed to reinstall Kodi and all addons. I just checked and the search by actor now works.

Have no idea why....but, since it is working maybe it does not need to be removed.

**Comment by Hemicrusher** [comment]
> Another IMDb change. I will remove this option.

If you got my last reply saying it works now after I did a reinstall of Kodi and my addons, just ignore it, since it is not working again....

Now when I look at Information for a movie, and click on the actor, it brings up a list of their movies....Is there a way to somehow use that hook or whatever in the Search Movies by Actor? Or use TMDB instead of IMDB?

Sorry if I am being a pest, I just like using Umbrella and appreciate the work you have done on it.

Thanks again!

**Comment by umbrellaplug** [comment]
I have replaced this with tmdb and I'm currently testing it.
