### ISSUE TITLE
[BUG] Internal Error while resolving source

### ISSUE THREAD

**Issue by Has3n** [umbrellaplug/umbrellaplug.github.io#378]
### Bug

Hi, as title says. Since today I get an umbrella error msg saying „internal error“ while I try to start a source. It does so while it says „resolving“ 

### Expected Result

The Episode to start playing

### Steps To Reproduce

I click the following: My TV Shows - Collection - Black Sails - S03 - XXVII

Same happens at any other Source, no matter if Movie or Series

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi v21
FireTV Stick HD
https://paste.kodi.tv/epazeqihim

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Real debrid is having issues.
