### ISSUE TITLE
Can I add a Chinese language interface

### ISSUE THREAD

**Issue by lear8168** [umbrellaplug/umbrellaplug.github.io#379]
### Feature

I am a Chinese user like your plugin very much, thank you for your selfless pay, I would like to recommend to friends, But no Chinese interface they feel very unfriendly hope that the technical team can choose a Chinese version of the interface, Thank you very much! My email address lear 8 @ 126.com

**Comment by umbrellaplug** [comment]
You're welcomed to create a Chinese translation file. strings.po
