### ISSUE TITLE
[BUG] 1 season shows dead

### ISSUE THREAD

**Issue by epidoma** [umbrellaplug/umbrellaplug.github.io#381]
### Bug

Sup man
After last update any shows with only 1 season wont open
like "the acolyte" and "Presumed inocent"

### Expected Result

..

### Steps To Reproduce

should be easy to reproduce
if not ill post logs or whatever.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

..

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Something to do with the flatten seasons setting. I'll check it out.

**Comment by epidoma** [comment]
Awesome man.
thanks

**Comment by umbrellaplug** [comment]
6.6.61 should have it fixed.
