### ISSUE TITLE
The TMDB API is not accessible

### ISSUE THREAD

**Issue by lear8168** [umbrellaplug/umbrellaplug.github.io#382]
### Bug

Please change the tmdb api to api.tmdb.org, which is not available in China. I switched to api.tmdb.org after testing and accessing it quickly

### Expected Result

Speed up tmdb poster loading

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

kodi22版

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This request is unclear. I'm not changing the tmdb api... what are you talking about?

**Comment by umbrellaplug** [comment]
no idea what this is about. already use the tmdb api.

**Comment by lear8168** [comment]
The default tmdb api address in the plug-in is not accessible in China, I tried to change the address to api.tmdb.org and the access is normal. Can the technical engineers add it to the subsequent upgrades?

**Comment by umbrellaplug** [comment]
This is in testing.
