### ISSUE TITLE
[FEATURE] Allow more than 25 titles to be displayed from IMDB Lists

### ISSUE THREAD

**Issue by daherlihy** [umbrellaplug/umbrellaplug.github.io#384]
### Feature

I have some IMDB lists with more than 25 titles in each, but when opening the lists in Umbrella, it's only showing the first 25 in accordance with the add-ons sort setting. 

Can this cap be lifted?

**Comment by adamosborne83** [comment]
Seems like IMDb changing their API's is going to be a full time job to keep on top of haha...

**Comment by umbrellaplug** [comment]
Use the setting in general for IMDb list limit.

**Comment by daherlihy** [comment]
Thanks for this however I changed the limit to the max value (250) but even after clearing the addon cache and Kodi's cache, it's still showing only 25 titles.

Tried on a couple of other devices and getting the same.

Perhaps this needs to be re-opened as a bug?

**Comment by umbrellaplug** [comment]
Nope. Just going to start removing all IMDb items. I'm tired of getting bugs for IMDb. I'll remove it

**Comment by daherlihy** [comment]
No worries at all mate, totally understandable. Thanks for looking into this.

**Comment by umbrellaplug** [comment]
You forgot to clear your cache after you changed the setting. I just checked and it works perfectly.

**Comment by daherlihy** [comment]
I've done as requested (i.e. changed the limit to 250, 240, etc.) and then cleared the cache on both the add-on and Kodi app. Still not showing me anymore than 25 titles unfortunately, so no idea what's going on.

I'd request you leave your addon with IMDB list access enabled though because very few other addons have it on at all and not all titles on IMDB are accessible on Trakt, etc. Even if it means me having to condense my list to less than 25 titles, I'm happy!

**Comment by umbrellaplug** [comment]
I understand your request. IMDb is making it harder and harder to scrape anything from their page. They want a lot of money for access to their api so they have made it hard for us to get around using it by putting a lot of javascript to prevent scraping. What i'm seeing here now is they only load the first 25 results on a request then use javascript to add the additional ones. Having a limit of only being able to be able to put 25 movies on a list is stupid in my opinion. I need to either find another way to do these or remove them.

Just giving you honest feedback here. I'd love to say "yeah, imdb will be supported" but it's unlikely. They're making it harder and harder.

**Comment by daherlihy** [comment]
Maybe you could keep IMDB support there but stress that it is "limited IMDB support/access", i.e. 25 titles max per list?
