### ISSUE TITLE
[Feature Request] Non trakt "In Progress" Umbrella+RD

### ISSUE THREAD

**Issue by shanestonk** [umbrellaplug/umbrellaplug.github.io#385]
### Feature

im on Android Tv with Kodi omega + umbrella + RD +
nimbus skin.

Hope umbrella+real debrid have "In Progress" for movie and tv shows function without trakt cos Trakt make my kodi+umbrella+ rd become very slow at loading many things. Probably make In Progress for movie and tv show using local storage not Trakt.

In Fen (fenlight) it already has the "In Progress" function without the need to install or add trakt account.

**Comment by umbrellaplug** [comment]
Then use fen.

**Comment by shanestonk** [comment]
> Then use fen. 

Can you share the method to hide the link "scraping" loading so fen dev can hide their "scrape" . the reason i love umbrella because your app can hide scrape and put it into loading umbrella logo or background. My android tv become very slow if i add trakt account with umbrella. i just need the "In Progress" (movie +shows)  function but probably local save not trakt save.

**Comment by umbrellaplug** [comment]
Yeah. I'll let him know.
