### ISSUE TITLE
[BUG] Umbrella freezes when navigating to "Next Page (2)" in My Movies>Collection

### ISSUE THREAD

**Issue by Hemicrusher** [umbrellaplug/umbrellaplug.github.io#386]
### Bug

Umbrella freezes when navigating to "Next Page (2)" in My Movies>Collection when there are exactly 20 movies in Collection. If there are 19 Movies, then the "Next Page (2)" does not show. If there are 21 Movies, then clicking on "Next Page (2)" takes you to the next page.

### Expected Result

"Next Page (2)" should not show when there are 20 Movies, which is the max for each page.

### Steps To Reproduce

There has to be exactly 20 Movies in "Collection".

Navigate to "Next Page (2)" in My Movies>Collection 
Click "Next Page (2)"
Umbrella freezes

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21
ONN 4K (2023)
[Link to Kodi Log File.](https://paste.kodi.tv/qaqajiwihi)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Well add some more movies or something... lol 

I'll see what I can find. Seems like a really low priority issue.

**Comment by umbrellaplug** [comment]
Can you please test with version 6.6.631 from the test repo and let me know if this resolves this issues for you?

https://umbrellakodi.github.io

**Comment by Hemicrusher** [comment]
> Can you please test with version 6.6.631 from the test repo and let me know if this resolves this issue for you?
> 
> https://umbrellakodi.github.io

That fixed it!

Thanks!!!!

**Comment by umbrellaplug** [comment]
Thanks for testing this. I'll close this issue out and the fix will be included in the next update.
