### ISSUE TITLE
[BUG] Scraping won't start from Trakt Series Watchlist on Xbox (Kodi 21.0)

### ISSUE THREAD

**Issue by tpaniaki** [umbrellaplug/umbrellaplug.github.io#388]
### Bug

Starting a new serie from my Trakt Watchlist won't scrape.

However, Long press -> Rescrape item starts as expected.

All other lists work fine. 

### Expected Result

Pressing play from first episode in series watchlist triggers the scrapping process.

### Steps To Reproduce

1. Go to your Trakt Series Watchlist on Xbox (21.0)
2. Select the first episode of a unwatched serie.
3. Witness the bug.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info
Kodi 21.0 on Xbox.
Umbrella 6.6.62

Log: https://paste.kodi.tv/utunepirix

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Unable to duplicate this issue. Do you have your default play action in kodi set to "info"?

**Comment by tpaniaki** [comment]
> Unable to duplicate this issue. Do you have your default play action in kodi set to "info"?

Yes it set to "Show Info". Setting to "Play" works.

**Comment by tpaniaki** [comment]
OK. However, not all playlists are affected that's why I doubted it was Kodi-related.

**Comment by umbrellaplug** [comment]
It's tv episode related with play next enabled.
