### ISSUE TITLE
[BUG] m2ts iteration picks the wrong file, results in "preview" playing from pack

### ISSUE THREAD

**Issue by ambulancePilot** [umbrellaplug/umbrellaplug.github.io#390]
### Bug

When trying to play from a pack of m2ts files, it picks the wrong one sometimes. When the torrent includes a preview file (usually a 10 - 12 minute file to show the quality of the rip), the preview file gets picked. No idea why.

### Expected Result

It should pick the largest file in the pack as that is usually the file that contains the movie.

### Steps To Reproduce

Scrape for the movie "Inside Out" using all providers and attempt to play the first result. It is a 55.56GB file from the "TERMiNAL" release group. It is a cache of m2ts files. The preview video will play.

https://paste.kodi.tv/dicacaheki.kodi

This is a log showing the wrong m2ts file playing.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

From what I can tell, this is happening because the first result is a collection of m2ts files. When the torrent is a collection of files, you can select which files you want to download. Each time someone selects a unique combination of files, it creates this as one variation of a cache of this magnet, which others can also now access without having to wait for download.

This movie has a cache available where the only file someone downloaded was the preview file. It's 0091.mt2s. Umbrella is selecting this cache. I am not sure why...

Thanks so much for your efforts. Take your time! I will look at it on the days I have time. I am running out of it this evening.

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This is a result of changes made recently to the titles filter to allow for more results. Torrentio sometimes returns these for different shows. Game of thrones is another good example. The benefit of more results outweighed the downfall of the incorrect files occasionally being played for episodes. This is a torrentio feature. Turning torrentio results off should resolve this mostly for you, but that's up to you.

**Comment by ambulancePilot** [comment]
The link is however coming from Bitsearch and it's for a movie, Inside Out.

I will try it with Torrentio and elfhosted disabled but I don't suspect that will fix it. I suspect the logic that determines which debrid cache to pick is slightly flawed. It is picking the 6 GB cache of a single file over the 55 GB cache with all the files for the same magnet for some reason.

**Comment by umbrellaplug** [comment]
I'm not going to be working with you on anything. I'd suggest using another addon.

**Comment by ambulancePilot** [comment]
You don't need to work with me.

If you're not interested in making your add-on better, that's fine. I'll try and figure it out myself and give you a solution. Up to you what you want to do with it. 

No idea where the attitude came from. Thought we were working together respectfully.

**Comment by umbrellaplug** [comment]
I don't want to deal with a person like you. It's pretty simple. Best of luck in whatever you do, but please find another addon to use. I don't want any more issues, comments, requests, or complaints from you. Your smug attitude and condescending comments are not anything I'm willing to deal with. I do this for free for love of the code and kodi, I'll keep doing what I'm doing. You need to find someone else to fuck with.

**Comment by ambulancePilot** [comment]
My comments have been nothing but respectful, and I'm not looking to fuck with you. Time and time again, I've told you I simply bring up issues because I believe they deserve to be fixed by virtue of their existence. 

Do you have some comments that you'd like to point out where I fucked with you? 

From my perspective, it's been a great working relationship. I brought an issue to your attention, you suggested a few things, I suggested a few things, we tested and figured out which solution was optimal and settled on it. 

What is your problem with that process? Are you unhappy that we fixed a bug in your code?
