### ISSUE TITLE
My trakt [liked lists] says nothing found

### ISSUE THREAD

**Issue by Faststreamer246** [umbrellaplug/umbrellaplug.github.io#391]
### Bug

The trakt liked list in the my tv shows section says nothing found but the trakt collection and other sections work fine, I've waited 24hrs to see if it would sync aswell as force sync but still doesn't work. If I go into settings --> trakt management and then liked lists it does show my liked lists. Any help appreciated. Thanks

### Expected Result

I expected it to show my trakt liked lists

### Steps To Reproduce

Go to my tv shows
My liked lists
And open that

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21 

### Checklist

- [x] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
No logs?

**Comment by Faststreamer246** [comment]
> No logs?

Sorry this didn't seem so much like a bug where a log was needed. If it is okay om your end them I'm fine to assume the issue is from trakt or something on my end. I dont get an error in kodi so didn't know that I could get a log? Please can you tell me how to get log. Thanks

**Comment by Faststreamer246** [comment]
https://github.com/user-attachments/assets/3be6de56-c5ba-4cda-b8c5-8513ad497209

Here is a video of the issue

**Comment by Faststreamer246** [comment]
Here is the log hopefully
http://paste.ubuntu.com/p/qVZpk6fxT5/

**Comment by adamosborne83** [comment]
> Here is the log hopefully
> http://paste.ubuntu.com/p/qVZpk6fxT5/

Log ideally needs to be in https://paste.kodi.tv/

Otherwise people need to log in etc.

**Comment by umbrellaplug** [comment]
It is working for me, but that doesn't mean there's not an issue. I'm not able to see those logs, I think I need to login or something. You can turn on logging for umbrella in the settings. Here's a link of how to turn those on. 

https://github.com/umbrellaplug/umbrellaplug.github.io#logs

Once you turn on logging try your list again then go to tools> logging and there's an option to upload log to pastebin right there in umbrella.

**Comment by Faststreamer246** [comment]
https://paste.kodi.tv/ewonuxezob

Is this okay? Thanks for the help

**Comment by umbrellaplug** [comment]
Yeah. Looking over them now. Nothing really standing out but I will see what I can find. I'm going to test and try liking some new lists and see if they show up or how long they take.

Stupid question but I have to check... do any of the lists you've "liked" have tv shows on them? Have you liked any tv show lists on trakt?

**Comment by Faststreamer246** [comment]
> Yeah. Looking over them now. Nothing really standing out but I will see what I can find. I'm going to test and try liking some new lists and see if they show up or how long they take.
> 
> Stupid question but I have to check... do any of the lists you've "liked" have tv shows on them? Have you liked any tv show lists on trakt?

Oh no.. I feel like the biggest idiot right now. My liked lists had movies not tv shows. I am so so sorry for the time I've wasted. Thank you so much for providing this addon. As someone that doesn't know the first thing about coding I don't know how you do it all but its truly amazing and again I'm really sorry.

**Comment by umbrellaplug** [comment]
No worries. Glad it was an easy one. Have a good day. I'm gonna mark this issue as completed now.
