### ISSUE TITLE
[BUG] itemes sometimes fail to play from RD cloud

### ISSUE THREAD

**Issue by lynx31** [umbrellaplug/umbrellaplug.github.io#392]
### Bug

Some items fail to play from RD cloud when it is selected as a source after scraping. Essentially the source in the cloud is selected but nothing happens. This only happens for some episodes. 

"Enable cloud scraper" is enabled under "Accounts (Debrid)"

### Expected Result

The source should play

### Steps To Reproduce

1. Open Kodi
2. Go to either "progress shows" widget or "progress episodes"
3. Select episode 
4. Select Real-Debrid| CLOUD as source

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi log: https://paste.kodi.tv/udexabelir.kodi
Umbrella log: https://paste.kodi.tv/cunubavilo.kodi

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This is due to spaces in the file name. I'll be pushing a fix for this later today.

**Comment by lynx31** [comment]
Thanks for such a quick reply and fantastic to hear that this will be fixed so soon! By the way, Umbrella also identified episodes incorrectly for this particular show (Paw Patrol). Is there a way to manually fix this through the addon? Thanks!

**Comment by umbrellaplug** [comment]
Unfortunately not. Umbrella doesn't do that. That would be from the scrapers and that's outside of my control.

**Comment by adamosborne83** [comment]
> Thanks for such a quick reply and fantastic to hear that this will be fixed so soon! By the way, Umbrella also identified episodes incorrectly for this particular show (Paw Patrol). Is there a way to manually fix this through the addon? Thanks!

Don't worry, kids soon grow out of paw patrol stage haha

**Comment by umbrellaplug** [comment]
Update has been pushed. Closing issue. Have a good one!
