### ISSUE TITLE
[BUG] Easynews streaming fails with error.

### ISSUE THREAD

**Issue by Hemicrusher** [umbrellaplug/umbrellaplug.github.io#394]
### Bug

Easynews sources fail to play and generate an error. This was first happening on my ONN 4K Google TV box, so I tested it on a clean Umbrella install in Kodi 21 on Win 10. 

### Expected Result

Easynews sources while slow to load, should play.

### Steps To Reproduce

Pick any movie or TV show and choose an Easynews source.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21 stable, Windows 10.

[KODI LOG FILE](https://paste.kodi.tv/fiyozagaju
)

Thanks!

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This is not really related to Umbrella. Once umbrella has passed the video off to kodi to play it's outside of my control.

```
2024-08-02 13:06:44.766 T:12752   error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x1801e086c60) Failed: Timeout was reached(28)
2024-08-02 13:07:14.775 T:12752   error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x1801d02b330) Failed: Timeout was reached(28)
```

That being said, let me give you a few suggestions that may help.
From your logs it looks like a curl timeout. You can set some advanced settings to change that.
https://kodi.wiki/view/Advancedsettings.xml#network

You could also check your easynews route and see if you can find a port or route that makes the connection a little faster or better for you.
https://members.easynews.com/route/

**Comment by Hemicrusher** [comment]
I did try changing the route in Easynews, but it did nothing. I will also look at advanced settings and setting the curl timeout. 

It's not even a big deal, as I only added Easynews as a backup to Real Debrid.... and since I already had an Easynews account, I figured I'd give it a try.

Thanks for all your help....feel free to close this.

Have a great weekend!

**Comment by umbrellaplug** [comment]
> I did try changing the route in Easynews, but it did nothing. I will also look at advanced settings and setting the curl timeout.
> 
> It's not even a big deal, as I only added Easynews as a backup to Real Debrid.... and since I already had an Easynews account, I figured I'd give it a try.
> 
> Thanks for all your help....feel free to close this.
> 
> Have a great weekend!

Cool. Don't forget to clear your provider cache in umbrella after changing your route in easynews. The links are cached and after changing your route you should get a new link so clearing the cache will make sure you are getting a new link from easynews using your new route after it's been set.

I will go ahead and close this out. Have a good weekend as well.
