### ISSUE TITLE
[BUG] Scraping won't work on any sources on Linux

### ISSUE THREAD

**Issue by tpaniaki** [umbrellaplug/umbrellaplug.github.io#395]
### Bug

Scraping can't be initiated.

### Expected Result

Scraping is initiated.

### Steps To Reproduce

1. Try to initiate a source on a Linux system.
2. Witness the bug.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21.0.0
Python 3.12.4
Umbrella 6.6.64
Cocoscrapers 1.0.23

Arch Linux

[Log](https://paste.kodi.tv/icitorovix).

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Works for me. No logs.

**Comment by tpaniaki** [comment]
> Works for me. No logs.

I linked the logs.

**Comment by umbrellaplug** [comment]
Yep. Sorry. See those now. You've got a whole lot of errors but I don't see any errors related to umbrella it looks like you make it into the play item function then something fails. You've got a huge amount of connect errors in your log but I'm not sure what those are for.

**Comment by tpaniaki** [comment]
> Yep. Sorry. See those now. You've got a whole lot of errors but I don't see any errors related to umbrella it looks like you make it into the play item function then something fails. You've got a huge amount of connect errors in your log but I'm not sure what those are for.

OK I'll investigate those. Thank you.

**Comment by mdmallardi** [comment]
Hi.  I too am having an issue when trying to scrape on Arch Linux with Python 3.12.  This started happening 2024-04-09, when Kodi was relinked against Python 3.12 (My apologies for reopening, but will gladly open a new one if you would rather.
[kodi.log.gz](https://github.com/user-attachments/files/17049316/kodi.log.gz)
