### ISSUE TITLE
[BUG] Trailers won't play from context menu (Play Trailer), but do from context menu (Information)

### ISSUE THREAD

**Issue by Hemicrusher** [umbrellaplug/umbrellaplug.github.io#398]
### Bug

Trailers won't play from context menu (Play Trailer), but play correctly from context menu (Information) with YouTube version 7.0.9 official. If I downgrade to 7.0.5+unofficial.1 included in Umbrella's repo, they play correctly in both context menu items.

### Expected Result

Trailers should play when choosing Play Trailer in the context menu.

### Steps To Reproduce

1) Pick a movie and open context menu, Play Trailer.
2) Nothing happens...no error displayed.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Using Kodi 21 on an ONN 4K 2023 

[Kodi Log File ](https://paste.kodi.tv/awamujamuq)

Thanks!

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
YouTube plugin issue. Umbrella just passing a url off to the plugin.

**Comment by Hemicrusher** [comment]
> YouTube plugin issue. Umbrella just passing a url off to the plugin.

So, is the only option to use an earlier version?

**Comment by Hemicrusher** [comment]
> YouTube plugin issue. Umbrella just passing a url off to the plugin.

BTW, why would it play when I choose Trailer in Information, and not directly when choosing Play Trailers in the Umbrella context menu?

**Comment by umbrellaplug** [comment]
Again....... this really doesn't have anything to do with Umbrella. Umbrella passes a command to the you-tube plugin to watch a trailer.
https://kodi.wiki/view/Add-on:YouTube

The command is being sent to the youtube addon.
