### ISSUE TITLE
[FEATURE] Progress Episodes - avoid episode thumb spoilers 

### ISSUE THREAD

**Issue by AdeHub** [umbrellaplug/umbrellaplug.github.io#399]
### Feature

In Arctic Horizon 2 or Arctic Fuse skins if you create a widget using Umbrella Progress Episodes then the default view is Landscape which shows an episode screenshot (episode thumb) and often contains spoilers

There's a Kodi setting Media->Videos->Show information for unwatched items->Episode thumb, turned on by default. The proposal is if this is turned off then use a different image instead of episode thumb, maybe season or fanart

Thanks

Edit: 

seems to work ok in Fentastic skin, i.e. Umbrella Progress Episodes as widget, Kodi Show information for unwatched items->Episode thumb, turned off

conversely in AF/AH2 skins it works with the default Add-on Next Episodes and also works with another popular Add-on

so is this something that could be changed in AF/AH2 skins or are they looking for a piece of information not set by Umbrella?

**Comment by umbrellaplug** [comment]
This is not a feature I'm interested in implementing at this time.
