### ISSUE TITLE
Mdblist Enhancement 

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#4]
I do not know if you are aware of it or not?

But, would it be possible to have the option to be able to add mdblist.com API into Umbrella to be able to access list that I create, I know the Dev is very willing to support and help and also, recently TMDBhelper has added it too.

**Comment by umbrellaplug** [comment]
Never heard of it till now. Do you know if there's an API already for it? What would be the purpose of it?

I'm asking because from a 20 second review of the page it looks like it's intergrated to Trakt. I can look into if it's something people are wanting. 

From what I understand, you can already import lists from Trakt. Seems like you would just make a list on mdblist, export to trakt, then import into plugin from trakt? Feel free to correct me. I honestly didn't do too much looking into this yet.

**Comment by adamosborne83** [comment]
> Never heard of it till now. Do you know if there's an API already for it? What would be the purpose of it?
> 
> I'm asking because from a 20 second review of the page it looks like it's intergrated to Trakt. I can look into if it's something people are wanting.
> 
> From what I understand, you can already import lists from Trakt. Seems like you would just make a list on mdblist, export to trakt, then import into plugin from trakt? Feel free to correct me. I honestly didn't do too much looking into this yet.

Yes already an API, As Jurial added it quite easy, so personally my main reason for preferring it over Trakt at present, is since trakt change the amount of movies etc per list, it has became a little restricted.
mdblist allows you to create lists of any spec and size.

**Comment by umbrellaplug** [comment]
> > Never heard of it till now. Do you know if there's an API already for it? What would be the purpose of it?
> > I'm asking because from a 20 second review of the page it looks like it's intergrated to Trakt. I can look into if it's something people are wanting.
> > From what I understand, you can already import lists from Trakt. Seems like you would just make a list on mdblist, export to trakt, then import into plugin from trakt? Feel free to correct me. I honestly didn't do too much looking into this yet.
> 
> Yes already an API, As Jurial added it quite easy, so personally my main reason for preferring it over Trakt at present, is since trakt change the amount of movies etc per list, it has became a little restricted. mdblist allows you to create lists of any spec and size.

I'm all about options. I'll check with the Developer about getting access to his api and start working on it.

**Comment by adamosborne83** [comment]
Know you chatted to the dev yesterday, is this possible or unlikely? Haha...

**Comment by umbrellaplug** [comment]
![Screen Shot 2022-07-02 at 11 47 12 AM](https://user-images.githubusercontent.com/107957815/177009276-f43b5cd5-0665-45d6-a3ff-49658b30692c.png)
![Screen Shot 2022-07-02 at 11 47 53 AM](https://user-images.githubusercontent.com/107957815/177009279-b8701509-47ba-459b-a4d7-4ba2a0bd2312.png)


in progress.....

**Comment by adamosborne83** [comment]
All works fine. Cheers
