### ISSUE TITLE
Tmdb Api key

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#40]
In the old version With my accounts I could get it to authorize fine but with this new version tried numerous times any suggestions and there would be no log for it since there is no error thank you

**Comment by umbrellaplug** [comment]
A lot of was changed with this last update, I will check on this.

**Comment by Arthur1967** [comment]
OK thank you because I really like your ad on I did try it with another
add-on and it works fine with other ones thank you for all the work you put
into this

**Comment by Arthur1967** [comment]
I see you fixed it I will try it when I get home from work thank you I will close this now
