### ISSUE TITLE
[BUG] when i try play my next episode in the progress episode widget it doesnt play the stream

### ISSUE THREAD

**Issue by Faststreamer246** [umbrellaplug/umbrellaplug.github.io#400]
### Bug

When I click the next episode in the widget I get the source list fine however when I try to play a source it doesn't play. 

But then if I try again it does play. So a bit of an odd issue.

Note that if I have just opened kodi it plays fine the first time so seems to be occurring when it's not the first time I'm playing something since kodi has been open.

I leave kodi open in the background often as then I don't need to reload my widgets every time and clicking the episode twice to play it isn't terrible. Still faster than loading kodi again

I am using fentastic in case its of relevance.

### Expected Result

I'd expect it to play the source first time

### Steps To Reproduce

Go to the episode in the play next widget and click the source. It doesn't load the first time if it's not the first thing you are watching since kodi has been open

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Log is:
https://paste.kodi.tv/wolixaluje

Kodi V 20
Thanks

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I don't see any errors in your log. I'm unable to duplicate the behavior on my setup. Have you rebooted your kodi?

**Comment by Faststreamer246** [comment]
> I don't see any errors in your log. I'm unable to duplicate the behavior on my setup. Have you rebooted your kodi?

Okay due to the fact this is fine when I open kodi for the first time / reboot I'll put it down the a kodi or skin issue. Or maybe the widget not reloading properly the first time I try the source.

Thanks for the fast reply it's a little shame but not too bad. The addon is still amazing and I'm sure this issue probably isn't due to umbrella

**Comment by umbrellaplug** [comment]
I should clarify, I don't see any Umbrella errors in your log. Your log does have errors though. Looks like "script.module.slyguy" Have you thought about maybe upgrading to a newer version of kodi? Another thing to check would be your kodi settings. Please go to kodi settings and clear any settings set for "Play next video automatically". This is likely been set to "Episodes" previously by Umbrella.

**Comment by Faststreamer246** [comment]
> I should clarify, I don't see any Umbrella errors in your log. Your log does have errors though. Looks like "script.module.slyguy" Have you thought about maybe upgrading to a newer version of kodi? Another thing to check would be your kodi settings. Please go to kodi settings and clear any settings set for "Play next video automatically". This is likely been set to "Episodes" previously by Umbrella.

Oh okay. I'll try that. As for the other error thanks for bringing it to my attention because I know you didn't have to. I think it may be something to do with iptv merge perhaps but I don't use it anyway just installed a while back so I'll leave it be. I think I am on version 21 actually.

**Comment by umbrellaplug** [comment]
You are on version 21. They pushed 21.1 earlier this week with a lot of bug fixes.

**Comment by Faststreamer246** [comment]
> You are on version 21. They pushed 21.1 earlier this week with a lot of bug fixes.

Thanks for confirming. If i update will i lose my setup? I can't backup on my onn box unfortunately so may just deal with the issue.

**Comment by adamosborne83** [comment]
> > You are on version 21. They pushed 21.1 earlier this week with a lot of bug fixes.
> 
> Thanks for confirming. If i update will i lose my setup? I can't backup on my onn box unfortunately so may just deal with the issue.

No, all settings and addons will stay the same.

**Comment by Faststreamer246** [comment]
> You are on version 21. They pushed 21.1 earlier this week with a lot of bug fixes.



> I should clarify, I don't see any Umbrella errors in your log. Your log does have errors though. Looks like "script.module.slyguy" Have you thought about maybe upgrading to a newer version of kodi? Another thing to check would be your kodi settings. Please go to kodi settings and clear any settings set for "Play next video automatically". This is likely been set to "Episodes" previously by Umbrella.

How do I clear the setting? Do I set to uncategorized. Thanks

**Comment by umbrellaplug** [comment]
When you open the setting it will show a list. Any in the list that are highlighted are currently turned on. The only setting that Umbrella sets here would be "Episodes" as long as that is not selected you should be getting the normal behavior.
