### ISSUE TITLE
[FEATURE] Allow Disabling of 'Use Custom Umbrella Dialogs' after latest update to 6.7.0

### ISSUE THREAD

**Issue by jmh2002** [umbrellaplug/umbrellaplug.github.io#401]
### Feature

I note that in the Change Log that updates were made to the 'Scraping and Progress Windows' but this also seems to have prevented Disabling 'Use Custom Umbrella Dialogs' in settings. (the setting is still there, but it no longer seems to work).

I would be pleased if the Disabling 'Use Custom Umbrella Dialogs' feature can still be functional as the custom dialogs don't seem to work well or look nice with the skin that I use (Xonfluence on Kodi v21).

Thanks :)

**Comment by umbrellaplug** [comment]
Yeah, these were removed. I will re-add the default prompt for scraping and resolving in the next update.

**Comment by jmh2002** [comment]
Thanks! :)

Should I go ahead and close this issue or will you close it when you do the update?

**Comment by umbrellakodi** [comment]
Update inbound.
