### ISSUE TITLE
[BUG] Dedicated mdblist user lists only shows first 20 items on the list

### ISSUE THREAD

**Issue by IamJanarthan** [umbrellaplug/umbrellaplug.github.io#403]
### Bug

Using mdblists via providing its API key in the settings only shows first 20 files from the list, there is no next page button too,
but when I use it via trakt linked lists it shows all files in single page.

"The pagination setting didn't work and the increasing the page item limit also didn't worked for this."

### Expected Result

mdblist user lists needs a next page button or a single page containing all items from the list

### Steps To Reproduce

1.Add your mdblist API to umbrella in settings
2.Locate to My Movies/Shows -->mdblists user lists
3.Open your list created in mdblist
4.Notice how it only shows first 20 items from the lists

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

1.Kodi V21.1 (Desktop version)
2.Artic fuse latest version

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Found the issue, next update will have this fixed.

**Comment by adamosborne83** [comment]
Working fine 🙂
