### ISSUE TITLE
Very large 4k files after movie search

### ISSUE THREAD

**Issue by onthatb0mbshell** [umbrellaplug/umbrellaplug.github.io#405]
### Bug

Hi, 
Hopefully posting in the correct area.
When searching for a movie I'm getting limited options, the options I do get are mostly very large 4K files, even if there is a lower resolution file it will still be very large, into the 10s of GBs. All results are by Bitsearch.

### Expected Result

Many more file options, with a choice of resolution and file size.

### Steps To Reproduce

Open umbrella.
Movie search
Type name
Search
Files returned.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21.1
Fire stick 4k
![17265037399553065324818688635864](https://github.com/user-attachments/assets/c8368406-7fea-494b-b8e5-54641877f598)
https://paste.kodi.tv/ocazobapac
I've checked settings but couldn't see anything wrong, uninstalled and reinstalled umbrella also.

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by adamosborne83** [comment]
> ### Bug
> 
> Hi, 
> Hopefully posting in the correct area.
> When searching for a movie I'm getting limited options, the options I do get are mostly very large 4K files, even if there is a lower resolution file it will still be very large, into the 10s of GBs. All results are by Bitsearch.
> 
> ### Expected Result
> 
> Many more file options, with a choice of resolution and file size.
> 
> ### Steps To Reproduce
> 
> Open umbrella.
> Movie search
> Type name
> Search
> Files returned.
> 
> ### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info
> 
> Kodi 21.1
> Fire stick 4k
> ![17265037399553065324818688635864](https://github.com/user-attachments/assets/c8368406-7fea-494b-b8e5-54641877f598)
> https://paste.kodi.tv/ocazobapac
> I've checked settings but couldn't see anything wrong, uninstalled and reinstalled umbrella also.
> 
> ### Checklist
> 
> - [X] I have included logs and the version of Kodi I am using..
> - [X] I have made a separate issue for each bug that I am reporting.
> - [X] I have verified this is not a setting.

Have you tried changing the file size limit?


![firetv_2024-09-16_17_37_49.jpg](https://github.com/user-attachments/assets/6aadeffe-27e1-4fa7-b3a9-d4e33e95485c)

**Comment by onthatb0mbshell** [comment]
Scraping only produces 12 results, so changing the file size limit won't help in this case, I can long press on the movie I want to scrape and I can get the optional menu and choose rescrape option, when I do this I get well over 100 file options ranging in file size and resolution.

**Comment by adamosborne83** [comment]
> Scraping only produces 12 results, so changing the file size limit won't help in this case, I can long press on the movie I want to scrape and I can get the optional menu and choose rescrape option, when I do this I get well over 100 file options ranging in file size and resolution.

When you rescrape, do you rescrape with all providers? 
If so, have you checked what providers you have set up by default in CoCo scrapers?

**Comment by onthatb0mbshell** [comment]
I done a complete uninstall and reinstall , so it's default at the moment, I've never made any changes within CoCo scrapers

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by umbrellaplug** [comment]
The logs provided are from Kodi and are not with debug enabled. This seems like a scraper issue, but I'm willing to at least look over what's happening if you can provide logs. Steps for how to enable the logging in umbrella can be found here:

https://github.com/umbrellaplug/umbrellaplug.github.io#logs

My experience installing fresh on a portable install with coco scrapers, real debrid, and umbrella gave me over 80 results for batman.

**Comment by onthatb0mbshell** [comment]
Hi, I uninstalled and reinstalled COCO scrapers, this seems to have
resolved my issue, so I'm guessing a change had been made within it that
was messing up my scrape results. Thanks for all input 👍

**Comment by onthatb0mbshell** [comment]
Reinstalled COCO scrapers and issue has been resolved. Thanks
