### ISSUE TITLE
Play Next repeats final episode

### ISSUE THREAD

**Issue by npmstart-pray** [umbrellaplug/umbrellaplug.github.io#406]
This just happened and I'm guessing it's the addon rather than the nimbus skin- was watching tv series that only has 2 episodes released, and at the end of the 2nd, I got a Play Next dialog. It wanted to (and did, when I selected Play) play the episode I just finished watching, the 2nd of 2 that have been released. I'm guessing it's a bug, because it works otherwise.

**Comment by umbrellaplug** [comment]
No logs, very little information, no steps to duplicate the issue, and opened an issue instead of using the bug reporting template.

**Comment by npmstart-pray** [comment]
Described the occurrence.  Doubt it could be replicated. Probably a metadata hiccup or some other strangeness that wouldn't appear in a log because there wasn't a crash of anything...I posted in case anyone had similar and could explain where the issue was, be it this addon, play next, kodi...

**Comment by adamosborne83** [comment]
> Described the occurrence.  Doubt it could be replicated. Probably a metadata hiccup or some other strangeness that wouldn't appear in a log because there wasn't a crash of anything...I posted in case anyone had similar and could explain where the issue was, be it this addon, play next, kodi...

Logs don't just show crashes, they show a whole host of information that would allow, the error, if there was one to be seen
