### ISSUE TITLE
[BUG] Finish watching context menu in widget

### ISSUE THREAD

**Issue by Liquidrag** [umbrellaplug/umbrellaplug.github.io#407]
### Bug

Is there a way to get the "unfinished progress manager - episodes" to show up from the homescreen widget? It shows within Umbrella. 

### Expected Result

"unfinished progress manager - episodes" shows as an option from the homescreen widget

### Steps To Reproduce

1 set "finish watching" as a widget
2 context menu>trakt manager> "unfinished progress manager - episodes" does not show as an option

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

I'm running kodi 21.1 on a mac, shield, and onn box, and they all behave the same way across platforms.
Here's a log, I hope I did it correctly. https://paste.kodi.tv/tanofekuke.kodi

Context menu from widget
<img width="1441" alt="Screen Shot 2024-09-18 at 11 13 28 AM" src="https://github.com/user-attachments/assets/2560bf9f-18ad-4b05-95ec-21798e44e26a">
Context menu from within umbrella
<img width="1437" alt="Screen Shot 2024-09-18 at 11 12 48 AM" src="https://github.com/user-attachments/assets/53ae5cd6-7ed9-4839-b005-c01580592cc3">

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by Liquidrag** [comment]
I've [mentioned](https://github.com/kodifitzwell/repo/issues/15#issue-2534154114) it to the Infinity dev and he has fixed it for infinity, I know you guys have collaborated before so maybe you can grab the fix from him?

**Comment by umbrellaplug** [comment]
You should use infinty.
