### ISSUE TITLE
Getting error as The caller does not have permission whil trying to play youtube videos 

### ISSUE THREAD

**Issue by ksadda77** [umbrellaplug/umbrellaplug.github.io#409]
### Bug

Hi Team,
I am getting error as 'The caller does not have permission' while trying to play youtube videos. Pls help.

### Expected Result

Error should not come 

### Steps To Reproduce

-

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Error should not come

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This has absolutely nothing to do with umbrella.
