### ISSUE TITLE
Adding clearart for Nimbus

### ISSUE THREAD

**Issue by derrgoo** [umbrellaplug/umbrellaplug.github.io#410]
### Feature

I talked with Nimbus dev and we can’t see clearart available in Umbrella. Any possibility to add this feature. This is an example below. Thank you!

![IMG_9640](https://github.com/user-attachments/assets/8e29a0b5-1eb2-4f3b-811b-d70ae5c63116)

**Comment by umbrellaplug** [comment]
No

**Comment by derrgoo** [comment]
No problem. Love your add on.
