### ISSUE TITLE
TV episode widget play icon

### ISSUE THREAD

**Issue by Ade-AV** [umbrellaplug/umbrellaplug.github.io#412]
### Bug

Hi

After Resolving and before playing there used to be a little Play icon appear on the widget Episode, this seems to have disappeared in a recent release, it's there for Movies but not Episodes. This is in Arctic Fuse

The icon is there in v6.6.62 but not v6.7.1

Any chance we can bring it back please?

Thanks

### Expected Result

As above, Play icon to show

### Steps To Reproduce

In Arctic Fuse create a Widget group over e.g. Next Episodes

Settings in Umbrella are for Background Dialog and Auto Play

Play Episode

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

21.1 let me know if you need logs

This is the Movie Play icon:

<img width="133" alt="Screen Shot 2024-10-03 at 2 40 11 PM" src="https://github.com/user-attachments/assets/8a0cf04d-9ff0-49bd-ba29-1828fb2f3c00">

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This is related to skin.

**Comment by Ade-AV** [comment]
Thanks, I created an issue on AF2 and got this response

"Nothing to do with the skin. I cannot help you with third party players for banned addons."
