### ISSUE TITLE
Only 1 page when listing Year (IMDB) for any year

### ISSUE THREAD

**Issue by jjzbird** [umbrellaplug/umbrellaplug.github.io#413]
### Bug

I love Umbrella, but noticed a bug for several months now.  After opening Umbrella when going to Discover Movies, then Year IMDB it doesn't matter when year I choose there is never an option at the bottom to go to page 2.  This works when going to Year TMDB.  I really like movies by year from IMDB.  

### Expected Result

Would love to be able to go to multiple pages of movies again after going to Discover Movies then Year IMDB.

### Steps To Reproduce

1.  Go to Discover Movies
2.  Go to Year IMDB
3. Select any year
4. Scroll to the bottom there is no option to go to page 2.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21.1 on Nvidia Shield.

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
This is not a bug. IMDb has made their website difficult to scrape recently to try to force people to pay for their api. It's over 150k a year. There will not be a next button on any IMDb lists in the addon. You can increase the number of items returned by changing the setting in settings: General.

**Comment by jjzbird** [comment]
Thanks for the fast response.  That is too bad, but I understand.  I have looked in the addon settings under general can't get more than 20 results.  Not sure what exact setting you are talking about, but I've looked around under general.

**Comment by stathis95194** [comment]
> Thanks for the fast response. That is too bad, but I understand. I have looked in the addon settings under general can't get more than 20 results. Not sure what exact setting you are talking about, but I've looked around under general.

Probably this one?

![image](https://github.com/user-attachments/assets/911fe455-69bc-43e5-b6df-735c82cbeb8e)
