### ISSUE TITLE
Trakt don't mark as watched 50% of the time

### ISSUE THREAD

**Issue by WALAO-WEI** [umbrellaplug/umbrellaplug.github.io#416]
### Bug

Like I said, I use some widgetor shorcut on my main page to access my progress épisode and watchlist.  50% of the time when I finish the serie or movie I don't see on the top left corner umbrella trying to mark as watched the series or movies I just finish.
the bug start around 3 weeks ago.  I roll back to a different build, remove umbrella and reinstall everything, clear cache in umbrella and clear cache kodi without success.

### Expected Result

Just want to know if the problem is on my side.  if it's the case, I will start a fresh new kodi.

### Steps To Reproduce

no step really.  from my main page I click on my shortcut and I acces progress episode and watchlist to play what I want to watch.  When I click on stop (at the end of the movie or serie I am all the time at 95% of more (i'm doing exactly the same than usual for the last 2-3 years with umbrella).
I have another problem and maybe it's related or not.  but each time I transfer my build on my both box from my computer I have to reinstall inputstream adaptive manually to be able to see the trailer.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

kodi 21.1, on fire cube (v2), my computer and a beelink gt (happen everywhere but didn't test a lot on PC).  
I use Xonfluence last version.  I included a picture of my setup.  And also 3 different umbrella log from 3 different day and box.  I will include also 1 kodi log in case you need it. 
![umbrella help](https://github.com/user-attachments/assets/1b677b1a-5084-4cd5-83d6-4e6dbfec12e8)

umbrella log
https://paste.kodi.tv/woliyugite
https://paste.kodi.tv/ibixowiwil
https://paste.kodi.tv/nevajozaqi

kodi log
https://paste.kodi.tv/edaxaluqex

I have a very good stable internet.  I use real debrid, the only thing I want to know is if it's on my side.  if it's the case, I will delete everything.  

One last thing, I'm able to marked them as watched manually but sometime when I do it, the day after when I open kodi they are not anymore mark as watched.

Thank you

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by adamosborne83** [comment]
Oh, my sweet lord. With that amount of errors, I'm surprised your console has not self destructed on you.

The log clearly shows an error getting to the trakt site.
Have you tried revoking authorisation, clear cache, restart device and connect to trakt again.

Also, what % do you have set for Umbrella to mark it as complete? Have you tried a lower amount? Maybe 80%.

**Comment by WALAO-WEI** [comment]
Yes I saw that earlier all the error than I have... I do build for different people in French.  Some addon don't exist  anymore in French and I had to remove them but look like uninstall was not working properly in that case.   The fact also than I take the setting for the last 5 years than I drag to all new version of kodi didn't help really maybe.  I did a lot of change in the paste with texture tools (4-5 years ago)  but I didn't do for kodi 21.  it's maybe a good idea to start back fresh.  for umbrella i'm at 75%.

**Comment by adamosborne83** [comment]
Look, trust me I'm not one who can criticise, as I usually copy the UserData folder over to save me time, but it your case. Just blow it up and start again.

**Comment by WALAO-WEI** [comment]
Yup, that's exactly what I was doing.. but maybe I did a little too much :).  it's suck to start from begining but sometime no choice :)

**Comment by adamosborne83** [comment]
Sometimes, script etc can change and then causes errors, if youve been doing it for as long as you've mentioned, defo start again.... book a week off just for umbrella settings 😀

**Comment by WALAO-WEI** [comment]
I know .. umbrella have so much option.  But in the same time I will install my old setup and check on the TV the way I did it and I will do everything on my computer.  save time, no mistake and I will be sure to have everything the same than I like.  I just use umbrella I don't want to lose all my setup loll.

**Comment by WALAO-WEI** [comment]
Thank you adamos for your time ... your answer is exactly the next step I wanted to do ... not a fun one but no choice lolll ;)
