### ISSUE TITLE
No stream available 

### ISSUE THREAD

**Issue by Faststreamer246** [umbrellaplug/umbrellaplug.github.io#417]
### Bug

So when choosing an episode the scraper dialogue shows that it's searching and actually finds links

But then after scraping it says no stream found

The only way to watch the stuff is to keep scraping until eventually the screen that's shows the links appears.

I'm not the only one with the issue as evidenced here:

https://www.reddit.com/r/Addons4Kodi/s/qGS1RFbYlq

And in the linked post within my post above 

Any help much appreciated sir

### Expected Result

I expect that after scraping I can choose the link I want.

### Steps To Reproduce

Choose an episode to watch and scrape for it.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi V20

This issue is also happening on fenlight suggesting real debrid and cocoscrapers are the 2 most likely culprits

However in my post at the end the part about trakt may be relevant surprisingly

There isn't a log yet, the other post within mine has a log and I'll try get one asap

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Without a log I'm going to be pretty useless.

**Comment by Faststreamer246** [comment]
> Without a log I'm going to be pretty useless.

Yeah I get that. No worries I'll try add the log when I can. If you read my reddit post and check the linked post within there is a log that may or may not be helpful

I'm surprised at how many people have only now mentioned they are having the issue to be honest - I thought it was only me

Definitely will try contact the cocoscrapers dev but struggling to figure out how - perhaps you know?

Anyway I'll get back to you with a log hopefully! Thanks so much

**Comment by Faststreamer246** [comment]
So I closed kodi and reopened and can't get the issue to occur now! I definitely don't think it is resolved given how intermittent the issue is so if I run into it again I'll then post a log.

If you could perhaps not close this issue for a day or 2 and I'll update tommroow I'd appreciate it

I will try encourage the people who commented on my posy saying they had the issue to post their logs - they probably won't but we can try

Thanks

**Comment by Faststreamer246** [comment]
Spoke too soon. Issue has occurred. Let me get the log

**Comment by Faststreamer246** [comment]
Am being told logging isn't enabled but is. Struggling to get the log

**Comment by Faststreamer246** [comment]
https://paste.kodi.tv/ihopihuxoy

Hopefully this works?

Thanks. The issue didn't happen for the first 5 ish eps I tried scraping. Then after maybe 2 to 3 mins it happened.

**Comment by Faststreamer246** [comment]
Should add I'm having to use a kodi fork for a seperate reason it's called wonderbox so in the log if you can ignore that then it may make life easier.

**Comment by umbrellaplug** [comment]
Can you turn on logging in coco scrapers and get a log from there so I can forward over to Joe?

**Comment by Faststreamer246** [comment]
I shall try and do this later. Thanks for the reply. Tikipeter is almost fully certain the issue is with RD, however one user has said that downgrading the cocoscraper version has fixed the issue for them.

Either way the issue almost certainly isn't with your addon or FEN. I'll try get that log when possible

**Comment by umbrellaplug** [comment]
Thanks. I've not had the issue myself but I'll see what I can figure out to help. I'm wondering if it's one of the new scrapers or some changes that were made for pack scraping recently in coco.

**Comment by Faststreamer246** [comment]
> Thanks. I've not had the issue myself but I'll see what I can figure out to help. I'm wondering if it's one of the new scrapers or some changes that were made for pack scraping recently in coco.

Oh okay that does sound like a decent shout. I didn't see any recent update to cocoscrapers which was making me inclined to rule out the issue but I really know nothing so I'll get that log to you and let you have a look! I'm sure it will mean much more to yourself. Appreciate the way you always look into stuff and give up your time. Thanks so much

**Comment by Faststreamer246** [comment]
https://paste.kodi.tv/ibikatutuq

Here is the cocoscrapers log I think. Let me know if its what your after.

**Comment by Faststreamer246** [comment]
https://paste.kodi.tv/kutavarulo

I grabbed another after trying some more episodes of shows. They worked until I tried a few more episodes and then next time I got the no stream I got this cocoscraper log

It was for a show that 100% will have links (severance which is super popular) so no available links definitely isn't a reason for the error seen in the log.

**Comment by Faststreamer246** [comment]
I suspect the timeout error seen is because the bitsearch scraper in coco is down. When that happens after 8 seconds the scraper does timeout and just gives the links it finds. But with this issue it finds links but then says no stream available

**Comment by umbrellaplug** [comment]
I apologize I'm standing in a river fishing today so I'm looking at all this from my phone. That first coco log was not what I was expecting. I thought there would be more errors or exceptions. Sorry to keep asking for stuff but if you could see coco and umbrella to both debug logs and to set to kodi log then once you get the error again send that kodi log that would be super helpful to see where it's failing.

**Comment by Faststreamer246** [comment]
https://paste.kodi.tv/udinapiguc

Maybe this? It's the kodi log and I set both umbrella and coco to kodi log in their respective debug pages in settings.

If its no good let me know but no rush to look at it.

Please just enjoy your fishing and break from all this - I hope you catch something good.

Thanks again

**Comment by TwilightMercy** [comment]
I've tested myself with old coco scrapers version (1.0.23) - experienced same issue

**Comment by Faststreamer246** [comment]
> I've tested myself with old coco scrapers version (1.0.23) - experienced same issue

Thanks for that confirmation mate. I don't really think it is a cocoscraper issue to be honest but if the dev can see the log I'm sure it would be good to confirm one way or the other

**Comment by umbrellaplug** [comment]
Should not have pointed me to a reddit thread involving u/RevolutionaryHole69

Closing this. I won't be looking into this at all. Hopefully that piece of shit can get AI to fix it for him. I will not work on anything related to that guy. If he's having issues... GREAT. maybe he'll use another addon and stfu.
