### ISSUE TITLE
Slow continuous playback error in Kodi

### ISSUE THREAD

**Issue by Sawatter** [umbrellaplug/umbrellaplug.github.io#42]
Hello!

Your add-on is amazing.  Thank you for the work you are doing and the quick updates so that we can watch content, I appreciate you!

I use Real-Debrid and am having issues with larger movie files and constantly get buffering and the continuous "slow" playback error in Kodi.  I have a very fast internet connection and the same size files will work in other addons.  

I am not sure what I am doing wrong, but I thought I would pass this along in case you are hearing the same reports from other users.

Thank you!

**Comment by umbrellaplug** [comment]
Thanks for the heads up. I'll look into this. I have real debrid as one of my services also. Is there a particular movie you can give me that did this to you that I can try to duplicate the issue?

**Comment by DoctorWhookah** [comment]
I had the same thing happen yesterday while watching Harley Quinn (don't judge me) via Real Debrid. It was the first choice in the list of streams and in the neighborhood of 4GB. I am running the latest version, or what was latest at the time, .57.

**Comment by umbrellaplug** [comment]
Try it out today with the latest update with the new scrapers. I haven't had any issues today in my testing. I was using Rome Season 1.

**Comment by umbrellaplug** [comment]
@DoctorWhookah Ayyyy, just noticed that username. So looks like update fixed osmc for you?

**Comment by DoctorWhookah** [comment]
@umbrellaplug It did resolve that issue, thank you! I just updated the repository and app to .59. I’ll test it out.

**Comment by Sawatter** [comment]
> Thanks for the heads up. I'll look into this. I have real debrid as one of my services also. Is there a particular movie you can give me that did this to you that I can try to duplicate the issue?

Thanks for the quick reply and apologies for me being slow, it was a long day.  I'm using 6.5.58. No other scraper setting was chosen outside of just authorizing Real Drbrid.

The movie is Jurassic World Dominion. 

- There is a 45.2 GB movie, the name ends in "animestotais.xyz", gives me issues, buffers, slow continuous playback error
- I tried the 30 GB move that ends in "x265.mp4" same issues as noted above

**Comment by umbrellaplug** [comment]
> > Thanks for the heads up. I'll look into this. I have real debrid as one of my services also. Is there a particular movie you can give me that did this to you that I can try to duplicate the issue?
> 
> Thanks for the quick reply @umbrellaplug and apologies for me being slow, it was a long day.
> 
> I have a 500 Mbps internet connection. I'm using Kodi 19.4 on the Nvidia Shield Pro using wifi with Umbrella 6.5.58. No other scraper setting was chosen outside of just authorizing Real Drbrid.
> 
> The movie is Jurassic World Dominion.
> 
>     * There is a 45.2 GB movie, the name ends in "animestotais.xyz", gives me issues, buffers, slow continuous playback error
> 
>     * I tried the 30 GB move that ends in "x265.mp4" same issues as noted above
> 
> 
> Also, how do I get the update to .59? I see no update for it yet and tried a version check and re-installing Umbrella

6.5.69 should be available on the repo now. You may need to manually install it as the dependencies have changed from umbrellascrapers to cocoscrapers.

**Comment by psp2111-ADSLGATE** [comment]
> > Thanks for the heads up. I'll look into this. I have real debrid as one of my services also. Is there a particular movie you can give me that did this to you that I can try to duplicate the issue?
> 
> Thanks for the quick reply @umbrellaplug and apologies for me being slow, it was a long day.
> 
> I have a 500 Mbps internet connection. I'm using Kodi 19.4 on the Nvidia Shield Pro using wifi with Umbrella 6.5.58. No other scraper setting was chosen outside of just authorizing Real Drbrid.
> 
> The movie is Jurassic World Dominion.
> 
> * There is a 45.2 GB movie, the name ends in "animestotais.xyz", gives me issues, buffers, slow continuous playback error
> * I tried the 30 GB move that ends in "x265.mp4" same issues as noted above
> 
> Also, how do I get the update to .59? I see no update for it yet and tried a version check and re-installing Umbrella

Sorry for interrupting but I hope no one mind.

Did you try to manualy increase the buffer size with advancedsettings.xml ?

if not downlaod OpenWizard Addon by adding this source to kodi "https://a4k-openproject.github.io/" and install the repo.
you should find OpenWizard in Program add-ons section within the Addons4Kodi repo.

after installing it go to OpenWizard > Maintenance > System Tweaks/Fixes > Advanced Settings > Cache & Network Presets > High-End Device Preset > Install > Force Close Kodi

start Kodi again and congratulations your buffer size increased from 20mb "Kodi Default" to 300mb, it should be more than enough.
this increase in buffer size is going to use more RAM of your device while streaming, if kodi crash while streaming you have to decrease it by using "Low-RAM Preset =100mb" or going back to Default.

I hope this will fix your problem 😉

**Comment by umbrellaplug** [comment]
> ugh, I didnt mean to spam you guys.  Just noticed I was marked as "spammy" which wasn't my intention. Sorry @umbrellaplug 

No worries. I don't think that was me that marked you that way. Sorry about that. Has your playback been better?
