### ISSUE TITLE
[Bug] Easynews sources freezing when skipping forward or backwards or jumping chapters if available

### ISSUE THREAD

**Issue by Nuklear92** [umbrellaplug/umbrellaplug.github.io#421]
One of the things that had me using Umbrella addon more lately has been on how reliable it's able to start EasyNews sources. However, there seems to be an issue where if you wanna skip forward or backwards the source will freeze completely and you have to manually stop playback. 

For example if I start a movie or episode using a EN source, if I don't skip forward or backwards it will play fine. Then, let's say I pause the movie or episode to watch at a later time, when I use the Trakt Scrobbe to jump back to where I left off using any EN source. When the playback starts and Kodi tries to resume where I left off based on the saved Trakt Scrobbe. The source will freeze completely, so basically EN sources only playback from beginning and can't be jump forward. 

I tried this using FenLight, POV, etc. and you can jump forward and backwards on any EN source when playback is running, only in umbrella addon you can't skip forward or backwards neither chapters if they're available.

**Comment by umbrellaplug** [comment]
lol. Ok. Once playback is passed off to kodi I have absolutely no control of this. Please stop opening issues for nonsense.

**Comment by Nuklear92** [comment]
> lol. Ok. Once playback is passed off to kodi I have absolutely no control of this. Please stop opening issues for nonsense. 

You were right, my apologies. I rebooted my Shield TV and for some odd reason now it's working correctly. Next time I open an issue I'll make sure to double check first and gather more proof if needed. 👍
