### ISSUE TITLE
[BUG] Cannot right click on searched sources

### ISSUE THREAD

**Issue by camembo** [umbrellaplug/umbrellaplug.github.io#423]
### Bug

immediately after 6.7.28 update, I can no longer right click on searched sources to access download

### Expected Result

after search of available sources, right click should present a pop-up window for download option

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 21.1

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
What kind of sources? What provider are they from? I need steps to duplicate.

**Comment by camembo** [comment]
I am using Premiumize.me. It does not matter what the actual source is. You can replicate by looking for a file and once the returned sources are displayed try to right click for the pop up window for download. That pop up window to allow the download is no longer there. It started immediately after the upgrade.
Charles 
***@***.***
December 21, 2024 10:10 AM, "umbrellaplug" ***@***.*** ***@***.******@***.***>)> wrote:
	What kind of sources? What provider are they from? I need steps to duplicate.

**Comment by umbrellaplug** [comment]
Likely something I've messed up in the update. I'll look into it.

**Comment by umbrellakodi** [comment]
Latest update should fix this.

**Comment by camembo** [comment]
It is fixed.  Thank you
