### ISSUE TITLE
[BUG] browse debrid pack

### ISSUE THREAD

**Issue by epidoma** [umbrellaplug/umbrellaplug.github.io#424]
### Bug

This got removed somewhere along the way with this realdebrid mess.
if it was by accident please bring it back.

### Expected Result

when scraping episodes with real-debrid i want to browse debree pack to manualy select episode from season,
I realise that beacause everything is uncached this will not work on all sources. but sources that are cached should still display content of pack.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

kodi 21.1
windows

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Browse debrid pack still works on cached links. I don't have a great way to check if an rd link is cached or not anymore so it's kind of luck of the draw. I'd recommend switching providers.

**Comment by epidoma** [comment]
@umbrellaplug 
I tried it with torbox now but still context menu dont show browse debrid pack.
here is a picture in case im not clear enough.
![browsedebridpack](https://github.com/user-attachments/assets/51ddd315-ce55-45a0-a879-1aad982bee2f)

**Comment by umbrellaplug** [comment]
> @umbrellaplug I tried it with torbox now but still context menu dont show browse debrid pack. here is a picture in case im not clear enough. ![browsedebridpack](https://private-user-images.githubusercontent.com/167754129/398243513-51ddd315-ce55-45a0-a879-1aad982bee2f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5ODMzMTMsIm5iZiI6MTczNDk4MzAxMywicGF0aCI6Ii8xNjc3NTQxMjkvMzk4MjQzNTEzLTUxZGRkMzE1LWNlNTUtNDVhMC1hODc5LTFhYWQ5ODJiZWUyZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxOTQzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGY4ZGYyZTA5ZWE1MDBlYzQxYmYxYTNkODFlMDhhYTQ3NmU1ODUwYmNhNWNlOTFhNWQ1OTY3ZGY3ODk2ZmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s4pzuFXx7Nfm-aRT3WYiE54liXnDYm69pCxxbOLCw-8)

Might be your skin. Works for me no problem.
![image](https://github.com/user-attachments/assets/3bd0a8b5-8218-46f1-9646-c76cfd3f2d19)

![image](https://github.com/user-attachments/assets/7a69e57c-93b2-47e3-bf7c-277a2bc2ea0f)

**Comment by epidoma** [comment]
thank you.
must be something on my end then. i tried default skin but still not showing.
I will investigate this more but its definitely something on my side if it works for you.
