### ISSUE TITLE
[BUG] No stream available

### ISSUE THREAD

**Issue by tomjimlondon** [umbrellaplug/umbrellaplug.github.io#426]
### Bug

Hello there!

I am facing the following issue; after successfully link All Debrid premium account, whenever I try to reproduce any content, it returns "No stream available"

Here are my log files:
Kodi log file uploaded to:
https://paste.kodi.tv/tuzeborecu
Umbrella log file uploaded to:
https://paste.kodi.tv/qecehezuze

### Expected Result

It should show a list of links available

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.1 for armv7 32bytes (firetv stick 4k)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
You need to add and enable an external provider.
