### ISSUE TITLE
[BUG] No Stream Available - Coco Module Error

### ISSUE THREAD

**Issue by xxxsskxxx** [umbrellaplug/umbrellaplug.github.io#427]
### Bug

Latest Kodi Nightly (clean install)
Latest Umbrella addon and Coco scraper module 
Coco external scraper setup in Umbrella addon settings with a successful message received 
Premiumize account linked successfully 

I select a movie or TV stream and receive errors pasted here

https://paste.kodi.tv/xefuqifote

### Expected Result

Stream should open and play 

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 22.0 Alpha 21.90.700 git 20241222-4af868a45b
Homatics Box R 4K Plus running android TV 14
Mullvad VPN setup on Asus router to route all traffic through my VPN

Coco error logs

https://paste.kodi.tv/xefuqifote

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
I'm not the developer of cocoscrapers.

**Comment by xxxsskxxx** [comment]
Umbrella log file states

Error: Loading cloud scraper module: "pm_cloud": 'FileFinder' object has no attribute 'find_module'

**Comment by xxxsskxxx** [comment]
> I'm not the developer of cocoscrapers.
Hey, that was quick lol. I've just added the detail from the umbrella log file. Cheers

**Comment by xxxsskxxx** [comment]
Something maybe up with Premiumize from what I can see. Wako also having issues. Will see what's going on. Not addon related at all.

Thanks

**Comment by umbrellaplug** [comment]
It looks like you have a version of kodi using a newer version of python that may have issues with the code we have for checking folders.

**Comment by umbrellaplug** [comment]
I'm going to load Ubuntu 24 in a virtual machine and see if I can duplicate the issue in umbrella. Umbrella and CocoScrapers use similar code for the cloud module scrapers and cocos scrapers and they detect which ones are available by detecting files in a folder, it seems to be having problems with that.

**Comment by xxxsskxxx** [comment]
> I'm going to load Ubuntu 24 in a virtual machine and see if I can duplicate the issue in umbrella. Umbrella and CocoScrapers use similar code for the cloud module scrapers and cocos scrapers and they detect which ones are available by detecting files in a folder, it seems to be having problems with that.

Brilliant thank you!

**Comment by umbrellaplug** [comment]
just noticed you're also running kodi 22 alpha...

i have not tested with this. this is not supported yet.

**Comment by umbrellaplug** [comment]
Do you have the ability to load coco from a zip file and umbrella from the test repo if I provide you links?

**Comment by umbrellaplug** [comment]
Try the umbrella version here:
https://umbrellakodi.github.io

Try this version of cocoscrapers:
https://www.dropbox.com/scl/fi/t8gc9cp98whwc6erkv03q/script.module.cocoscrapers-1.0.29.zip?rlkey=260jeqprmlorvqhtnauaqyrrd&st=p771al0d&dl=0

**Comment by xxxsskxxx** [comment]
Absolute legend!! Working perfectly. Thank you very much for the quick turnaround.

Merry Christmas!
