### ISSUE TITLE
[BUG] can't access to the cloud storage Alldebrid

### ISSUE THREAD

**Issue by benojack68** [umbrellaplug/umbrellaplug.github.io#430]
### Bug

Hello , since I used umbrella on Kodi I can't have access to the debrid link from my cloud storage on this app on Kodi. The link are in the storage on the website of alldebrid but I don't know why I don't see them on umbrella / premium services ... I saw the torrents can be read but not the simple links.. do you have an ideas ? I used the latest version of Kodi and umbrella and have a premium access to all debrid . Many thanks in advance ;)

### Expected Result

Open debrided link from Alldebrid cloud storage 

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi on Google tv lastest version and same for umbrella 

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
All debrid announced they are having issues with their servers that should be resolved Jan 1st.

**Comment by benojack68** [comment]
Many thanks for your answer ;) I asked them but they are not explain the problem. Hope it's will be fix as said ;) 
Best ;)
