### ISSUE TITLE
Premiumize Real Debrid Trakt does not save after authorization 

### ISSUE THREAD

**Issue by ohmichael** [umbrellaplug/umbrellaplug.github.io#45]
Premiumize Real Debrid Trakt does not save after authorization

**Comment by umbrellaplug** [comment]
My accounts was removed yesterday and scraper packages were changed today. Can you please make sure you have the latest version of the plugin 6.5.59 and cocoscrapers installed. I recommend cleaning settings then clearing cache and re-entering account information. 

I know this is a pain, but it should be the only time I have major changes to how account information is stored in the plugin.

**Comment by umbrellaplug** [comment]
Also, please make sure you're hitting "ok" after authorizing in settings. kodi actually doesn't save those settings if you go "back" instead of okay.

**Comment by ohmichael** [comment]
I did all that & I hit save umbrella I deleted the old & installed the new I authorized twice then hit save in settings like I do with Ezra too - Ezra saves just this doesn’t I only brought it up because I thought it was me so I was messing around with others similar to this addon to see if it was my end but it seems it’s the addon & not me. I thought you should know why I said something.

**Comment by ohmichael** [comment]
I normally have to authorize just once by the way but yours even after two times it still don’t save after hitting the okay save button in settings after authorizing. I’m not mad just beating others to saying the same thing. :D enjoy your day I’ll be around.

**Comment by umbrellaplug** [comment]
Okay, so I'm not seeing the same behavior you are. When you authorize it closes settings while you authorize once authorized it returns to settings and you should see whatever debrid services you authorized show more settings. This is not done the same as Ezra anymore so I'm not sure if you're authorizing in the correct place or not.

My Accounts was removed. Most accounts are now authorized in "Accounts" section of settings within the plugin. Not my accounts. I'm having trouble understanding some of your response, so I'm not sure if you're saying it's working for you now or if you're still having issues. Can you please clarify?

**Comment by umbrellaplug** [comment]
Just attempted this on multiple devices. It is working as expected for me. Can you try again and submit a log?

**Comment by ohmichael** [comment]
Alright I’ll reinstall if it works I’ll let you know

**Comment by ohmichael** [comment]
Seems it fixed itself I closed out of kodi then reopened it & everything appeared in settings anyways I appreciate everything you’ve done closing this problem fixed

**Comment by umbrellaplug** [comment]
Glad to hear that's working for you. Cache on kodi has got us all many times! Enjoy!
