### ISSUE TITLE
[Request] Can you add Arabic as an option in metadata languages? 

### ISSUE THREAD

**Issue by psp2111-ADSLGATE** [umbrellaplug/umbrellaplug.github.io#46]
Hi @umbrellaplug 

First I want to thank you for the awesome work you put to this addon especially in last week.
I have been using the addon for two weeks now and I really loving it so far, I noticed that the addon doesn't have Arabic as an option in metadata languages or as you call it in the settings "api language".

I also tried to set it to "AUTO" while kodi interface lang is set to Arabic but did not work and the metadata lang still in English.
Personally I more interested in "Arabic Saudi Arabia" or "ar-SA" for TMDb. anyway I hope my request is simple and easy to add.

Thanks again for this addon ;).

**Comment by umbrellaplug** [comment]
I have added this. It will be in the next update. It does add the meta-data but keep in mind it's still hit or miss based on if there's a translation on TMDB or not. If you know anyone interested I can provide the strings file as well for translation as well if you wanted Arabic within the plugin also.

**Comment by psp2111-ADSLGATE** [comment]
> I have added this. It will be in the next update. It does add the meta-data but keep in mind it's still hit or miss based on if there's a translation on TMDB or not. If you know anyone interested I can provide the strings file as well for translation as well if you wanted Arabic within the plugin also.

Thank you so much 

I am aware that the translated metadata depends on TMDb database, and need to be already translated their to show up in the plugin.

about the translation of the plugin's strings, I will be more than happy to do that, but first let me try the metadata in Arabic and make sure it work just fine and doesnt couse any issue with the scraper's functionality or other plugins like a4ksubtitles, TMDb Helper.

**Comment by umbrellaplug** [comment]
Version 6.5.60 has ar-SA available for tmdb. Please let me know if that works for you. You will need to clear your metadata cache.
