### ISSUE TITLE
Resume not working

### ISSUE THREAD

**Issue by Dinzy3** [umbrellaplug/umbrellaplug.github.io#47]
Resume is not working in Umbrella.  I am on the latest stable Kodi, default skin, windows.  When I click resume at XX:YY it just loads the movie from the start.  This issue has been present for weeks.  

Actually now kodi crashes every time so I cant add any more details.

**Comment by umbrellaplug** [comment]
Crashes were being caused by a different plugin. If you can get me some details and some logs on your resume issue I'm happy to look into the issue.

**Comment by Dinzy3** [comment]
crashes were related to Fen.  I got that sorted.  I loaded a lord of the rings movie and told it to resume.  I also updated to a nightly kodi build hoping that might fix the crashes.  This install is probably due for a full wipe especially with venom/fen/ezra/umbrella/ 53 versions of my accounts, etc.  

[kodi.old.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/9255447/kodi.old.log)

**Comment by umbrellaplug** [comment]
Would you like to try a test build with a possible fix?

**Comment by umbrellaplug** [comment]
Fixed in the next release. Watch for version 6.5.60.

**Comment by Dinzy3** [comment]
great.  thanks.

**Comment by Dinzy3** [comment]
confirming the fix works.

**Comment by umbrellaplug** [comment]
Great! Glad to hear it's working for you now.
