### ISSUE TITLE
Request: Nav mass meta categories

### ISSUE THREAD

**Issue by Zecho1** [umbrellaplug/umbrellaplug.github.io#48]
I know you're busy so no biggie.  If you find the time though, an option in "Navigation" to en/disable all items by meta provider n would be great considering how many times I reinstall.

Something like:
[ ] Disable all Trakt sections
[ ] Disable all IMDB
[ ] Disable all TMDB

**Comment by umbrellaplug** [comment]
Nah, will not be dedicating time to duplicate settings that already exist.

**Comment by Zecho1** [comment]
Alright. I'll do it.  Should be easy since you've already done it on every
other category.
