### ISSUE TITLE
resume point

### ISSUE THREAD

**Issue by gecXMAN** [umbrellaplug/umbrellaplug.github.io#49]
It looks like that resume point and continue watching is not working with strm files when items are played from library.
When I'm using addon directly everything works fine but when I export titles to library they not apear in continue watching(I'm using titan bingie skin) and when I play them again they start from beginning. 
Umbrella is connected with trakt account and no matter whether I use trakt for resume point or local addon feature result is the same.

**Comment by gecXMAN** [comment]
I have to reply to myself, in new version from today resume point is working in every combination !
Well done :)

**Comment by umbrellaplug** [comment]
Thanks! Have a great one!
