### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#5]
Sorry just adding this before I look through maybe you can see why before me.

https://paste.kodi.tv/fesudekaki

**Comment by adamosborne83** [comment]
Sorry, can see its down to fanart, something to prob do with universal scrappers when updating library items.

**Comment by umbrellaplug** [comment]
Strange, are you using your own key for fanart.tv? I don't see that key anywhere in Umbrella. Was wondering if it was maybe to do with that. Weird timing though because I changed the key for fanart out in Umbrella yesterday.

**Comment by adamosborne83** [comment]
> Strange, are you using your own key for fanart.tv? I don't see that key anywhere in Umbrella. Was wondering if it was maybe to do with that. Weird timing though because I changed the key for fanart out in Umbrella yesterday.

Hey, yes I use my own api key for it, but I can assume it's down to Universal Movie Scrapers as it does not have the option to add my own personal api.
So don't think it's an umbrella issue, thanks though :-)

**Comment by umbrellaplug** [comment]
Cool, I just pushed the fanart update for you for your ezra request. :)

Closing this issue for now. Let me know if you figure out it's something with Umbrella.
