### ISSUE TITLE
Suggestion to increase scraping speed

### ISSUE THREAD

**Issue by LITUATUI** [umbrellaplug/umbrellaplug.github.io#50]
Fen has useful option called "Stop Search if Most Sources Finished".

Would it be possible to implement something similar in Umbrella?

For example, if we have 20 torrent website sources active in CocoScrapers, after getting results from 10 websites scraping is terminated. This way we won't get slowed down by slow torrent websites.

It doesn't need to be 1/2 to terminate scraping, it could be 2/3, this way we would eliminate the 1/3 slowest sources.

Finally, can you enable the discussion section? This way we would leave the issues section to report bugs.

Thanks for your work, this addon is awesome.

**Comment by umbrellaplug** [comment]
> Fen has useful option called "Stop Search if Most Sources Finished".
> 
> Would it be possible to implement something similar in Umbrella?
> 
> For example, if we have 20 torrent website sources active in CocoScrapers, after getting results from 10 websites scraping is terminated. This way we won't get slowed down by slow torrent websites.
> 
> It doesn't need to be 1/2 to terminate scraping, it could be 2/3, this way we would eliminate the 1/3 slowest sources.
> 
> Finally, can you enable the discussion section? This way we would leave the issues section to report bugs.
> 
> Thanks for your work, this addon is awesome.

Checkout Pre-Emptive termination setting in Umbrella.

Opened up discussions. We'll see how that goes. I haven't had much time to look into it yet.

**Comment by 123Venom** [comment]
@LITUATUI 

20 scrapers enabled for every scrape is serious overkill and slowing you down in itself.  I'm not exactly sure how many torrent scrapers are enabled in CocoScrapers as a default but previously in FenomScrapers it was 9-10.  I only use 5 myself and my scrape completes in 2-3secs.  On a rare occasion that I can't find sources for something less popular I'll use `Rescrape with all providers`.  That's it's point so a typical scrape can use as few as possible, to yield good results, and when needed you have a quick easy context menu to Rescrape with all at your finger tips.  Torrentio is the best scraper hands down and it alone indexes...
`yts, eztv, rarbg, 1337x, thepiratebay, kickasstorrents, torrentgalaxy`

Give it a try using less scrapers and for unpopular titles use `Rescrape with all providers`.

**Comment by gecXMAN** [comment]
Can You tell which 5 scrapers do you use?

**Comment by 123Venom** [comment]
Sure....bitsearch, eztv, glodls, magnetdl, torrentio.  I know a dev who only runs torrentio.

**Comment by gecXMAN** [comment]
Thanks, I tried with this scrapers and they are working fine and fast so far, also it looks like for only cached RD links torrentio is enough.
