### ISSUE TITLE
PLAY FROM HERE Missing from Context Menu

### ISSUE THREAD

**Issue by rogermae** [umbrellaplug/umbrellaplug.github.io#52]
[Play only this] is showing instead of PLAY FROM HERE. Is this on purpose. Started with 6.5.6.1

**Comment by umbrellaplug** [comment]
"Play Only This" is not included anywhere in the plugin or context menu addon. Are you you using a skin?

**Comment by umbrellaplug** [comment]
Please check the lastest version pushed today.

**Comment by rogermae** [comment]
Yes. I was going to reach out to the build's dev next.

Kind Regards
Roz Artis

________________________________

**Comment by rogermae** [comment]
Thanks, back to normal. Appreciate you.

Kind Regards
Roz Artis
________________________________

**Comment by umbrellaplug** [comment]
Great I will close this issue as it seems the update resolved your problem.
