### ISSUE TITLE
Mark episode as watched Trakt

### ISSUE THREAD

**Issue by marcuspax** [umbrellaplug/umbrellaplug.github.io#54]
First, thank you for the awesome work you're doing. 
I'm using umbrella version 6.5.63 on Mibox S, and once I finish watching an episode on my Trakt progress list, the episode is not marked as watched automatically. 
Let me know if you need more information.

**Comment by umbrellaplug** [comment]
I will look into this. Changes were made to the player module in the plugin that could be affecting this.

**Comment by umbrellaplug** [comment]
I was unable to duplicate this issue. I watched two episodes of sandman. Both were marked as watched locally and on trakt. Can you please provide more details of your setup and logs?

**Comment by marcuspax** [comment]
Tried again to watch Only Murders in the building 2x8, and after the episode ended, still it was unwatched in Trakt and also still existed in my progress list on umbrella. See the screenshots below from umbrella log file. 


![image](https://user-images.githubusercontent.com/96535879/183717347-1f839239-9bb5-41ee-ab6b-68eb228dfc43.jpeg)
![image](https://user-images.githubusercontent.com/96535879/183717430-2d7fed8b-1781-4895-a3d0-e7f9fdfbfe7b.jpeg)
![image](https://user-images.githubusercontent.com/96535879/183717498-9642bdd9-4ca1-46c1-8207-5b90a38316a9.jpeg)

**Comment by umbrellaplug** [comment]
I'm sorry, but I need the log. A few snapshots of the log aren't sufficient to troubleshoot the issue. 

Please follow the instructions in the wiki section here for logs.

**Comment by marcuspax** [comment]
Issue seems to be resolved. 
Reinstalled umbrella and disabled Trakt scrobbling. Episodes being marked as watched now.

**Comment by umbrellaplug** [comment]
Sweet! Let me know if issues come up.
