### ISSUE TITLE
Sorting trakt lists aphabetically is reversed

### ISSUE THREAD

**Issue by HypoLuxa** [umbrellaplug/umbrellaplug.github.io#55]
Open a trakt list (collection, personal list) in addon. These are shows, not episodes.

The lists are displayed in reverse alphabetical order and not alphabetically. 

This happens when changed in settings or in the skin, both have no effect in the list sorting.

Thank you for doing this and for your work. We all appreciate it.
Cheers

**Comment by umbrellaplug** [comment]
Tested this and I was able to set show sorting to "Title" then Descending or Ascending and it worked no problem for me. Alphabetical would be by Title and appears to be working for me. If this is not working for you, it appears it may be related to the skin you're using.

**Comment by HypoLuxa** [comment]
I thought of that, I would not have opened issue if that were the case.

Problem being, this only happens in Umbrella, using the same skin and same list it does not happen in other addons.

To be clear, this happens on, 'watchlist", 'collection' or any custom lists you may have made, it also happens on 'liked lists', all trakt. So for example, Umbrella>My TV Shows>Collection is sorted backwards, again, only in Umbrella, no matter the skin.

If I can be more detailed in helping you reproduce this, let me know.

**Comment by umbrellaplug** [comment]
I'm flat out not seeing the same results. Please check your settings. Here's multiple screenshots. In my settings I tested this with changing TV Shows> Watchlist > Sort By Title > Ascending and Descending.

Now I hope I don't have to explain this, but just in case.... 
Ascending is to start at the beginning and go to the end. A TO Z
Descending is to start at the end and go to the start. Z TO A

Here's screenshots of my settings and the results it had on my trakt watchlist when I changed them.
![settings](https://user-images.githubusercontent.com/107957815/184262008-f29d21fb-114e-455a-b49e-d8c0cdc44672.PNG)
![ascending](https://user-images.githubusercontent.com/107957815/184262036-0cbbe85a-87ac-40d2-8602-0820df088671.PNG)
![descending](https://user-images.githubusercontent.com/107957815/184262038-0269fb3e-7260-45e3-b5b6-52467100005a.PNG)
