### ISSUE TITLE
Mark watched in Trakt

### ISSUE THREAD

**Issue by marcuspax** [umbrellaplug/umbrellaplug.github.io#56]
Hello @umbrellaplug 
The issue has recurred. Don't know what's happening but here's the log file:

https://paste.kodi.tv/wawoputeho

Watched Mad Men 3x10 and when the episode ended, it wasn't marked as watched. 

__Originally posted by @umbrellaplug in https://github.com/umbrellaplug/umbrellaplug.github.io/issues/54#issuecomment-1210017163__

**Comment by umbrellaplug** [comment]
It appears trakt may be having some issues. You can see in your log towards the bottom you got an error back from Trakt.

**Comment by zois1** [comment]
Here also trakt not working for collection tv shows .....

**Comment by umbrellaplug** [comment]
No logs.

**Comment by zois1** [comment]
![20220811_135425.jpg](https://user-images.githubusercontent.com/31615115/184127888-5d13cfbd-7a34-4ab9-a937-3c92f29cbe60.jpg)![20220811_135418.jpg](https://user-images.githubusercontent.com/31615115/184127922-a15212a8-2795-4a1c-989d-bfd9abdffd35.jpg)

**Comment by umbrellaplug** [comment]
Pictures of logs are not logs. I apologize, but there are clear instructions on how to get logs in the wiki of the github. Please open an issue with logs if this issue continues.
