### ISSUE TITLE
Sorting of TV Shows 

### ISSUE THREAD

**Issue by TechXXX** [umbrellaplug/umbrellaplug.github.io#62]
Hi, I'm a complete newbie to all of this so my apologies if this is posted in the wrong place. Someone in this thread suggested I raise this issue with the dev on github so here I am trying to do that ---> https://www.reddit.com/r/Addons4Kodi/comments/wt9ql6/sorting_of_tv_shows_in_umbrella/

As mentioned in the thread I'm just trying to open a tv show from a widget, I've set my tv shows to flattened so when I click on a tv show I'd like it to go to the most recent episode on first click. Sort direction/order do not appear to work (see reddit thread for more info). 

Kind regards,

Bas

**Comment by umbrellaplug** [comment]
I have added a new subsetting into Umbrella that will allow you to reverse the sort order from ascending to descending when using "flatten season" settings. It will be in the next update.

**Comment by TechXXX** [comment]
Outstanding, thanks a lot.

**Comment by umbrellaplug** [comment]
Latest update was pushed. Sort by descending is now an available option under "Flatten TV Seasons". Closing this issue out. Have a good one!
