### ISSUE TITLE
Add Option for "File Size Limit" for Bandwidth inst

### ISSUE THREAD

**Issue by bd94** [umbrellaplug/umbrellaplug.github.io#73]
Would be a nice feature to allow filtering bandwidth for a file vs total size limit. Aka set a limit for 20 Mbit/s. Makes much more sense than total size limits.

**Comment by umbrellaplug** [comment]
Unsure what you're asking for. I can't determine the speed at which you stream a file. The file size is the amount of bandwidth it's going to use. 

Bandwidth is the same as file size.

**Comment by bd94** [comment]
So instead of having file size limits set in "Sorting and Filters > Source Filtering Options" which are currently arbitrary. IE. a 4GB file could require a 1Mbps or 50Mbps internet connection to stream w/o buffering depending on the media's length.

It would be a limit based off of a set speed. Say my internet is a 10Mbps connection. I would prefer to only play media that doesn't buffer. So a 4GB for a hour file would require an internet speed of 14.4Mbps to maintain a smooth stream. A 4GB file that plays for 2 hours only requires 7.2Mbps. 

If I currently set a 4gb limit under the previous settings it may buffer on a shorter movie but not a longer one. Makes more sense to have a filter based off of bandwidth not total data. Bandwidth is a measure of speed or how fast you may transfer data aka doing a speed test. Total data is just well the total amount of data the file requires. 

Perfect example of this implemented is in FEN.

**Comment by umbrellaplug** [comment]
This request was added in the latest update.
