### ISSUE TITLE
View types changing

### ISSUE THREAD

**Issue by curtyman11** [umbrellaplug/umbrellaplug.github.io#74]
I have movie and tv show view types set to “media info”. When I’m on the first page of results, they are shown the way I have it set. But when I proceed to a 2nd page and beyond it changes to “list” view.

**Comment by umbrellaplug** [comment]
Can you explain to me what you mean by set my view type to "display media info"?

My options when setting viewtypes are "List, Poster, Shift, Infowall, Widelist, Wall, and Fanart"

I tested using Poster and Infowall and going into Movies> Trakt (Trending) and my second page on both views retained the view. Can you please provide me with some more information and steps to try to duplicate your issue?

**Comment by curtyman11** [comment]
https://paste.kodi.tv/bunayikosi

**Comment by umbrellaplug** [comment]
From your log I'm not seeing any obvious reason this is happening. I'm unable to duplicate the issue unfortunately.

**Comment by curtyman11** [comment]
Well I’m really grateful that you tried to help. I’m stumped too. I might try doing a complete reinstall when I have time.

**Comment by umbrellaplug** [comment]
It's a strange issue, I do not like to tell users "I have no idea". It bothers me honestly. I am pushing out a new update soon that has the format for settings.xml changed to newer format. Might be worth a try to test after updating. Should be out later tonight.

**Comment by curtyman11** [comment]
Sounds good I’ll check it out tomorrow. You do great work with this addon.
