### ISSUE TITLE
Filepursuit

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#75]
This is more of a question I have a free file pursuit account what would you set priority at thank you

**Comment by umbrellaplug** [comment]
You set your api key in the scrapers and once you do it open the ability to set your priority in the umbrella plugin settings.

**Comment by Arthur1967** [comment]
I understand that and I did that but what should I set the priority at thank you

**Comment by umbrellaplug** [comment]
Sure, well it's really up to you. It goes from 1-10. 10 being "This is high priority put it to the top" so it really just depends on where in your source list you want the results from file pursuit to show. Honestly, file pursuit is not the best lately so I'm not sure I would want a real high priority on them as it would put them at the top of your links in source select or for autoplay.

**Comment by Arthur1967** [comment]
OK and I do see that it's not the best lately but I just leave it in there thank you have a good night
