### ISSUE TITLE
Sorting DV/HDR

### ISSUE THREAD

**Issue by djdirty60** [umbrellaplug/umbrellaplug.github.io#8]
Good day,

Is it possible that there will be a function that you can choose that first comes with Dolby Vision and then HDR and the rest?  

For example:

1.4K/DolbyVision/DolbyAtmos/56.3GB
7.4K/HDR/DollyAtmoz/44.7GB

thanks in advance

**Comment by umbrellaplug** [comment]
Can you give me more details? Umbrella already has a setting under Settings>Source Options> Source Filtering Options Sub-Header - Prioritize HDR and Dolby-Vision to top. Is your request different from this setting?

**Comment by djdirty60** [comment]
Klopt dat werkt ook, maar dan staan ze door elkaar heen. Maar een functie dat je kan kiezen dat eerst de dolby vision boven aan komen en daarna de HDR. Dus niet meer door elkaar heen

**Comment by umbrellaplug** [comment]
I can look into this. Some research is required as to identifiers that could be used for sorting.

**Comment by umbrellaplug** [comment]
In the latest update I have added a new setting. If you prioritize hdr and Dolby vision to top. You now have an additional toggle to put Dolby vision first. Try it out and let me know if this accomplishes your request.

**Comment by djdirty60** [comment]
Yes this is great..... thanks for everything 👍👍👍👍👍
