### ISSUE TITLE
[Request] Export .strm's of GDrive worker file links directly

### ISSUE THREAD

**Issue by cboRD181** [umbrellaplug/umbrellaplug.github.io#81]
So I've recently begun using the gdrive worker functionality in umbrella as an alternative to the official Google Drive addon and it works remarkably more smoothly for me -- no endless "watching for changes" buffering, no unexplainable API quota hits, no incomplete .strm exports, audio isn't muted briefly after pausing and resuming, etc.  In addition to just conveying my gratitude, I'd like to suggest the ability, when importing to library, to generate .strm's to the workers indexed files themselves, rather than have those .strm files scrape all selected umbrella sources before playing.  Alternatively, an option to export the index in its entirety as .strms would suffice and be hugely useful, for those of us who already have Kodi formatted data (I've tried in the past to add a gd index as an http source in Kodi directly but couldn't get it to work).

Also, and I'm sure this is the case, but it'd be nice to get confirmation that our links aren't shared anywhere, since the gdrive worker generator isn't password protected.  Thanks for reading and for all the amazing work!

**Comment by umbrellaplug** [comment]
I can look into the strm files request. Currently the worker only returns blank if no query is provided and didn't have an existing get all method. As for password protection on worker link, not currently. Anyone who has that link would have access to your content from links provided by the worker. The worker is actually the authorized client not you individually.

**Comment by umbrellaplug** [comment]
I'd also be interested to understand what type of STRM file you are looking for?

I've been working with the library a bit lately because of a feature request and I've found that the strm files generated in library can either point directly to tmdbhelper or umbrella depending upon the selection in settings for library import. I had a request from a friend using Jellyfin to be able to create a STRM file directly from the source selection menu. I'm wondering if you selected a gdrive link in that selection menu and used the "Create STRM" context menu item if it would give you what you are looking for. It adds it to your plugin download folder.

**Comment by cboRD181** [comment]
Thanks for the reply.  The type of STRM I'm looking for indeed seems to be the same as your friend's request for Jellyfin.  I just tried using the selection menu but I don't see an option in the context menu to create a STRM to an individual source file; the only option I see is "Additional Link Info" which lists the url of the file.  The STRMs I'm looking for would point directly to that url.  So when adding a show to a library, the STRMs would point directly to whichever url would have been selected by the autoplay settings, and not re-initiate a scraping process every time.  If that's not feasible I understand. 

As for the worker only returning blank with no query, there are other versions which produce an index of all files (https://github.com/alx-xlx/goindex) which may be easier to scrape.  Personally, having a way to scrape and convert an index like this into STRMs which retain the file structure and point to the urls of the files directly would be ideal, but that's probably out of scope for you.

**Comment by umbrellaplug** [comment]
You're not getting the strm option because you do not have download enabled in the settings of the plugin. Enable that and try the create strm file from the source select menu and select the gdrive source.

**Comment by umbrellaplug** [comment]
Let me know if anything else comes up. I'm looking into some of your links for gdrive worker url improvements.
