### ISSUE TITLE
Unaired tv episodes still shows up

### ISSUE THREAD

**Issue by jaimsitecom** [umbrellaplug/umbrellaplug.github.io#84]
Did i miss a setting option on how to NOT SHOW unaired TV episodes into the Kodi library?

I’ve already unclicked:
SETTINGS>TV SHOWS>SHOW UNAIRED SEASONS/EPISODES
and
SETTINGS>TRAKT>BROWSE PROGRESS: LOAD ALL EPISODES OF SERIES
also
SETTINGS>LIBRARY>INCLUDE EPISODES W UNKNOWN AIRDATES

all these are unclicked, but everytime library updates or i add new tv shows, future episodes still show up inside the season folders of the Kodi library. 

Is there something i missed to have this thing disabled?

thanks!

**Comment by jaimsitecom** [comment]
Update:

adding new tv shows to kodi library gets the same bug. All episodes (.strm) including unaired ones  or future episodes gets downloaded into the shows’ folders. Even if the setting option of ‘not to download unaired tv shows’ is chosen

hoping this gets looked into and gets a fix. 

Thanks in advance.

**Comment by umbrellaplug** [comment]
Whoa. Hey sorry for the long wait on response here. I somehow missed this. I will look into the issue.

**Comment by umbrellaplug** [comment]
Resolved in latest update. Will be pushing soon. Currently in testing. 

Did not make any adjustments for movies. Only added an option when importing to library to include unaired episodes. Making this option default to false. Unfortunately any episodes already imported will need to be removed.

I tested with multiple shows and new episodes are only added on the day they air or after now.

**Comment by jaimsitecom** [comment]
> 

Thank you so much!  This is great! Yes, that’s what i did the past few days, i manually deleted future episodes. Yes, no problem on the MOVIES side. 

Thanks again for sharing your work and more power to you!
