### ISSUE TITLE
Imdb

### ISSUE THREAD

**Issue by Arthur1967** [umbrellaplug/umbrellaplug.github.io#91]
ur154626892 is my ID I can get my ratings to show up but I cannot get my lists to show up. Can you offer some help? Thanks.

**Comment by umbrellaplug** [comment]
I would like to verify it's your "watchlist" that's not working? Ratings works but watchlist does not? Is that correct?

**Comment by Arthur1967** [comment]
Exactly my watchlist will not populate nor any of my personal list, but
ratings will populate

**Comment by Arthur1967** [comment]
It seem to work before the latest update, and I have my list as public so
it should show up. Thank you.

**Comment by umbrellaplug** [comment]
Looks like IMDB is having trouble with their website. I get a 404 when I attempt to go to your watchlist.

https://www.imdb.com/user/ur154626892/watchlist

I went to this address: (which works)
https://www.imdb.com/user/ur154626892/
Then clicked on watchlist.

**Comment by Arthur1967** [comment]
OK I have just been using my movie database API key thank you. I will just
leave it as is until it gets fixed with IMDb. Have a good day.

**Comment by umbrellaplug** [comment]
No problem, have a good one!
