### ISSUE TITLE
Future request: alternative to 24hr delay import of tv episodes to kodi library

### ISSUE THREAD

**Issue by jaimsitecom** [umbrellaplug/umbrellaplug.github.io#92]
I’ll try my best to explain what i’m trying to request here. 😀

Ok, i am from the Philippines. Our timezone is at +8:00. It’s fairly easy to determine the airtime of tv show episodes, it’s just always the opposite time of day of Eastern time. So for example, if the show airs at Oct 4, 9pm ET, here in the Philippines, it translates to Oct. 5, 9am. 

So anyway, i just want to ask if there’s a way to make a setting option where i can set  UMBRELLA to only download shows that are already released or already aired. Or would it be easier to have a 12hr delay as a choice instead of only stuck at 24hr delay? Sorry for this, i guess it’s the OC in me, that wants to see episodes in my kodi library that  actually have streams already. If i turn off the 24hr delay, my library will be loaded with a day in advance episodes. On the other hand, if i turn on the 24hr delay, it  works for tv shows that air before midnight. But shows like ANDOR, SHE HULK, RINGS OF POWER, which air at midnight and beyond, won’t get imported into my library until the next day. So i am kinda stuck, it will be either i get advance import or delayed import if i use the 24hr delay or not. 

Anyways, sorry in advance if my request sounds crazy. 

Thanks anyways!

**Comment by umbrellaplug** [comment]
Just to elaborate, I understand your request. :) I enjoy Rick and Morty and it has an 11pm air time so it shows for me all day but I can't play it till the end of the night.

**Comment by jaimsitecom** [comment]
> Just to elaborate, I understand your request. :) I enjoy Rick and Morty and it has an 11pm air time so it shows for me all day but I can't play it till the end of the night.

Yep. That’s my OC-ness… hehe

**Comment by jaimsitecom** [comment]
Thanks anyways! I appreciate the quick response. I Love Umbrella man! Ty!

**Comment by jaimsitecom** [comment]
Wait, a 12hr delay is not possible tho?

**Comment by jaimsitecom** [comment]
That would be nice

**Comment by phatboyj** [comment]
A slider would be great but will it make a difference as was explained by the Dev he can only get the date of air so how is anything less than 24hrs which represents a day going to make a difference as in with out a time reference hoe do you break down a day in other words I know that the dev can provide the slider but will it function as requested ?

**Comment by jaimsitecom** [comment]
> A slider would be great but will it make a difference as was explained by the Dev he can only get the date of air so how is anything less than 24hrs which represents a day going to make a difference as in with out a time reference how do you break down a day in other words I know that the dev can provide the slider but will it function as requested ?
> 
> or is there in-fact a way to get the air time like from trakt as I know some of the shows show an airdate and time on the trakt episode pages however they are not always accurate as they are pulled from TMDB i think

It would be to me, like a 10-12hr delay might be perfect for my timezone, as i wouldnt have to wait a whole day for shows aired after midnight. By the time a show airs, a couole of hours delay would be ample enough since sources needa couple of hours before they release em publicly anyways. So i still think an adjustable time when to import makes a big difference, at least to me. 😅

**Comment by umbrellaplug** [comment]
Yes, time of day for import is possible. It currently runs every 6 hours. Next update will have slider for delay amount in hours and I will also look into adding a once a day import option with a set time.

**Comment by jaimsitecom** [comment]
> Yes, time of day for import is possible. It currently runs every 6 hours. Next update will have slider for delay amount in hours and I will also look into adding a once a day import option with a set time.

Yay! Ty so much

**Comment by jaimsitecom** [comment]
Thanks again for the added features. 

Tho the slider for frequency of checking for library update is a nice touch, But would it be possible to make it a dropdown for a specific time of day when to check and download the new epiaodes to the library?  Most of the time we turm on kodi right before noon, and i usually prefer to have update checks in the afternoon (say around 4 or 5pm) so it would be perfect to have the new epiaodes at night time here (philippines). I know our time zone is opposite of US times but, i prefer to have the new episodes imported right before evening times. 😀

also, am still playing around with the delay of import setting. Hoping i would be able to match it properly with the setting of frequency of service interval. Otherwise, if ever the ‘SPECIFIC TIME’ of checking for new episode is feasible, the old setting which is 24h delay is a good pairing for that. 

Well, still hoping a good combo comes out of my experiments on both these new features.

**Comment by umbrellaplug** [comment]
In order to accomplish this, just set the slider to 24 hours then do an "import now" on your lists at the time you want you import each day. Going forward it will import at that time.

**Comment by umbrellaplug** [comment]
There's a few things to remember here. The service that triggers this runs every 15 minutes.
Every 15 minutes after you fire-up the addon it does a check to see if you have done an import within the time range set by that slider minus the last time an import was done.

**Comment by jaimsitecom** [comment]
> In order to accomplish this, just set the slider to 24 hours then do an "import now" on your lists at the time you want you import each day. Going forward it will import at that time.

Oh yeah. That’s correct. I’ll just make a shortcut of import now. Dumb me. Hahaha

thanks

**Comment by jaimsitecom** [comment]
The 24hr delay slider don’t seem to work anymore. I set the frequency check to 24, then also set back the delay to  the original 24hr delay, but unaired tvshows (next day) show up in the library. Before the new setting was implemented, the 24h delay was really strict and it worked by delaying importing of unaired tv episodes.

**Comment by umbrellaplug** [comment]
Well it was worth a shot. I won't be investing anymore time into this as it's just a preference for someone and not an actual issue or problem. I'll revert back to before slider setup on next update. Closing this issue.

**Comment by jaimsitecom** [comment]
Went back to version 6.5.75 (no slider delay)

24h delay works. Unaired tv episodes wont get downloaded til next day after it airs at realtime

**Comment by jaimsitecom** [comment]
> Went back to version 6.5.75 (no slider delay)
> 
> 24h delay works. Unaired tv episodes wont get downloaded til next day after it airs at realtime

Yes. Thanks for trying anyways.
