### ISSUE TITLE
[FEATURE REQUEST] Add ability to enable resume point from Trakt scrobbles without authorizing Trakt first

### ISSUE THREAD

**Issue by rtuRgALp** [umbrellaplug/umbrellaplug.github.io#94]
Hello,

I really like Umbrella! One way to improve it would be to allow a user to set the resume point for content to be Trakt scrobbles without having to authorize Trakt in the add on itself first. Currently, this option only appears after authorizing Trakt. 

Another add on that does this well is The Promise (a clone/fork of The Oath). Homelander also has this feature (another Oath fork, I think). I have the option to configure the source for resume points without first authorizing Trakt to customize my scrobbling experience. I can either manage it via the official Kodi-Trakt add-on or in the third party add-on itself. Users are warned not to enable scrobbling in the third party add on if they are using the Kodi add-on for scrobbling already. In those case, a user could authorize Trakt in Umbrella just for lists and collections. 

The user story in this case can be something like:
As a user, I want to set my resume point to Trakt scrobbles without authorizing Trakt in Umbrella itself, so that I can use the Trakt Kodi Add-on for scrobbling. 

This benefits the user to have more options for Trakt syncing and also allows the user limit API calls to Trakt out of umbrella. 

Hope that makes sense!

**Comment by umbrellaplug** [comment]
I will not be doing this. If you want to use trakt features you need to authorize trakt.

**Comment by rtuRgALp** [comment]
Ok, thank you for your consideration.

**Comment by umbrellaplug** [comment]
No problem. Trakt is deeply integrated within the plugin for many features. It's a lot more work than it seems. Please don't take my quick answer as not taking your request into consideration.

**Comment by rtuRgALp** [comment]
No worries!

Where can I make a donation to support your support of this add-on?

**Comment by rtuRgALp** [comment]
So, I believe I misstated my initial request. 

It is not to enable Trakt resume points without authorizing Trakt. It’s to set Trakt resume point without enabling scrobbling from Umbrella.

Of course one has to authorize Trakt for Umbrella to pick up the synced resume point. But it would be nice to still do so without turning on scrobbling from the add-on. Some user may like to let the Trakt add-on itself do that. 

I just wanted to make this clarification in case you’d be willing to reconsider. Thank you.
