### ISSUE TITLE
[FEATURE] "Preferred" video size for sorting.

### ISSUE THREAD

**Issue by Spark-NV** [umbrellaplug/umbrellaplug.github.io#96]
My thought was a setting to set a "preferred" video size to go along with the hard limit of video size. like a preferred limit for movies could be set to something like 5gb and it auto tries to play a movie closest files to your preferred size.

I say this so you can have a preferred size(my brother really likes the rarbg 2-3gb rips for there size/quality ratio due to his isp data monthly limit) but if your preferred size isn't available it will choose the next closest that also falls inline with your hard size limit. like the hard size limits being set to 2gb low and 10gb high. with the preferred being set at 4gb, a 4gb version isnt available but a 4.2 and a 3.1 is available. it would auto choose the 4.2 as its the closest.

auto choose/play is assuming you have the option that auto selects a source instead of bringing up the source select list of course.

**Comment by Spark-NV** [comment]
Or maybe a way to add list of preferred scene groups as each group generally has things some people like about it like very high quality or they always are Dv etc.

Maybe this list could just be keywords you enter that are used as a list to compare against that it tries to use when it sees them. like in my original comment you would put rarbg as a keyword, now when you go to play a movie if a pre-cached or file hosted source has that word in it it is the top priority.

**Comment by umbrellaplug** [comment]
I'm not sure what you're asking for here. It seems like you're asking for a second limit to be put in place for a preferred file size vs a hard file size limit? Request just isn't real clear. The second comment you made afterwards, I'm really confused. Are you suggesting I make a list you can add preferred trigger words into and put them at the top of your results for sources? I'm not sure this is something that would be widely used.

**Comment by Spark-NV** [comment]
i mean for the preferred size one. if you set your ideal size is 5gb the auto picking of the source when you just click play after it scrapes the sources would try to select a source that is as close as possible to your selected ideal/preferred file size.

the hard limit for file sizes can still remain for its hard limiting capabilities but the preferred option would be attempted for every play to stay as close as possible when the source is available.

For example you select a movie, the addon checks for sources, then removes all sources that are outside of the current file size limits then instead of doing whatever algorithm you currently use for auto selecting the source it would auto select the source that is as closest to the file size as possible to the "ideal/preferred size" from the sources that are left.


And as far as the second thing, it was just a thought, its not really an ideal solution, and your right it wouldnt be used by many, i was only thinking of very niche use cases like my brother who is on a data cap that he has to work around and the rarbg scene releases(around 2-3gb) are his favorite for this reason. but if you set the hard limit within the settings to 2gb for the low cutoff and 3gb for the high you wouldnt have any sources alot if rarbg hasnt made there own release for said movie.

**Comment by umbrellaplug** [comment]
Seems like really just needing a sort by preferred file size. Filter for min and max and sort for making the results sort by your "preferred file size"

**Comment by Spark-NV** [comment]
Yea that works if you have the option set to show the source list every time you select a file. But it you have the option set to just auto pick a source it seems it randomly picks a source to play that’s what I am talking about it affecting., which idk what the algorithm is for deciding which source to play when you have it set to not bring up the source select menu
