### ISSUE TITLE
[BUG] Some Trakt lists missing

### ISSUE THREAD

**Issue by skynetisnow** [umbrellaplug/umbrellaplug.github.io#97]
Been using Umbrella from the beginning, love your work. The last week or two, some of my Trakt TV show lists have gone missing, the only two I actually use daily, and have not returned. On the Trakt website itself and on other third party apps the lists are still there.

**Comment by umbrellaplug** [comment]
Can you try doing a force trakt sync to local database from tools trakt management.

**Comment by umbrellaplug** [comment]
Did this resolve your issue?

**Comment by skynetisnow** [comment]
> Did this resolve your issue?

No, unfortunately it did nothing

**Comment by umbrellaplug** [comment]
I would need some logs to further troubleshoot this.

**Comment by skynetisnow** [comment]
I'm running umbrella on 3 different devices and the same two lists are missing on all three devices, but only in umbrella. Inside of trakt management tools, under trakt import manager, the two missing lists are there, but importing them does nothing. How would i go about getting you the logs you need

**Comment by umbrellaplug** [comment]
Importing those lists brings them into your library. That would only work if you've setup library folders in the addon. Where are these lists missing from exactly? Your "my TV shows" section? Logs can be uploaded by enabling logging in the settings and using the logging tools in options to upload your log to pastebin. Please enable logs, try losing the lists, then send me the logs of that. I'll see what I can find.

**Comment by skynetisnow** [comment]
Yes, in My TV Shows. On second look there are actually 3 lists missing. 

https://paste.kodi.tv/wapufozune

**Comment by umbrellaplug** [comment]
Nothing obvious in that log for me.  What skin are you using so I can try to duplicate this?

**Comment by skynetisnow** [comment]
> Nothing obvious in that log for me. What skin are you using so I can try to duplicate this?

Aeon Knox skin. Other than that, completely standard build on all 3 devices, nothing else installed on two of them except umbrella. The third device has a second addon I'm using temporarily. The devices are a Google TV, a Google Chromecast with Google TV, and an Amazon Fire TV Stick 4k Max

**Comment by Has3n** [comment]
Having exactly the same issue. Access to lists working fine in Seren, since a week or two not anymore in Umbrella. Cleared all caches, forced sync to local database. Accessing the list in my movies either won’t stop or just stops without effect.

Enabled logging, restarted kodi and umbrella: https://paste.kodi.tv/mixotakumu

**Comment by umbrellaplug** [comment]
This is due to the list being mixed content. Movies and Shows. I will see what I can do, but mixed lists are not currently supported. They only showed before because they were duplicated.

**Comment by skynetisnow** [comment]
So there must be some random movie accidentally added to the list somewhere? I'll check it out and report back

**Comment by skynetisnow** [comment]
I just set the list to hide tv shows and only show movies and it brought the list size down to zero. Not sure what show to remove

**Comment by skynetisnow** [comment]
The lists just randomly reappeared just now. No idea what happened

**Comment by umbrellaplug** [comment]
That sounds like a trakt results issue, but there is for sure a problem here with mixed lists from the changes that I made for library imports. I'm putting together a fix for it now. In my environment if a list is mixed I can pull the list into movies, but not tv and i'm not able to actually browse the list at all. it is as Has3n reported.

**Comment by umbrellaplug** [comment]
Okay this has been fixed. Next update should resolve any issues with Trakt "mixed" content lists. Fix will be pushed with next update. Next update will be pushed once current set of code changes I'm working on is completed.
