### ISSUE TITLE
‘Already exist in library’ error

### ISSUE THREAD

**Issue by jaimsitecom** [umbrellaplug/umbrellaplug.github.io#98]
When tryinh to add new tv show s to kodi library, it will say ‘checking library…then wil flash Title already exist in library’ even if it’s not there yet. 

Only happened today. I got to add yesterday but today, cannot anymore add new shows. Ended up adding it on Favorites instead.

**Comment by umbrellaplug** [comment]
Need more details. What show? Did you already have the show in your library? Can you provide steps to duplicate the issue on my side and logs?

**Comment by jaimsitecom** [comment]
Show is not in the Library. I searched a new show and tried to ‘add it into the library’ via context menu, it said ‘title already in library’. If i check the library nothing is added. Checked the tv folder via file explorer, no folder of the show or any .strms added.

**Comment by jaimsitecom** [comment]
I found the problem. It’s the TVDB scraper. It was down but now it’s up amd the show is added into the library. Sorry about this.

**Comment by jaimsitecom** [comment]
This issue just came back. Now it doesn’t seem to be connected with tvdb scraper. I tried adding a newly released tv show SHANTARAM, and it Umbrella told me it’s already in my livrary even if it’s really not.

**Comment by jaimsitecom** [comment]
Umbrella error log:
[Umbrella log](https://mega.nz/file/sAoDVSIS#Pd1sLGyowUjA9fmcGh_5dWovRyDvXZoTuHyLUO8yhR0)

**Comment by jaimsitecom** [comment]
I tested adding new tv shows via TMDB HELPER and it worked. So to determine the tvscraper tvdb is really working

**Comment by jaimsitecom** [comment]
I also unclicked SUBSTITUTE TITLE NAME setting, didn’t work too.

**Comment by umbrellaplug** [comment]
Substitute title name is really only used for titles that are incorrect on results in foreign languages or certain scenarios where you want to scrape for something different than the actual title shows. It was made to assist someone with dutch title substitution issues on certain titles.

I'll look into this. I'll add this and see if I can get the same results. Is the show in your library now? I do not have this show in my library now. To duplicate your issue would I attempt to add it from context menu to library or add it to a list I'm importing into my library?

**Comment by jaimsitecom** [comment]
> 

No still couldn’t add it. I don’t know why it won’t add shows in this version. The last one works ok when adding new shows.

**Comment by umbrellaplug** [comment]
Okay, I'm seeing the same behavior here. I will find the problem.

**Comment by jaimsitecom** [comment]
Thanks alot! Appreciate everything you do! Ty ty

**Comment by umbrellaplug** [comment]
It's now allowing me to add this show without issue.... ugghhhhhhh something weird going on here.

**Comment by jaimsitecom** [comment]
Indeed! Hahahaha i tried adding it today and it went thru. What could be causing the erratic behavior? 

Also, the 24hr delay slider don’t seem to work anymore. I set the frequency check to 24, then also set back the delay to 24, but unaired tvshows (next day) show up in the library. Before the new setting was implemented, the 24h delay was really strict and it worked by delaying importing of unaired tv episodes.

**Comment by jaimsitecom** [comment]
This bug still exists in the latest ver 6.5.80. Am suspecting it may be connected to the tv show info provider?  Am currently using TMDB TV SHOW ver 1.4.16. Do you think it’s possible that this causes also the error (other issue i inquired the other day)?  May i know what tv show info provider you use for your tv shows folder?  Is ‘THE TVDB v4’ the latest and best?

**Comment by umbrellaplug** [comment]
Nah. It's a bug. I've been trying to duplicate it but it's hard due to it being date and release date related. What show are you trying to add that's doing it today?

**Comment by jaimsitecom** [comment]
Oh i see. I tried adding The Crown season 5 and an episode of Andor… it said i already have em in my Library but i really don’t. But eventually after several hours, it adds them into the Library. So weird. But thanks again!

**Comment by umbrellaplug** [comment]
Have not seen this issue since the last update. I'm going to close for now. If it comes back up let me know.

**Comment by jaimsitecom** [comment]
Thanks again!
