### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by Redsand51** [umbrellaplug/umbrellaplug.github.io#99]
Filenames are causing issues when downloading. Appears special characters from torrents are not accepted by system and some files not saved.  System shows download progress but no file actually saved.  Duplicate download popup boxes appear. Very old issue with Venom.

**Comment by umbrellaplug** [comment]
Got an example?

**Comment by umbrellaplug** [comment]
no example provided. generic check for valid filename with 3 letter extension added. if invalid file, warning thrown before download and canceled. will be in next update.

**Comment by Redsand51** [comment]
The test I ran was on a small scaled down Linux based system. I tried to duplicate on a windows system but no issues. I'll again test the Linux system and see if I can duplicate and provide some insight. Thanks for the efforts. Much appreciated.
